import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("PQF Legal Basis & Level 6 Descriptors", "Under Republic Act 10968 (Philippine Qualifications Framework Act), a graduate of a Bachelor of Secondary Education (BSEd) or Bachelor of Elementary Education (BEEd) program is classified at what PQF qualification level?", "Level 6 (Baccalaureate degree level).", ["Level 5 (Diploma / Technical-Vocational level).", "Level 7 (Post-Baccalaureate / Master's degree level).", "Level 8 (Doctoral and Post-Doctoral level)."], "Under RA 10968, Level 6 corresponds to Baccalaureate degrees, which includes Teacher Education degrees. Level 5 is Diploma, Level 7 is Post-Baccalaureate/Master's, and Level 8 is Doctoral."),
  ("PQF Level 6: Expected Independence", "According to the PQF Level 6 descriptors, which of the following best describes the degree of independence expected of a licensed baccalaureate teacher education graduate?", "Independent professional practice in specialized educational settings with self-directed competence.", ["Requires continuous direct step-by-step supervision from school heads in all daily lesson deliveries.", "Acts strictly as an instructional aide under constant master teacher monitoring.", "Autonomous only in preparing visual materials but completely dependent on supervisors for lesson objectives."], "PQF Level 6 descriptors mandate that graduates demonstrate independent, self-directed professional practice and application in their field."),
  ("PPST Career Stages (DepEd Order 42, s. 2017)", "Teacher Clara is a newly hired teacher who has just passed the Licensure Examination for Teachers (LET). According to the Philippine Professional Standards for Teachers (PPST), in which career stage is Teacher Clara classified?", "Career Stage 1: Beginning Teacher.", ["Career Stage 2: Proficient Teacher.", "Career Stage 3: Highly Proficient Teacher.", "Career Stage 4: Distinguished Teacher."], "Under the PPST (DepEd Order 42, s. 2017), newly licensed teachers entering the profession are classified as Beginning Teachers (Stage 1). They gain experience to reach Proficient (Stage 2), Highly Proficient/Master Teacher (Stage 3), and Distinguished (Stage 4)."),
  ("PPST Career Stage 2: Proficient Teacher", "A teacher who professionally displays skills in planning, implementing, and managing learning programs independently, and who holds a regular permanent teaching item, is at which PPST career stage?", "Career Stage 2: Proficient Teacher.", ["Career Stage 1: Beginning Teacher.", "Career Stage 3: Highly Proficient Teacher.", "Career Stage 4: Distinguished Teacher."], "Stage 2 (Proficient Teachers) are professionally independent in the application of skills vital to teaching and learning, providing focused support to learners."),
  ("PPST Career Stage 3: Highly Proficient", "Master Teacher Eduardo regularly mentors colleagues, leads curriculum innovations in his department, and conducts action research. Under PPST, which career stage does he embody?", "Career Stage 3: Highly Proficient Teacher.", ["Career Stage 1: Beginning Teacher.", "Career Stage 2: Proficient Teacher.", "Career Stage 4: Distinguished Teacher."], "Stage 3 (Highly Proficient / Master Teachers) consistently display high performance, mentor colleagues, lead curriculum enrichment, and guide peers."),
  ("PPST Domains: Domain 1 (Content Knowledge & Pedagogy)", "A teacher utilizes in-depth subject mastery to teach difficult chemistry concepts while integrating literacy and numeracy skills across the lesson. Which PPST Domain is primarily demonstrated?", "Domain 1: Content Knowledge and Pedagogy.", ["Domain 2: Learning Environment.", "Domain 3: Diversity of Learners.", "Domain 4: Curriculum and Planning."], "Domain 1 emphasizes teachers' mastery of subject content, application of pedagogy, and integration of literacy, numeracy, and higher-order thinking skills."),
  ("PPST Domains: Domain 2 (Learning Environment)", "Teacher Roberto ensures his classroom is physically safe, promotes fair and inclusive participation, and manages learner behavior constructively without physical punishment. This aligns with:", "Domain 2: Learning Environment.", ["Domain 1: Content Knowledge and Pedagogy.", "Domain 5: Assessment and Reporting.", "Domain 6: Community Linkages and Professional Engagement."], "Domain 2 focuses on creating safe, secure, fair, supportive, and positive classroom learning environments conducive to learning."),
  ("PPST Domains: Domain 3 (Diversity of Learners)", "Designing differentiated learning activities to accommodate gifted pupils, indigenous children, and students with learning difficulties demonstrates mastery in:", "Domain 3: Diversity of Learners.", ["Domain 4: Curriculum and Planning.", "Domain 7: Personal Growth and Professional Development.", "Domain 2: Learning Environment."], "Domain 3 highlights the teacher's ability to design instruction that responds to learners' linguistic, cultural, socio-economic, and physical/cognitive diversity."),
  ("Direct vs Indirect Instruction: Deductive Approach", "In a grammar class, Teacher Maria first states the rule for subject-verb agreement with singular subjects, provides clear examples on the board, and then instructs pupils to practice on worksheets. What instructional approach was used?", "Deductive / Direct Instruction approach (rule to examples).", ["Inductive / Inquiry-based approach (examples to rule).", "Discovery learning approach.", "Socratic dialogue approach."], "The Deductive approach moves from the general rule or principle to specific applications and practice exercises (Rule -> Examples -> Practice)."),
  ("Inductive Instruction: Discovery Learning", "Teacher Juan shows students five different plant leaves, guides them to observe similarities and differences in leaf veins, and asks them to formulate the definition of parallel and netted venation on their own. This exemplifies:", "Inductive / Discovery Instruction approach (examples to general principle).", ["Deductive rule-transmission method.", "Expository lecture method.", "Direct demonstration approach."], "The Inductive approach begins with specific observations, data, or examples, guiding learners to discover and formulate the underlying concept, rule, or generalization."),
  ("Constructivist Teaching Principles", "In a constructivist classroom, what is the primary role of the classroom teacher during instructional activities?", "A facilitator and guide who mediates learning and scaffolds students as they construct their own knowledge.", ["An authoritarian lecturer who transmits fixed encyclopedic facts into passive student minds.", "A strict disciplinarian who enforces silent rote memorization without discussion.", "A detached observer who provides zero instructional support or structure."], "Constructivism (Piaget, Vygotsky, Bruner) posits that learners actively construct knowledge; the teacher acts as a facilitator, guide, and creator of collaborative learning opportunities."),
  ("Inquiry-Based Learning: The 5E Model", "In the 5E Instructional Model (Engage, Explore, Explain, Elaborate, Evaluate), what occurs during the 'Explore' phase?", "Students actively investigate objects, conduct experiments, and gather data through hands-on collaborative activities.", ["The teacher delivers a formal lecture introducing scientific vocabulary terms.", "Students take a high-stakes standardized pen-and-paper summative test.", "The teacher assigns homework reading from an encyclopedia."], "In the Explore phase, learners actively explore the phenomenon through hands-on activities, collecting evidence before formal concept introduction."),
  ("Problem-Based Learning (PBL)", "Students in a social studies class are given a real-world scenario: 'Our municipality is experiencing severe river flooding during typhoons. Propose a sustainable flood-mitigation plan for the local council.' This instructional strategy is:", "Problem-Based Learning (PBL).", ["Rote drill-and-practice instruction.", "Traditional didactic recitation.", "Direct teacher-led demonstration."], "Problem-Based Learning engages learners in solving complex, authentic, ill-structured real-world problems, promoting critical thinking and research skills."),
  ("Project-Based Learning (PjBL)", "How does Project-Based Learning (PjBL) differ from traditional classroom assignments?", "Students work over an extended period to investigate a driving question and create a tangible, authentic public product or presentation.", ["Students memorize vocabulary lists for a 10-minute quiz.", "The teacher reads a textbook chapter aloud while pupils sit quietly.", "Students complete identical fill-in-the-blank worksheets."], "Project-Based Learning involves sustained inquiry over time resulting in an authentic product, artifact, or public presentation that solves a driving question."),
  ("Cooperative Learning: Essential Elements (Johnson & Johnson)", "According to David and Roger Johnson, which essential element of cooperative learning ensures that 'we sink or swim together'—meaning each member's success depends on the success of all?", "Positive Interdependence.", ["Individual Accountability.", "Face-to-Face Promotive Interaction.", "Group Processing."], "Positive Interdependence is the core of cooperative learning where team members realize that individual success is linked to the collective success of the entire team.")
]
d.extend([
  ("Cooperative Learning: Jigsaw Technique (Aronson)", "In Elliot Aronson's 'Jigsaw' cooperative learning strategy, how is content mastered and shared among students?", "Each student becomes an expert on one section in an 'expert group' and returns to teach it to their 'home group'.", ["Students complete identical multiple-choice worksheets in complete silence.", "The highest-scoring student completes the entire assignment for the group.", "The teacher lectures to the whole class while students take verbatim notes."]),
  ("Cooperative Learning: Think-Pair-Share (Lyman)", "Frank Lyman's 'Think-Pair-Share' strategy promotes active cognitive engagement by structuring the sequence as:", "Students think individually about a prompt, discuss their thoughts with a partner, and then share insights with the larger class.", ["Students listen to a lecture, take a partner test, and submit homework.", "The teacher calls on one student to answer on the spot without wait time.", "Students write an individual essay without any peer interaction."]),
  ("Dale's Cone of Experience: Direct Purposeful Experiences", "At the very base of Edgar Dale's Cone of Experience, providing the most concrete, hands-on sensory learning, are:", "Direct, Purposeful Experiences (firsthand physical experiences and real-life manipulation of objects).", ["Verbal Symbols (reading printed text and spoken words).", "Visual Symbols (charts, maps, diagrams).", "Still Pictures and Audio Recordings."]),
  ("Dale's Cone of Experience: Contrived Experiences", "When a real object is too dangerous, too massive, or inaccessible (e.g., the human circulatory system or a volcano), a teacher utilizes a 3D cutaway model. In Dale's Cone, this is a:", "Contrived Experience (a realistic model, mockup, or simulation).", ["Dramatized Experience.", "Demonstration.", "Verbal Symbol."]),
  ("Dale's Cone of Experience: Abstract Level", "At the very apex (top) of Dale's Cone of Experience, representing the most abstract and least sensory-rich instructional materials, are:", "Verbal Symbols (spoken words, printed text, mathematical symbols).", ["Field Trips and Study Tours.", "Educational Television.", "Direct Hands-on Experiences."]),
  ("Differentiated Instruction: Content, Process, Product (Tomlinson)", "Carol Ann Tomlinson defines Differentiated Instruction as adapting which three key curricular elements according to learner readiness, interest, and profile?", "Content (what is learned), Process (how it is learned), and Product (how learning is demonstrated).", ["Classroom Budget, School Calendar, and Administrative Staffing.", "Textbook Publisher, Font Size, and Printing Paper Color.", "School Building Code, Room Temperature, and Lighting Level."]),
  ("Differentiated Instruction: Tiered Activities", "When a teacher creates three versions of an assignment on fractions—basic concept reinforcement, on-level application, and advanced problem solving—the teacher is using:", "Tiered Activities (differentiation by readiness level).", ["Standardized uniform pacing.", "Rote memorization drills.", "Punitive task tracking."]),
  ("Classroom Management: Kounin's 'Withitness'", "According to Jacob Kounin's classroom management research, a teacher who demonstrates 'Withitness' is one who:", "Accurately perceives what is happening in all parts of the classroom at all times ('eyes in the back of the head') and addresses misbehavior early.", ["Ignores student disruptions until a major fight breaks out.", "Leaves the classroom unattended during group activities.", "Strictly focuses on one student while ignoring the rest of the class."]),
  ("Classroom Management: Kounin's Overlapping", "A teacher is conducting a reading circle with six students at the front while smoothly gesturing to redirect a distracted student across the room without stopping the lesson. This skill is:", "Overlapping (managing more than one classroom event simultaneously).", ["Flip-flopping.", "Dangle.", "Thrust."]),
  ("Classroom Management: Kounin's Smoothness & Momentum", "Kounin defines 'Momentum' and 'Smoothness' in lesson delivery as:", "Maintaining appropriate instructional pacing and smooth transitions between activities without abrupt stops or digressions.", ["Shouting instructions loudly to startle inattentive students.", "Stopping the entire lesson to search for a lost whiteboard marker.", "Switching topics randomly without instructional connection."]),
  ("Classroom Management: Satiation (Kounin)", "In Kounin's framework, 'Satiation' occurs in the classroom when:", "Students become bored, restless, and disengaged because a teacher prolongs an activity long after mastery has been achieved.", ["Students feel energized by a novel hands-on science experiment.", "The teacher provides immediate constructive feedback on essays.", "The classroom environment is perfectly organized."]),
  ("Classroom Management: Canter's Assertive Discipline", "Lee Canter's 'Assertive Discipline' model is characterized by a teacher who:", "Clearly establishes rules, explicitly teaches behavioral expectations, and applies consistent, predictable consequences calmly and firmly.", ["Uses passive avoidance and never corrects misbehavior.", "Uses hostile sarcasm and public humiliation against students.", "Allows students to set all rules without teacher leadership."]),
  ("Questioning Techniques: Wait Time (Rowe)", "Mary Budd Rowe's research showed that when teachers increase 'Wait Time' (pausing after asking a question and after a student responds) to 3 to 5 seconds:", "Student responses become longer, higher-order thinking increases, and more students participate.", ["Students completely forget the question asked.", "Classroom discipline breaks down into chaos.", "The pacing of the lesson becomes unacceptably delayed."]),
  ("Questioning Techniques: Bloom's Taxonomy (HOTS vs LOTS)", "Which of the following teacher questions best targets 'Evaluation' in the Revised Bloom's Taxonomy (Anderson & Krathwohl)?", "'Defend your position on whether the construction of a coastal bypass road justifies the environmental impact on mangrove reserves.'", ["'List the four main steps of the scientific method.'", "'Calculate the area of a rectangle with length 10 cm and width 5 cm.'", "'Define the term photosynthesis in your own words.'"]),
  ("Questioning Techniques: Probing Questions", "When a student gives a correct but incomplete answer, the teacher asks: 'What evidence from the story supports that conclusion?' This is an example of:", "Probing / Clarifying questioning (prompting deeper elaboration and justification).", ["Leading questioning that gives away the answer.", "Rhetorical questioning requiring no response.", "Closed questioning limiting answers to yes or no."])
])
d.extend([
  ("Lesson Planning: DepEd Order 42, s. 2016 (DLL / DLP)", "Under DepEd Order 42, s. 2016 (Policy Guidelines on Daily Lesson Preparation for K to 12), newly hired teachers during their first year are required to prepare a:", "Detailed Lesson Plan (DLP), providing step-by-step instructional procedures.", ["Daily Lesson Log (DLL), which is a simplified template for experienced teachers.", "Syllabus outline without daily objectives.", "Weekly gradebook record only."]),
  ("Lesson Planning: Instructional Alignment (SMART Objectives)", "In formulating behavioral lesson objectives, which of the following adheres strictly to SMART criteria (Specific, Measurable, Attainable, Relevant, Time-bound)?", "'At the end of the 60-minute lesson, Grade 8 learners will correctly solve at least 4 out of 5 linear equations in one variable.'", ["'Students will appreciate the beauty of mathematics in daily life.'", "'Learners will understand all algebra concepts completely by Friday.'", "'The class will develop deep love for equation solving.'"]),
  ("Explicit Instruction Model (Archer & Hughes)", "The Explicit Instruction model follows which structured pedagogical sequence for teaching skills?", "'I Do' (Teacher Modeling), 'We Do' (Guided Practice with Feedback), and 'You Do' (Independent Practice).", ["'You Do' first, followed by teacher correction at the end of the semester.", "'We Do' continuously without any individual independent practice.", "'I Do' for 60 minutes with zero student practice."]),
  ("Teaching Models: Gagne's Nine Events of Instruction", "In Robert Gagne's Nine Events of Instruction, what is the very FIRST event that a teacher must execute to initiate a lesson?", "Gain Attention (stimulating interest and focus through a hook, challenge, or question).", ["Inform learners of objectives.", "Stimulate recall of prior learning.", "Assess performance."]),
  ("Teaching Models: Gagne's Stimulating Recall of Prior Learning", "Connecting today's lesson on multiplying fractions with yesterday's lesson on simplifying fractions fulfills which of Gagne's instructional events?", "Stimulating recall of prior learning (activating relevant prerequisite schemas).", ["Presenting the content stimulus.", "Providing learner guidance.", "Enhancing retention and transfer."]),
  ("Classroom Management: Dreikurs' Mistaken Goals of Behavior", "Rudolf Dreikurs identified four mistaken goals behind student misbehavior. When a student acts out to be the center of the teacher's focus, the goal is:", "Attention-seeking (which can be redirected by giving positive attention for constructive behavior).", ["Power and control.", "Revenge.", "Display of inadequacy."]),
  ("Classroom Management: Glasser's Choice Theory", "William Glasser's 'Choice Theory' asserts that all human behavior is an attempt to satisfy five basic psychological needs:", "Survival, Love/Belonging, Power/Competence, Freedom, and Fun.", ["Food, Sleep, Shelter, Clothing, and Medicine.", "Money, Fame, Dominance, Status, and Luxury.", "Id, Ego, Superego, Libido, and Thanatos."]),
  ("Classroom Management: Preventive Discipline", "Which of the following teacher actions represents 'Preventive Discipline' in the classroom?", "Establishing clear classroom routines, smooth transitions, and engaging lesson materials before problems emerge.", ["Waiting for students to misbehave and immediately sending them to the guidance office.", "Assigning 100 math problems as a punitive measure for talking in class.", "Posting a list of misbehaving students publicly on the school bulletin board."]),
  ("Teaching Strategies: Socratic Method (Elenchus)", "The classical Socratic Method of teaching is characterized by:", "Disciplined, systematic questioning to challenge assumptions, expose contradictions, and lead learners to deeper conceptual insights.", ["Didactic lecturing where the teacher talks continuously for an hour.", "Silent individual reading of assigned textbook chapters without discussion.", "Administering multiple-choice standardized tests daily."]),
  ("Teaching Strategies: Flipped Classroom Model", "In a 'Flipped Classroom' instructional model, how are classroom time and homework restructured?", "Direct instruction (video lectures/readings) is completed at home before class, freeing classroom time for active problem-solving and collaborative projects.", ["Students complete homework worksheets in silence during class while the teacher grades papers.", "All exams are taken at home without teacher supervision.", "Lectures are delivered in class and all group projects are done alone at home."]),
  ("Teaching Strategies: Reciprocal Teaching (Palincsar & Brown)", "Reciprocal Teaching improves reading comprehension through structured student dialogue utilizing which four core cognitive strategies?", "Predicting, Questioning, Clarifying, and Summarizing.", ["Reading, Writing, Listening, and Speaking.", "Memorizing, Reciting, Drilling, and Testing.", "Defining, Translating, Copying, and Repeating."]),
  ("Teaching Strategies: Mind Mapping & Graphic Organizers", "Using a Venn diagram to compare and contrast Mitosis and Meiosis in biology is an effective instructional strategy because:", "Visual graphic organizers help learners spatially organize relationships, similarities, and differences between concepts.", ["It eliminates the need for students to read scientific textbooks.", "It replaces laboratory experiments with 2D drawings.", "It guarantees a perfect score on standardized tests."]),
  ("Assessment in Pedagogy: Formative Assessment Techniques", "Which of the following is an authentic 'Formative Assessment' technique used DURING instruction to check for student understanding and adjust pacing?", "'Exit Tickets' where students write a 1-sentence summary and 1 lingering question before leaving class.", ["A 100-item end-of-term standardized comprehensive exam.", "A final graduation research thesis defense.", "A permanent letter grade recorded on the report card."]),
  ("Classroom Seating Arrangements & Pedagogy", "Which classroom seating arrangement is most effective for promoting small-group collaborative problem-solving and peer interaction?", "Cluster / Pod seating (desks grouped in tables of 4 to 5 students).", ["Traditional straight rows facing forward (best for direct instruction/individual testing).", "Auditorium tiered seating facing a stage.", "Placing all desks facing the back wall."]),
  ("Culturally Responsive Pedagogy (Gay & Ladson-Billings)", "A teacher in an indigenous community integrates local epic folklore, traditional farming seasons, and community elders' knowledge into science and social studies. This exemplifies:", "Culturally Responsive Teaching (connecting curriculum to learners' cultural knowledge and lived experiences).", ["Linguistic assimilationism.", "Ethnocentric standardization.", "Pedagogical deficit orientation."])
])
d.extend([
  ("Metacognitive Teaching: Thinking Aloud", "When a math teacher models problem-solving by verbalizing her internal thought processes, questions, and error-checking steps at the board, she is using:", "Think-Aloud modeling to develop students' metacognitive self-monitoring.", ["Rote computational drill.", "Behaviorist stimulus-response conditioning.", "Silent lecture delivery."]),
  ("Scaffolding in Pedagogy (Bruner & Vygotsky)", "Instructional 'Scaffolding' is best defined as:", "Temporary supportive structures, cues, or guidance provided by the teacher that are gradually removed as the learner gains independence.", ["Permanent physical hand-holding throughout the entire school year.", "Giving students the exact answers to exam questions in advance.", "Assigning work that is far beyond a student's cognitive capability without assistance."]),
  ("Teaching Models: Ausubel's Meaningful Verbal Learning", "David Ausubel's theory asserts that meaningful learning occurs when new information is subsumed under existing cognitive structures using:", "Advance Organizers (introductory conceptual frameworks that bridge what learners know and what they need to know).", ["Mechanical rote repetition drills.", "Random guessing without schema connection.", "Continuous multiple-choice quizzes."]),
  ("Teaching Strategies: Role-Playing & Simulation", "In a history class, students reenact the Malolos Congress debates on the separation of Church and State, adopting the roles of historical delegates. This strategy promotes:", "Experiential empathy, active critical analysis, and perspective-taking through dramatic simulation.", ["Passive rote memorization of historical dates.", "Silent individual study of encyclopedias.", "Authoritarian recitation of textbook paragraphs."]),
  ("Teaching Strategies: Debates & Structured Controversy", "Using Structured Academic Controversy in the classroom encourages students to:", "Research both sides of an issue, present evidence systematically, listen to opposing arguments, and synthesize a consensus position.", ["Engage in personal ad hominem insults against classmates.", "Refuse to listen to any differing perspectives.", "Conform blindly to the teacher's personal political opinion."]),
  ("Classroom Climate: High Expectations (Pygmalion Effect)", "Rosenthal and Jacobson's 'Pygmalion Effect' research in education demonstrated that:", "Teacher expectations function as self-fulfilling prophecies—holding high, supportive expectations significantly boosts student academic performance.", ["Student intelligence is unchangeable regardless of teacher behavior.", "Low teacher expectations encourage students to work harder independently.", "Classroom seating position determines 100% of student learning outcomes."]),
  ("Feedback in Instruction (Hattie & Timperley)", "According to John Hattie and Helen Timperley, the most effective instructional feedback answers which three fundamental questions for the learner?", "'Where am I going?' (Feed Up), 'How am I doing?' (Feed Back), and 'Where to next?' (Feed Forward).", ["'What grade did I get?', 'Who scored higher than me?', and 'When is vacation?'", "'Why did you fail?', 'Who made this mistake?', and 'What is the penalty?'", "'How much does this test cost?', 'Where is the school office?', and 'Who is the principal?'"]),
  ("Feedback: Formative vs Praise", "A teacher writes on a student's essay: 'Good job!' versus 'Your thesis is clear, but paragraph 3 needs concrete historical evidence to support your claim on economic causes.' Why is the second comment superior?", "It provides specific, actionable, task-level descriptive feedback that guides tangible improvement.", ["Because 'Good job!' damages student self-esteem.", "Because longer comments are legally mandated by DepEd orders.", "Because critical comments lower student stress levels."]),
  ("Classroom Management: Proximity Control", "When Teacher Carlos notices two students whispering and off-task during independent seatwork, he calmly walks over and stands near their desks while continuing to assist others. This technique is:", "Proximity Control (using physical presence non-verbally to redirect behavior without disrupting instruction).", ["Authoritarian public scolding.", "Sarcastic humiliation.", "Sending students to detention immediately."]),
  ("Classroom Management: Non-Verbal Cues", "A teacher maintains eye contact, smiles, and uses a gentle open-palm gesture to invite a hesitant student to share an idea. This demonstrates:", "Positive non-verbal communication that fosters psychological safety and encourages risk-taking in learning.", ["Aggressive non-verbal dominance that intimidates students.", "Passive indifference to student learning.", "Inappropriate classroom boundary crossing."]),
  ("Instructional Technology Integration: SAMR Model", "A teacher transitions from having students write essays on paper to having them collaborate simultaneously on a shared Google Doc with peer comments and embedded multimedia. In the SAMR model, this reaches:", "Modification / Redefinition (significant task redesign and collaborative transformation).", ["Substitution only (direct tech replacement with no functional change).", "Augmentation only.", "Elimination."]),
  ("Teaching Competencies: Literacy across the Curriculum", "Under PPST Indicator 1.4.2, teachers must display proficiency in integrating literacy across learning areas. In a physical education class, this is achieved by:", "Having students analyze sports rulebooks, write tactical game reflections, and explain biomechanical principles using academic terminology.", ["Forcing students to memorize spelling words while doing pushups.", "Replacing all physical exercise with silent grammar reading.", "Ignoring all verbal communication during sports activities."]),
  ("Teaching Competencies: Numeracy across the Curriculum", "In a secondary Social Studies class studying the Industrial Revolution, the teacher integrates numeracy by:", "Guiding students to analyze demographic growth charts, interpret wage vs inflation graphs, and calculate percentage changes in urban populations.", ["Requiring students to solve quadratic algebraic formulas without historical context.", "Eliminating all historical discussions in favor of basic arithmetic drills.", "Having students calculate the physical weight of textbooks."]),
  ("Pedagogical Models: 4As Instructional Framework", "The widely used 4As Lesson Framework in Philippine basic education follows which systematic learning flow?", "Activity, Analysis, Abstraction, and Application.", ["Attention, Assessment, Action, and Achievement.", "Aim, Approach, Assignment, and Appreciation.", "Acquisition, Assimilation, Adaptation, and Alignment."]),
  ("Pedagogical Framework: 4As (Abstraction Phase)", "During the 'Abstraction' phase of the 4As lesson plan, the teacher and learners:", "Synthesize concepts, formulate general principles, and clarify the core generalizations derived from the analysis.", ["Perform an icebreaker game without discussion.", "Take a 50-item multiple-choice final examination.", "Pack their bags and prepare to leave the classroom."])
])
d.extend([
  ("Classroom Management: Group Alerting (Kounin)", "A teacher asks a challenging question to the entire class, pauses for everyone to think, and then calls on a student at random. In Kounin's terms, this is:", "Group Alerting (keeping all students cognitively active and accountable before selecting a speaker).", ["Unstructured calling out.", "Targeting and intimidation.", "Flip-flopping."]),
  ("Classroom Management: Accountability (Kounin)", "Having all students hold up individual whiteboards with their worked-out math answers simultaneously is an example of:", "High learner accountability and active participation check.", ["Passive seatwork surveillance.", "Over-dwelling on minor details.", "Negative behavioral sanction."]),
  ("Instructional Materials: Dale's Cone (Demonstrations)", "When a science teacher demonstrates the dissection of a flower under a document camera before students perform it, in Dale's Cone this is a:", "Demonstration (visual and procedural modeling).", ["Verbal symbol.", "Abstract symbol.", "Direct purposeful experience."]),
  ("21st Century Pedagogies: Gamification in Education", "In pedagogical design, 'Gamification' refers to:", "Applying game-design elements (such as points, badges, leaderboards, and quest-based challenges) in educational contexts to boost intrinsic motivation and engagement.", ["Playing commercial action video games in class without learning objectives.", "Replacing all academic curriculum with esports competitions.", "Gambling with monetary stakes during classroom quizzes."]),
  ("Pedagogical Models: Kolb's Experiential Learning Cycle", "David Kolb's Experiential Learning Cycle structures learning through four sequential stages:", "Concrete Experience, Reflective Observation, Abstract Conceptualization, and Active Experimentation.", ["Input, Storage, Retrieval, and Output.", "Remembering, Understanding, Applying, and Creating.", "Stimulus, Response, Conditioning, and Extinction."]),
  ("Differentiated Instruction: Learning Stations / Centers", "Setting up classroom stations where students rotate between independent reading, hands-on experimentation, digital simulations, and teacher-led conferences is an example of:", "Learning Stations / Centers for differentiated instructional delivery.", ["Rigid whole-group lecture instruction.", "Standardized tracking of low-performing students.", "Punitive isolation centers."]),
  ("Classroom Rules: Positive Phrasing", "Educational psychology recommends that classroom rules should be phrased positively (e.g., 'Walk safely in the hallway') rather than negatively (e.g., 'Do not run') because:", "Positively stated rules clearly describe the desired expected behavior and foster a supportive climate.", ["Negative rules are illegal under DepEd orders.", "Students cannot understand words with the letter 'N'.", "Positively stated rules eliminate the need for teacher supervision."]),
  ("Teaching Strategies: Gallery Walk", "In a 'Gallery Walk' instructional activity, students:", "Display their group project posters on classroom walls and rotate in teams to examine, analyze, and leave constructive sticky-note feedback on peers' work.", ["Visit a commercial art museum in another city.", "Sit in their chairs while the teacher displays museum slides.", "Take a written essay examination in silence."]),
  ("Teaching Strategies: Socratic Seminars (Fishbowl)", "In an inner-outer circle 'Fishbowl' discussion, the inner circle students engage in dialogue on a text while the outer circle students:", "Actively listen, observe discussion dynamics, track arguments, and take notes before rotating into the inner circle.", ["Sleep or study for another subject.", "Interrupt the inner circle by shouting corrections.", "Leave the classroom to go to the canteen."]),
  ("Pedagogical Principles: Universal Design for Learning (UDL)", "The three core principles of Universal Design for Learning (UDL) mandate providing multiple means of:", "Representation (how content is presented), Action & Expression (how learners demonstrate knowledge), and Engagement (how learners are motivated).", ["Textbook printing, Standardized testing, and Letter grading.", "Classroom lighting, Room temperature, and Seating height.", "School budgeting, Teacher hiring, and Facility maintenance."]),
  ("Classroom Management: Restorative Justice Practices", "When a conflict occurs between two students, a teacher using 'Restorative Justice' approaches the situation by:", "Bringing the involved parties together in a guided dialogue to understand harm, repair relationships, and restore community trust.", ["Immediately issuing automatic suspensions without hearing both sides.", "Publicly shaming the offending student on the school stage.", "Ignoring the conflict and telling students to fight outside school."]),
  ("Teaching Models: Inquiry-Based Learning Levels (Banchi & Bell)", "In 'Open Inquiry' (the highest level of inquiry learning), students are responsible for:", "Formulating their own research questions, designing the experimental procedure, and analyzing results with minimal teacher guidance.", ["Following a step-by-step cookbook laboratory manual where all outcomes are predetermined.", "Listening to a teacher lecture on chemistry equations.", "Copying scientific definitions from an encyclopedia."]),
  ("Teaching Strategies: Peer Tutoring", "Research on 'Cross-Age Peer Tutoring' demonstrates that:", "Both the tutor and the tutee make significant academic and social-emotional gains through cognitive restructuring and reinforcement.", ["Only the tutee benefits, while the tutor loses valuable study time.", "Peer tutoring causes severe behavioral conflicts in 100% of cases.", "Tutors should replace licensed teachers in the classroom."]),
  ("Assessment for Learning: Rubric Types (Analytic vs Holistic)", "Why is an 'Analytic Rubric' (which scores individual criteria like Organization, Evidence, Mechanics separately) more pedagogically useful for formative feedback than a 'Holistic Rubric'?", "It provides detailed diagnostic feedback identifying specific areas of strength and precise areas needing improvement.", ["It takes zero time for teachers to design and grade.", "It assigns a single general letter grade without explanation.", "It eliminates the need for students to write essays."]),
  ("Professional Reflection: Schon's Reflective Practice", "Donald Schon distinguished between 'Reflection-in-Action' and 'Reflection-on-Action'. 'Reflection-in-Action' occurs when a teacher:", "Critically monitors, assesses, and adjusts instructional delivery and pacing IN REAL-TIME while teaching a lesson.", ["Writes a post-lesson reflection in a journal hours after school ends.", "Reads educational research textbooks during vacation.", "Attends a weekend professional development seminar."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This question evaluates teaching competence in {item[0]}. {item[2]} represents standard pedagogical best practice and DepEd/PPST policy."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('methodsAndStrategiesExams.ts', 'METHODS_AND_STRATEGIES_EXAM_QUESTIONS', questions)
