import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Historical Methodology: Primary vs Secondary Sources", "In historical methodology, an original 1898 diary written by an active officer of the Katipunan is classified as a:", "Primary source (an authentic firsthand document created during the time under study).", ["Secondary source (a scholarly analysis written decades later).", "Tertiary source (an encyclopedia summary index).", "Historiographical bibliography."], "Primary sources are firsthand contemporary accounts, records, or physical artifacts produced during the historical period under investigation."),
  ("Historical Methodology: External Criticism", "A historian examines the physical ink composition, paper watermarks, handwriting style, and seal of a 17th-century Spanish colonial decree to verify its physical authenticity. This process is:", "External Criticism (lower criticism / provenance and authenticity verification).", ["Internal Criticism (higher criticism / analyzing truthfulness and credibility of content).", "Deconstructive anachronism.", "Quantitative demographic census."], "External criticism tests the physical authenticity, authorship, date, and provenance of a document (detecting forgeries), while internal criticism evaluates the credibility of its assertions."),
  ("Historical Methodology: Internal Criticism", "When a historian analyzes the motives, potential biases, political allegiance, and factual consistency of a witness's testimony in an 1896 trial transcript, she is performing:", "Internal Criticism (evaluating the credibility and accuracy of the content).", ["External Criticism.", "Paleographical ink radiocarbon dating.", "Physical binding restoration."], "Internal criticism examines the meaning, reliability, perspective, and factual veracity of the content within an authentic document."),
  ("First Voyage Around the World: Pigafetta's Chronicle", "Antonio Pigafetta's Primo Viaggio Intorno al Mondo (First Voyage Around the World) is historically significant because it provides:", "The primary eyewitness European account of Ferdinand Magellan's expedition, the first circumnavigation, and early Visayan encounters in 1521.", ["A detailed military map of the 1898 Battle of Manila Bay.", "The complete Spanish translation of the Quran for Mindanao sultanates.", "The original architectural blueprints for Intramuros cathedrals."], "Pigafetta, the Italian chronicler who sailed with Magellan, produced the most detailed primary account of the expedition, early Filipino customs, and the Battle of Mactan."),
  ("Battle of Mactan: Lapu-Lapu (1521)", "According to Pigafetta's eyewitness account, what tactical factor contributed decisively to the defeat and death of Ferdinand Magellan in the Battle of Mactan (April 27, 1521)?", "Magellan's ships could not approach the shore due to shallow reefs, forcing his heavily armored soldiers to wade through water while facing superior warrior numbers and terrain.", ["Lapu-Lapu's warriors possessed advanced European artillery and steam cannons.", "Magellan was poisoned by his own Spanish crew before landing on the beach.", "A massive volcanic eruption destroyed Magellan's fleet during the duel."], "Pigafetta recorded that shallow coral reefs prevented Magellan's ships from anchoring close enough for cannon fire to support his 49 landing troops, leaving them vulnerable to Mactan warriors."),
  ("Pre-Colonial Society: Plasencia's Customs of the Tagalogs", "Fray Juan de Plasencia's 1589 account Relación de las Costumbres de los Tagalos describes pre-colonial social stratification. In this society, the 'Timawa' were:", "Free men / commoners who did not pay tribute or render forced manual labor to the datu, but accompanied him in war.", ["The ruling hereditary aristocratic chieftains and lawgivers.", "Slaves who lived inside their master's house with zero property rights (Aliping Saguiguilid).", "Foreign European merchants residing in coastal trading enclaves."], "Plasencia documented Tagalog social classes: Datu (chiefs), Maharlica (nobles), Timawa (freemen), Aliping Namamahay (serfs with own houses), and Aliping Saguiguilid (household slaves)."),
  ("Pre-Colonial Society: Aliping Namamahay vs Saguiguilid", "In Plasencia's account, an 'Aliping Namamahay' differed from an 'Aliping Saguiguilid' because the Namamahay:", "Lived in their own private houses, owned personal property, and could not be arbitrarily sold by their master.", ["Could be bought and sold at will and lived inside the master's private quarters.", "Held sovereign judicial power over criminal disputes in the barangay.", "Were exempt from all military service during inter-island expeditions."], "Aliping Namamahay were tenant-like serfs who owned property and lived in their own homes, whereas Aliping Saguiguilid were household slaves lacking independent property who could be transferred."),
  ("Cavite Mutiny (1872): Spanish vs Filipino Accounts", "Governor-General Rafael Izquierdo's official Spanish report framed the 1872 Cavite Mutiny as:", "A premeditated, vast separatist conspiracy led by native secular clergy (GOMBURZA) to overthrow Spanish sovereignty in the islands.", ["A minor localized labor mutiny over the sudden abolition of tax and polo exemptions for arsenal workers.", "A commercial dispute regarding maritime tobacco monopoly shipping tariffs.", "A peaceful religious pilgrimage that was accidentally dispersed by municipal police."], "Izquierdo and Spanish authorities used the mutiny to fabricate a grand treason narrative against Filipino reformists and secular priests, leading to the execution of GOMBURZA."),
  ("Cavite Mutiny: Trinidad Pardo de Tavera's Account", "Dr. Trinidad Pardo de Tavera and French writer Edmund Plauchut argued that the 1872 Cavite incident was essentially:", "A localized mutiny by Filipino arsenal workers and soldiers protesting the abolition of their long-standing tax and labor exemptions.", ["A full-scale socialist revolution organized by the Katipunan.", "A foreign naval invasion orchestrated by the British Empire.", "A religious dispute regarding Latin liturgical translations."], "Pardo de Tavera documented that the mutiny was a localized reaction to Governor-General Izquierdo's harsh decree removing exemptions from tribute and polo y servicio for Cavite arsenal workers."),
  ("Execution of GOMBURZA (1872)", "The public garrote execution of Fathers Mariano Gomez, Jose Burgos, and Jacinto Zamora on February 17, 1872 served as a turning point in Philippine history because:", "It awakened Filipino national consciousness and galvanized a whole generation of reformists, including Jose Rizal.", ["It convinced the Spanish Crown to grant immediate independence to the Philippines.", "It resulted in the immediate expulsion of all Spanish religious orders from Asia.", "It led to the signing of the Treaty of Paris with the United States."], "The martyrdom of GOMBURZA shattered the illusion of Spanish justice, profoundly radicalizing young Filipinos and inspiring the Propaganda Movement; Rizal dedicated El Filibusterismo to their memory."),
  ("The Cry of Balintawak / Pugad Lawin Controversy", "Historians analyze conflicting primary testimonies from Pio Valenzuela, Santiago Alvarez, and Guillermo Masangkay regarding the 'Cry' of August 1896, which centers on disagreements over:", "The exact date (August 23, 24, or 26) and precise geographical location where Katipuneros tore their cédulas and declared revolution.", ["Whether Andres Bonifacio was actually present during the Philippine Revolution.", "The total monetary budget spent on buying gunpowder from American merchants.", "The Latin grammatical phrasing used in the Katipunan initiation oaths."], "Primary accounts by participants conflict regarding whether the Cry occurred at Pugad Lawin on Aug 23 (Valenzuela), Bahay Toro on Aug 24 (Alvarez), or Balintawak on Aug 26 (Masangkay)."),
  ("1899 Malolos Constitution: Separation of Church and State", "The Malolos Constitution, drafted by Felipe Calderon for the First Philippine Republic, was marked by intense parliamentary debate that was decided by a single vote on the issue of:", "The separation of Church and State and freedom of religious worship (Article 5).", ["The immediate adoption of English as the sole national language.", "The annexation of the Philippine archipelago to the British Commonwealth.", "The total abolition of all municipal taxation."], "The Malolos Congress engaged in a fiery debate between those favoring Roman Catholicism as the state religion and those demanding complete separation of Church and State, passed by a one-vote margin (amendment by Pablo Tecson)."),
  ("Agrarian Reform History: Spanish Encomienda System", "During the early Spanish colonial era, the 'Encomienda' was:", "A royal grant entrusting a Spanish conquistador with the right to collect tribute from natives in exchange for protection and religious instruction.", ["A title of absolute private real estate ownership over the physical soil.", "A public agricultural college established to train native farmers in sugar refining.", "A commercial trading ship operating between Manila and Acapulco."], "The encomienda was not a land grant, but a grant of royal administrative jurisdiction empowering the encomendero to collect tribute and draft labor in exchange for maintaining peace and Catholic conversion."),
  ("Agrarian Reform History: Friar Lands & CARP", "The large agrarian haciendas acquired by Spanish religious orders that became centers of agrarian unrest in Laguna, Cavite, and Bulacan were known as:", "Friar Lands (Haciendas de los Frailes).", ["Encomienda Real.", "Comandancias Politico-Militares.", "Sitios de Ganado Mayor."], "Friar lands dominated rich agricultural regions; disputes over rental hikes (such as the Calamba Hacienda dispute involving Rizal's family) fueled widespread revolutionary fervor."),
  ("Taxation History: Polo y Servicio & Bandala", "Under Spanish colonial taxation, 'Polo y Servicio' was mandatory forced manual labor for 40 days (later 15 days), while 'Bandala' was:", "The compulsory sale of agricultural crops (such as rice and tobacco) to the colonial government at fixed, low, or promissory prices.", ["A head tax paid annually to obtain a personal identification document (Cédula).", "A direct tax on imported Chinese porcelain and Mexican silver coins.", "A tithe paid exclusively to local municipal parish priests."], "Bandala was an oppressive economic system where Filipino farmers were forced to sell their harvest quotas to the government, which often paid with worthless promissory notes.")
]
d.extend([
  ("Rizal Law: RA 1425 Legislative History", "Republic Act 1425 (The Rizal Law), authored primarily by Senator Claro M. Recto and sponsored by Jose P. Laurel, mandated:", "The compulsory inclusion of courses on the life, works, and writings of Jose Rizal, particularly Noli Me Tangere and El Filibusterismo, in all educational curricula.", ["The mandatory conversion of all Philippine universities into state military academies.", "The banning of Spanish language teaching in secondary schools.", "The total confiscation of all private ancestral land holdings in Luzon."]),
  ("Rizal Law: Controversy and Catholic Opposition", "During the 1956 congressional debates on the Rizal Bill, the Catholic Church hierarchy fiercely opposed the measure on the grounds that:", "Rizal's novels contained passages that allegedly attacked Catholic dogmas, clergy, and religious institutions, violating religious freedom.", ["The bill would increase national public debt and inflation rates.", "Rizal had advocated for the annexation of the Philippines by the British Empire.", "The novels were written in outdated Spanish prose that students could not read."]),
  ("Rizal's Poetry: A La Juventud Filipina (1879)", "In his prize-winning poem A La Juventud Filipina (To the Philippine Youth), the 18-year-old Jose Rizal famously called the Filipino youth:", "'Bella esperanza de la Patria Mia' (Fair hope of my Fatherland), urging them to use arts and sciences for national glory.", ["'Los bravos soldados de la Corona' (The brave soldiers of the Spanish Crown).", "'Los herederos del Imperio Romano' (The heirs of the Roman Empire).", "'Los siervos obedientes de la Iglesia' (The obedient servants of the Church)."]),
  ("Rizal's Annotations of Morga's Sucesos (1890)", "Why did Jose Rizal spend months at the British Museum in London transcribing and annotating Antonio de Morga's 1609 Sucesos de las Islas Filipinas?", "To prove scientifically that pre-colonial Filipinos had a rich, civilized culture, flourishing trade, high literacy, and maritime industry before Spanish arrival.", ["To write a military manual for immediate armed uprising in Manila.", "To secure a lucrative commercial publishing copyright from English merchants.", "To translate British constitutional law into Tagalog dialect."]),
  ("Rizal's Essay: Sobre la Indolencia de los Filipinos", "In his celebrated 1890 essay Sobre la Indolencia de los Filipinos (On the Indolence of the Filipinos), Rizal argued that Filipino indolence was:", "A chronic symptom and direct result of Spanish misrule, forced labor (polo), lack of economic incentives, and poor education, rather than an innate racial trait.", ["An immutable genetic defect inherited from ancient ancestors.", "A myth invented entirely by British travelers in the 19th century.", "A temporary physical illness caused by drinking impure well water."]),
  ("Rizal's Essay: Filipinas Dentro de Cien Años", "In Filipinas Dentro de Cien Años (The Philippines a Century Hence, 1889-1890), Rizal presciently predicted that if Spain failed to reform, the Philippines would:", "Declare independence through revolution and likely fall under the geopolitical influence of the United States of America.", ["Be peacefully purchased by the German Empire for agricultural trade.", "Voluntarily merge into the British Raj in India.", "Return permanently to pre-colonial tribal sultanates."]),
  ("Rizal's Letter to the Young Women of Malolos (1889)", "In his famous letter to the 20 young women of Malolos who petitioned to open a Spanish-language night school, Rizal emphasized that:", "Mothers are the first teachers of children and must be enlightened, courageous, rational, and free from blind superstitious obedience.", ["Women should remain strictly confined to domestic kitchen chores and silent prayer.", "Women should avoid learning Spanish to preserve indigenous tribal dialects.", "Women must surrender all property titles to local monastic parish priests."]),
  ("Noli Me Tangere: Title Meaning and Dedication", "The title Noli Me Tangere is a Latin phrase taken from the Gospel of John (20:17) meaning 'Touch Me Not'. To whom did Rizal dedicate this first novel?", "To his beloved Fatherland (A Mi Patria) to expose the social cancer afflicting Philippine society.", ["To the three secular martyr priests (GOMBURZA).", "To his European ophthalmology professors in Heidelberg.", "To the Spanish Governor-General Emilio Terrero."]),
  ("El Filibusterismo: Dedication to GOMBURZA", "Unlike Noli Me Tangere, Rizal's darker, more radical second novel El Filibusterismo (published in Ghent, 1891) was explicitly dedicated to:", "The memory of the three martyr priests Gomez, Burgos, and Zamora (GOMBURZA) executed in 1872.", ["The Spanish Queen Regent Maria Cristina.", "The Katipunan supreme council headed by Andres Bonifacio.", "The Filipino student community in Barcelona."]),
  ("Noli Me Tangere: Character Symbolism (Crisostomo Ibarra)", "In Noli Me Tangere, Juan Crisostomo Ibarra represents:", "The idealistic, educated, wealthy Filipino reformist who believes progress and national redemption can be achieved through education and institutional reforms.", ["The radical revolutionary advocating violent armed terrorism.", "The uneducated peasant driven to banditry by friar landgrabbing.", "The hypocritical native who mimics Spanish high society."]),
  ("Noli Me Tangere: Character Symbolism (Elias)", "In Noli Me Tangere, the enigmatic boatman 'Elias' represents:", "The common, oppressed masses who have lost faith in peaceful reform and believe violent revolution is the inevitable path to justice.", ["The corrupt secular municipal police force (Guardia Civil).", "The wealthy collaborator class seeking colonial titles.", "The pious church devotee blindly following friar decrees."]),
  ("Noli Me Tangere: Character Symbolism (Maria Clara)", "Maria Clara, daughter of Capitan Tiago and Dona Pia Alba (fathered by Padre Damaso), culturally symbolizes:", "The pure, pious, sheltered, and suffering Filipino womanhood conditioned by colonial religious dogma.", ["The fierce indigenous warrior chieftain leading armed revolts.", "The modern commercial businesswoman in urban Manila.", "The secular scientific academic researcher."]),
  ("Noli Me Tangere: Character Symbolism (Sisa)", "The tragic character 'Sisa', who loses her sanity after her young sons Crispin and Basilio are brutalized by the church sacristan mayor, symbolizes:", "The suffering, impoverished Motherland (Patria) driven to madness and despair by colonial oppression.", ["The wealthy Spanish peninsulares living in Intramuros.", "The corrupt municipal tax collectors.", "The secularized university faculty."]),
  ("El Filibusterismo: Character Transformation (Simoun)", "In El Filibusterismo, Crisostomo Ibarra returns disguised as the sinister, wealthy jeweler 'Simoun', whose secret objective is to:", "Accelerate colonial corruption, tyranny, and economic misery to spark widespread public outrage and violent revolution.", ["Open an accredited vocational high school in San Diego.", "Reconcile peacefully with Padre Damaso and marry Maria Clara in Spain.", "Surrender his fortune to the Royal Audiencia in Manila."]),
  ("El Filibusterismo: The Deathbed Dialogue of Simoun & Padre Florentino", "In the concluding chapter of El Filibusterismo, what profound philosophical truth does Padre Florentino impart to the dying Simoun?", "Hate never produces anything but monsters, and crime never produces freedom; national liberation is achieved through virtue, sacrifice, and love, not terrorism.", ["Violent assassinations and chemical bombs are the only guaranteed path to democracy.", "Filipinos should permanently remain loyal colonial subjects of the Spanish Crown.", "Wealth and gold can purchase sovereign independence from international banks."])
])
d.extend([
  ("Rizal in Dapitan Exile (1892-1896): Multifaceted Service", "During his four-year exile in Dapitan, Zamboanga del Norte, Rizal demonstrated practical community leadership by:", "Operating an eye clinic, opening a school for local boys, engineering a gravity waterworks system, and collecting biological specimens.", ["Organizing an armed naval assault against the Spanish fleet in Manila.", "Publishing commercial mining stocks in Madrid stock exchanges.", "Serving as the municipal mayor under the Spanish colonial army."]),
  ("Rizal in Dapitan: Biological Discoveries", "While in Dapitan exile, Rizal sent zoological specimens to the Dresden Museum in Germany, resulting in which three species being named in his honor?", "Draco rizali (flying lizard), Apogonia rizali (small beetle), and Rhacophorus rizali (tree frog).", ["Panthera rizali, Equus rizali, and Crocodylus rizali.", "Tarsius rizali, Pithecophaga rizali, and Bubalus rizali.", "Gallus rizali, Sus rizali, and Cervus rizali."]),
  ("Rizal's Final Poem: Mi Ultimo Adios (1896)", "On the eve of his execution at Bagumbayan (December 30, 1896), Rizal hid his untitled farewell masterpiece (later titled Mi Ultimo Adios) inside:", "An alcohol cooking lamp (cocinilla) which he handed to his sister Trinidad with the whisper 'There is something inside'.", ["The inner lining of his leather boots.", "The pocket of his woolen overcoat.", "A hollowed-out Spanish dictionary."]),
  ("The Retraction Controversy: Historical Debate", "Historians debate whether Jose Rizal signed an official document retracting his Masonic affiliation and anti-Catholic writings prior to his execution because:", "The alleged original document was discovered 39 years later in 1935 by Fr. Manuel Garcia, with conflicting text versions and questionable witnesses.", ["Rizal was publicly executed by hanging in London instead of Manila.", "The Spanish Crown destroyed all colonial archives in 1898.", "No Spanish friars ever visited Rizal in Fort Santiago."]),
  ("La Liga Filipina (July 3, 1892)", "Jose Rizal founded the civic organization 'La Liga Filipina' in Tondo, Manila with which core motto and objective?", "'Unus Instar Omnium' (One Like All), aiming to unite the archipelago into a compact, vigorous, and homogenous body for mutual protection and economic progress.", ["'Viva Espana' (Long Live Spain), aiming to assimilate the Philippines into a Spanish province.", "'Kalayaan o Kamatayan' (Freedom or Death), aiming for immediate armed insurrection.", "'Pax Romana', aiming to restore medieval monastic feudalism."]),
  ("Katipunan Founding (July 7, 1892)", "Immediately following the arrest and deportation of Jose Rizal to Dapitan on July 7, 1892, Andres Bonifacio, Teodoro Plata, and Ladislao Diwa founded:", "Kataas-taasang, Kagalang-galangang Katipunan ng mga Anak ng Bayan (KKK), concluding that peaceful reform had failed.", ["The Federal Party of the Philippines.", "The National Democratic Movement.", "The Philippine Independent Church (IFI)."]),
  ("Propaganda Movement: La Solidaridad", "The official fortnightly newspaper of the Propaganda Movement published in Barcelona and Madrid from 1889 to 1895 to advocate peaceful political reforms was:", "La Solidaridad (first edited by Graciano Lopez Jaena, later by Marcelo H. del Pilar).", ["Kalayaan (official organ of the Katipunan).", "El Heraldo de la Revolucion.", "La Independencia."]),
  ("Propaganda Movement: Core Demands", "Which of the following was a primary political objective advocated by the Filipino reformists in La Solidaridad?", "Representation of the Philippines in the Spanish Cortes, secularization of parishes, freedom of speech/press, and equality before the law.", ["Immediate armed military invasion of Madrid by Filipino guerrillas.", "The unconditional expulsion of all Chinese merchants from Southeast Asia.", "The permanent re-establishment of the Manila-Acapulco Galleon Trade."]),
  ("1896 Philippine Revolution: Tejeros Convention (1897)", "At the contentious Tejeros Convention in San Francisco de Malabon, Cavite (March 22, 1897), the conflict between the Magdalo and Magdiwang factions culminated in:", "The establishment of a new revolutionary government electing Emilio Aguinaldo as President and the insult against Andres Bonifacio by Daniel Tirona.", ["The signing of the Treaty of Paris ending the Spanish-American War.", "The unconditional surrender of all Filipino revolutionary forces to Spain.", "The dissolution of the First Philippine Republic."]),
  ("Pact of Biak-na-Bato (December 1897)", "The Pact of Biak-na-Bato brokered between Governor-General Primo de Rivera and Emilio Aguinaldo established that:", "Aguinaldo and revolutionary leaders would go into voluntary exile in Hong Kong in exchange for 800,000 Mexican pesos in indemnities and promised reforms.", ["Spain granted complete sovereign independence to the Philippine archipelago.", "The United States annexed the Philippines as an unincorporated territory.", "Andres Bonifacio was reinstated as Supreme Leader of the Katipunan."]),
  ("Declaration of Philippine Independence (June 12, 1898)", "The Acta de la Proclamacion de la Independencia del Pueblo Filipino read in Kawit, Cavite on June 12, 1898 was drafted and read by:", "Ambrosio Rianzares Bautista.", ["Emilio Aguinaldo.", "Apolinario Mabini.", "Felipe Agoncillo."]),
  ("Philippine Flag Symbolism (1898)", "The original Philippine national flag sewn in Hong Kong by Marcela Agoncillo, Lorenza Agoncillo, and Delfina Herbosa featured three golden stars symbolizing:", "Luzon, Panay (representing the Visayas), and Mindanao.", ["Luzon, Visayas, and Palawan.", "Manila, Cavite, and Laguna.", "Freedom, Equality, and Fraternity."]),
  ("Philippine National Anthem: Lupang Hinirang", "The musical score of the Philippine national anthem (originally Marcha Nacional Filipina) was composed by Julian Felipe, while the original Spanish lyrics were written by:", "Jose Palma (in his 1899 poem Filipinas).", ["Jose Rizal.", "Marcelo H. del Pilar.", "Amado V. Hernandez."]),
  ("Treaty of Paris (December 10, 1898)", "Under the Treaty of Paris that concluded the Spanish-American War, Spain ceded the Philippines to the United States for the sum of:", "$20,000,000 (Twenty Million US Dollars).", ["$50,000,000.", "$10,000,000.", "$5,000,000."]),
  ("Philippine-American War: San Juan Bridge Incident (1899)", "The Philippine-American War officially broke out on the night of February 4, 1899 when:", "Private William W. Grayson of the US Army shot and killed a Filipino soldier at the corner of Calle Sociego and Silencio in Santa Mesa, Manila.", ["Filipino revolutionary troops shelled the American naval fleet in Subic Bay.", "General Douglas MacArthur invaded Lingayen Gulf.", "President William McKinley was assassinated in Washington, D.C."])
])
d.extend([
  ("Battle of Tirad Pass (1899): Gregorio del Pilar", "General Gregorio del Pilar, the 'Boy General', fought heroically and sacrificed his life at the Battle of Tirad Pass on December 2, 1899 primarily to:", "Delay the advancing American forces (33rd Infantry under Major March) and cover the retreat of President Emilio Aguinaldo into Northern Luzon.", ["Capture the American naval supply fleet anchored in Ilocos Sur.", "Sign an armistice agreement with General Elwell Otis.", "Rescue captured Spanish friars held in Isabela."]),
  ("Capture of Aguinaldo in Palanan (1901)", "President Emilio Aguinaldo was captured in Palanan, Isabela on March 23, 1901 through an undercover operation orchestrated by:", "General Frederick Funston using pro-American Macabebe Scouts disguised as revolutionary reinforcements.", ["General Arthur MacArthur leading a direct cavalry charge.", "Commodore George Dewey using naval battleship bombardments.", "Filipino reformist diplomats from the Hong Kong junta."]),
  ("American Colonial Governance: Philippine Bill of 1902", "The Cooper Act (Philippine Organic Act of 1902) provided for the establishment of which landmark democratic institution in the Philippines?", "The Philippine Assembly (an elected bicameral lower house for Filipino legislators inaugurated in 1907).", ["The Supreme Court of the United States in Manila.", "The Philippine Commonwealth Government.", "The Central Bank of the Philippines."]),
  ("American Colonial Legislation: Sedition Law of 1901", "During the early American pacification era, Act No. 292 (Sedition Act of 1901) strictly penalized:", "Any person who advocated or uttered seditious words against US authority, or promoted Philippine independence even peacefully.", ["Importing American manufactured goods into Manila ports.", "Teaching English language courses in public elementary schools.", "Refusing to pay municipal property taxes."]),
  ("American Colonial Legislation: Flag Law of 1907", "Act No. 1696 (The Flag Law of 1907) enacted by the Philippine Commission prohibited:", "The public display of the Philippine national flag, Katipunan banners, emblems, and patriotic symbols.", ["The flying of the American Stars and Stripes over government buildings.", "The manufacture of cotton textiles in Ilocos provinces.", "The printing of Spanish language newspapers."]),
  ("Jones Law of 1916 (Philippine Autonomy Act)", "The Jones Law of 1916 is of paramount historical importance because its preamble officially pledged that:", "The United States would grant Philippine independence as soon as a stable government could be established.", ["The Philippines would become a permanent 51st state of the American Union.", "Filipinos would be granted full citizenship rights inside mainland USA.", "English would be replaced by Tagalog as the sole official language of administration."]),
  ("Tydings-McDuffie Act of 1934 (Philippine Independence Act)", "The Tydings-McDuffie Act authored by Sen. Millard Tydings and Rep. John McDuffie provided for:", "A 10-year transition period under the Philippine Commonwealth leading to full sovereign independence on July 4, 1946.", ["Immediate unconditional independence within 24 hours of signing.", "The permanent annexation of Mindanao as an American territory.", "The abolition of all Philippine military and police forces."]),
  ("1935 Philippine Constitution: Commonwealth Government", "The 1935 Philippine Constitution was ratified to establish the Commonwealth of the Philippines, electing which leaders as President and Vice President?", "Manuel L. Quezon (President) and Sergio Osmena (Vice President).", ["Jose P. Laurel (President) and Benigno Aquino Sr. (Vice President).", "Emilio Aguinaldo (President) and Mariano Trias (Vice President).", "Ramon Magsaysay (President) and Carlos P. Garcia (Vice President)."]),
  ("Commonwealth Era: National Language Policy", "Under President Manuel L. Quezon (Executive Order No. 134, Dec. 30, 1937), which indigenous Philippine language was chosen as the basis for the National Language?", "Tagalog, recommended by the Institute of National Language (Surian ng Wikang Pambansa).", ["Cebuano (Sugbuanon).", "Ilocano (Samtoy).", "Hiligaynon (Ilonggo)."]),
  ("World War II: Fall of Bataan (April 9, 1942)", "Following months of heroic resistance without food and ammunition, Major General Edward P. King Jr. surrendered Allied forces on Bataan, leading directly to:", "The infamous Bataan Death March, where 75,000 Filipino and American prisoners were forced to march over 100 kilometers to Camp O'Donnell under brutal conditions.", ["The immediate liberation of Manila by naval forces.", "The unconditional surrender of the Imperial Japanese Navy.", "The signing of the San Francisco Peace Treaty."]),
  ("World War II: Fall of Corregidor (May 6, 1942)", "The last fortress of Allied resistance in Manila Bay to fall to Japanese forces under General Masaharu Homma was:", "Corregidor Island (under Lieutenant General Jonathan Wainwright).", ["Fort Santiago in Intramuros.", "Camp John Hay in Baguio.", "Mactan Island in Cebu."]),
  ("World War II: Second Philippine Republic (Laurel)", "During the Japanese occupation (1942-1945), who served as President of the Japanese-sponsored Second Philippine Republic, striving to shield citizens from atrocities?", "Jose P. Laurel.", ["Jorge Vargas.", "Manuel Roxas.", "Benigno Aquino Sr."]),
  ("Post-War Independence (July 4, 1946)", "On July 4, 1946, the United States formally recognized the independence of the Republic of the Philippines (Third Republic), inaugurating as President:", "Manuel A. Roxas.", ["Elpidio Quirino.", "Ramon Magsaysay.", "Diosdado Macapagal."]),
  ("Post-War Legislation: Bell Trade Act & Parity Rights", "The controversial Bell Trade Act of 1946 conditioned US post-war rehabilitation funds on the Philippine Constitution being amended to grant:", "Parity Rights (granting US citizens equal rights as Filipinos in the exploitation of natural resources and public utilities).", ["Free passage for Filipino immigrants to mainland USA.", "The immediate abolition of all American military bases in Clark and Subic.", "The total cancellation of all Philippine foreign debt."]),
  ("Post-War Governance: Ramon Magsaysay ('Man of the Masses')", "President Ramon Magsaysay (1953-1957) successfully quelled the agrarian Hukbalahap rebellion and earned public adoration by championing:", "'Those who have less in life should have more in law', opening Malacanang to the common people and instituting rural land resettlement (EDCOR).", ["Massive militarization and martial law across all provinces.", "Total alignment with Soviet communist satellite states.", "Banning all foreign investments in Philippine agriculture."])
])
d.extend([
  ("Post-War Governance: Carlos P. Garcia ('Filipino First Policy')", "President Carlos P. Garcia's administration (1957-1961) is best remembered for enacting the 'Filipino First Policy' (Resolution No. 204), which gave priority to:", "Filipino business enterprises and local capital over foreign investors in foreign exchange allocations and economic concessions.", ["Foreign multinational monopolies over local cooperative guilds.", "Agricultural crop export monopolies owned by colonial landlords.", "The complete privatization of all national public schools."]),
  ("Post-War Governance: Diosdado Macapagal's Independence Date Shift", "President Diosdado Macapagal (1961-1965) officially changed Philippine Independence Day from July 4 to June 12 by signing Proclamation No. 28, declaring that:", "True national independence was declared by Filipinos themselves in Kawit, Cavite on June 12, 1898, rather than granted by a foreign nation.", ["July 4 had zero historical documentation in American colonial records.", "Spain requested the change during a diplomatic summit in Madrid.", "June 12 coincided with the harvest of the national agricultural crop."]),
  ("1972 Martial Law: Proclamation 1081", "President Ferdinand E. Marcos signed Proclamation No. 1081 placing the entire Philippines under Martial Law on September 21, 1972 (announced Sept 23), citing:", "The threat of communist rebellion (CPP-NPA) and civil unrest, leading to authoritarian rule and parliamentary restructuring under the 1973 Constitution.", ["An imminent naval invasion by the British Empire.", "A severe agricultural drought in the Visayan islands.", "The total collapse of international maritime trade routes."]),
  ("1986 EDSA People Power Revolution", "The peaceful four-day popular uprising along Epifanio de los Santos Avenue (EDSA) on February 22-25, 1986 that ended 14 years of authoritarian rule was catalyzed by:", "The assassination of Ninoy Aquino, fraudulent results of the 1986 Snap Elections, and the military defection of Enrile and Ramos supported by Cardinal Sin.", ["An armed naval bombardment by international United Nations peacekeeping forces.", "A sudden nationwide general workers strike organized by foreign labor unions.", "The total destruction of the central banking currency vaults."]),
  ("1987 Philippine Constitution: Core Characteristics", "The 1987 Constitution ratified under President Corazon C. Aquino is characterized by:", "Robust human rights protections, institutional checks and balances, term limits, creation of the Commission on Human Rights, and strict limits on martial law.", ["The concentration of absolute lifetime power in the executive office.", "The total abolition of the Supreme Court and legislative branches.", "The permanent re-establishment of royal aristocratic titles."]),
  ("Rizal's Youth: Education in Ateneo Municipal", "Jose Rizal earned his Bachelor of Arts degree with highest honors (Sobresaliente) from the Ateneo Municipal de Manila, where Jesuit education emphasized:", "Rigid discipline, religious instruction, humanities, Latin, rhetoric, and competitive academic leagues (Roman and Carthaginian Empires).", ["Purely military naval strategy without academic coursework.", "Rote agricultural manual labor in colonial sugar plantations.", "Commercial banking and international currency speculation."]),
  ("Rizal's Youth: Studies at UST and Discrimination", "While studying Medicine and Philosophy at the University of Santo Tomas (UST), Rizal felt dissatisfied because:", "Dominican professors were perceived as hostile, obsolete pedagogical methods were used, and Filipino students suffered racial discrimination.", ["The university prohibited the reading of Latin textbooks.", "The campus was located in Madrid rather than Manila.", "The tuition fees were paid in Mexican silver coins."]),
  ("Rizal's Secret Departure for Spain (1882)", "Rizal departed secretly for Spain in May 1882 aboard the Spanish steamer Salvadora with the primary mission (shared with his brother Paciano) to:", "Observe European life, culture, laws, and governments in order to prepare himself for the liberation of his oppressed people.", ["Escape minor municipal gambling debts in Calamba.", "Seek a permanent commission as an officer in the Spanish Royal Navy.", "Establish a commercial tobacco export warehouse in Barcelona."]),
  ("Rizal in Madrid: Freemasonry Affiliation", "In 1883, Rizal joined the Masonic lodge Acacia in Madrid primarily because:", "Freemasons openly criticized friar abuses in the Philippines and championed freedom of speech, human dignity, and progressive thought.", ["It was a secret military organization dedicated to manufacturing firearms.", "It offered guaranteed financial stipends to international university students.", "It was mandatory for obtaining a European medical license."]),
  ("Rizal's Medical Specialization: Ophthalmology", "Rizal chose to specialize in ophthalmology under Dr. Louis de Wecker in Paris and Dr. Otto Becker in Heidelberg primarily to:", "Cure the failing eyesight of his beloved mother, Dona Teodora Alonso Realonda.", ["Earn exorbitant medical consultation fees in wealthy European capitals.", "Manufacture glass lenses for military sniper rifles.", "Secure an appointment as royal physician to the Spanish monarchy."]),
  ("Rizal's Poem: Sa Aking Mga Kabata Controversy", "Modern historical scholars (e.g., Ambeth Ocampo, Virgilio Almario) have cast serious doubt on whether the 8-year-old Rizal authored the poem 'Sa Aking Mga Kabata' because:", "The poem contains the word 'kalayaan' (which Rizal admitted he first encountered in 1882) and utilizes 20th-century Tagalog orthography not used in 1869.", ["Rizal never learned to speak or write the Tagalog language.", "The original manuscript was written in ancient German gothic script.", "The poem was officially signed by Andres Bonifacio in 1896."]),
  ("Rizal's Mother: Dona Teodora Alonso Realonda", "Dona Teodora Alonso, Rizal's first teacher, was an extraordinary woman of high culture and intellect who influenced him deeply by:", "Teaching him the alphabet, cultivating his love for literature through fables (e.g., The Moth and the Flame), and modeling moral courage.", ["Encouraging him to avoid reading books to prevent eyesight strain.", "Forcing him to pursue a career as a Spanish naval officer.", "Demanding that he enter a monastic cloistered monastery in Rome."]),
  ("Rizal and the Calamba Land Dispute (1887-1888)", "Upon his first return to Calamba in 1887, Rizal drafted an official petition for the Calamba tenants documenting:", "The arbitrary rental increases, failure of the Dominican hacienda to issue receipts, and dispossession of farmers, resulting in the eviction of his family.", ["A demand that all Calamba farms be sold to British tea merchants.", "A request that the Spanish government build a military base on Mt. Makiling.", "An apology to the friars for delays in paying harvest tributes."]),
  ("Rizal's Final Hours: Bagumbayan (Dec. 30, 1896)", "At 7:03 AM on December 30, 1896, Jose Rizal was shot at Bagumbayan. As the execution squad fired, Rizal's final words were:", "'Consummatum est!' (It is finished!), followed by his turning to fall face upward toward the morning sun.", ["'Viva Espana!'", "'Patria Adorada!'", "'Libertad o Muerte!'"]),
  ("Significance of Rizal's Martyrdom in Nation-Building", "Jose Rizal is venerated as the foremost Philippine National Hero because:", "His intellectual genius, literary masterworks, and supreme moral sacrifice articulated a unified national identity and awakened a people to sovereign dignity.", ["He possessed the largest personal military army in Southeast Asia.", "He signed the Treaty of Paris that purchased the Philippine islands.", "He was appointed Governor-General of the Philippines by the Spanish Cortes."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item evaluates competence in {item[0]}. {item[2]} represents established historical and historiographical consensus."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('rizalExams.ts', 'RIZAL_EXAM_QUESTIONS', questions)
