import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Patterns in Nature: Fibonacci Sequence", "In the standard Fibonacci sequence defined recursively by F(n) = F(n-1) + F(n-2) with F(1)=1, F(2)=1, F(3)=2, F(4)=3, what is the 10th Fibonacci number (F10)?", "55.", ["34.", "89.", "144."], "The Fibonacci sequence is 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89... The 10th term F(10) = 55."),
  ("Patterns in Nature: The Golden Ratio (Phi)", "The ratio of consecutive terms in the Fibonacci sequence (F(n+1)/F(n)) converges as n approaches infinity to the Golden Ratio (Phi, Greek letter phi). What is its exact mathematical value?", "(1 + sqrt(5)) / 2 approximately equal to 1.6180339887...", ["(1 + sqrt(3)) / 2 approximately equal to 1.366.", "(1 + sqrt(2)) / 2 approximately equal to 1.207.", "(sqrt(5) - 1) / 2 approximately equal to 0.618."], "The Golden Ratio Phi = (1 + sqrt(5))/2 is the positive root of x^2 - x - 1 = 0, approximately 1.6180339887..."),
  ("Patterns in Nature: Fractals & Self-Similarity", "A geometric object that exhibits self-similarity across all scales—meaning any magnified part looks mathematically identical or similar to the whole object—is called a:", "Fractal (e.g., Mandelbrot Set, Koch Snowflake, Sierpinski Triangle, Romanesco broccoli).", ["Platonic Solid.", "Eulerian Circuit.", "Tessellated Polygon.", "Mobius Strip."], "Fractals possess self-similarity (repeating patterns at every scale) and typically have non-integer fractal dimensions."),
  ("Patterns in Nature: Regular Tessellations", "A 'Regular Tessellation' is a tiling of the plane using only one type of regular polygon with zero gaps or overlaps. Which are the only three regular polygons that can form regular tessellations?", "Equilateral Triangles, Squares, and Regular Hexagons.", ["Equilateral Triangles, Regular Pentagons, and Regular Octagons.", "Squares, Regular Pentagons, and Regular Decagons.", "Regular Hexagons, Regular Heptagons, and Regular Nonagons."], "Only polygons whose interior angles divide 360 degrees evenly can tile the plane regularly: Triangles (60 deg * 6 = 360), Squares (90 deg * 4 = 360), Hexagons (120 deg * 3 = 360)."),
  ("Patterns in Nature: Radial Symmetry", "A sea anemone, sunflower disc, or starfish whose body parts are arranged symmetrically around a central axis exhibits:", "Radial (Rotational) Symmetry.", ["Bilateral (Mirror) Symmetry.", "Asymmetry.", "Translational Symmetry only."], "Radial symmetry occurs when an organism can be divided into identical halves by any plane passing through its central longitudinal axis."),
  ("Mathematical Language: Sets & Subsets", "Given a set S with n distinct elements, what is the total number of subsets (including the empty set and S itself) in the power set P(S)?", "2^n.", ["2n.", "n^2.", "n! (n factorial)."], "The power set of a set with n elements always contains exactly 2^n subsets, since each element has 2 independent choices (included or excluded)."),
  ("Mathematical Logic: Conjunction vs Disjunction", "In symbolic logic, a compound proposition formed by the logical operator 'AND' (conjunction, p ^ q) is true only when:", "Both propositions p and q are simultaneously true.", ["At least one of the propositions is true.", "Proposition p is true and proposition q is false.", "Both propositions p and q are false."], "A conjunction (p ^ q) is strictly true only when both conjuncts are true; if either proposition is false, the entire conjunction is false."),
  ("Mathematical Logic: Conditional Statement (Implication)", "In symbolic logic, under what single truth-value condition is a conditional statement (p -> q, 'If p then q') evaluated as FALSE?", "When the antecedent (p) is TRUE and the consequent (q) is FALSE.", ["When both antecedent (p) and consequent (q) are false.", "When the antecedent (p) is false and the consequent (q) is true.", "When both antecedent (p) and consequent (q) are true."], "A conditional implication (p -> q) is false ONLY when a true antecedent leads to a false consequent (T -> F = F). In all other truth combinations, it is vacuously or genuinely true."),
  ("Mathematical Logic: Converse, Inverse, Contrapositive", "Given the conditional statement 'If it rains (p), then the ground is wet (q)', what is its logically equivalent Contrapositive?", "'If the ground is not wet (~q), then it does not rain (~p).'", ["'If the ground is wet (q), then it rains (p)' (Converse).", "'If it does not rain (~p), then the ground is not wet (~q)' (Inverse).", "'It rains (p) and the ground is not wet (~q)' (Negation)."], "A conditional statement (p -> q) is logically equivalent ONLY to its contrapositive (~q -> ~p). The converse (q -> p) and inverse (~p -> ~q) are equivalent to each other, but not to the original statement."),
  ("Mathematical Logic: Tautology vs Contradiction", "In propositional logic, a compound proposition that is evaluated as TRUE under all possible truth-value assignments of its components is a:", "Tautology (e.g., p v ~p).", ["Contradiction (e.g., p ^ ~p).", "Contingency.", "Fallacy."], "A tautology is a logical formula that is always true in every possible interpretation; a contradiction is always false; a contingency depends on the truth values."),
  ("Mathematical Reasoning: Inductive vs Deductive Reasoning", "A scientist observes 500 white swans across diverse European lakes and concludes: 'Therefore, all swans on Earth are white.' What form of reasoning was used, and is the conclusion guaranteed?", "Inductive reasoning (moving from specific observations to a general conclusion), which is probable but not logically guaranteed.", ["Deductive reasoning (moving from general premises to a specific certainty), which is absolutely guaranteed.", "Direct mathematical proof by contradiction.", "Transfinite transductive deduction."], "Inductive reasoning moves from specific empirical instances to generalized hypotheses; conclusions may be strongly supported, but are never guaranteed against counterexamples (such as black swans)."),
  ("Mathematical Reasoning: Deductive Proof", "Consider the argument: 'All humans are mortal (Premise 1). Socrates is human (Premise 2). Therefore, Socrates is mortal (Conclusion).' This valid argument exemplifies:", "Deductive reasoning, where the conclusion necessarily follows with certainty from true general premises.", ["Inductive generalization from statistical sampling.", "Abductive guessing based on incomplete data.", "Post hoc correlational inference."], "Deductive reasoning applies general principles/rules to specific cases to reach logically certain, valid conclusions."),
  ("Statistics: Measures of Central Tendency", "Given the discrete data set of quiz scores: 12, 15, 15, 18, 20, 22, 90. Which measure of central tendency provides the most realistic, robust representation of typical student performance in the presence of the extreme outlier (90)?", "Median (the middle score when data is ordered: 18).", ["Mean (arithmetic average: 27.4).", "Mode (most frequent score: 15).", "Mid-range (51)."], "The median is resistant/robust to extreme outliers, whereas the arithmetic mean is pulled heavily toward extreme values (90), inflating the average."),
  ("Statistics: Measures of Dispersion (Standard Deviation)", "What does a very low Standard Deviation (e.g., SD = 1.2) indicate about a distribution of exam scores compared to a high Standard Deviation (e.g., SD = 9.8)?", "The scores are closely clustered and concentrated near the mean, indicating high consistency/homogeneity.", ["The students performed poorly and failed the examination.", "The exam had zero validity and reliability.", "The scores are extremely spread out, dispersed, and heterogeneous."], "Standard deviation measures the average dispersion or spread of data points from the arithmetic mean. Low SD indicates tight clustering/homogeneity; high SD indicates wide spread/heterogeneity."),
  ("Statistics: Empirical Rule (Normal Distribution 68-95-99.7)", "In a perfectly bell-shaped, symmetrical Normal Distribution, approximately what percentage of all data values fall within plus or minus 2 standard deviations (mu +- 2 sigma) of the mean?", "95.44% (approximately 95%).", ["68.26% (approximately 68%).", "99.73% (approximately 99.7%).", "50.00%."], "The Empirical (68-95-99.7) Rule for normal distributions dictates: ~68% falls within 1 SD, ~95% falls within 2 SD, and ~99.7% falls within 3 SD of the mean.")
]
d.extend([
  ("Statistics: Standard Scores (Z-Score)", "A student scores X = 85 on a nationwide test where the population mean is mu = 70 and standard deviation is sigma = 10. What is the student's Z-Score, and what does it signify?", "Z = +1.5, meaning the score is 1.5 standard deviations above the population mean.", ["Z = +15.0, meaning the student scored 15 times better than average.", "Z = -1.5, meaning the score is 1.5 standard deviations below average.", "Z = +0.85, indicating an 85th percentile rank."]),
  ("Statistics: Pearson Correlation Coefficient (r)", "A Pearson correlation coefficient of r = -0.88 between student hours spent playing mobile games and final GPA indicates:", "A strong negative linear relationship (as gaming hours increase, GPA significantly decreases).", ["A weak positive linear relationship.", "Zero statistical correlation between the two variables.", "That playing mobile games directly causes biological brain damage."]),
  ("Statistics: Correlation vs Causation", "A statistical study finds a strong positive correlation (r = +0.91) between ice cream sales and drownings at beaches. This high correlation is best explained by:", "A confounding / lurking third variable (hot summer weather) that independently increases both swimming and ice cream consumption.", ["Eating ice cream directly causes swimmers to suffer fatal muscle cramps.", "Drownings cause survivors to buy ice cream to soothe emotional grief.", "Statistical data collection fraud by ice cream manufacturers."]),
  ("Mathematics of Finance: Simple Interest Formula", "How much Simple Interest (I = P * r * t) is earned on a principal investment of P = Php 50,000 invested at an annual interest rate of r = 6% for a period of t = 3 years?", "Php 9,000.", ["Php 3,000.", "Php 15,000.", "Php 59,000."]),
  ("Mathematics of Finance: Compound Interest Formula", "Using the compound interest formula A = P(1 + r/n)^(nt), what is the total future maturity value of P = Php 100,000 invested for t = 2 years at an annual interest rate of r = 8% compounded semi-annually (n = 2)?", "Php 116,985.86.", ["Php 116,000.00.", "Php 108,000.00.", "Php 136,048.90."]),
  ("Mathematics of Finance: Compounding Frequency Power", "Why does compound interest generate significantly greater long-term wealth than simple interest at the identical nominal rate?", "Because interest earned in each period is added to the principal, earning interest on accumulated interest exponentially.", ["Because simple interest formulas deduct government income tax automatically.", "Because compound interest relies on unpredictable stock market gambles.", "Because banks waive all administrative fees for compound accounts."]),
  ("Mathematics of Finance: Annuities (Ordinary Annuity)", "An 'Ordinary Annuity' in financial mathematics is defined as:", "A sequence of equal, periodic cash payments made or received at the END of each compounding period.", ["A lump-sum deposit left untouched for 50 years without interest.", "A cash payment made at the beginning of each period (Annuity Due).", "A lottery jackpot that decreases in value each month."]),
  ("Mathematics of Finance: Amortization", "When a homeowner pays off a 15-year mortgage through regular monthly payments, 'Amortization' ensures that over time:", "The proportion of each monthly payment allocated to principal increases, while the proportion allocated to interest decreases.", ["The entire monthly payment pays only interest for 15 years with zero principal reduction.", "The monthly payment doubles in price every calendar year.", "The interest rate increases exponentially every month."]),
  ("Voting Theory: Plurality Method", "In an election with four candidates, Candidate A receives 38% of first-place votes, Candidate B receives 32%, Candidate C receives 20%, and Candidate D receives 10%. Under the 'Plurality Method', the winner is:", "Candidate A (the candidate with the highest number of first-place votes, regardless of whether a majority is reached).", ["Candidate B, because B has fewer negative votes.", "No one; a new election must be called with different candidates.", "Candidates A and B must share the executive office jointly."]),
  ("Voting Theory: Majority Criterion", "The 'Majority Criterion' in social choice theory states that if a candidate receives more than 50% of all first-place votes, that candidate should:", "Always win the election.", ["Be eliminated in the first round of voting.", "Compete in a coin toss against the runner-up.", "Receive an honorary medal without taking office."]),
  ("Voting Theory: Borda Count Method", "In the 'Borda Count' voting system with 4 candidates, points are assigned to voters' preference rankings (e.g., 4 pts for 1st, 3 pts for 2nd, 2 pts for 3rd, 1 pt for 4th). The winner is:", "The candidate who accumulates the highest total sum of points across all ballots.", ["The candidate with the most last-place votes.", "The candidate who spent the lowest financial budget on campaigns.", "The candidate randomly drawn from a ballot box."]),
  ("Voting Theory: Condorcet Criterion", "A candidate who beats every other candidate in head-to-head pairwise comparisons is called a 'Condorcet Winner'. Arrow's Impossibility Theorem proved that:", "No ranked-choice voting system with 3 or more candidates can satisfy all fairness criteria simultaneously.", ["Democracy is mathematically identical to dictatorship in all circumstances.", "Voters always vote for the wealthiest candidate on the ballot.", "Pairwise comparisons can never be calculated on computers."]),
  ("Apportionment: Hamilton's Largest Remainder Method", "In legislative apportionment, Alexander Hamilton's method allocates standard quotas by giving each state its lower quota, and distributing surplus seats to:", "The states with the largest fractional remainders (decimal parts) of their standard quotas.", ["The state with the highest physical land area.", "The state that pays the highest federal income taxes.", "The smallest state regardless of quota calculations."]),
  ("Apportionment: Alabama Paradox", "The 'Alabama Paradox' in apportionment mathematics occurs when:", "An increase in the total number of legislative seats to be apportioned causes a state to LOSE a seat, with no change in populations.", ["A state secedes from the federation during a census recount.", "Two states with identical populations receive different numbers of senators.", "A state's population triples but its quota remains zero."]),
  ("Graph Theory: Vertices and Edges (Euler's Seven Bridges of Konigsberg)", "Leonhard Euler founded Graph Theory in 1736 by proving that crossing all Seven Bridges of Konigsberg exactly once without retracing (an Euler Path) was impossible because:", "More than two landmasses (vertices) had an ODD number of bridges (edges) connected to them.", ["The bridges were constructed of unstable wooden planks that collapsed.", "The river was too wide for mathematical measurement.", "The bridges were guarded by Prussian military sentries."])
])
d.extend([
  ("Graph Theory: Euler Path Theorem", "According to Euler's Theorem, a connected graph has an 'Eulerian Path' (a path that visits every edge exactly once) if and only if it has:", "Exactly 0 or exactly 2 vertices of odd degree.", ["All vertices of odd degree.", "Exactly 4 vertices of odd degree.", "No vertices connected by edges."]),
  ("Graph Theory: Euler Circuit Theorem", "A connected graph has an 'Eulerian Circuit' (a closed trail that starts and ends at the same vertex, visiting every edge exactly once) if and only if:", "Every vertex in the graph has an EVEN degree.", ["At least two vertices have an odd degree.", "The graph contains no loops or multiple edges.", "The total number of edges is a prime number."]),
  ("Graph Theory: Hamiltonian Circuit vs Euler Circuit", "While an Euler Circuit visits every EDGE in a graph exactly once, a 'Hamiltonian Circuit' must:", "Visit every VERTEX (node) in the graph exactly once and return to the starting vertex.", ["Visit every edge twice in alphabetical order.", "Cross the maximum number of bridges possible in a river.", "Disconnect the graph into two separate subgraphs."]),
  ("Graph Theory: Traveling Salesperson Problem (TSP)", "The Traveling Salesperson Problem (TSP) seeks to find:", "The Hamiltonian circuit with the lowest total edge weight (distance, time, or cost) visiting every city once.", ["The shortest path between two isolated vertices using Dijkstra's algorithm.", "The minimum number of colors needed to color a geographic map.", "The maximum volume of network data flow through a fiber-optic cable."]),
  ("Graph Theory: Four-Color Theorem", "The Four-Color Theorem (proven by Appel and Haken in 1976 using computer assistance) states that:", "Any contiguous map on a flat plane can be colored using at most 4 colors such that no two adjacent regions share the same color.", ["Every planar graph requires exactly 12 colors.", "Maps drawn on spheres cannot be colored mathematically.", "Three-dimensional topological models require infinite colors."]),
  ("Modular Arithmetic: Clock Arithmetic", "In modular arithmetic modulo 12 (12-hour clock arithmetic), what is the evaluation of (8 + 9) mod 12?", "5 (since 8 + 9 = 17, and 17 divided by 12 gives a remainder of 5).", ["17.", "1.", "7."]),
  ("Modular Arithmetic: Multiplicative Congruence", "What is the remainder when (7 * 8) is evaluated in modulo 5 arithmetic: (7 * 8) mod 5?", "1 (since 7 * 8 = 56, and 56 = 5 * 11 + 1).", ["6.", "0.", "2."]),
  ("Cryptography: Caesar Cipher (Shift Cipher)", "In classical cryptography, if a message is encrypted using a Caesar Cipher with a shift key of k = +3, the plaintext word 'CAT' encrypts to:", "'FDW' (C->F, A->D, T->W).", ["'EBS'.", "'ZBQ'.", "'DCA'."]),
  ("Cryptography: Symmetric vs Asymmetric Encryption", "In modern public-key (asymmetric) cryptography (such as RSA encryption):", "A public key is used to encrypt the message, while a mathematically linked private key is used to decrypt it.", ["Both sender and receiver share the identical secret password over unsecure email.", "Messages are encoded using mechanical Caesar substitution wheels.", "No mathematical prime numbers are involved in key generation."]),
  ("Cryptography: RSA Algorithm and Prime Factorization", "The security of the RSA public-key cryptosystem relies fundamentally on the computational difficulty of:", "Factoring extremely large composite numbers into their two large prime factors.", ["Calculating simple addition of two single-digit numbers.", "Sorting alphabetical dictionaries in reverse order.", "Measuring physical electrical resistance in copper wires."]),
  ("Linear Regression: Line of Best Fit (y = mx + b)", "In linear regression analysis, the 'Line of Best Fit' is calculated using the Method of Least Squares, which minimizes:", "The sum of the squared vertical distances (residuals/errors) between data points and the regression line.", ["The arithmetic mean of the independent variable x.", "The total number of collected data sample points.", "The variance of the dependent variable y."]),
  ("Statistics: Coefficient of Determination (R^2)", "If the correlation between two variables is r = 0.80, what is the Coefficient of Determination (R^2), and how is it interpreted?", "R^2 = 0.64 (64%), meaning 64% of the total variation in the dependent variable is explained by the independent variable.", ["R^2 = 0.80 (80%), meaning the test is 80% reliable.", "R^2 = 1.60, indicating an impossible statistical error.", "R^2 = 0.40, indicating a weak relationship."]),
  ("Mathematical Logic: Quantifiers (Universal vs Existential)", "What is the correct logical negation of the universally quantified statement: 'All teachers in this school hold a master's degree'?", "'There exists at least one teacher in this school who does not hold a master's degree.'", ["'No teachers in this school hold a master's degree.'", "'All teachers in this school do not hold a master's degree.'", "'Some teachers in this school hold a master's degree.'"]),
  ("Set Theory: Venn Diagrams (Inclusion-Exclusion Principle)", "In a survey of 100 students: 60 like Math, 50 like Science, and 20 like both Math and Science. How many students like NEITHER Math nor Science?", "10 students (using |M u S| = 60 + 50 - 20 = 90; 100 - 90 = 10).", ["30 students.", "20 students.", "0 students."]),
  ("Probability: Mutually Exclusive Events", "Two events A and B are 'Mutually Exclusive' (disjoint) if:", "They cannot occur at the same time (P(A and B) = 0).", ["The occurrence of event A changes the probability of event B.", "Event A is mathematically guaranteed to cause event B.", "P(A or B) = 1 in all sample spaces."])
])
d.extend([
  ("Probability: Independent Events", "Two events A and B are statistically 'Independent' if:", "The occurrence of event A has no effect on the probability of event B occurring (P(A and B) = P(A) * P(B)).", ["Event A and event B share identical physical outcomes.", "P(A) is equal to 0.", "Event A and event B must happen simultaneously."]),
  ("Probability: Permutations vs Combinations", "In combinatorics, 'Permutations' (nPr) are used when ORDER MATTERS (e.g., race podium finishes or PIN codes), while 'Combinations' (nCr) are used when:", "Order does not matter (e.g., selecting a committee of 3 members from a group of 10).", ["Every item must be painted with four colors.", "The numbers must be prime factors.", "The total sample size is infinite."]),
  ("Combinatorics: Permutations Calculation", "In how many distinct ways can 1st, 2nd, and 3rd place trophies be awarded among 8 contestants in a speech contest (8P3)?", "336 ways (8 * 7 * 6 = 336).", ["56 ways (8C3).", "512 ways (8^3).", "24 ways."]),
  ("Combinatorics: Combinations Calculation", "In how many different ways can a teacher select a 4-student delegation from a class of 10 students (10C4)?", "210 ways (10! / (4! * 6!) = (10 * 9 * 8 * 7) / (4 * 3 * 2 * 1) = 210).", ["5,040 ways (10P4).", "40 ways.", "10,000 ways."]),
  ("Data Management: Box-and-Whisker Plots", "In an exploratory data analysis box plot (Box-and-Whisker Plot), what does the box itself represent?", "The Interquartile Range (IQR = Q3 - Q1), containing the middle 50% of the data values.", ["The absolute range of the entire data set from minimum to maximum.", "The 95% confidence interval of the sample mean.", "The frequency of the mode in categorical data."]),
  ("Data Management: Identifying Outliers (IQR Method)", "Using John Tukey's standard box plot rule, a data value is flagged as a statistical 'Outlier' if it falls:", "Below Q1 - 1.5(IQR) or above Q3 + 1.5(IQR).", ["Exactly equal to the arithmetic mean.", "Between Q1 and Q3.", "Below the 50th percentile."]),
  ("Mathematical Reasoning: Proof by Contradiction", "In formal mathematics, a 'Proof by Contradiction' (Reductio ad Absurdum) establishes the truth of a proposition P by:", "Assuming that P is FALSE (~P is true) and demonstrating that this assumption logically leads to an impossible contradiction.", ["Conducting a survey of 1,000 professional mathematicians.", "Drawing a geometric diagram on graph paper.", "Calculating numerical examples on a scientific calculator."]),
  ("Number Theory: Prime Numbers & Sieve of Eratosthenes", "An ancient Greek algorithm used to find all prime numbers up to a specified integer n by systematically crossing out multiples of each prime is the:", "Sieve of Eratosthenes.", ["Euclidean Algorithm.", "Pascal's Triangle.", "Fibonacci Spiral."]),
  ("Number Theory: Greatest Common Divisor (GCD)", "Using the Euclidean Algorithm, what is the Greatest Common Divisor (GCD) of 48 and 18?", "6 (since 48 = 18*2 + 12; 18 = 12*1 + 6; 12 = 6*2 + 0).", ["12.", "3.", "2."]),
  ("Number Theory: Least Common Multiple (LCM)", "What is the Least Common Multiple (LCM) of 12 and 15?", "60 (since 12 = 2^2 * 3, 15 = 3 * 5; LCM = 2^2 * 3 * 5 = 60).", ["180.", "30.", "3."]),
  ("Geometric Transformations: Translations and Rotations", "An 'Isometry' (rigid transformation) in geometry is a transformation that preserves:", "Length, angle measure, and geometric distance, keeping the original figure congruent.", ["Color hue and tonal value only.", "Area while altering side lengths.", "Perspective while shrinking dimensions."]),
  ("Geometric Patterns: Wallpaper Groups", "In two-dimensional planar crystallography, how many mathematically distinct 'Wallpaper Groups' (plane symmetry groups) exist that can tile the plane infinitely?", "17 distinct wallpaper groups.", ["7 frieze groups.", "12 platonic groups.", "3 regular groups."]),
  ("Frieze Patterns: Infinitely Repeating Borders", "A geometric pattern that repeats infinitely along a single straight LINE or strip (such as architectural molding or textile borders) is called a:", "Frieze Pattern (of which there are exactly 7 distinct mathematical symmetry types).", ["Wallpaper Pattern.", "Fractal Dimension.", "Tessellation Grid."]),
  ("Statistics: Skewness in Data Distributions", "In a 'Positively Skewed' (Right-Skewed) distribution with a long tail stretching to the right, how are the Mean, Median, and Mode typically related?", "Mode < Median < Mean (the Mean is pulled right toward the high outlier tail).", ["Mean < Median < Mode (Left-Skewed).", "Mean = Median = Mode (Symmetrical).", "Median < Mode < Mean."]),
  ("Statistics: Negatively Skewed Distributions", "In a 'Negatively Skewed' (Left-Skewed) distribution (e.g., an easy exam where most students scored high, with a few very low scores), what is the relationship?", "Mean < Median < Mode (the Mean is pulled down by the low score tail).", ["Mode < Median < Mean.", "Mean = Median = Mode.", "Mode = Mean < Median."])
])
d.extend([
  ("Mathematics of Finance: Effective Annual Rate (EAR)", "Why is the Effective Annual Rate (EAR or APY) of a loan always HIGHER than its nominal Annual Percentage Rate (APR) when interest is compounded more than once a year?", "Because EAR accounts for the compounding of interest during intermediate sub-periods (interest on interest).", ["Because banks charge illegal penalty fees.", "Because inflation automatically increases every month.", "Because government bonds lose value annually."]),
  ("Mathematics of Finance: Sinking Funds", "A 'Sinking Fund' in municipal and corporate finance is an interest-earning account established specifically to:", "Accumulate a predetermined lump-sum fund over time through regular periodic deposits to retire future debt or replace aging capital equipment.", ["Distribute cash dividends to stock shareholders daily.", "Pay executive bonuses during bankruptcy liquidation.", "Evade federal corporate income taxes."]),
  ("Voting Theory: Arrow's Impossibility Theorem", "Kenneth Arrow's landmark 1951 Impossibility Theorem in mathematical economics proved that in any ranked-choice voting system with 3 or more candidates:", "No voting rule can simultaneously satisfy Pareto efficiency, non-dictatorship, independence of irrelevant alternatives, and unrestricted domain.", ["A majority winner always exists in every election.", "Dictatorships are mathematically impossible.", "Borda count is the only fair voting method."]),
  ("Graph Theory: Planar Graphs & Euler's Formula", "For any connected planar graph drawn without crossing edges, Euler's Planar Formula relates Vertices (V), Edges (E), and Faces (F) by:", "V - E + F = 2.", ["V + E + F = 0.", "V * E = 2F.", "V^2 - E^2 = F."]),
  ("Graph Theory: Complete Graphs (Kn)", "In a 'Complete Graph' with n vertices (Kn), where every vertex is connected to every other vertex by a unique edge, what is the total number of edges?", "n(n - 1) / 2.", ["n^2.", "2n.", "n!"]),
  ("Graph Theory: Minimum Spanning Tree (Kruskal's Algorithm)", "Kruskal's Algorithm finds the 'Minimum Spanning Tree' (MST) of a connected weighted graph by:", "Repeatedly adding the edge of minimum weight that does not create a cycle, until all vertices are connected.", ["Connecting vertices in alphabetical order regardless of weight.", "Selecting the longest edge in the graph first.", "Finding the Eulerian circuit of highest cost."]),
  ("Number Theory: Modular Inverses & Cryptography", "In modular arithmetic, the integer x is the 'Modular Multiplicative Inverse' of a modulo m if:", "(a * x) is congruent to 1 (mod m).", ["(a + x) is congruent to 0 (mod m).", "(a * x) is congruent to 0 (mod m).", "(a - x) is equal to m."]),
  ("Statistics: Law of Large Numbers", "The 'Law of Large Numbers' in probability theory states that as the number of experimental trials increases:", "The empirical relative frequency of an event gets closer and closer to its true theoretical probability.", ["The sample variance becomes infinitely large.", "The outcomes become completely non-random.", "The standard deviation equals the sample mean."]),
  ("Statistics: Central Limit Theorem", "The Central Limit Theorem (CLT) is foundational in inferential statistics because it guarantees that for any population distribution, the sampling distribution of the sample mean:", "Approaches a Normal Distribution as the sample size n becomes sufficiently large (typically n >= 30).", ["Becomes perfectly flat and uniform.", "Transforms into a binomial distribution.", "Shrinks to a single discrete integer."]),
  ("Statistics: Type I vs Type II Error", "In hypothesis testing, a 'Type I Error' (alpha error) occurs when the researcher:", "Rejects the Null Hypothesis (H0) when it is actually TRUE (a 'False Positive').", ["Fails to reject H0 when it is actually FALSE (a 'False Negative', Type II Error).", "Accepts both H0 and H1 simultaneously.", "Calculates an incorrect sample mean."]),
  ("Statistics: Type II Error", "In hypothesis testing, a 'Type II Error' (beta error) occurs when the researcher:", "Fails to reject the Null Hypothesis (H0) when H0 is actually FALSE (a 'False Negative').", ["Rejects H0 when H0 is true (Type I).", "Calculates a negative Z-score.", "Uses a sample size larger than 100."]),
  ("Mathematical Logic: De Morgan's Laws", "According to De Morgan's Laws in propositional logic, the negation of a conjunction ~(p ^ q) is logically equivalent to:", "~p v ~q (Not p OR Not q).", ["~p ^ ~q.", "p -> ~q.", "~(p v q)."]),
  ("Mathematical Logic: De Morgan's Law for Disjunction", "According to De Morgan's Laws, the negation of a disjunction ~(p v q) is logically equivalent to:", "~p ^ ~q (Not p AND Not q).", ["~p v ~q.", "p ^ q.", "~p -> q."]),
  ("Patterns in Nature: Voronoi Tessellations", "A 'Voronoi Diagram' (seen in giraffe coat patterns, dragonfly wings, and soap bubbles) partitions a plane into regions where each cell consists of all points:", "Closer to its corresponding seed/generating point than to any other seed.", ["Arranged in perfect concentric circles.", "Painted with identical spectral colors.", "Formed by equilateral triangles only."]),
  ("Mathematics in Modern World: Algorithmic Thinking", "In contemporary mathematics and computer science, an 'Algorithm' is defined as:", "A finite, unambiguous, step-by-step sequence of well-defined instructions for solving a problem or performing a computation.", ["A random guess made during statistical testing.", "A continuous mathematical function with zero derivatives.", "A philosophical debate on ethical morals."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item evaluates mathematical competence in {item[0]}. {item[2]} represents standard mathematical definition and derivation."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('mathExams.ts', 'MATH_EXAM_QUESTIONS', questions)
