import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Legal Bases: RA 11650 (Inclusive Education Act)", "Republic Act 11650 (Instituting a Policy of Inclusion and Services for Learners with Disabilities in Support of Inclusive Education Act) mandates that:", "No learner shall be denied admission to any public or private basic education institution on the basis of disability, establishing Inclusive Learning Resource Centers (ILRCs).", ["All children with disabilities must be institutionalized in isolated psychiatric facilities.", "Schools may charge 500% higher tuition fees to students with physical impairments.", "Only students with perfect standardized test scores may attend public schools."], "RA 11650 mandates the policy of inclusion in all schools, guaranteeing free and appropriate public education and creating Inclusive Learning Resource Centers (ILRCs) in all school divisions."),
  ("Legal Bases: RA 7277 (Magna Carta for Disabled Persons)", "Republic Act 7277 (Magna Carta for Disabled Persons), as amended, guarantees which fundamental rights for persons with disabilities in the Philippines?", "Equal opportunities in education, employment, barrier-free access, social services, and protection against discrimination.", ["Mandatory physical labor without pay in government factories.", "Prohibition from voting in national democratic elections.", "Revocation of driver's licenses for family members."], "RA 7277 provides comprehensive rights for PWDs, including educational access, 20% discounts, equal employment opportunities, and anti-discrimination protections."),
  ("International Declarations: Salamanca Statement (UNESCO 1994)", "The landmark UNESCO 1994 Salamanca Statement on Special Needs Education established the global principle that:", "Regular schools with an inclusive orientation are the most effective means of combating discriminatory attitudes, creating welcoming communities, and achieving education for all.", ["Children with disabilities should be educated only in separate segregated institutions.", "Special education should be abolished entirely without any individualized support.", "Only wealthy nations are obligated to provide special education."], "The Salamanca Statement (1994) is the foundational global charter for inclusive education, asserting that regular schools must accommodate all children regardless of physical, intellectual, social, or linguistic conditions."),
  ("International Frameworks: UNCRPD (Article 24)", "Article 24 of the United Nations Convention on the Rights of Persons with Disabilities (UNCRPD) explicitly mandates that States Parties shall ensure:", "An inclusive education system at all levels and lifelong learning directed to the full development of human potential, dignity, and self-worth.", ["The segregation of children with physical disabilities into hospital wards.", "The total exclusion of deaf learners from sign language access.", "The elimination of all individualized educational accommodations."], "UNCRPD Article 24 legally obligates signatory nations to ensure inclusive, quality, and free primary and secondary education for persons with disabilities on an equal basis with others."),
  ("Special Education vs Inclusive Education", "How does 'Inclusive Education' fundamentally differ from traditional 'Mainstreaming' (Integration)?", "Inclusion reshapes and adapts the general classroom environment, curriculum, and pedagogy to welcome all learners, whereas Mainstreaming expects the child to adapt to the unchanged regular classroom.", ["Inclusion educates children in separate buildings; Mainstreaming puts them in one room.", "Inclusion is only for gifted children; Mainstreaming is for athletic pupils.", "Inclusion is illegal under Philippine law; Mainstreaming is mandatory."], "Mainstreaming places the burden on the child to 'fit in' to the existing regular classroom structure, while Inclusive Education restructures school culture, policies, and practices to fit the diverse needs of all learners."),
  ("Specific Learning Disabilities: Dyslexia", "A 9-year-old pupil with normal intelligence experiences persistent difficulty with accurate word recognition, phonological decoding, and spelling despite standard reading instruction. This child demonstrates symptoms of:", "Dyslexia (a specific learning disability of neurological origin affecting phonological processing).", ["Dyscalculia.", "Dyspraxia.", "Conduct Disorder."], "Dyslexia is a specific neurodevelopmental learning disability characterized by difficulties with accurate and/or fluent word recognition, poor spelling, and decoding abilities."),
  ("Specific Learning Disabilities: Dyscalculia", "A Grade 4 pupil struggles severely to understand basic number concepts, tell time on an analog clock, memorize multiplication facts, and perform simple arithmetic operations despite average verbal skills. This indicates:", "Dyscalculia (a specific learning disability in mathematical cognition).", ["Dyslexia.", "Dysgraphia.", "Aphasia."], "Dyscalculia is a specific learning disability involving innate difficulty in learning or comprehending arithmetic, number concepts, arithmetic facts, and mathematical reasoning."),
  ("Specific Learning Disabilities: Dysgraphia", "A student exhibits extremely labored, illegible handwriting, inconsistent spacing between words, severe fatigue when gripping a pen, and difficulty organizing written thoughts on paper despite strong oral expression. This is:", "Dysgraphia (a specific learning disability affecting fine-motor writing and orthographic output).", ["Dyslexia.", "Dyscalculia.", "Autism."], "Dysgraphia is a neurological condition that impairs fine motor handwriting mechanics, letter formation, spatial spacing, and written expression fluency."),
  ("Neurodevelopmental Disorders: ADHD (Three Subtypes)", "Under the DSM-5, Attention-Deficit/Hyperactivity Disorder (ADHD) is categorized into which three diagnostic presentations?", "Predominantly Inattentive, Predominantly Hyperactive-Impulsive, and Combined Presentation.", ["Mild, Aggressive, and Psychotic.", "Visual, Auditory, and Kinesthetic.", "Acute, Chronic, and Terminal."], "ADHD presents in three distinct clinical subtypes: Predominantly Inattentive (distractibility/disorganization), Predominantly Hyperactive-Impulsive (fidgeting/impulsivity), and Combined Presentation."),
  ("Instructional Accommodations for ADHD", "Which classroom management accommodation is most effective for a student with ADHD who is easily overstimulated and struggles with sustained focus?", "Seating the student near the front away from high-distraction doors/windows, breaking assignments into short 'chunked' steps, and providing discreet movement breaks.", ["Isolating the student in a dark storage closet for 45 minutes.", "Giving the student 100 extra math homework problems as punishment.", "Shouting loudly every time the student shifts in their seat."], "Accommodations for ADHD include reduced distractions, preferential seating near instruction, chunked assignments, clear visual checklists, and planned physical movement breaks."),
  ("Autism Spectrum Disorder (ASD): Core Characteristics", "Under the DSM-5, Autism Spectrum Disorder (ASD) is clinically characterized by persistent deficits in social communication/interaction AND:", "Restricted, repetitive patterns of behavior, interests, activities, or sensory sensitivities.", ["Severe intellectual deterioration over time.", "Violent conduct toward school property.", "A complete inability to see visual colors."], "ASD is characterized by two core diagnostic domains: persistent deficits in social communication and social interaction, along with restricted, repetitive behaviors, rituals, and atypical sensory responses."),
  ("Accommodations for Autism: Visual Schedules and Social Stories", "Why are 'Visual Schedules' and Carol Gray's 'Social Stories' highly effective evidence-based interventions for learners with Autism?", "They provide predictable visual structure, ease transition anxiety, and explicitly explain social expectations and cues in concrete, understandable terms.", ["They cure neurological autism within 24 hours.", "They force the student to complete standardized tests in complete silence.", "They eliminate the need for any verbal speech therapy."], "Visual schedules provide cognitive predictability and reduce transition-related anxiety, while Social Stories explicitly teach social norms, perspective-taking, and appropriate responses."),
  ("Intellectual Disability (ID): Diagnostic Criteria (AAIDD & DSM-5)", "To diagnose an 'Intellectual Disability', a learner must exhibit significant limitations in BOTH:", "Intellectual Functioning (IQ typically below 70) AND Adaptive Behavior (conceptual, social, and practical life skills), originating during the developmental period.", ["Physical height and body mass index.", "Visual eyesight acuity and hearing pitch.", "Athletic running speed and basketball coordination."], "Diagnosis of Intellectual Disability requires concurrent deficits in intellectual functioning (reasoning, problem solving) and adaptive behavior across conceptual, social, and practical daily domains, with onset before age 18."),
  ("Sensory Impairments: Visual Impairment Accommodations", "When teaching a student who is totally blind in an inclusive science class, the most appropriate instructional accommodations include:", "Braille textbooks, tactile 3D relief models, raised-line diagrams, screen-reading software with audio descriptions, and clear verbal descriptions of visual displays.", ["Showing silent 2D documentary films without audio description.", "Writing all notes on the chalkboard in small yellow chalk.", "Excusing the student from all science learning permanently."], "Inclusive accommodations for visual impairment include tactile models, Braille, auditory descriptions, tactile graphics, and accessible digital text."),
  ("Sensory Impairments: Deaf & Hard of Hearing (Sign Language)", "Under Republic Act 11106 (The Filipino Sign Language Act), Filipino Sign Language (FSL) is legally recognized as:", "The official national sign language of the Philippines and the medium of instruction for deaf learners in schools.", ["A temporary, informal slang without grammatical structure.", "An illegal dialect prohibited in government offices.", "A foreign language imported from South America."], "RA 11106 declares Filipino Sign Language (FSL) as the official national sign language of the government and the mandated medium of instruction for deaf learners in basic education.")
]
d.extend([
  ("Gifted and Talented Learners: Renzulli's Three-Ring Model", "Joseph Renzulli's 'Three-Ring Conception of Giftedness' defines gifted behaviors as resulting from the interaction of which three traits?", "Above-Average Ability, High Task Commitment (Perseverance/Motivation), and High Creativity.", ["High Socioeconomic Status, Wealthy Parents, and Expensive Tutors.", "Physical Athletic Speed, Tall Height, and Perfect Vision.", "Photographic Memory, Rote Obedience, and Silent Demeanor."]),
  ("Gifted Learners: Acceleration vs Enrichment", "In gifted education, 'Curriculum Compacting and Enrichment' allows a gifted student who has already mastered Grade 5 math to:", "Compress standard grade-level content to eliminate repetitive drill, freeing time to explore advanced, interdisciplinary, real-world investigative projects.", ["Skip all high school education and enroll immediately in medical school at age 10.", "Sit in the back of the classroom and grade the teacher's papers for 5 hours.", "Take identical 50-item basic arithmetic quizzes every single day."]),
  ("Individualized Education Plan (IEP): Legal Mandate & Purpose", "An 'Individualized Education Plan' (IEP) is a legally binding educational document designed to:", "Set individualized measurable annual goals, specify accommodations/modifications, and outline specialized related services for a child with special needs.", ["Record disciplinary detentions and punishments.", "Serve as an official receipt for school fees.", "Rank students alphabetically on the school honors board."]),
  ("IEP Team Composition: Key Stakeholders", "Under special education best practice, the multidisciplinary IEP team must include:", "The Special Education teacher, Regular Education teacher, School Head/Administrator, Parents/Guardians, Related Service Specialists (e.g., SLP, OT), and the Student (when appropriate).", ["Only the school security guard and cafeteria manager.", "Exclusively the commercial textbook sales agent.", "Only the municipal mayor and local police chief."]),
  ("Universal Design for Learning (UDL): Three Principles (CAST)", "Universal Design for Learning (UDL) removes barriers to learning proactively from the very start by designing curricula with multiple means of:", "Engagement (the 'Why' of learning), Representation (the 'What' of learning), and Action & Expression (the 'How' of learning).", ["Assessment, Grading, and Ranking.", "Lecturing, Memorizing, and Testing.", "Hiring, Budgeting, and Firing."]),
  ("UDL Principle 1: Multiple Means of Representation", "A teacher who presents a lesson on the water cycle using an animated video with captions, a physical tactile 3D relief model, a simplified reading text with a glossary, and hands-on lab demonstration is applying:", "UDL Principle: Multiple Means of Representation.", ["UDL Principle: Multiple Means of Action and Expression.", "UDL Principle: Multiple Means of Engagement.", "Traditional single-textbook delivery."]),
  ("UDL Principle 2: Multiple Means of Action & Expression", "Allowing students to demonstrate their understanding of a historical event by writing an essay, creating a comic book, recording a podcast, or coding an interactive quiz provides:", "Multiple Means of Action and Expression (UDL).", ["Multiple Means of Representation.", "Single-format standardized testing.", "Curricular exclusion."]),
  ("UDL Principle 3: Multiple Means of Engagement", "Offering students choices in learning topics, collaborative vs independent workspaces, and real-world authentic challenges aligns with which UDL principle?", "Multiple Means of Engagement (fostering motivation, relevance, and self-regulation).", ["Multiple Means of Representation.", "Multiple Means of Expression.", "Rote compliance training."]),
  ("Multi-Tiered System of Supports (MTSS) / Response to Intervention (RTI)", "In the 3-Tier MTSS/RTI framework, what occurs at 'Tier 1' (Universal Instruction)?", "High-quality, evidence-based differentiated core instruction delivered to ALL students in the general education classroom (effective for approximately 80-85% of learners).", ["Intensive one-on-one individualized clinical therapy.", "Targeted small-group supplemental interventions (Tier 2).", "Permanent placement in a residential institution."]),
  ("MTSS/RTI: Tier 2 (Targeted Group Interventions)", "In MTSS/RTI, students who do not make adequate progress with Tier 1 universal instruction receive 'Tier 2' support, which consists of:", "Targeted, evidence-based small-group interventions with frequent progress monitoring alongside core instruction (serving ~10-15% of students).", ["Universal whole-class lecturing.", "Immediate surgical or medical hospitalization.", "Expulsion from the school system."]),
  ("MTSS/RTI: Tier 3 (Intensive Individualized Interventions)", "In MTSS/RTI, 'Tier 3' represents:", "Intensive, highly individualized, targeted interventions with high-frequency progress monitoring and potential multidisciplinary evaluation for special education services.", ["General classroom assemblies.", "Weekly school sports competitions.", "Standardized textbook reading."]),
  ("Least Restrictive Environment (LRE)", "The principle of the 'Least Restrictive Environment' (LRE) mandates that students with disabilities must be educated:", "With peers without disabilities to the maximum extent appropriate, only moving to more specialized settings when education in regular classes with supports cannot be achieved.", ["In complete physical isolation in homebound confinement at all times.", "In segregated institutions located outside city boundaries.", "Exclusively in underground sensory deprivation rooms."]),
  ("Continuum of Special Education Placements (Deno's Cascade)", "Evelyn Deno's Cascade of Services models special education placements from least restrictive to most restrictive in which order?", "General Education Class with supports -> Resource Room (Pull-out) -> Self-Contained Special Class -> Special Day School -> Residential/Hospital Facility.", ["Hospital -> Self-Contained -> Regular Class with supports.", "Resource Room -> Regular Class -> Kindergarten.", "Day School -> University -> High School."]),
  ("Accommodations vs Modifications: Practical Distinction", "Giving a student with dyslexia audio recordings of grade-level history texts and extended testing time is an __________, while reducing the reading curriculum to a Grade 1 level for a high school student is a __________.", "Accommodation (standard remains identical); Modification (standard is fundamentally altered).", ["Modification; Accommodation.", "Exclusion; Punishment.", "Disciplinary action; Reward."]),
  ("Assistive Technology: Augmentative and Alternative Communication (AAC)", "An Augmentative and Alternative Communication (AAC) device (e.g., a Picture Exchange Communication System / PECS or a speech-generating tablet app) benefits non-verbal learners by:", "Providing an expressive communication medium to express needs, thoughts, and ideas without relying on oral speech.", ["Teaching students to run faster in physical education.", "Replacing the need for all cognitive learning.", "Administering medical sedation."])
])
d.extend([
  ("Physical Impairments: Cerebral Palsy (CP)", "Cerebral Palsy is a non-progressive neuromuscular disorder caused by brain injury before, during, or shortly after birth that affects:", "Muscle tone, motor coordination, movement, and posture.", ["Cognitive emotional empathy.", "Vision color perception only.", "The speed of fingernail growth."]),
  ("Accommodations for Cerebral Palsy & Motor Disabilities", "To accommodate a student with spastic Cerebral Palsy who has limited manual hand dexterity, an inclusive teacher should provide:", "Adaptive pencil grips, weighted keyboards, slant boards, speech-to-text dictation software, and barrier-free physical classroom accessibility.", ["Mandatory handwriting penmanship competitions.", "Physical isolation during all academic activities.", "Zero accommodations."]),
  ("Behavioral Disorders: Emotional and Behavioral Disorders (EBD)", "Students with Emotional and Behavioral Disorders (EBD) frequently demonstrate internalizing behaviors (e.g., severe withdrawal, depression, anxiety) or externalizing behaviors such as:", "Persistent verbal/physical aggression, defiance, tantrums, and disruptive acting-out that significantly interfere with learning.", ["Exceptional mathematical calculus performance.", "Continuous peaceful meditation in silence.", "Fluent multilingual reading skills."]),
  ("Behavioral Interventions: Functional Behavior Assessment (FBA)", "A 'Functional Behavior Assessment' (FBA) is conducted by an educational team primarily to:", "Identify the underlying function, environmental triggers (Antecedents), and maintaining consequences of a challenging behavior to design positive interventions.", ["Punish the student with public embarrassment.", "Calculate the financial cost of broken pencils.", "Assign an automatic letter grade 'F' on the report card."]),
  ("Behavioral Interventions: Positive Behavioral Interventions and Supports (PBIS)", "PBIS is a school-wide, tiered proactive framework that emphasizes:", "Explicitly teaching, modeling, and reinforcing positive behavioral expectations rather than relying solely on punitive disciplinary sanctions.", ["Using physical corporal punishment for all minor infractions.", "Ignoring all student behavior until severe violence occurs.", "Expelling any student who receives three verbal warnings."]),
  ("Speech and Language Disorders: Articulation vs Language Disorders", "While an 'Articulation Disorder' involves physical difficulty producing specific speech sounds (e.g., lisping or substituting /w/ for /r/), a 'Language Disorder' involves:", "Impairment in comprehending and/or formulating linguistic grammar, vocabulary, semantics, and pragmatics (receptive and expressive language).", ["A broken vocal cord requiring throat surgery.", "Difficulty running on the playground track.", "A complete refusal to eat cafeteria food."]),
  ("Sensory Processing Disorder (SPD): Sensory Overload in Classrooms", "A student who covers his ears, screams, and hides under desks during loud fire drills or chaotic cafeteria transitions is likely experiencing:", "Sensory Overload / Hypersensitivity (difficulty processing and filtering intense environmental sensory stimuli).", ["Intentional malicious defiance.", "A complete lack of cognitive intelligence.", "A sudden attack of biological flu fever."]),
  ("Sensory Accommodations: Sensory Corners and Fidget Tools", "Providing noise-canceling headphones, weighted lap pads, and a designated quiet 'calm-down corner' in an inclusive classroom serves to:", "Help neurodivergent learners self-regulate sensory inputs and emotional arousal before behavioral crises escalate.", ["Encourage students to sleep during math lessons.", "Isolate students permanently from peer friendships.", "Punish pupils for making noise."]),
  ("Down Syndrome (Trisomy 21): Characteristics & Inclusive Pedagogy", "Down Syndrome is a genetic chromosomal condition (Trisomy 21) characterized by distinct physical features, mild-to-moderate intellectual disability, and:", "Strengths in visual learning, strong social-emotional empathy, and benefits from concrete, hands-on, visual instructional scaffolds.", ["Extreme aggression and violent psychotic hallucinations.", "Total inability to learn any reading or social skills.", "Complete physical blindness from birth."]),
  ("Traumatic Brain Injury (TBI) in Students", "A student who returns to school following recovery from a severe vehicular Traumatic Brain Injury (TBI) may exhibit:", "Cognitive fatigue, memory lapses, slowed processing speed, and emotional lability, requiring reduced cognitive load and extended time.", ["Immediate miraculous photographic memory.", "Permanent immunity to physical pain.", "Zero need for educational adjustments."]),
  ("Hearing Impairments: Conductive vs Sensorineural Hearing Loss", "While 'Conductive Hearing Loss' is caused by mechanical blockages or damage in the outer/middle ear (often medically treatable), 'Sensorineural Hearing Loss' is caused by:", "Damage to the inner ear hair cells (cochlea) or the auditory nerve pathways to the brain, typically permanent and requiring hearing aids or cochlear implants.", ["Wax buildup in the ear canal.", "A minor head cold with ear congestion.", "Listening to low-volume classical music."]),
  ("Classroom Acoustic Management for Deaf / Hard of Hearing", "To optimize learning for a student with hearing impairment in an inclusive classroom, the teacher should:", "Face the class directly when speaking (enabling speechreading), minimize background classroom ambient noise, repeat peer comments, and use FM assistive systems.", ["Speak while writing with their back turned to the class.", "Turn off all classroom lights during lectures.", "Shout aggressively into the student's ear from behind."]),
  ("Inclusive Collaboration: Co-Teaching Models (Cook & Friend)", "Marilyn Friend and Lynne Cook identified six co-teaching models. In the 'Station Teaching' model, how do teachers and students interact?", "Content is divided into stations; the General Ed teacher leads one, the Special Ed teacher leads another, and students rotate through all stations.", ["One teacher lectures while the other teacher grades papers in the hallway.", "Both teachers sit in silence while students read alone.", "One teacher teaches on Monday, and the other teaches on Friday."]),
  ("Co-Teaching Models: Parallel Teaching", "In 'Parallel Teaching', both the general education and special education teachers:", "Split the heterogeneous class into two equal halves and teach the identical lesson content simultaneously, lowering the student-teacher ratio.", ["Teach completely different unrelated subjects in the same room.", "Argue publicly about lesson objectives in front of pupils.", "Leave the classroom to attend an administrative meeting."]),
  ("Co-Teaching Models: Alternative (Differentiated) Teaching", "In 'Alternative Teaching', one teacher manages the large group while the other teacher:", "Works with a small group of learners to provide specialized pre-teaching, enrichment, remedial reteaching, or assessment.", ["Stands by the door to check student uniform compliance.", "Corrects homework assignments with red ink in silence.", "Conducts a private phone call."])
])
d.extend([
  ("Co-Teaching Models: Team Teaching (Teaming)", "In 'Team Teaching', the general education teacher and the special education teacher:", "Share instructional delivery fluidly, co-leading whole-class discussions, modeling collaborative dialogue, and seamlessly supporting all learners.", ["Divide the classroom with a physical wooden barricade.", "Take turns teaching every 30 seconds with a timer.", "Compete to see which teacher can talk the loudest."]),
  ("Inclusive Pedagogy: Peer-Mediated Instruction", "Using 'Peer-Assisted Learning Strategies' (PALS) in inclusive classrooms pairs stronger readers with struggling peers primarily to:", "Provide structured, reciprocal practice, immediate feedback, and positive social interaction in reading fluency and comprehension.", ["Relieve the teacher of all responsibility for teaching reading.", "Allow advanced students to do all the work while struggling students sleep.", "Rank students publicly based on their reading speeds."]),
  ("Transition Planning in Special Education (IDEA / DepEd)", "In special education transition planning (from secondary school to adult life), the transition plan must address which key domains?", "Post-secondary education/vocational training, integrated competitive employment, independent living skills, and community participation.", ["Childhood nursery rhymes and kindergarten games.", "Mandatory institutional confinement in state hospitals.", "Perpetual dependence on parental supervision with zero life autonomy."]),
  ("Twice-Exceptional (2e) Learners: Dual Identification", "A 'Twice-Exceptional' (2e) learner is a student who exhibits:", "Exceptional giftedness or high cognitive talent in one or more areas COMBINED with a specific learning disability (e.g., ADHD, Dyslexia, or Autism).", ["Two separate physical disabilities (e.g., blindness and deafness).", "Twin siblings enrolled in the same grade level.", "A student who has failed two consecutive academic school years."]),
  ("Instructional Strategies for Twice-Exceptional Learners", "To effectively educate a Twice-Exceptional (2e) learner, the inclusive teacher must:", "Provide advanced, complex enrichment to nurture their high intellectual strengths while simultaneously providing specialized accommodations for their learning disability.", ["Focus exclusively on remediating their weaknesses until all deficits disappear, ignoring their gifts.", "Deny all gifted services until the learning disability is 100% cured.", "Treat the student as an unmotivated, lazy troublemaker."]),
  ("Differentiated Assessment for Exceptional Learners", "When assessing a student with severe expressive language impairment on history content knowledge, an inclusive teacher should:", "Allow the student to demonstrate historical understanding through graphic organizers, chronological image sorting, or interactive digital timelines instead of an oral presentation.", ["Assign an automatic zero because the student cannot speak fluently.", "Force the student to deliver a 30-minute speech in front of the entire school.", "Excuse the student from learning history completely."]),
  ("Environmental Accessibility: Universal Architectural Design", "Under the Accessibility Law (Batas Pambansa Blg. 344), school campuses must be made barrier-free by incorporating:", "Ramps with gentle slopes, accessible handrails, wide doorways, tactile paving, accessible restrooms, and clear visual/auditory emergency signals.", ["Narrow spiral staircases without elevators.", "Steep concrete curbs that block wheelchairs.", "Restrooms located exclusively on the fourth floor with no elevator."]),
  ("Curriculum Adaptation: Environmental Adaptations", "Adjusting classroom lighting, installing acoustic carpeting, providing noise-dampening curtains, and arranging wide aisles for wheelchair navigation are examples of:", "Environmental / Physical Adaptations for inclusive accessibility.", ["Curricular content modifications.", "Punitive behavioral tracking.", "Standardized curriculum tests."]),
  ("Inclusive Culture: Combating Ableism in Schools", "In inclusive education philosophy, 'Ableism' is defined as:", "Systemic discrimination, prejudice, and societal stereotyping against individuals with disabilities, assuming non-disabled standards are superior and normal.", ["A medical surgical procedure to correct bone fractures.", "The specialized study of human anatomical movement.", "A sports training program for Olympic athletes."]),
  ("Person-First Language vs Identity-First Language", "While traditional professional practice emphasizes 'Person-First Language' (e.g., 'a student with autism'—centering the person before the diagnosis), some neurodiversity advocates prefer 'Identity-First Language' (e.g., 'an autistic person') to:", "Affirm disability as an integral, positive, and empowering aspect of personal identity and neurodivergence.", ["Insult and demean the individual.", "Confuse teachers and school administrators.", "Hide the fact that a disability exists."]),
  ("IEP Progress Monitoring & Data Collection", "Why is continuous, objective 'Progress Monitoring' (e.g., using Curriculum-Based Measurement / CBM) legally and pedagogically vital in implementing an IEP?", "To provide empirical evidence on whether the student is meeting specific annual goals, allowing timely adjustments to instructional strategies if progress stalls.", ["To prove that the special education teacher should receive a bonus salary.", "To assign random grades at the end of the semester without grading.", "To convince parents to withdraw their child from school."]),
  ("Assistive Tech: Low-Tech vs High-Tech Tools", "In special education, a 'Low-Tech Assistive Tool' is exemplified by a __________ while a 'High-Tech Assistive Tool' is exemplified by a __________.", "Pencil grip or tactile ruler; Eye-gaze tracking communication system or motorized wheelchair.", ["Supercomputer server; Wooden chair.", "Smartphone; Printed encyclopedia.", "Microchip implant; Video projector."]),
  ("Parent-Professional Partnerships in Inclusive Education", "Effective parent-professional partnerships in special and inclusive education are built upon:", "Mutual respect, transparent communication, shared decision-making, and recognizing parents as the primary experts on their child's daily life and history.", ["Authoritarian professional dictation where teachers order parents what to do.", "Excluding parents from all IEP team meetings and decisions.", "Blaming parents whenever a student struggles with homework."]),
  ("Mental Health & Trauma-Informed Inclusive Classrooms", "A 'Trauma-Informed' inclusive teacher approaches a student exhibiting severe distress or withdrawal by shifting the fundamental question from 'What is wrong with you?' to:", "'What happened to you, and how can we create a safe, supportive space for you to heal and learn?'", ["'Why are you always failing my class?'", "'Who gave you permission to feel sad?'", "'How many demerit points do you want today?'"]),
  ("Inclusive Education Synthesis: Education for All (EFA)", "The ultimate philosophy of Inclusive Education asserts that every child, regardless of ability, socioeconomic background, ethnicity, or gender:", "Has an inherent, inalienable right to quality education, social belonging, human dignity, and the opportunity to reach their full potential alongside peers.", ["Must pass an IQ exam before being granted permission to enter a classroom.", "Should be educated only if their family can pay high private school fees.", "Must be separated from society to prevent disturbing others."])
])
d.extend([
  ("Sensory Impairments: Deafblindness", "Deafblindness is a unique combination of concurrent hearing and visual impairments that causes severe communication and developmental needs. The primary mode of instruction often relies on:", "Tactile Sign Language (hand-over-hand signing), tactile symbols, and structured routines.", ["Watching television documentaries with subtitles only.", "Listening to audio radio lectures.", "Writing with colored chalk on blackboards."]),
  ("Sensory Impairments: Orientation and Mobility (O&M)", "In special education for blind and low-vision learners, 'Orientation and Mobility' (O&M) training teaches students to:", "Know where they are in space (Orientation) and move safely, efficiently, and independently through their environment using white canes and sensory cues (Mobility).", ["Draw detailed portraits using oil pastels.", "Fix electrical wiring inside computers.", "Drive commercial motor vehicles on highways."]),
  ("Orthopedic Impairments: Muscular Dystrophy", "Muscular Dystrophy is a group of progressive genetic diseases characterized by:", "Progressive muscle weakness and degeneration of skeletal muscles over time, requiring adaptive physical positioning and motorized mobility aids.", ["Sudden permanent deafness in adulthood.", "Severe loss of verbal reading comprehension.", "High blood pressure after physical exercise."]),
  ("Health Impairments: Childhood Epilepsy and Seizures", "If a student experiences a generalized tonic-clonic epileptic seizure in the classroom, the teacher's immediate first-aid response must be to:", "Keep calm, ease the student to the floor, clear sharp objects, place something soft under the head, turn the student gently onto one side, and NEVER insert anything into the mouth.", ["Force a wooden spoon or pencil into the student's mouth.", "Hold the student down with heavy physical force.", "Splash cold water into the student's face."]),
  ("Health Impairments: Type 1 Diabetes in the Classroom", "When a student with Type 1 Diabetes exhibits sudden trembling, cold sweating, dizziness, and confusion (Hypoglycemia), the teacher should immediately:", "Provide a fast-acting source of simple sugar (such as fruit juice, candy, or glucose tablets) and monitor recovery in accordance with their health plan.", ["Force the student to run 10 laps on the track to burn energy.", "Administer heavy physical punishment for lack of attention.", "Deprive the student of all food and fluids for 24 hours."]),
  ("Health Impairments: Severe Asthma Management", "To ensure an inclusive and safe environment for a student with chronic severe asthma, the classroom teacher must:", "Know the student's Asthma Action Plan, ensure rapid access to their rescue inhaler, and minimize known environmental triggers (dust, strong chemical fumes, mold).", ["Ban the student from keeping their prescribed inhaler in school.", "Force the student to clean dusty chalkboard erasers.", "Deny all physical education participation permanently."]),
  ("Early Childhood Special Education: Early Intervention", "Why is 'Early Intervention' (services from birth to age 5) critical for infants and toddlers with identified developmental delays?", "Because neural neuroplasticity is at its lifetime peak during early childhood, significantly improving long-term developmental, cognitive, and communicative outcomes.", ["Because children can take standardized college entrance exams at age 3.", "Because special education laws expire when a child turns 6.", "Because early intervention eliminates the need for any primary schooling."]),
  ("Specialized Services: Speech-Language Pathologist (SLP)", "In an inclusive school, a Speech-Language Pathologist (SLP) works with students primarily to:", "Diagnose, treat, and support speech articulation, receptive/expressive language, voice, fluency (stuttering), and pragmatic social communication disorders.", ["Perform orthopedic surgeries in hospital operating rooms.", "Prescribe psychiatric pharmaceutical medications.", "Audit school financial tax balance sheets."]),
  ("Specialized Services: Occupational Therapist (OT)", "An Occupational Therapist (OT) in an educational setting provides specialized therapy to help learners improve:", "Fine-motor skills (handwriting, scissor use), sensory processing regulation, visual-motor integration, and activities of daily living (ADLs).", ["Large-scale macro-economic financial planning.", "Athletic marathon running endurance.", "Vocal choir singing range."]),
  ("Specialized Services: Physical Therapist (PT)", "In an inclusive education team, a Physical Therapist (PT) specifically focuses on improving a child's:", "Gross-motor function, posture, gait, physical mobility, range of motion, and safe physical navigation across campus facilities.", ["Silent reading speed and spelling accuracy.", "Mathematical calculus calculation skills.", "Foreign language grammatical translation."]),
  ("Behavioral Strategies: Priming and Pre-Correction", "Before transitioning from a quiet reading lesson to a noisy physical science lab, the teacher reviews behavioral expectations, previews upcoming steps, and checks for understanding. This strategy is:", "Priming and Pre-Correction (proactive behavioral preview to ensure smooth, successful transitions).", ["Reactive punitive reprimanding.", "Extinction burst conditioning.", "Negative response cost penalty."]),
  ("Assistive Technology: Graphic Organizers (Software)", "Using digital mind-mapping and graphic organizing software (e.g., Inspiration or Kidspiration) helps students with learning disabilities because it:", "Provides visual spatial scaffolding to brainstorm, structure, organize, and outline complex ideas before writing.", ["Writes the entire research paper automatically without student thought.", "Replaces all reading instruction with audio cartoons.", "Guarantees a perfect standardized exam score."]),
  ("Differentiated Instruction in Inclusion: Tiered Assignments", "A teacher designs three levels of a history assignment: Tier 1 matches key historical figures to events with visual cues; Tier 2 writes short analytical explanations; Tier 3 evaluates conflicting perspectives. This exemplifies:", "Tiered Assignments differentiated by readiness level within an inclusive classroom.", ["Rigid single-standard instruction.", "Discriminatory tracking based on socioeconomic status.", "Punitive academic isolation."]),
  ("Classroom Culture: Fostering Neurodiversity Acceptance", "How can an inclusive teacher best nurture a culture of neurodiversity and empathy among all students?", "By openly discussing neurodiversity as natural human variation, modeling unconditional positive regard, and celebrating diverse strengths and contributions.", ["By pretending that no differences exist and silencing any discussion of disability.", "By pointing out a disabled student's mistakes as warnings to other pupils.", "By separating neurodivergent pupils behind classroom dividers."]),
  ("Inclusive Leadership: The Role of the Inclusive School Head", "An effective inclusive school principal demonstrates leadership by:", "Creating a welcoming school culture, providing resources/professional development for teachers, ensuring barrier-free infrastructure, and upholding zero-reject policies.", ["Denying admission to any student requiring special accommodations to keep test averages high.", "Ordering teachers to hide special education students during government accreditation visits.", "Abolishing all individualized education plans in favor of uniform testing."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item assesses specialized knowledge in {item[0]}. {item[2]} represents evidence-based special and inclusive education theory, RA 11650, and UDL guidelines."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('inclusiveEducationExams.ts', 'INCLUSIVE_EDUCATION_EXAM_QUESTIONS', questions)
