import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Globalization: Definitional Core (Manfred Steger)", "According to political scientist Manfred Steger, 'Globalization' is best defined as:", "The expansion and intensification of social relations and consciousness across world-time and world-space.", ["The total elimination of all sovereign nation-states and physical borders by 2000.", "The exclusive domination of the global economy by a single corporate monopoly.", "A static, completed historical event that occurred during the 16th century."]),
  ("Globalization: Three Major Scholarly Perspectives", "David Held categorizes globalization theorists into three camps. 'Hyperglobalists' argue that global economic integration has:", "Weakened the nation-state, creating a borderless global marketplace driven by transnational corporations.", ["Had zero impact on traditional sovereign national boundaries (Skeptics).", "Transformed states in complex, contradictory, and unprecedented ways without eliminating them (Transformationalists).", "Completely reversed all international trade back to medieval feudalism."]),
  ("Global Economy: Bretton Woods Conference (1944)", "The landmark 1944 Bretton Woods Conference in New Hampshire established the post-WWII international monetary architecture, creating which two foundational institutions?", "The International Monetary Fund (IMF) and the World Bank (IBRD).", ["The World Trade Organization (WTO) and the United Nations Security Council.", "The European Union (EU) and the North Atlantic Treaty Organization (NATO).", "The Organization of Petroleum Exporting Countries (OPEC) and ASEAN."]),
  ("Global Economy: International Monetary Fund (IMF)", "The primary operational mandate of the International Monetary Fund (IMF) is to:", "Ensure the stability of the international monetary and financial system, manage balance-of-payments crises, and provide short-term emergency loans.", ["Fund long-term infrastructure reconstruction projects in war-torn provinces (World Bank role).", "Adjudicate international maritime border disputes between sovereign navies (ICJ role).", "Enforce global labor human rights standards in textile factories (ILO role)."]),
  ("Global Economy: World Bank Group", "The overarching institutional mission of the World Bank is to:", "Provide long-term development loans, technical assistance, and policy advice to reduce poverty and foster sustainable economic development.", ["Regulate international floating currency exchange rates daily.", "Impose direct trade tariffs on imported foreign agricultural products.", "Print the official national paper currencies of sovereign states."]),
  ("Global Economy: General Agreement on Tariffs and Trade (GATT) to WTO", "In 1995, the General Agreement on Tariffs and Trade (GATT) was officially succeeded and transformed into the:", "World Trade Organization (WTO), which possesses legally binding dispute settlement mechanisms for international trade.", ["North American Free Trade Agreement (NAFTA).", "Asia-Pacific Economic Cooperation (APEC).", "Trans-Pacific Partnership (TPP)."]),
  ("Global Economy: The Washington Consensus", "The 'Washington Consensus', promoted by the IMF, World Bank, and US Treasury in the late 20th century, advocated economic policies centered on:", "Trade liberalization, privatization of state enterprises, deregulation, and fiscal austerity.", ["Strict protectionist import quotas and state-owned corporate monopolies.", "The complete nationalization of all private commercial banking assets.", "Universal basic income funded by 100% corporate wealth taxes."]),
  ("Global Governance: United Nations Principal Organs", "Under the UN Charter, which principal organ of the United Nations is charged with the primary responsibility for the maintenance of international peace and security?", "The Security Council (UNSC).", ["The General Assembly (UNGA).", "The International Court of Justice (ICJ).", "The Economic and Social Council (ECOSOC)."]),
  ("Global Governance: UN Security Council Permanent Five (P5)", "The United Nations Security Council consists of 15 members, including five permanent members (P5) who hold the power to 'Veto' substantive resolutions. Who are the P5?", "United States, United Kingdom, France, Russian Federation, and China.", ["United States, Germany, Japan, United Kingdom, and India.", "United States, Canada, Australia, France, and Germany.", "China, India, Brazil, Russian Federation, and South Africa (BRICS)."]),
  ("Global Governance: International Court of Justice (ICJ)", "The International Court of Justice (ICJ), seated at the Peace Palace in The Hague, Netherlands, functions primarily to:", "Settle legal disputes submitted to it by sovereign states in accordance with international law, and give advisory opinions.", ["Conduct criminal prosecutions against individual citizens for international human rights crimes (ICC role).", "Impose direct military blockades on sovereign naval ports.", "Collect annual tax contributions from commercial shipping corporations."]),
  ("Global Governance: International Criminal Court (ICC)", "Unlike the ICJ which adjudicates disputes between sovereign states, the International Criminal Court (ICC, established under the Rome Statute) prosecutes:", "Individual persons accused of genocide, crimes against humanity, war crimes, and the crime of aggression.", ["Corporate business monopolies violating antitrust regulations.", "Maritime shipping insurance underwriters in contractual disputes.", "Sovereign central banks defaulting on international bond debts."]),
  ("Regionalism: Founding of ASEAN (1967)", "The Association of Southeast Asian Nations (ASEAN) was officially founded on August 8, 1967 with the signing of the Bangkok Declaration by five founding member nations:", "Philippines, Indonesia, Malaysia, Singapore, and Thailand.", ["Philippines, Vietnam, Cambodia, Laos, and Myanmar.", "Philippines, Japan, South Korea, China, and Taiwan.", "Indonesia, Brunei, Timor-Leste, Singapore, and Papua New Guinea."]),
  ("Regionalism: The ASEAN Way", "The foundational diplomatic norm governing ASEAN relations, known as the 'ASEAN Way', is characterized by:", "Strict adherence to non-interference in internal affairs, consensus-based decision making, and informal consultation over legalistic confrontation.", ["Authoritarian military enforcement of democratic elections in member states.", "Immediate expulsion of any member state experiencing economic inflation.", "Mandatory adoption of a single common currency (like the Euro)."]),
  ("Regionalism: ASEAN Community Pillars", "Formally established in 2015, the ASEAN Community is structured upon which three integrative pillars?", "ASEAN Political-Security Community (APSC), ASEAN Economic Community (AEC), and ASEAN Socio-Cultural Community (ASCC).", ["ASEAN Agricultural League, ASEAN Industrial Guild, and ASEAN Maritime Fleet.", "ASEAN Monetary Union, ASEAN Military Alliance, and ASEAN Judicial Court.", "ASEAN Tourism Board, ASEAN Sports Council, and ASEAN Telecom Grid."]),
  ("Regionalism: Regional Comprehensive Economic Partnership (RCEP)", "Ratified by the Philippines in 2023, the Regional Comprehensive Economic Partnership (RCEP) is historically significant as:", "The world's largest Free Trade Agreement (FTA), encompassing the 10 ASEAN members plus Australia, China, Japan, South Korea, and New Zealand.", ["A military defense mutual pact establishing a unified Asian army.", "A treaty banning all agricultural commerce across the Pacific Ocean.", "A common environmental tax imposed on foreign tourism flights."])
]
d.extend([
  ("Global North vs Global South: The Brandt Line", "The socio-economic and political concept of the 'Global North vs Global South' (visualized historically by the Brandt Line) divides the world primarily based on:", "Differences in wealth, industrial development, human development indices, and historical colonial power relations, rather than strict geography.", ["Hemispheric latitude above and below the physical equator.", "The presence or absence of active volcanic mountain ranges.", "The official linguistic adoption of Spanish or English."]),
  ("Global North vs Global South: Dependency Theory", "Dependency Theory (developed by Raúl Prebisch and Fernando Henrique Cardoso) argues that the economic underdevelopment of the Global South is caused by:", "A global capitalist system that drains raw materials from peripheral nations to enrich industrialized core nations through unequal terms of trade.", ["The innate genetic laziness of tropical populations.", "The complete refusal of developing nations to trade in global markets.", "A chronic shortage of physical silver and gold coinage."]),
  ("Global Stratification: Wallerstein's World-Systems Theory", "Immanuel Wallerstein's World-Systems Theory divides the global capitalist division of labor into which three structural tiers?", "Core (high-skill/capital-intensive), Semi-Periphery (industrializing intermediary), and Periphery (low-skill/labor-intensive raw material extraction).", ["First World, Second World, and Third World.", "Upper Class, Middle Class, and Lower Class.", "Developing, Emerging, and Underdeveloped."]),
  ("Global Media: Cultural Imperialism vs Hybridization", "While critics of 'Cultural Imperialism' argue that Western media homogenizes global cultures into an 'Americanized McWorld', scholars of 'Hybridization' argue that:", "Global media flows combine with local traditions to create dynamic, syncretic new cultural expressions (e.g., K-pop, Pinoy Hip-Hop).", ["Local cultures are completely erased within 48 hours of television broadcasts.", "Audiences passively absorb foreign media messages without any interpretation.", "Cultural exchange is mathematically impossible across geographic borders."]),
  ("Global Culture: Roland Robertson's 'Glocalization'", "Sociologist Roland Robertson coined the term 'Glocalization' to describe the complex global process wherein:", "Global products, business strategies, and cultural practices are adapted and tailored to fit local cultural tastes and norms.", ["All local culinary traditions are replaced by identical canned goods.", "National governments completely ban all imported foreign media.", "Companies sell products exclusively within their city of origin."]),
  ("Global Culture: Arjun Appadurai's Five Scapes", "Anthropologist Arjun Appadurai conceptualized global cultural flows through five dimensions: Ethnoscapes (people), Technoscapes (tech), Finanscapes (money), Mediascapes (images/info), and:", "Ideoscapes (political ideas, values, and freedom/democracy narratives).", ["Chronoscapes.", "Geoscapes.", "Bioscapes."]),
  ("Religion and Globalization: Secularization vs Resurgence", "Contrary to early secularization theories predicting the disappearance of religion, globalization has catalyzed a 'Religious Resurgence' by:", "Providing global communication networks that enable transnational religious movements, identity mobilization, and interfaith dialogue.", ["Banning all religious practices across all United Nations member states.", "Replacing all global religious scriptures with corporate marketing manuals.", "Forcing all individuals to adopt atheism."]),
  ("Religion and Globalization: Fundamentalism", "Religious Fundamentalism often arises in the contemporary global era as a defensive psychological and cultural reaction against:", "The rapid cultural changes, moral relativism, secularization, and perceived corruption of traditional values brought by globalization.", ["The introduction of renewable solar panel electricity.", "The translation of religious scriptures into modern print fonts.", "The construction of municipal public library buildings."]),
  ("Demography & Migration: Demographic Transition Model (DTM)", "In the Demographic Transition Model, 'Stage 2' is characterized by:", "Rapid population growth caused by a dramatic drop in death rates (due to sanitation/medicine) while birth rates remain high.", ["High birth rates and high death rates resulting in stable population (Stage 1).", "Falling birth rates and low death rates slowing population growth (Stage 3).", "Low birth rates and low death rates with aging population (Stage 4)."]),
  ("Demography: Global Aging & Population Decline", "Many nations in the Global North and East Asia (e.g., Japan, South Korea, Italy) currently face a demographic crisis characterized by:", "Below-replacement fertility rates (TFR < 2.1) and an aging population, creating severe labor shortages and pension strain.", ["Rapid exponential population growth that doubles populations every 5 years.", "Massive child infant mortality epidemics.", "The complete abandonment of all urban cities."]),
  ("Global Migration: Push and Pull Factors", "In migration studies, which of the following represents a classic 'Push Factor' that compels individuals to emigrate from their home country?", "War, political persecution, violent civil conflict, severe poverty, or environmental disaster in the origin country.", ["Higher wages, stable political governance, and abundant job opportunities in the destination country (Pull Factor).", "Reuniting with family members who are already settled citizens abroad (Pull Factor).", "Free university scholarships provided by foreign governments (Pull Factor)."]),
  ("Global Migration: Philippine Remittance Economy", "Filipino international labor migration (OFWs) plays a transformative macroeconomic role in the Philippines, with personal remittances accounting for approximately:", "8% to 10% of national Gross Domestic Product (GDP), driving domestic household consumption and foreign exchange stability.", ["0.1% of national GDP with negligible economic impact.", "100% of the entire national government annual budget.", "Zero impact on foreign currency reserves."]),
  ("Global Migration: The 'Brain Drain' Phenomenon", "In development economics, 'Brain Drain' refers to the detrimental socio-economic consequence wherein a developing nation loses:", "Its highly educated, skilled professionals (e.g., doctors, nurses, engineers, scientists) to higher-paying foreign countries.", ["Its national historical archives during armed conflicts.", "Its physical electrical supply during monsoon typhoons.", "Its agricultural soil fertility due to chemical overuse."]),
  ("Sustainable Development: UN Sustainable Development Goals (SDGs 2030)", "Adopted by all United Nations Member States in 2015, the '2030 Agenda for Sustainable Development' establishes how many universal Sustainable Development Goals (SDGs)?", "17 Goals (with 169 associated targets addressing poverty, inequality, climate, and justice).", ["8 Goals (The historical Millennium Development Goals / MDGs).", "10 Goals.", "25 Goals."]),
  ("Sustainable Development: SDG 1 and SDG 4", "Under the UN 2030 Agenda, SDG 1 aims for 'No Poverty', while SDG 4 specifically aims to:", "Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all.", ["Achieve gender equality and empower all women and girls (SDG 5).", "Ensure availability and sustainable management of water and sanitation (SDG 6).", "Ensure access to affordable, reliable, sustainable modern energy (SDG 7)."])
])
d.extend([
  ("Global Food Security: The Global Food System", "The contemporary global food system is characterized by an acute paradox where:", "Nearly one billion people suffer from chronic hunger and malnutrition while over one billion suffer from obesity and massive food waste.", ["Food production is mathematically impossible across tropical latitudes.", "All food commodities are owned by a single family in Switzerland.", "Global agricultural yields have declined to zero since 1950."]),
  ("Global Food Security: Food Sovereignty", "In contrast to 'Food Security' (which focuses on food availability), the concept of 'Food Sovereignty' (championed by La Via Campesina) asserts:", "The right of peoples and local communities to define their own agricultural and food systems, prioritizing healthy, culturally appropriate food.", ["The exclusive right of multinational corporations to patent all plant genetic seeds.", "The mandatory importation of foreign agricultural surplus.", "The total elimination of all local organic family farming."]),
  ("Global Environmental Governance: The Montreal Protocol (1987)", "The 1987 Montreal Protocol is celebrated as the most successful international environmental treaty in history because it:", "Universally phased out the global production and consumption of ozone-depleting substances (such as chlorofluorocarbons / CFCs).", ["Completely eliminated all plastic waste from the Pacific Ocean.", "Banned the combustion of petroleum fuels in commercial aircraft.", "Prevented all volcanic eruptions in the northern hemisphere."]),
  ("Global Environmental Governance: Kyoto Protocol (1997)", "The 1997 Kyoto Protocol was historically significant as the first international agreement to:", "Set legally binding greenhouse gas emission reduction targets for industrialized (Annex I) developed nations.", ["Establish the United Nations Security Council.", "Impose uniform global income tax deductions on all workers.", "Ban the use of commercial internet services in Africa."]),
  ("Global Finance: Transnational Corporations (TNCs)", "Transnational Corporations (TNCs) differ from traditional domestic businesses because they:", "Own or control production facilities and operational assets across multiple sovereign countries, driving global trade and supply chains.", ["Operate exclusively within a single municipal trading town.", "Are prohibited from generating commercial profits.", "Are owned directly by the United Nations General Assembly."]),
  ("Global Finance: Foreign Direct Investment (FDI)", "In macroeconomic development, 'Foreign Direct Investment' (FDI) occurs when a foreign investor:", "Establishes lasting business operations or acquires physical enterprise assets (such as factories or branches) in a host economy.", ["Buys speculative lottery tickets in a foreign municipality.", "Sends informal holiday greeting cards to foreign pen pals.", "Exchanges currency at an international airport terminal."]),
  ("Global Finance: Global Value Chains (GVCs)", "In modern globalized manufacturing, a 'Global Value Chain' (GVC)—such as for the Apple iPhone or Toyota automobile—means that:", "Different stages of the production process (R&D, sourcing raw materials, manufacturing parts, assembly, and marketing) are distributed across multiple countries.", ["A single artisan craftsman manufactures the entire vehicle by hand in one village.", "Products must be consumed only within the country where iron ore was mined.", "All manufacturing components are transported exclusively by horse-drawn wagons."]),
  ("Global Civil Society: Non-Governmental Organizations (NGOs)", "International NGOs (such as Amnesty International, Greenpeace, and Doctors Without Borders) act as vital actors in global governance by:", "Holding governments and TNCs accountable, advocating for human rights, delivering humanitarian aid, and framing international policy norms.", ["Commanding sovereign standing armies to conduct invasions.", "Printing international paper currency notes.", "Signing binding international trade treaties on behalf of states."]),
  ("Global Cities: Saskia Sassen's Global City Concept", "Sociologist Saskia Sassen defines 'Global Cities' (such as New York, London, and Tokyo) as:", "Strategic command-and-control nodes of the global economy, concentrating advanced producer services (finance, law, accounting, and telecommunications).", ["Cities with the largest geographic physical land areas.", "Ancient historical archaeological ruin sites.", "Cities that completely prohibit international foreign trade."]),
  ("Global Cities: Manila as a Globalized Metropolis", "In global urban studies, Metro Manila is integrated into the global city network primarily as:", "A major global hub for Business Process Outsourcing (BPO / call centers), high-density labor migration, and financial real estate concentration.", ["A major global center for arctic icebreaker manufacturing.", "An isolated agricultural commune with zero internet connectivity.", "The primary physical headquarters of the United Nations Secretariat."]),
  ("Global Security: Non-Traditional Security Threats", "Contemporary international security studies increasingly focus on 'Non-Traditional Security Threats', which encompass:", "Climate change, global pandemics, transnational cyber-attacks, human trafficking, and resource scarcity.", ["Conventional interstate naval battleship duels with cannonballs.", "Medieval feudal cavalry skirmishes over castle moats.", "Standard diplomatic passport visa stamp formatting disputes."]),
  ("Global Security: Human Security Paradigm", "The United Nations Development Programme (UNDP 1994) introduced the 'Human Security' paradigm, shifting the focus of security from:", "The territorial defense of sovereign state borders to the protection and empowerment of individual human lives (freedom from fear and freedom from want).", ["The nuclear armament stockpiles of superpowers to planetary space laser defenses.", "National gross domestic product to corporate executive bonuses.", "Military conscription quotas to prison architecture."]),
  ("Global Health Governance: World Health Organization (WHO)", "The World Health Organization (WHO), a specialized agency of the United Nations headquartered in Geneva, is mandated to:", "Direct and coordinate international public health responses, establish global health standards, and manage health emergencies (e.g., pandemics).", ["Manufacture and sell commercial pharmaceutical drugs for corporate profit.", "Impose mandatory criminal prison sentences on unvaccinated individuals.", "Collect income taxes from private hospital patients."]),
  ("Global Trade: Protectionism vs Free Trade", "While 'Free Trade' advocates the elimination of tariffs and trade barriers to maximize economic efficiency, 'Protectionism' utilizes tariffs and quotas to:", "Shield domestic industries and local agricultural producers from foreign competitive import dumping.", ["Force domestic workers to accept lower wages.", "Ban all exports of domestic manufactured goods to foreign markets.", "Eliminate all national borders and customs checkpoints."]),
  ("Global Economy: Outsourcing and Offshoring", "Multinational corporations utilize 'Business Process Outsourcing' (BPO) to countries like the Philippines and India primarily to:", "Reduce operational costs, access highly skilled English-proficient talent pools, and leverage 24/7 global timezone coverage.", ["Escape all compliance with local labor legislation.", "Relocate their physical corporate headquarters to rural villages.", "Eliminate the use of digital telecommunications software."])
])
d.extend([
  ("Global Politics: Multipolarity vs Unipolarity", "The post-Cold War transition from American 'Unipolarity' (the 1990s US hegemony) toward contemporary 'Multipolarity' is marked by:", "The rise of multiple competing global and regional powers (such as China, the European Union, India, and the BRICS bloc).", ["The concentration of all global military power in a single small island nation.", "The total disappearance of all sovereign national foreign ministries.", "The establishment of a single planetary world government under one emperor."]),
  ("Global Politics: Soft Power vs Hard Power (Joseph Nye)", "Harvard scholar Joseph Nye coined 'Soft Power' to describe the ability of a nation to achieve its goals through:", "Attraction, cultural appeal, political values, and diplomatic persuasion, rather than military coercion or economic threats (Hard Power).", ["Threatening nuclear military bombardment against neighboring states.", "Imposing total naval economic blockades on commercial shipping.", "Bribing foreign diplomats with illegal offshore cash accounts."]),
  ("Global Law: UNCLOS and Maritime Sovereignty", "The 1982 United Nations Convention on the Law of the Sea (UNCLOS) establishes that a coastal state's 'Exclusive Economic Zone' (EEZ) extends:", "Up to 200 nautical miles from its territorial baselines, granting sovereign rights over exploration and exploitation of marine resources.", ["Up to 12 nautical miles (Territorial Sea).", "Up to 500 nautical miles.", "Across all international high seas without limitation."]),
  ("Philippine Foreign Policy: 2016 South China Sea Arbitral Ruling", "On July 12, 2016, the Permanent Court of Arbitration (PCA) in The Hague issued a historic landmark ruling in favor of the Philippines, concluding that:", "China's historic claim to maritime areas within the 'nine-dash line' has no legal basis under UNCLOS, and that Mischief Reef and Scarborough Shoal are within the Philippine EEZ/regime.", ["The Philippines must surrender all military bases in Palawan to foreign navies.", "UNCLOS does not apply to the Asian continent.", "Sovereign states are prohibited from fishing in their own coastal waters."]),
  ("Global Demography: The Malthusian Trap", "Thomas Malthus' 1798 'Essay on the Principle of Population' warned that unchecked population would outstrip resources because:", "Population grows geometrically (exponentially: 1, 2, 4, 8, 16...), while food production increases only arithmetically (linearly: 1, 2, 3, 4, 5...).", ["Food production grows exponentially while human populations remain constant.", "Technological progress completely eliminates the biological need for food.", "Human beings have a natural biological lifespan of 200 years."]),
  ("Global Demography: The Demographic Dividend", "The 'Demographic Dividend' refers to the accelerated economic growth potential that occurs when a nation's:", "Proportion of working-age population (15-64) is significantly larger than the non-working dependent population (young and elderly).", ["Birth rate exceeds 50 births per 1,000 citizens annually.", "Elderly population over age 80 comprises 90% of the citizenry.", "Total population declines by 50% within a single decade."]),
  ("Global Ethics: Cosmopolitanism vs Communitarianism", "While 'Cosmopolitanism' asserts that all human beings belong to a single global moral community with universal obligations, 'Communitarianism' argues that:", "Moral duties and identities are grounded fundamentally within specific local cultural, national, and historical communities.", ["Human beings have zero ethical obligations to anyone, including family.", "Global corporations should dictate all personal moral choices.", "Universal human rights are identical to municipal corporate bylaws."]),
  ("Global Culture: Cultural Homogenization ('McDonaldization')", "Sociologist George Ritzer's concept of 'McDonaldization' critiques modern global institutional culture for spreading the principles of:", "Efficiency, Calculability, Predictability, and Control through non-human technology across global society.", ["Spontaneity, Artistic Uniqueness, Chaos, and Intuition.", "Traditional Craftsmanship, Religious Asceticism, and Manual Labor.", "Absolute Egalitarian Democracy and Environmental Preservation."]),
  ("Global Inequality: The Gini Coefficient", "In global and national economic analysis, the 'Gini Coefficient' is a standard statistical metric used to measure:", "Income or wealth inequality within a population, ranging from 0 (perfect equality) to 1 (maximum inequality).", ["The average life expectancy of infants at birth.", "The annual percentage rate of national currency inflation.", "The physical depth of oceanic tectonic trenches."]),
  ("Global Environment: The Anthropocene", "Scientists increasingly designate the current geological epoch as the 'Anthropocene' to recognize that:", "Human industrial and technological activity has become the dominant driver of global environmental, climate, and planetary geological change.", ["Dinosaurs have re-emerged as the apex biological species on Earth.", "The Earth has entered an irreversible permanent ice age.", "Volcanic activity has ceased across all continental tectonic plates."]),
  ("Global Governance: The European Union (EU) as Supranational Integration", "The European Union (EU) represents a unique form of 'Supranational Governance' because member states:", "Pool portions of their national sovereignty in shared institutions (e.g., European Parliament, European Central Bank) that enact binding regional laws.", ["Surrender their distinct national languages and adopt Latin.", "Abolish all local municipal police forces in favor of a private security company.", "Merge all private bank accounts into a single personal checking account."]),
  ("Global Trade: Fair Trade Movement", "The 'Fair Trade' global certification movement aims to reform traditional international trade by:", "Guaranteeing fair minimum prices, safe working conditions, environmental standards, and community development premiums for marginalized Southern farmers.", ["Maximizing middleman broker profits in Western commodity exchanges.", "Subsidizing corporate agricultural conglomerates to dump surplus grain.", "Banning all coffee and cocoa imports from developing nations."]),
  ("Global Media: The 'Global Village' (Marshall McLuhan)", "Media theorist Marshall McLuhan famously coined the term 'The Global Village' (1962) to predict that electronic mass media would:", "Shrink the world psychologically and socially, connecting diverse human populations into an interconnected, instantaneous sensory collective.", ["Force all human beings to live in physical straw-hut rural villages.", "Destroy all electrical and electronic communication worldwide.", "Eliminate all forms of spoken and written human languages."]),
  ("Global Politics: Civil Society and Transnational Advocacy Networks (TANs)", "Margaret Keck and Kathryn Sikkink's concept of the 'Boomerang Pattern' in Transnational Advocacy Networks (TANs) explains how domestic NGOs:", "Bypass oppressive local governments by appealing to international allies and global organizations, who then pressure the domestic state from above.", ["Throw wooden boomerangs during diplomatic parliamentary summits.", "Export manufactured weaponry to foreign revolutionary factions.", "File domestic bankruptcy petitions in municipal tax courts."]),
  ("Global Economy: The Informal Economy / Shadow Economy", "In developing cities across the Global South (including Metro Manila), the 'Informal Economy' (street vending, unregistered services) accounts for a massive labor share because:", "It provides vital survival livelihoods for marginalized populations who are excluded from formal corporate and public sector employment.", ["It is strictly operated by foreign billionaire investment banks.", "It requires formal registration with the International Monetary Fund.", "It is 100% tax-subsidized by international United Nations grants."])
])
d.extend([
  ("Global Demography: Urbanization and Megacities", "A 'Megacity' in global demography is officially defined by the United Nations as an urban agglomeration with a population of:", "10 million inhabitants or more (e.g., Tokyo, Delhi, Shanghai, Metro Manila).", ["1 million inhabitants.", "500,000 inhabitants.", "50 million inhabitants."]),
  ("Global Demography: Slums and Informal Settlements", "According to UN-Habitat, the rapid, unplanned urbanization across the Global South has led to nearly one billion people living in informal settlements characterized by:", "Lack of clean water, inadequate sanitation, substandard housing, overcrowding, and insecure land tenure.", ["Excessive luxury swimming pools and private helicopter pads.", "Zero exposure to environmental pollution and flood hazards.", "100% home ownership guaranteed by international treaties."]),
  ("Global Health: Pandemics in an Interconnected World", "The rapid worldwide transmission of the COVID-19 pandemic demonstrated that modern globalization has created:", "Hyper-connected global aviation and trade networks that allow localized infectious pathogens to become global health crises in days.", ["Complete biological immunity across all international passenger flights.", "The total elimination of all bacterial respiratory illnesses.", "Instant universal access to medical vaccines within 2 minutes of outbreak."]),
  ("Global Ethics: Climate Justice and Loss and Damage", "The concept of 'Climate Justice' in international negotiations (e.g., the COP28 'Loss and Damage' Fund) asserts that:", "Industrialized nations historically responsible for the vast majority of carbon emissions must provide financial compensation to vulnerable developing nations.", ["Developing nations must pay all costs of repairing industrial smog in Europe.", "Small island nations should be abandoned to ocean rising tides without assistance.", "All fossil fuel reserves should be consumed immediately."]),
  ("Global Politics: The Responsibility to Protect (R2P)", "The United Nations 'Responsibility to Protect' (R2P) doctrine, endorsed by all member states in 2005, establishes that when a sovereign state fails to protect its own population from mass atrocities:", "The international community has a moral and legal duty to intervene through diplomatic, humanitarian, or coercive means under Chapter VII.", ["Foreign corporations may seize private agricultural land holdings.", "The state is granted absolute legal immunity from all human rights treaties.", "The United Nations must dissolve all international courts."]),
  ("Global Economy: De-Dollarization & Currency Hegemony", "Discussions surrounding 'De-Dollarization' by the BRICS economies reflect efforts to:", "Reduce reliance on the US Dollar in international trade settlements, oil pricing, and central bank foreign reserves.", ["Abolish all forms of physical and digital money worldwide.", "Adopt the ancient Roman silver denarius as the sole international currency.", "Force all international trade to be conducted through agricultural bartering."]),
  ("Global Environment: Planetary Boundaries Framework", "The Stockholm Resilience Centre's 'Planetary Boundaries' framework identifies nine critical Earth system processes (e.g., climate, biosphere integrity, nitrogen/phosphorus cycles) within which:", "Humanity can continue to develop and thrive for generations without triggering catastrophic, non-linear planetary environmental collapse.", ["Industrial mining corporations can pollute waterways without regulation.", "Global population must be forcibly relocated to Mars.", "Economic GDP growth is guaranteed to reach 100% annually."]),
  ("Global Media: Fake News and Algorithmic Polarization", "In contemporary global media studies, the proliferation of viral disinformation and fake news on social media is driven primarily by:", "Engagement-based algorithms designed to maximize platform watch-time and ad revenue by promoting sensational, polarizing, and outrage-inducing content.", ["Strict government censorship that eliminates all online entertainment.", "The total disappearance of all digital smartphones.", "The mandatory fact-checking of every internet post by university panels."]),
  ("Global Economy: Cryptocurrencies and Decentralized Finance (DeFi)", "Cryptocurrencies (such as Bitcoin and Ethereum) represent a novel frontier in global finance because they utilize decentralized blockchain technology to:", "Enable peer-to-peer digital transactions and value transfers without the intermediation of traditional central banks or financial institutions.", ["Guarantee that zero financial inflation will ever occur in national economies.", "Physical gold bars stored inside municipal banking basements.", "Provide free physical cash cards to all global citizens."]),
  ("Global Governance: Human Rights Instruments (UDHR 1948)", "Adopted by the United Nations General Assembly in Paris on December 10, 1948, the 'Universal Declaration of Human Rights' (UDHR):", "Articulates fundamental human rights to be universally protected for all human beings, regardless of race, nationality, religion, or sex.", ["Establishes an international military police force stationed in all schools.", "Mandates the payment of monetary tribute to the European Union.", "Bans all national legislative elections in sovereign states."]),
  ("Global Migration: Refugee Convention (1951)", "Under the 1951 UN Refugee Convention, the foundational principle of 'Non-Refoulement' strictly prohibits states from:", "Expelling or returning a refugee to a territory where their life or freedom would be threatened on account of race, religion, nationality, or political opinion.", ["Granting temporary emergency asylum to displaced mothers and children.", "Providing emergency medical food rations to displaced families.", "Allowing international humanitarian Red Cross volunteers into border zones."]),
  ("Global Politics: Geopolitical Conflict and Supply Chains", "Recent geopolitical crises (e.g., Russia-Ukraine war, Middle East tensions) illustrate that contemporary global supply chains are:", "Highly vulnerable to maritime chokepoints (e.g., Suez Canal, Strait of Malacca), energy disruptions, and global food inflation.", ["Completely immune to physical geography and military conflicts.", "Operated exclusively through teleportation laser satellites.", "Owned entirely by non-profit humanitarian charities."]),
  ("Global Culture: Transnational Diaspora Communities", "In contemporary globalization, 'Transnational Diaspora Communities' (such as the global Filipino diaspora) maintain active identity and development ties by:", "Engaging in cross-border cultural exchange, philanthropic investments in home provinces, political voting, and dual citizenship.", ["Completely severing all familial and cultural ties with their motherland.", "Refusing to learn the language of their host country.", "Surrendering all their financial earnings to foreign immigration authorities."]),
  ("Global Economy: Sovereign Wealth Funds", "A 'Sovereign Wealth Fund' (SWF)—such as Norway's Government Pension Fund Global or the Philippines' Maharlika Investment Fund—is:", "A state-owned investment fund composed of financial assets (stocks, bonds, real estate) managed to generate long-term national wealth for future generations.", ["A private personal bank account owned by an individual municipal mayor.", "An international emergency loan provided by the International Monetary Fund.", "A tax penalty fund collected from defaulting commercial corporations."]),
  ("The Contemporary World: Global Citizenship", "In 21st-century education, cultivating 'Global Citizenship' empowers learners to:", "Understand their interconnectedness with the wider world, respect diversity, champion human rights, and take responsible action for global sustainability.", ["Abandon their love and loyalty for their own native homeland.", "Refuse participation in local community civic development.", "Prioritize private commercial profit over social justice and environmental health."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This question evaluates understanding in {item[0]}. {item[2]} reflects established global studies, international relations, and socio-economic consensus."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('socialStudiesExams.ts', 'SOCIAL_STUDIES_EXAM_QUESTIONS', questions)
