import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Philosophical Foundations: Essentialism (Bagley)", "A school curriculum that strictly prioritizes traditional core academic disciplines (3Rs: Reading, wRiting, aRithmetic) and teacher-centered transmission of cultural heritage exemplifies:", "Essentialism (William Bagley).", ["Progressivism (John Dewey).", "Existentialism (Jean-Paul Sartre).", "Reconstructionism (Theodore Brameld)."], "Essentialism focuses on traditional academic basics, core knowledge, teacher authority, and cultural heritage transmission."),
  ("Philosophical Foundations: Perennialism (Hutchins & Adler)", "A university curriculum centered on studying the 'Great Books of the Western World' and timeless, enduring universal truths that have stood the test of centuries is rooted in:", "Perennialism (Robert Maynard Hutchins & Mortimer Adler).", ["Essentialism.", "Progressivism.", "Behaviorism."], "Perennialism views truth as timeless and universal; curriculum should focus on the enduring great works of literature, philosophy, and classical human achievements."),
  ("Philosophical Foundations: Progressivism (John Dewey)", "John Dewey's 'Progressivism' views education not as preparation for life, but as life itself. A progressive curriculum is characterized by:", "Learner-centered inquiry, experiential learning ('learning by doing'), hands-on problem solving, and democratic classroom processes.", ["Rigid rote memorization of static canonical facts.", "Teacher-centered authoritative lecturing with zero student input.", "Strict religious dogmatic indoctrination."], "Progressivism emphasizes active, experiential learning, real-world problem-solving, reflective inquiry, and democratic student participation."),
  ("Philosophical Foundations: Social Reconstructionism (Brameld & Counts)", "George Counts in Dare the School Build a New Social Order? and Theodore Brameld advocated 'Social Reconstructionism', which asserts that the curriculum must:", "Critique systemic social injustices and empower students to become active change-agents who reconstruct and improve society.", ["Preserve existing social stratification and economic inequality uncritically.", "Focus exclusively on ancient Greek Latin grammar without modern application.", "Prepare students to be obedient corporate factory workers without political voice."], "Reconstructionism views schools as instruments of social reform and transformation, addressing pressing societal crises such as poverty, racism, and inequality."),
  ("Philosophical Foundations: Existentialism in Curriculum", "An existentialist approach to curriculum design emphasizes:", "Individual freedom of choice, personal self-definition, authenticity, and exploring personal values through the humanities and arts.", ["Standardized uniform pacing where all students must produce identical assignments.", "Strict behavioral conditioning through operant rewards and punishments.", "Passive compliance with corporate workforce mandates."], "Existentialism stresses individual autonomy, self-determination, personal responsibility, and subjective meaning-making in education."),
  ("Historical Foundations: Franklin Bobbitt (The Curriculum, 1918)", "Franklin Bobbitt, who published the first textbook on curriculum in 1918, viewed curriculum as:", "A scientific series of structured educational experiences designed to train students for specific adult occupational and social roles.", ["A spiritual voyage into medieval monastic mysticism.", "A random collection of unrelated classroom games.", "A purely administrative budget allocation document."], "Bobbitt pioneered the scientific, efficiency-oriented approach to curriculum, analyzing adult activities to formulate specific educational training objectives."),
  ("Historical Foundations: Werrett Charters & Activity Analysis", "Werrett Charters expanded Bobbitt's work by developing 'Activity Analysis' in curriculum, which involves:", "Systematically analyzing occupational tasks and activities to derive precise, measurable learning objectives and instructional content.", ["Memorizing classical poetry without practical relevance.", "Letting students design curricula with zero teacher involvement.", "Eliminating all vocational subjects from secondary schools."], "Charters emphasized activity and job analysis as the scientific basis for determining curriculum objectives and instructional content."),
  ("Historical Foundations: William Kilpatrick (The Project Method)", "William Heard Kilpatrick, a student of John Dewey, introduced the 'Project Method' in curriculum, defining a project as:", "A 'hearty purposeful act' carried on in a social environment that engages learners in real-world creative construction.", ["A 100-item multiple-choice pencil-and-paper quiz.", "A silent individual reading of dictionary definitions.", "A punitive disciplinary assignment given to misbehaving pupils."], "Kilpatrick's Project Method emphasizes wholehearted, purposeful activity carried out by students in a social context (producer, consumer, problem, or drill projects)."),
  ("Historical Foundations: Harold Rugg & Integrated Curriculum", "Harold Rugg advocated that the curriculum should NOT be fragmented into isolated, rigid academic subjects, but instead should:", "Integrate social studies, history, economics, and sociology around real-world contemporary social problems and active student research.", ["Focus strictly on Latin grammar drills.", "Separate all subjects into watertight isolated compartments.", "Eliminate all social science courses from public high schools."], "Rugg pioneered integrated social studies textbooks, organizing content around critical social problems, democratic issues, and active student inquiry."),
  ("Historical Foundations: Hollis Caswell (Curriculum as Experiences)", "Hollis Caswell redefined curriculum by shifting the concept from a fixed course of study or syllabus to:", "'All the learning experiences children have under the guidance of teachers.'", ["Only the physical printed textbooks purchased by the school.", "The physical architecture of classroom school buildings.", "The municipal budget allocated for teacher salaries."], "Caswell and Campbell (1935) famously defined curriculum as all the experiences learners have under the direction and guidance of the school."),
  ("Curriculum Models: Ralph Tyler's Objective-Centered Model (1949)", "Ralph Tyler's seminal Basic Principles of Curriculum and Instruction presents a linear model structured around four fundamental questions in which sequence?", "1. Purpose/Objectives -> 2. Learning Experiences -> 3. Organization of Experiences -> 4. Evaluation of Outcomes.", ["1. Evaluation -> 2. Textbooks -> 3. Class Schedule -> 4. Objectives.", "1. Budget -> 2. Building -> 3. Hiring -> 4. Teaching.", "1. Exams -> 2. Homework -> 3. Grading -> 4. Graduation."], "The Tyler Rationale is the classic deductive, linear curriculum model: Determine objectives, select learning experiences, organize experiences, and evaluate effectiveness."),
  ("Tyler's Model: Sources of Objectives", "According to Ralph Tyler, curriculum planners must derive educational objectives from which three primary sources?", "Studies of the Learners, Studies of Contemporary Life, and Suggestions from Subject Specialists (screened through Philosophy and Psychology).", ["Government military decrees, Corporate marketing goals, and Royal edicts.", "Textbook sales records, Real estate prices, and School tuition rates.", "Standardized test score distributions only."], "Tyler identified three sources: the learners themselves, contemporary societal needs, and subject specialists, which are then screened through the school's educational philosophy and psychology of learning."),
  ("Curriculum Models: Hilda Taba's Grassroots (Inductive) Model", "Hilda Taba criticized Tyler's top-down approach, proposing an 'Inductive / Grassroots Model' based on the core conviction that:", "Teachers, who actually teach the curriculum, should be the primary designers who develop curriculum units inductively from classroom practice.", ["Curriculum must be dictated exclusively by centralized national ministries without teacher input.", "Curriculum should be created by commercial textbook sales corporations.", "Students should write all national curriculum standards alone."], "Taba's Grassroots Approach argues that curriculum development should begin from the bottom up (teachers diagnosing needs, formulating objectives, selecting content, and organizing learning)."),
  ("Curriculum Models: Saylor, Alexander, and Lewis Model", "The Saylor, Alexander, and Lewis curriculum model conceptualizes curriculum planning as a systematic process progressing through:", "Goals/Objectives -> Curriculum Designing -> Curriculum Implementation (Instruction) -> Curriculum Evaluation.", ["Hiring -> Budgeting -> Purchasing -> Grading.", "Testing -> Failing -> Retesting -> Passing.", "Syllabus -> Textbook -> Exam -> Graduation."], "Saylor and Alexander's model structures curriculum planning systematically across goals/domains, design selection, instructional implementation, and comprehensive evaluation."),
  ("Curriculum Models: Peter Oliva's 12-Component Model", "Peter Oliva's comprehensive curriculum model is characterized as:", "A systematic, step-by-step, comprehensive 12-component framework that bridges philosophical foundations with classroom instructional implementation and evaluation.", ["A purely theoretical essay without practical applicability.", "A 2-step process that eliminates all evaluation.", "A model designed exclusively for technical automotive schools."])
]
d.extend([
  ("Curriculum Types: Allan Glatthorn's Seven Types", "Allan Glatthorn categorized curriculum into operational types. The official curriculum documents, syllabi, course guides, and curriculum standards issued by DepEd/CHED represent the:", "Written (Official) Curriculum.", ["Taught Curriculum.", "Supported Curriculum.", "Assessed Curriculum."]),
  ("Curriculum Types: Taught Curriculum", "The actual day-to-day instructional activities, lessons, discussions, and pedagogical methods executed by the teacher inside the classroom constitute the:", "Taught Curriculum.", ["Written Curriculum.", "Hidden Curriculum.", "Null Curriculum."]),
  ("Curriculum Types: Supported Curriculum", "The instructional resources, textbooks, science laboratories, digital learning platforms, audio-visual materials, and library facilities that support teaching represent the:", "Supported Curriculum.", ["Taught Curriculum.", "Assessed Curriculum.", "Learned Curriculum."]),
  ("Curriculum Types: Assessed Curriculum", "The formative quizzes, quarterly summative tests, performance task rubrics, and national achievement examinations used to measure student mastery constitute the:", "Assessed Curriculum.", ["Supported Curriculum.", "Written Curriculum.", "Hidden Curriculum."]),
  ("Curriculum Types: Learned Curriculum", "The actual learning outcomes, knowledge, skills, values, and behavioral changes that students demonstrably internalize and achieve represent the:", "Learned Curriculum.", ["Written Curriculum.", "Taught Curriculum.", "Supported Curriculum."]),
  ("Curriculum Types: Hidden Curriculum (Jackson & Apple)", "Philip Jackson coined the term 'Hidden Curriculum' to describe:", "The unintended, implicit, unwritten messages, social values, norms, obedience habits, and behavioral expectations absorbed from school culture and social structure.", ["The official printed syllabus published by the ministry of education.", "Textbooks locked in storage basements that students cannot access.", "Elective courses that students choose to take secretly."]),
  ("Curriculum Types: Null Curriculum (Elliot Eisner)", "Elliot Eisner introduced the concept of the 'Null Curriculum' to refer to:", "The topics, perspectives, critical histories, or knowledge domains that schools explicitly do NOT teach, thereby signaling they lack importance.", ["The written course syllabus printed on blank paper.", "Lessons that students fail on final examinations.", "Curriculum documents that have expired legally."]),
  ("Curriculum Design Models: Subject-Centered Design", "A curriculum design structured around separate, traditional academic subject disciplines (e.g., Biology, Chemistry, Physics, History) with a focus on logical content mastery is:", "Subject-Centered Curriculum Design.", ["Learner-Centered Design.", "Problem-Centered Design.", "Experience-Centered Design."]),
  ("Curriculum Design: Correlation vs Integration", "In subject-centered design, 'Correlated Design' links two related subjects while keeping them separate (e.g., studying Philippine literature alongside Philippine history), whereas 'Broad Fields Design':", "Merges related subjects into a single comprehensive learning area (e.g., combining history, economics, geography into 'Social Studies' / Araling Panlipunan).", ["Eliminates all social science subjects entirely.", "Teaches subjects in completely different languages.", "Restricts all learning to mathematical calculations."]),
  ("Curriculum Design: Learner-Centered Design", "A curriculum design organized around the developmental needs, individual interests, self-expression, and real-life experiences of the student (championed by Rousseau, Pestalozzi, and Dewey) is:", "Learner-Centered / Child-Centered Design.", ["Subject-Centered Design.", "Core Problem Design.", "Discipline-Based Design."]),
  ("Curriculum Design: Problem-Centered Design (Life Situations)", "A curriculum design organized around persistent life situations, contemporary community problems, and social challenges (e.g., climate change, poverty, public health) is:", "Problem-Centered / Life-Situations Design.", ["Subject-Centered Design.", "Traditional Discipline Design.", "Static Rote Design."]),
  ("K to 12 Basic Education Act: Republic Act 10533", "Republic Act 10533 (Enhanced Basic Education Act of 2013) expanded Philippine basic education from a 10-year cycle to a 13-year compulsory framework comprising:", "1 year of Universal Kindergarten, 6 years of Elementary, 4 years of Junior High School, and 2 years of Senior High School.", ["10 years of Elementary and 3 years of College.", "6 years of High School only with zero elementary education.", "8 years of Primary and 5 years of Technical School."]),
  ("K to 12 Curriculum Principles: Spiral Progression (Bruner)", "The 'Spiral Progression' approach in the K to 12 curriculum (rooted in Jerome Bruner's educational theory) dictates that concepts and skills are:", "Taught across grade levels with increasing depth, breadth, and cognitive complexity, continuously revisiting and building upon foundational schemas.", ["Taught once in a single grade and never mentioned or reinforced again.", "Restricted exclusively to high school senior students.", "Taught in reverse alphabetical order."]),
  ("K to 12 Curriculum: Mother Tongue-Based Multilingual Education (MTB-MLE)", "Under the original K to 12 framework (RA 10533), MTB-MLE was mandated from Kindergarten to Grade 3 based on research demonstrating that:", "Children learn to read, write, and comprehend cognitive concepts faster and build stronger literacy when initial instruction is in their native Mother Tongue.", ["Children should only hear foreign languages from birth.", "Local indigenous languages have zero linguistic vocabulary.", "English should be the sole spoken medium in kindergarten classrooms."]),
  ("K to 12 Senior High School Curriculum Tracks", "Under DepEd's K to 12 Senior High School curriculum, which of the following represents the four official curricular tracks available to students?", "Academic Track, Technical-Vocational-Livelihood (TVL) Track, Sports Track, and Arts & Design Track.", ["General Track, Military Track, Agricultural Track, and Maritime Track.", "Primary Track, Secondary Track, Tertiary Track, and Post-Graduate Track.", "Science Track, Math Track, English Track, and Filipino Track."])
])
d.extend([
  ("Backward Design / Understanding by Design (UbD - Wiggins & McTighe)", "Grant Wiggins and Jay McTighe's 'Backward Design' (UbD) framework structures curriculum planning in which three sequential stages?", "Stage 1: Identify Desired Results -> Stage 2: Determine Acceptable Evidence -> Stage 3: Plan Learning Experiences and Instruction.", ["Stage 1: Plan Daily Activities -> Stage 2: Teach the Lesson -> Stage 3: Make up a Test.", "Stage 1: Buy Textbooks -> Stage 2: Assign Grades -> Stage 3: Define Goals.", "Stage 1: Administer Finals -> Stage 2: Calculate GPA -> Stage 3: Write Syllabus."]),
  ("UbD: Stage 1 (Big Ideas & Essential Questions)", "In Stage 1 of UbD, teachers design 'Essential Questions' which are characterized as:", "Open-ended, thought-provoking, intellectually engaging questions that spark inquiry and recur throughout life (e.g., 'What makes a society just?').", ["Closed factual questions that can be answered in one second with a yes/no.", "Multiple-choice exam questions copied from standardized test banks.", "Administrative queries regarding school supply inventories."]),
  ("UbD: Six Facets of Understanding", "Wiggins and McTighe define genuine conceptual understanding through the 'Six Facets of Understanding':", "Explanation, Interpretation, Application, Perspective, Empathy, and Self-Knowledge.", ["Recall, Recognition, Repetition, Recitation, Retention, and Response.", "Reading, Writing, Arithmetic, Art, Athletics, and Attendance.", "Observation, Measurement, Classification, Prediction, Inference, and Communication."]),
  ("Curriculum Implementation: Models of Curriculum Change", "In curriculum implementation, the 'Concerns-Based Adoption Model' (CBAM) tracks how teachers adopt innovations through:", "Stages of Concern (from awareness/informational concerns to collaboration and refocusing) and Levels of Use.", ["Mandatory physical compliance inspections by armed police.", "Immediate financial penalties for teachers asking questions.", "Standardized student multiple-choice score tracking only."]),
  ("Curriculum Change: Overcoming Resistance to Change", "To overcome teacher resistance to a new curriculum reform, educational leadership research recommends:", "Involving teachers in planning, providing continuous professional training and coaching, and ensuring adequate instructional resources.", ["Issuing punitive top-down administrative reprimands for any hesitancy.", "Implementing the change secretly without informing faculty members.", "Replacing all senior teachers with temporary interns."]),
  ("Curriculum Evaluation: Stufflebeam's CIPP Model", "Daniel Stufflebeam's CIPP Evaluation Model is a comprehensive framework that evaluates curriculum across which four dimensions?", "Context Evaluation, Input Evaluation, Process Evaluation, and Product Evaluation.", ["Content, Instruction, Pedagogy, and Performance.", "Curriculum, Infrastructure, Personnel, and Profit.", "Cognitive, Interpersonal, Physical, and Psychological."]),
  ("CIPP Model: Context Evaluation", "In Stufflebeam's CIPP model, 'Context Evaluation' serves primarily to:", "Assess the underlying baseline needs, problems, assets, and educational context of the target community to determine goals.", ["Evaluate the final standardized test scores of graduating students.", "Audit the financial receipts of textbook publishers.", "Observe daily teacher classroom attendance records."]),
  ("CIPP Model: Input Evaluation", "In Stufflebeam's CIPP model, 'Input Evaluation' assesses:", "The available human resources, budget, alternative strategies, facilities, and action plans to determine how best to achieve goals.", ["The historical origin of ancient curriculum theories.", "The final career placement rates of alumni.", "The physical room temperature of school classrooms."]),
  ("CIPP Model: Process Evaluation", "In the CIPP model, 'Process Evaluation' is conducted during implementation to:", "Monitor the ongoing execution of curriculum activities, identify operational bottlenecks, and provide formative feedback for refinement.", ["Decide whether to permanently cancel the program before it begins.", "Record final letter grades on graduation diplomas.", "Calculate the annual property tax of school buildings."]),
  ("CIPP Model: Product Evaluation", "In the CIPP model, 'Product Evaluation' measures:", "The actual outcomes, achievements, intended/unintended impacts, and long-term effectiveness of the curriculum against its objectives.", ["The initial budget proposal submitted to legislators.", "The physical dimensions of printed curriculum guides.", "The daily morning announcements made over the school intercom."]),
  ("Curriculum Evaluation: Scriven's Formative vs Summative Evaluation", "Michael Scriven famously distinguished between Formative and Summative evaluation in curriculum: 'When the cook tastes the soup, that's Formative; when the guests taste the soup, that's Summative.' This means:", "Formative evaluation is conducted during development to improve the program; Summative is conducted at the end to judge overall worth/effectiveness.", ["Formative evaluation is for grading students; Summative is for grading teachers.", "Formative is conducted by parents; Summative is conducted by students.", "Formative is illegal; Summative is legally mandated."]),
  ("Curriculum Evaluation: Scriven's Goal-Free Evaluation", "In Michael Scriven's 'Goal-Free Evaluation' approach, the evaluator intentionally avoids knowing the program's official stated goals primarily to:", "Discover and assess ALL actual outcomes, including unintended side-effects and serendipitous impacts, without preconceived bias.", ["Save time by skipping data collection entirely.", "Allow the school principal to write the evaluation report without research.", "Focus only on the financial balance sheet of the school."]),
  ("Curriculum Criteria: Continuity, Sequence, Integration (Tyler)", "Ralph Tyler identified three major criteria for effective curriculum organization. 'Sequence' requires that:", "Each successive learning experience builds upon preceding ones, taking concepts to progressively higher levels of depth and complexity.", ["All subjects are taught at the exact same hour every day.", "Textbooks are printed on glossy paper stock.", "All students finish assignments in identical amounts of time."]),
  ("Curriculum Criteria: Integration", "Tyler's criterion of 'Integration' in curriculum organization ensures that:", "Learning experiences across different subject areas are horizontally connected, helping students perceive unified knowledge rather than fragmented facts.", ["Subjects are kept in completely isolated 45-minute compartments.", "Students are prohibited from discussing science concepts in math class.", "Textbooks are bound into a single 5,000-page heavy volume."]),
  ("Curriculum Alignment: Horizontal vs Vertical Alignment", "While 'Vertical Alignment' ensures smooth progression of learning competencies from grade level to grade level, 'Horizontal Alignment' ensures that:", "Curriculum standards, instructional materials, daily lessons, and classroom assessments within the SAME grade level are mutually congruent.", ["Classroom whiteboards are hung parallel to the floor.", "All teachers in a school earn identical monthly salaries.", "School desks are arranged in straight horizontal lines."])
])
d.extend([
  ("Curriculum Contextualization: Localization & Indigenization", "Under DepEd Order 35, s. 2016, what is the difference between 'Localization' and 'Indigenization' of the curriculum?", "Localization relates learning content to local information/materials, while Indigenization enhances the curriculum based on the indigenous community's cultural worldview and life systems.", ["Localization translates English into Tagalog; Indigenization translates Tagalog into Spanish.", "Localization is for elementary; Indigenization is for high school.", "Localization is illegal; Indigenization is voluntary."]),
  ("Curriculum Adaptation for Inclusive Education", "When a teacher adapts the regular general education curriculum for a learner with low vision by providing large-print texts, high-contrast digital displays, and extra time, this is:", "An Instructional Accommodation (adapting accessibility and format without lowering learning standards).", ["A Curricular Modification (substantially altering or lowering core learning standards).", "A Punitive Disciplinary Sanction.", "A Complete Curriculum Exclusion."]),
  ("Curricular Modifications vs Accommodations", "In inclusive education, how does a 'Curricular Modification' differ fundamentally from an 'Accommodation'?", "Modifications change WHAT the student is taught and alter performance expectations, while Accommodations change HOW the student accesses the identical curriculum.", ["Modifications apply only to sports; Accommodations apply only to math.", "Modifications are free; Accommodations require monthly cash payments.", "Modifications are designed by parents; Accommodations are designed by students."]),
  ("Curriculum Mapping: Mapping Matrix (Heidi Hayes Jacobs)", "According to Heidi Hayes Jacobs, the primary purpose of 'Curriculum Mapping' is to:", "Create visual temporal roadmaps of taught content, competencies, skills, and assessments to identify curriculum gaps, redundancies, and misalignments.", ["Calculate the physical square footage of school classrooms.", "Assign daily homework scores on report cards.", "Design architectural blueprints for school building construction."]),
  ("Curriculum Implementation: Fidelity of Implementation", "In curriculum research, 'Fidelity of Implementation' measures the extent to which:", "A newly adopted curriculum innovation is being delivered in classrooms as originally designed and intended by curriculum planners.", ["Teachers arrive at school before 7:00 AM every morning.", "School libraries buy 100 new books every semester.", "Students memorize textbook chapters word-for-word."]),
  ("Curriculum Implementation: Mutual Adaptation Model", "In contrast to strict fidelity, the 'Mutual Adaptation' perspective recognizes that:", "Teachers and administrators actively adapt, adjust, and reshape the curriculum innovation to fit their unique local classroom realities and learner needs.", ["Teachers must strictly follow scripted manuals without changing a single word.", "Innovations must fail in 100% of school districts.", "Curriculum should never be changed after publication."]),
  ("Curriculum Stakeholders: Roles in Development", "Who are the primary curriculum implementers whose professional competence, attitudes, and pedagogical choices determine the actual success of any curriculum reform?", "Teachers (the frontline curriculum implementers).", ["School security guards.", "Commercial advertising agencies.", "Textbook printing press operators."]),
  ("Curriculum Stakeholders: Learners as the Core", "In student-centered curriculum development, why are learners considered the central stakeholder and heart of the curriculum?", "Because the curriculum exists ultimately for their holistic development, cognitive growth, and life empowerment.", ["Because students pay taxes directly to the national treasury.", "Because students design all national educational laws.", "Because students grade teacher performance daily."]),
  ("Curriculum Development: Needs Assessment Phase", "The very first phase in any systematic curriculum development cycle is the 'Needs Assessment', which serves to:", "Identify the discrepancy (gap) between current learner/societal conditions and desired educational outcomes to justify curriculum goals.", ["Print 10,000 copies of the syllabus before testing.", "Hire construction workers to build new auditoriums.", "Assign final course grades to all enrolled students."]),
  ("Curriculum Design: Core Curriculum Design", "A 'Core Curriculum' design model ensures that:", "A common, foundational set of essential learning competencies and shared cultural knowledge is required for all learners regardless of specialization.", ["Students choose 100% of their classes with zero required subjects.", "Only students pursuing engineering take science classes.", "All vocational subjects are eliminated from high schools."]),
  ("Curriculum Scope and Sequence", "In curriculum documentation, 'Scope' defines the breadth and depth of content and skills covered, while 'Sequence' defines:", "The chronological order, logical progression, and pacing in which learning experiences are delivered across time.", ["The monetary budget allocated for purchasing textbooks.", "The physical weight of student backpacks.", "The room numbers where classes are held."]),
  ("Curriculum Balance: Cognitive, Affective, Psychomotor", "An effective, holistic curriculum maintains 'Balance' by ensuring equitable attention to which three learning domains (Bloom/Krathwohl/Dave)?", "Cognitive (Knowledge/Head), Affective (Values/Attitudes/Heart), and Psychomotor (Skills/Actions/Hands).", ["Physical, Chemical, and Biological.", "Reading, Writing, and Typing.", "Economic, Political, and Administrative."]),
  ("Curriculum Articulation: Vertical and Horizontal", "Curriculum 'Articulation' refers to the smooth coordination and interconnectedness of learning experiences so that:", "Transition from one grade level to the next (vertical) and across subjects within a grade (horizontal) occurs without gaps, overlaps, or contradictions.", ["All school buildings are connected by covered walkways.", "Students wear identical school uniforms in all grades.", "Teachers teach for 8 hours without stopping."]),
  ("Curriculum Pilot Testing / Try-Out Phase", "Before a new national curriculum is mandated across thousands of schools, curriculum developers conduct 'Pilot Testing' in sample schools to:", "Gather empirical formative feedback on feasibility, clarity, pacing, and instructional materials to make necessary revisions.", ["Prove that the original curriculum draft was 100% perfect without flaws.", "Spend surplus government funds before the fiscal year ends.", "Eliminate all teacher input from the revision process."]),
  ("Curriculum Reform: MATATAG Curriculum (DepEd)", "The revised 'MATATAG Curriculum' in Philippine basic education was designed specifically to:", "Decongest curriculum competencies, strengthen foundational literacy and numeracy, and emphasize character building and peace education.", ["Add 500 new memorization competencies to every grade level.", "Eliminate all teaching of reading and writing in early grades.", "Replace all certified teachers with automated tablet screens."])
])
d.extend([
  ("Curriculum Change: Types of Change (McNeil)", "According to John McNeil, a 'Substitution' curriculum change occurs when:", "One existing instructional element (e.g., an outdated textbook) is replaced by a newer element with no fundamental change in curriculum structure.", ["The entire philosophy and structure of the school system is overhauled (Restructuring).", "Minor modifications are made to lesson sequence (Alteration).", "A completely new learning track is added (Perturbation)."]),
  ("Curriculum Change: Restructuring / Fundamental Change", "When a national education system transitions from a 10-year basic education cycle to the K to 12 system with senior high tracks, this represents:", "Restructuring (system-wide, fundamental structural and organizational transformation).", ["Minor substitution of one textbook.", "A temporary 1-week curriculum perturbation.", "Routine daily lesson planning."]),
  ("Curriculum Evaluation: Formative vs Summative Decisions", "A curriculum evaluation committee decides to revise Grade 7 science modules during mid-year implementation based on quarterly feedback. This decision is:", "Formative in nature (aimed at ongoing improvement, refinement, and pedagogical adjustment).", ["Summative in nature (aimed at final program termination or accreditation).", "A punitive disciplinary sanction against authors.", "An administrative budget audit."]),
  ("Curriculum Evaluation: Summative Decisions", "After 5 years of implementing a national scholarship curriculum, the department conducts a comprehensive evaluation to decide whether to continue, expand, or terminate the program. This is:", "Summative evaluation (evaluating overall merit, worth, and long-term viability).", ["Formative diagnostic checking.", "Pilot testing.", "Needs assessment."]),
  ("Curriculum Materials: Textbook Quality Standards", "When evaluating instructional textbooks for curriculum adoption, the primary pedagogical criteria must include:", "Content accuracy, alignment with curriculum standards, absence of bias, developmental appropriateness, and quality of pedagogical activities.", ["The brightness and glossy sheen of the outer cover page.", "The physical weight of the bound book.", "The commercial marketing fame of the publishing corporation."]),
  ("Curriculum Alignment: The Intended vs Implemented vs Achieved Curriculum", "In international curriculum studies (e.g., TIMSS/PISA), learning gaps occur primarily when there is a significant mismatch between:", "The Intended Curriculum (what is officially prescribed), the Implemented Curriculum (what is actually taught), and the Achieved Curriculum (what students learn).", ["The color of classroom chalk and the color of school buses.", "The school principal's salary and the school tuition rate.", "The morning flag ceremony and the afternoon dismissal time."]),
  ("Curriculum Design: Discipline-Based vs Interdisciplinary Design", "While 'Discipline-Based Design' teaches subjects in isolation according to academic domains, 'Interdisciplinary Design':", "Combines knowledge, concepts, and inquiry methods from two or more disciplines to explore a central theme or real-world problem.", ["Prohibits students from reading books outside their major subject.", "Forces all teachers to teach all subjects simultaneously.", "Eliminates all scientific research in high schools."]),
  ("Curriculum Evaluation: Teacher Evaluation in Curriculum", "Why is continuous teacher evaluation and classroom observation an integral component of curriculum evaluation?", "Because the quality and fidelity of classroom instructional delivery directly determine the success of the curriculum.", ["To find excuses to fire experienced senior teachers.", "To replace teacher observations with automated computer surveillance.", "To calculate the annual electricity consumption of classrooms."]),
  ("Curriculum Integration: Theme-Based Learning Units", "In an integrated curriculum, a Grade 4 team designs a 3-week unit around the theme 'Water: Life, Ecology, and Society' integrating Science, Math, Social Studies, and English. This is an example of:", "Thematic / Interdisciplinary Curriculum Integration.", ["Subject-Centered isolated compartmentalization.", "Null curriculum omission.", "Rote drill-and-practice curriculum."]),
  ("Curriculum Innovation: Service-Learning in the Curriculum", "Service-Learning integrates meaningful community service with academic curriculum study primarily to:", "Enrich learning experiences, teach civic responsibility, and strengthen local communities through structured reflective practice.", ["Use students as unpaid manual laborers for private commercial businesses.", "Replace academic learning with unguided social socializing.", "Avoid classroom instructional hours."]),
  ("Curriculum Standards: Content Standards vs Performance Standards (DepEd)", "In DepEd's K to 12 curriculum guides, 'Content Standards' define what learners should know and understand, while 'Performance Standards' define:", "What learners should be able to do, produce, or perform using their knowledge and skills in authentic contexts.", ["The exact percentage of students who will pass the course.", "The number of hours the teacher must spend lecturing.", "The physical dimensions of the classroom bulletin board."]),
  ("Curriculum Competencies: Learning Competencies (LCs)", "In DepEd curriculum guides, a 'Learning Competency' (LC) is defined as:", "A specific statement of knowledge, skills, and attitudes that a learner is expected to demonstrate in every lesson/grading period.", ["A general philosophical motto of the school district.", "A commercial brand of educational software.", "A list of rules for school cafeteria behavior."]),
  ("Curriculum Supervision: Clinical Supervision Model", "In curriculum supervision, Goldhammer and Cogan's 'Clinical Supervision' model is characterized as:", "A collaborative, collegial, data-based cycle (Pre-conference, Observation, Analysis, Post-conference) aimed at improving teacher instructional practice.", ["An authoritarian inspection aimed at catching and punishing teacher mistakes.", "A medical examination conducted by school physicians in the clinic.", "A standardized written multiple-choice test administered to school principals."]),
  ("Curriculum Alignment: Curriculum-Instruction-Assessment Triad", "The cornerstone principle of effective curriculum design requires the seamless alignment of the 'CIA Triad', which encompasses:", "Curriculum (Objectives/Standards), Instruction (Pedagogical Activities), and Assessment (Evidence of Learning).", ["Content, Infrastructure, and Administration.", "Classrooms, Internet, and Audio-visuals.", "Computers, Incentives, and Attendance."]),
  ("Curriculum Foundations: Synthesis for 21st Century Learning", "Ultimately, an effective 21st-century curriculum must be dynamic, responsive, and holistic, preparing learners not merely to memorize static content, but to:", "Think critically, innovate creatively, collaborate empathetically, and adapt flexibly as lifelong learners in an interconnected world.", ["Passively obey authoritarian commands without questioning.", "Perform repetitive mechanical factory labor with zero critical voice.", "Memorize encyclopedias word-for-word without real-world application."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item assesses competence in {item[0]}. {item[2]} reflects established curriculum theory, Philippine basic education policy (RA 10533), and instructional design principles."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('curriculumDevExams.ts', 'CURRICULUM_DEV_EXAM_QUESTIONS', questions)
