import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Kasaysayan ng Wikang Pambansa: Saligang Batas 1987", "Ayon sa Artikulo XIV, Seksiyon 6 ng Saligang Batas ng 1987, ano ang opisyal na ipinapahayag hinggil sa Wikang Pambansa ng Pilipinas?", "Ang wikang pambansa ng Pilipinas ay Filipino; samantalang nililinang, ito ay dapat payabungin at pagyamanin pa salig sa umiiral na mga wika sa Pilipinas at iba pang mga wika.", ["Ang wikang pambansa ay Tagalog lamang at hindi dapat baguhin kailanman.", "Ang wikang pambansa ay Ingles upang mapalakas ang pakikipagkalakalan sa ibang bansa.", "Ang wikang pambansa ay Kastila batay sa tradisyong kolonyal."]),
  ("Kasaysayan ng Wikang Pambansa: Wikang Opisyal", "Alinsunod sa Artikulo XIV, Seksiyon 7 ng Saligang Batas ng 1987, ano ang mga opisyal na wika ng Pilipinas ukol sa mga layunin ng komunikasyon at pagtuturo?", "Filipino at, hangga't walang ibang itinatadhana ang batas, Ingles.", ["Tagalog at Kastila.", "Filipino at Cebuano.", "Ingles at Kastila lamang."]),
  ("Kasaysayan ng Wikang Pambansa: Komisyon sa Wikang Filipino (KWF)", "Itinatag sa ilalim ng Batas Republika Blg. 7104 ang ahensiyang pampamahalaan na may mandatong magsagawa, mag-ugnay, at magtaguyod ng mga pananaliksik para sa pagpapaunlad at pagpapalaganap ng Filipino. Ito ay ang:", "Komisyon sa Wikang Filipino (KWF).", ["Surian ng Wikang Pambansa (SWP).", "Linangan ng mga Wika sa Pilipinas (LWP).", "Pambansang Lupon sa Edukasyon."]),
  ("Kasaysayan ng Wikang Pambansa: Ama ng Wikang Pambansa", "Sino ang kinikilalang 'Ama ng Wikang Pambansa' dahil sa kaniyang masidhing pagtataguyod na magkaroon ng isang pambansang wikang magbubuklod sa sambayanang Pilipino sa ilalim ng Pamahalaang Komonwelt?", "Manuel L. Quezon.", ["Jose Rizal.", "Lope K. Santos.", "Francisco Balagtas."]),
  ("Kasaysayan ng Wikang Pambansa: Ama ng Balarilang Filipino", "Sino ang kinikilalang 'Ama ng Balarilang Filipino' na sumulat ng makasaysayang aklat na Balarila ng Wikang Pambansa at nagbalangkas ng orihinal na Abakada na may 20 titik?", "Lope K. Santos.", ["Manuel L. Quezon.", "Severino Reyes.", "Jose Corazon de Jesus."]),
  ("Ortograpiyang Pambansa: Ponolohiya (Ponema)", "Sa lingguwistikang Filipino, ano ang tawag sa pinakamaliit na makabuluhang yunit ng tunog ng isang wika na nagpapaiba ng kahulugan ng isang salita (tulad ng /p/ at /b/ sa 'pala' at 'bala')?", "Ponema.", ["Morpema.", "Sintaks.", "Semantika."]),
  ("Ortograpiyang Pambansa: Ponemang Suprasegmental", "Alin sa mga sumusunod ang tumutukoy sa mga ponemang suprasegmental na nagbibigay ng wastong tono, haba, diin, at antala sa pagbigkas upang maging malinaw ang mensahe?", "Tono/Intonasyon, Haba/Diin, at Antala/Hinto.", ["Patinig, Katinig, at Diptonggo.", "Simuno, Panaguri, at Kaganapan.", "Salitang-ugat, Panlapi, at Kataga."]),
  ("Ortograpiyang Pambansa: Diptonggo", "Alin sa mga sumusunod na salita ang nagtataglay ng tunay na 'Diptonggo' (kombinasyon ng patinig at malapatinig na /w/ o /y/ sa loob ng iisang pantig)?", "Bahay, giliw, reyna, kahoy.", ["Aliw-iw, kuwento, tiyan, piyesta.", "Kalesa, bintana, pinto, mesa.", "Pangarap, pag-asa, dangal, puri."]),
  ("Ortograpiyang Pambansa: Pares-Minimal", "Ano ang tawag sa pares ng mga salita na magkatulad na magkatulad ang bigkas maliban sa isang magkaibang ponema sa magkatulad na posisyon, na nagpapatunay na ang dalawang tunog ay magkahiwalay na ponema (hal. tela - tila; paso - baso)?", "Pares-Minimal.", ["Kambal-Katinig (Klaster).", "Alopono.", "Diptonggo."]),
  ("Ortograpiyang Pambansa: Kambal-Katinig (Klaster)", "Alin sa mga sumusunod na salita ang nagpapakita ng 'Klaster' o kambal-katinig (dalawang magkasunod na katinig sa loob ng iisang pantig)?", "Pluma, drayber, trak, braso.", ["Balita, musika, saya, tuwa.", "Bahay, tulay, reyna, gulay.", "Aral, sulat, basa, gawa."]),
  ("Morpolohiya: Morpema at Pagbabagong Morpoponemiko", "Sa salitang 'pang-aral' na naging 'panulat' (mula sa pang- + sulat), anong uri ng pagbabagong morpoponemiko ang naganap kung saan ang ponemang /ng/ ay naging /n/ at nawala ang unang titik /s/ ng salitang-ugat?", "Asimilasyong Ganap.", ["Asimilasyong Parsiyal (Di-Ganap).", "Metatesis.", "Pagpapalit ng Ponema."]),
  ("Morpolohiya: Metatesis", "Kapag ang salitang-ugat na 'tanim' ay nilapian ng '-in-' at naging 'tinanim', at kalaunan ay naging 'tamnan' o 'nilipad' (mula sa in- + lipad), anong pagbabagong morpoponemiko ang nagpapakita ng paglilipat ng posisyon ng mga ponema?", "Metatesis.", ["Pagkakaltas ng Ponema.", "Reduplikasyon.", "Paglilipat-diin."]),
  ("Morpolohiya: Pagkakaltas ng Ponema", "Sa paglalapi ng salitang 'takip' + '-an' na naging 'takpan' (nawala ang patinig na /i/), anong pagbabagong morpoponemiko ang nasasaksihan?", "Pagkakaltas ng Ponema.", ["Metatesis.", "Asimilasyon.", "Pagsusudlong."]),
  ("Sintaksis: Ayos ng Pangungusap sa Filipino", "Ang pangungusap na 'Masigasig na nag-aaral ang mga mag-aaral para sa pagsusulit' ay nasa anong ayos kung saan nauuna ang Panaguri bago ang Paksa/Simuno?", "Karaniwang Ayos (Likas na ayos ng wikang Filipino).", ["Di-Karaniwang Ayos (may panandang 'ay').", "Balintiyak na Ayos.", "Tambalang Ayos."]),
  ("Sintaksis: Di-Karaniwang Ayos", "Paano wastong isinusulat sa 'Di-Karaniwang Ayos' ang pangungusap na 'Matiyagang nagtuturo ang guro sa silid-aralan'?", "'Ang guro ay matiyagang nagtuturo sa silid-aralan.'", ["'Nagtuturo nang matiyaga ang guro sa silid-aralan.'", "'Sa silid-aralan nagtuturo ang matiyagang guro.'", "'Guro ang matiyagang nagtuturo sa silid-aralan.'"])
]
d.extend([
  ("Barayti ng Wika: Dayalek", "Ang barayti ng wika na nalilikha batay sa heograpikong dimensiyon o partikular na rehiyon at lalawigan (hal. Tagalog-Batangas, Tagalog-Bulacan, Tagalog-Quezon) ay tinatawag na:", "Dayalek (Wikain).", ["Sosyolek.", "Idyolek.", "Etnolek."]),
  ("Barayti ng Wika: Sosyolek", "Ang barayti ng wika na nabubuo batay sa dimensiyong sosyal o kinabibilangang pangkat ng tao (tulad ng 'Gay Lingo/Swardspeak', 'Jargon ng mga abogado', at 'Conyo/Konyo talk') ay:", "Sosyolek.", ["Dayalek.", "Etnolek.", "Ekolek."]),
  ("Barayti ng Wika: Idyolek", "Ang natatangi, pansarili, at personal na estilo o paraan ng pagsasalita ng isang indibidwal na nagiging kaniyang tatak (hal. ang boses ni Noli de Castro: 'Magandang Gabi, Bayan!') ay tinatawag na:", "Idyolek.", ["Sosyolek.", "Dayalek.", "Register."]),
  ("Barayti ng Wika: Etnolek", "Ang barayti ng wika na nadedebelop mula sa mga salita at kultura ng mga etnolingguwistikong pangkat (tulad ng 'vakuul' ng mga Ivatan o 'palangga' ng mga Ilonggo) ay:", "Etnolek.", ["Ekolek.", "Pidgin.", "Creole."]),
  ("Barayti ng Wika: Ekolek", "Ang barayti ng wika na karaniwang maririnig at ginagamit lamang sa loob ng tahanan ng isang pamilya (tulad ng 'pappy', 'mumsy', 'palikuran/tuts') ay tinatawag na:", "Ekolek.", ["Etnolek.", "Dayalek.", "Sosyolek."]),
  ("Barayti ng Wika: Register ng Wika", "Ang paggamit ng salitang 'Mouse' bilang computer peripheral sa larangan ng Information Technology, subalit bilang 'maliit na hayop' sa larangan ng Zoology, ay nagpapakita ng:", "Register ng Wika (espesyalisadong kahulugan ng salita sa isang partikular na disiplina/propesyon).", ["Idyolek.", "Etnolek.", "Pidgin."]),
  ("Barayti ng Wika: Pidgin vs Creole", "Ang 'Pidgin' ay wika na walang pormal na estruktura na nabubuo kapag ang dalawang taong may magkaibang wika ay nagtatangkang mag-usap ('Nobody's Native Language'). Kapag ito ay naging unang wika ng isang komunidad (tulad ng Chavacano sa Zamboanga), ito ay nagiging:", "Creole.", ["Dayalekto.", "Sosyolek.", "Idyolek."]),
  ("Kakayahang Komunikatibo: Modelong SPEAKING ni Dell Hymes", "Sa modelong SPEAKING ni Dell Hymes para sa mabisang komunikasyon, ano ang kinakatawan ng titik 'S' (Setting) at 'P' (Participants)?", "S = Setting at Pook ng pag-uusap; P = Participants o mga Kalahok sa komunikasyon.", ["S = Sintaksis; P = Ponolohiya.", "S = Simuno; P = Panaguri.", "S = Suliranin; P = Pamamaraan."]),
  ("Kakayahang Komunikatibo: SPEAKING (Ends at Act Sequence)", "Sa modelong SPEAKING ni Dell Hymes, ano ang ibig sabihin ng titik 'E' (Ends) at 'A' (Act Sequence)?", "E = Ends (layunin at pakay ng pakikipag-usap); A = Act Sequence (daloy, pagkakasunod-sunod ng mga pangyayari).", ["E = Emosyon; A = Aksiyon.", "E = Edukasyon; A = Analisis.", "E = Ebalwasyon; A = Argumentasyon."]),
  ("Kakayahang Komunikatibo: Canale at Swain (Lingguwistiko)", "Ayon kina Michael Canale at Merrill Swain, ang kakayahang makaunawa at makabuo ng mga istruktura sa wika na sang-ayon sa mga tuntunin ng gramatika ay tinatawag na:", "Kakayahang Lingguwistiko / Gramatikal.", ["Kakayahang Sosyolingguwistiko.", "Kakayahang Diskorsal.", "Kakayahang Istratedyik."]),
  ("Kakayahang Komunikatibo: Kakayahang Sosyolingguwistiko", "Ang kakayahan ng isang tagapagsalita na iangkop ang kaniyang wika, tono, at pagpili ng salita batay sa kausap, lugar, konteksto, at sitwasyong panlipunan ay:", "Kakayahang Sosyolingguwistiko.", ["Kakayahang Lingguwistiko.", "Kakayahang Ponolohikal.", "Kakayahang Ortograpiko."]),
  ("Kakayahang Komunikatibo: Kakayahang Istratedyik", "Kapag ang isang tagapagsalita ay gumamit ng mga kilos ng kamay, pag-uulit, pagpapaliwanag sa ibang salita (paraphrase), o pagsenyas upang maiwasan ang breakdown sa komunikasyon kapag nakalimutan ang isang termino, siya ay nagpapakita ng:", "Kakayahang Istratedyik (Strategic Competence).", ["Kakayahang Diskorsal.", "Kakayahang Gramatikal.", "Kakayahang Ortograpiko."]),
  ("Kakayahang Komunikatibo: Kakayahang Diskorsal", "Ang kakayahang mapag-ugnay-ugnay ang mga serye ng mga pangungusap upang makabuo ng isang makabuluhan, buo, at lohikal na teksto (pasulat man o pasalita) ay:", "Kakayahang Diskorsal.", ["Kakayahang Sosyolingguwistiko.", "Kakayahang Ponetiko.", "Kakayahang Leksikal."]),
  ("Tayutay: Pagtutulad (Simile)", "Sa pahayag na 'Ang kaniyang mga mata ay tulad ng mga nagniningning na bituin sa kalangitan', anong tayutay ang ginamit na hayagang naghahambing gamit ang mga salitang 'tulad ng', 'kawangis', o 'parang'?", "Pagtutulad (Simile).", ["Pagwawangis (Metaphor).", "Pagsasatao (Personification).", "Pagmamalabis (Hyperbole)."]),
  ("Tayutay: Pagwawangis (Metaphor)", "Sa tanyag na linyang 'Ang edukasyon ay ang tanglaw sa madilim na landas ng kamangmangan', anong tayutay ang tuwirang naglalapat ng katangian nang WALANG ginagamit na mga salitang pantulad?", "Pagwawangis (Metaphor).", ["Pagtutulad (Simile).", "Pagpapalit-saklaw (Synecdoche).", "Paghihimig (Onomatopoeia)."])
])
d.extend([
  ("Tayutay: Pagsasatao (Personification)", "Sa linyang 'Sumasayaw ang mga dahon sa saliw ng malamyos na simoy ng hanging amihan', anong tayutay ang nagkakaloob ng mga katangiang pantao sa mga bagay na walang buhay?", "Pagsasatao (Personification / Pagbibigay-katauhan).", ["Pagmamalabis (Hyperbole).", "Pagwawangis (Metaphor).", "Pag-uyam (Irony)."]),
  ("Tayutay: Pagmamalabis (Hyperbole)", "Sa pahayag na 'Bumaha ng luha sa buong lalawigan nang mabalitaan ang maagang pagpanaw ng kanilang minamahal na pinuno', anong tayutay ang labis-labis na nagpapasidhi sa katotohanan?", "Pagmamalabis (Hyperbole).", ["Pagtutulad (Simile).", "Pagtanggi (Litotes).", "Pagtawag (Apostrophe)."]),
  ("Tayutay: Pagpapalit-saklaw (Synecdoche)", "Sa pahayag na 'Maraming bibig ang kaniyang pinapakain araw-araw mula sa kaniyang maliit na suweldo', anong tayutay ang gumagamit ng isang bahagi upang kumatawan sa kabuuan (o kabuuan para sa bahagi)?", "Pagpapalit-saklaw (Synecdoche / Senekdoke).", ["Pagpapalit-tawag (Metonymy).", "Paghihimig (Onomatopoeia).", "Pagtatambis (Oxymoron)."]),
  ("Tayutay: Pagpapalit-tawag (Metonymy)", "Sa pangungusap na 'Iginagalang ng buong bansa ang Malacañang bilang luklukan ng kapangyarihan ng Ehekutibo', anong tayutay ang nagpapalit ng katawagan batay sa malapit na kaugnayan?", "Pagpapalit-tawag (Metonymy).", ["Pagpapalit-saklaw (Synecdoche).", "Pagsasatao.", "Pagwawangis."]),
  ("Tayutay: Paghihimig (Onomatopoeia)", "Sa linyang 'Ang lagaslas ng tubig sa batis at ang tiktak ng orasan ay nagpapakalma sa kaniyang isip', anong tayutay ang gumagamit ng mga salitang nagpapahiwatig ng tunog ng mismong bagay?", "Paghihimig (Onomatopoeia).", ["Pagtutulad.", "Pagtatambis.", "Pag-uyam."]),
  ("Tayutay: Pag-uyam (Irony / Sarcasm)", "Sa pahayag na 'Kay linis-linis naman ng iyong silid, ni hindi mahulugan ng karayom sa dami ng nakakalat na basura!', anong tayutay ang nagpapahayag ng kabaligtaran ng tunay na kahulugan sa paraang mapanukso?", "Pag-uyam (Irony / Sarcasm).", ["Pagtutulad.", "Pagmamalabis.", "Pagsasatao."]),
  ("Idyoma at Sawikain: 'Bukas ang Palad'", "Ano ang talinghagang kahulugan ng matalinghagang sawikaing 'Bukas ang palad' sa kulturang Pilipino?", "Matulungin, bukas-loob, at mapagbigay sa mga nangangailangan.", ["Mabilis manuntok sa away.", "Tamad magtrabaho.", "Madaling mabulag sa pera."]),
  ("Idyoma at Sawikain: 'Kusang-Palo'", "Kapag sinabi ng guro na ang mag-aaral ay may 'Kusang-palo', ano ang ibig ipahiwatig nito?", "May sariling pagkukusa at gumagawa ng tungkulin nang hindi na kailangan pang utusan o bantayan.", ["Palaging napaparusahan sa paaralan.", "Mabilis magalit kapag napagsasabihan.", "Mahilig mamalo ng kapwa mag-aaral."]),
  ("Idyoma at Sawikain: 'Balat-Sibuyas'", "Ang isang taong inilalarawan bilang 'Balat-sibuyas' ay nagtataglay ng anong katangian?", "Masyadong maramdamin, madaling masaktan ang damdamin, o labis na sensitibo.", ["Mabangong magsalita.", "Maputi at makinis ang kutis.", "Mahilig magluto ng pagkaing Pilipino."]),
  ("Panitikang Pilipino: Epiko ng Luzon (Biag ni Lam-ang)", "Ang 'Biag ni Lam-ang' ay ang bantog na epikong-bayan na nagmula sa anong rehiyon at pangkat sa Hilagang Luzon na isinulat ni Pedro Bucaneg?", "Ilokos (mga Ilokano).", ["Bicol (mga Bikolano).", "Kordilyera (mga Igorot).", "Katagalugan."]),
  ("Panitikang Pilipino: Epiko ng Visayas (Hinilawod)", "Ang 'Hinilawod', na itinuturing na isa sa pinakamahabang epikong-bayan sa buong daigdig na naglalahad ng pakikipagsapalaran ng tatlong magkakapatid na demi-god (Labaw Donggon, Humadapnon, Dumalapdap), ay nagmula sa mga Sulod ng:", "Panay (Kanlurang Kabisayaan).", ["Cebu.", "Samar-Leyte.", "Bohol."]),
  ("Panitikang Pilipino: Epiko ng Mindanao (Darangen)", "Ang 'Darangen', na kinilala ng UNESCO bilang Masterpiece of the Oral and Intangible Heritage of Humanity na nagsasalaysay ng kabayanihan ni Prinsipe Bantugan, ay epiko ng mga:", "Maranao (sa Lanao, Mindanao).", ["Tausug (sa Sulu).", "Maguindanao.", "Yakan."]),
  ("Panitikang Kolonyal: Awit vs Korido", "Ano ang pangunahing pagkakaiba ng estruktura at himig ng 'Awit' (tulad ng Florante at Laura) at 'Korido' (tulad ng Ibong Adarna)?", "Ang Awit ay may 12 pantig bawat taludtod at mabagal na himig (andante); ang Korido ay may 8 pantig bawat taludtod at mabilis na himig (allegro).", ["Ang Awit ay may 8 pantig; ang Korido ay may 12 pantig.", "Ang Awit ay walang tugma; ang Korido ay may perpektong tugma.", "Ang Awit ay patungkol sa mga hayop; ang Korido ay patungkol sa mga santo."]),
  ("Panitikang Kolonyal: Florante at Laura (Balagtas)", "Ang obramastra ni Francisco 'Balagtas' Baltazar na Florante at Laura ay isang awit na naglalaman ng matatalinghagang aral at alegorya laban sa:", "Katiwalian, kawalang-katarungan, at kalupitan ng pamahalaang kolonyal ng Espanya sa Pilipinas.", ["Pagsalakay ng mga piratang Olandes.", "Maling pamamahala ng mga Amerikanong sundalo.", "Panghihimasok ng bansang Hapon."]),
  ("Panitikang Kolonyal: Ang Mahal na Pasyon", "Ang panrelihiyong tulang pasalaysay na inaawit tuwing Mahal na Araw sa Pilipinas na naglalarawan ng buhay, pagpapakasakit, kamatayan, at muling pagkabuhay ni Hesukristo ay ang:", "Pasyon (tulad ng Pasyong Henesis ni Gaspar Aquino de Belen).", ["Komedya.", "Senakulo.", "Tibag."])
])
d.extend([
  ("Panitikang Pilipino: Sarswela (Severino Reyes)", "Sino ang tinaguriang 'Ama ng Sarswelang Tagalog' at may-akda ng bantog na dulang Walang Sugat na gumamit ng sagisag-panulat na 'Lola Basyang'?", "Severino Reyes.", ["Hermogenes Ilagan.", "Aurelio Tolentino.", "Juan Abad."]),
  ("Panitikang Pilipino: Dulang Sedisyoso (Kahapon, Ngayon at Bukas)", "Ang makabayang dulang 'Kahapon, Ngayon at Bukas' na naglantad ng imperyalismong Amerikano at naging dahilan ng pagkakulong ng may-akda nito sa kasong sedisyon ay isinulat ni:", "Aurelio Tolentino.", ["Juan Abad (may-akda ng Tanikalang Guinto).", "Severino Reyes.", "Patricio Mariano."]),
  ("Makrong Kasanayan: Pakikinig (Mapanuring Pakikinig)", "Sa proseso ng komunikasyon, ang 'Mapanuring Pakikinig' (Critical Listening) ay nagaganap kapag ang tagapakinig ay:", "Nagtatasa, nagtitimbang ng mga ebidensiya, at sumusuri sa katotohanan at bias ng mensaheng ipinapahayag bago magpasiya.", ["Nakikinig lamang upang maglibang at maaliw sa musika.", "Nakikinig nang may pagkaawa sa personal na suliranin ng kausap.", "Walang kamalay-malay na sumasang-ayon sa lahat ng sinasabi ng tagapagsalita."]),
  ("Makrong Kasanayan: Pagsasalita (Pagtatalumpati)", "Sa paghahanda ng isang 'Talumpati ng Panghihikayat', ano ang pinakamahalagang layunin ng mananalumpati?", "Mahikayat ang mga tagapakinig na tanggapin ang kaniyang tindig, baguhin ang kanilang pananaw, o kumilos ayon sa panukala.", ["Magpatawa at magkuwento ng mga nakakatawang anekdota.", "Magbigay lamang ng purong kahulugan mula sa diksiyonaryo.", "Magbasa ng mabilis nang walang intonasyon at emosyon."]),
  ("Makrong Kasanayan: Pagbasa (Iskaning vs Iskiming)", "Ang mabilisang pagbasa na nakatuon sa paghahanap ng partikular at tiyak na impormasyon (tulad ng numero ng telepono, petsa, o pangalan sa listahan) ay tinatawag na:", "Iskaning (Scanning).", ["Iskiming (Skimming / Mabilisang pagkuha ng pangkalahatang ideya).", "Analitikal na Pagbasa.", "Kritikal na Pagbasa."]),
  ("Makrong Kasanayan: Pagbasa (Iskiming)", "Kapag ang isang mag-aaral ay mabilisang binabasa ang pamagat, talaan ng nilalaman, at pambungad na talata ng isang aklat upang makuha ang pangkalahatang buod, siya ay nagsasagawa ng:", "Iskiming (Skimming).", ["Iskaning (Scanning).", "Tahimik na pagbasa.", "Palinggwistikang pagbasa."]),
  ("Makrong Kasanayan: Antas ng Pagbasa (Mortimer Adler)", "Sa teorya ng pagbasa ni Mortimer Adler, ang pinakamataas na antas ng pagbasa kung saan pinaghahambing at pinag-uugnay ng mambabasa ang maraming akda ukol sa iisang paksa ay ang:", "Sintopikal na Antas (Syntopical Reading).", ["Inspeksiyonal na Antas.", "Analitikal na Antas.", "Primaryang Antas."]),
  ("Akademikong Pagsulat: Abstrak", "Ano ang isang maikli ngunit komprehensibong buod ng isang akademikong sulatin (tulad ng tesis o disertasyon) na naglalaman ng layunin, metodolohiya, resulta, at konklusyon?", "Abstrak.", ["Bionote.", "Sintesis.", "Panukalang Proyekto."]),
  ("Akademikong Pagsulat: Sintesis / Buod", "Ang pagsasama-sama ng iba't ibang akda, ideya, at sanggunian upang makabuo ng isang bago, malinaw, at organisadong kabuuang teksto ay tinatawag na:", "Sintesis (Synthesis).", ["Abstrak.", "Katitikan ng Pulong.", "Memo."]),
  ("Akademikong Pagsulat: Bionote", "Ang isang maikling talata (karaniwang 2-3 pangungusap o hanggang isang talata) na naglalahad ng mga propesyonal na kredensiyal, natamong edukasyon, at karangalan ng isang awtor ay ang:", "Bionote.", ["Talambuhay (Autobiography).", "Curriculum Vitae.", "Posisyong Papel."]),
  ("Akademikong Pagsulat: Katitikan ng Pulong (Minutes)", "Sa pagsulat ng opisyal na 'Katitikan ng Pulong' (Minutes of the Meeting), alin sa mga sumusunod ang HINDI dapat isama?", "Mga pansariling opinyon, personal na tsismis, at emosyonal na kuro-kuro ng kalihim.", ["Petsa, oras, at pook kung saan idinaos ang pulong.", "Talaan ng mga dumalo at lumiban sa pulong.", "Mga opisyal na mosyon, desisyon, at itinalagang 'action items'."]),
  ("Akademikong Pagsulat: Panukalang Proyekto", "Ano ang isang detalyadong dokumento na naglalaman ng plano ng mga gagawing hakbang, badyet, rasyonal, at inaasahang pakinabang upang makahingi ng pag-apruba o pondo?", "Panukalang Proyekto (Project Proposal).", ["Posisyong Papel.", "Agenda ng Pulong.", "Bionote."]),
  ("Akademikong Pagsulat: Posisyong Papel", "Ang isang akademikong sulatin na nagpapahayag ng tiyak na tindig, panig, o pananaw ng isang manunulat hinggil sa isang kontrobersiyal na isyu na sinusuportahan ng matibay na ebidensiya ay:", "Posisyong Papel (Position Paper).", ["Abstrak.", "Memorandum.", "Katitikan ng Pulong."]),
  ("Akademikong Pagsulat: Agenda ng Pulong", "Ang opisyal na talaan ng mga paksang pag-uusapan at tatalakayin sa isang pormal na pagpupulong na ipinamamahagi bago magsimula ang pulong ay ang:", "Agenda.", ["Katitikan.", "Panukala.", "Bionote."]),
  ("Wika at Kultura: Ugnayan ng Wika at Identidad", "Bakit sinasabing ang wika ay 'kaluluwa ng isang kultura'?", "Sapagkat sa wika nakapaloob ang karunungan, tradisyon, sistema ng pagpapahalaga, at kolektibong kaisipan ng isang lahi.", ["Sapagkat ang wika ay nakasulat lamang sa mga sinaunang bato.", "Sapagkat ang wika ay ginagamit lamang sa mga seremonya ng kasal.", "Sapagkat ang wika ay hindi maaaring magbago sa paglipas ng panahon."])
])
d.extend([
  ("Gramatika: Wastong Gamit ng 'Nang' at 'Ng'", "Alin sa mga sumusunod na pangungusap ang nagpapakita ng WASTONG gamit ng salitang 'nang'?", "Tumakbo nang mabilis ang bata upang hindi mahuli sa klase.", ["Uminom nang tubig ang uhaw na manlalaro.", "Bumili nang bagong sapatos si Maria.", "Kinain nang pusa ang isda."]),
  ("Gramatika: Wastong Gamit ng 'Din/Rin' at 'Daw/Raw'", "Kailan ginagamit ang mga katagang 'rin' at 'raw' sa halip na 'din' at 'daw'?", "Kapag ang sinusundang salita ay nagtatapos sa PATINIG (a, e, i, o, u) o malapatinig na /w/ at /y/.", ["Kapag ang sinusundang salita ay nagtatapos sa KATINIG maliban sa /w/ at /y/.", "Kapag ang pangungusap ay nagsisimula sa pandiwa.", "Kapag ang pangungusap ay patanong lamang."]),
  ("Gramatika: Wastong Gamit ng 'May' at 'Mayroon'", "Alin sa mga sumusunod ang gumagamit nang WASTO sa salitang 'Mayroon'?", "Mayroon bang natirang pagkain sa kusina?", ["Mayroon kaming bagong guro bukas.", "Mayroon asong tumatahol sa bakuran.", "Mayroon siyang mabait na puso."]),
  ("Gramatika: Wastong Gamit ng 'Pahiran' at 'Pahirin'", "Ang salitang 'Pahirin' ay nangangahulugang alisin o tanggalin ang isang bagay (wipe off), habang ang 'Pahiran' ay nangangahulugang:", "Lagyan o palamanan ang isang bagay (apply on / spread on).", ["Itapon sa basurahan.", "Sunugin gamit ang apoy.", "Hugasan gamit ang sabon."]),
  ("Gramatika: Wastong Gamit ng 'Operahin' at 'Operahan'", "Sa medikal na konteksto sa Filipino, 'Operahin' ang partikular na bahagi ng katawan (hal. bukol/apendiks), samantalang 'Operahan' ang:", "Mismong tao o pasyente (hal. operahan ang maysakit).", ["Mga kagamitan sa ospital.", "Mga gamot sa botika.", "Mga nars sa klinika."]),
  ("Panitikan: Nobela (Banaag at Sikat ni Lope K. Santos)", "Ang nobelang Banaag at Sikat (1906) ni Lope K. Santos ay itinuturing na 'Bibliya ng Manggagawang Pilipino' sapagkat ito ay tumatalakay sa:", "Sosyalismo, karapatan ng mga manggagawa, at laban ng uring anakpawis laban sa kapitalismo.", ["Romantikong pag-iibigan ng mga maharlika sa Espanya.", "Pakikipagsapalaran ng mga pirata sa Sulu.", "Mga alamat ng mga diwata sa kabundukan."]),
  ("Panitikan: Maikling Kuwento (Walang Panginoon ni Deogracias Rosario)", "Sino ang kinikilalang 'Ama ng Maikling Kuwentong Tagalog' na sumulat ng mga klasikong akda tulad ng Greta Garbo at Ako'y Mayroong Isang Ibon?", "Deogracias A. Rosario.", ["Genoveva Edroza-Matute.", "Amado V. Hernandez.", "Macario Pineda."]),
  ("Panitikan: Kuwentong Nagwagi ng Palanca (Kuwento ni Mabuti)", "Ang makabagbag-damdaming kuwentong 'Kuwento ni Mabuti', na kauna-unahang nagkamit ng Unang Gantimpala sa Don Carlos Palanca Memorial Awards (1951), ay isinulat ni:", "Genoveva Edroza-Matute.", ["Liwayway Arceo.", "Lualhati Bautista.", "Paz Marquez-Benitez."]),
  ("Panitikan: Nobelang Sosyal (Dekada '70 ni Lualhati Bautista)", "Ang premyadong nobelang Dekada '70 ni Lualhati Bautista ay masining na naglalarawan ng:", "Pakikibaka, pagkamulat, at pagbabago ng isang pamilyang Pilipino sa ilalim ng Batas Militar.", ["Buhay ng mga Pilipinong manggagawa sa Hawaii noong 1920.", "Pananakop ng mga Ingles sa Maynila.", "Sinaunang ritwal ng mga babaylan sa Kabisayaan."]),
  ("Panitikan: Makata ng Manggagawa (Amado V. Hernandez)", "Sino ang Pambansang Alagad ng Sining sa Panitikan na tinaguriang 'Makata ng Manggagawa' at may-akda ng mga obrang Isang Dipang Langit at Luha ng Buwaya?", "Amado V. Hernandez.", ["Jose Corazon de Jesus (Huseng Batute).", "Alejandro Abadilla.", "Virgilio Almario."]),
  ("Panitikan: Ama ng Makabagong Tulang Tagalog (AGA)", "Sino ang may-akda ng tanyag na tulang 'Ako ang Daigdig' na nagpasimula ng malayang taludturan (free verse) sa panulaang Tagalog?", "Alejandro G. Abadilla (AGA).", ["Jose Corazon de Jesus.", "Ildefonso Santos.", "Teo S. Baylen."]),
  ("Panitikan: Hari ng Balagtasan (Huseng Batute)", "Sino ang kinoronahang unang 'Hari ng Balagtasan' noong 1925 na sumulat ng makabayang tulang Bayan Ko?", "Jose Corazon de Jesus.", ["Florentino Collantes.", "Lope K. Santos.", "Inigo Ed. Regalado."]),
  ("Ugnayan ng Wika: Intelektuwalisasyon ng Wikang Filipino", "Ayon kay Dr. Bonifacio Sibayan, ang 'Intelektuwalisasyon' ng wikang Filipino ay tumutukoy sa:", "Proseso ng paglinang sa Filipino upang magamit ito bilang wika ng karunungan, iskolarling talakayan, at mataas na antas ng pananaliksik sa akademya.", ["Pagsasalin ng lahat ng aklat sa wikang Ingles.", "Pag-aalis ng lahat ng hiram na salita sa diksiyonaryo.", "Paglilimita sa paggamit ng Filipino sa pang-araw-araw na tsismis lamang."]),
  ("Pananaliksik sa Wika: Etnograpiya ng Komunikasyon", "Ang metodolohiya sa pananaliksik na nakatuon sa pagsusuri ng mga padron, tuntunin, at kahulugan ng pakikipagtalastasan sa loob ng isang partikular na kultural na komunidad ay:", "Etnograpiya ng Komunikasyon.", ["Eksperimental na Disenyo.", "Kuantitatibong Sarbey.", "Pormatibong Ebalwasyon."]),
  ("Malayuning Komunikasyon: Mabisang Pagpapahayag", "Sa pangkalahatan, ang layunin ng kursong 'Malayuning Komunikasyon' (Purposive Communication) sa antas tersiyarya ay:", "Makahubog ng mga mag-aaral na may mataas na antas ng kakayahang komunikatibo sa pakikipagtalastasan sa iba't ibang konteksto, kultura, at layunin.", ["Magsaulo ng mga lumang tuntunin sa gramatika nang walang aplikasyon.", "Limitahan ang komunikasyon sa loob lamang ng silid-aralan.", "Turuan ang mga mag-aaral na umiwas sa pakikipag-usap sa mga dayuhan."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"Sinusuri ng aytem na ito ang kasanayan sa {item[0]}. Ang {item[2]} ang kumakatawan sa pamatayang tuntunin sa gramatika, lingguwistika, at panitikang Filipino."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('filipinoExams.ts', 'FILIPINO_EXAM_QUESTIONS', questions)
