import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Philosophy of Art: Mimetic Theory", "Plato famously argued in The Republic that visual art should be viewed with suspicion because it is merely a 'copy of a copy' (mimesis). In Plato's hierarchy, what does a painted table represent?", "An imitation of physical reality, which is itself an imperfect reflection of the eternal Form.", ["The ultimate metaphysical reality superior to pure reason.", "A direct manifestation of divine mathematical geometry.", "A purely emotional entity devoid of physical composition."], "In Plato's Theory of Forms, physical objects are copies of ideal Forms. A painting of a table is an imitation of an imitation (twice removed from ultimate reality)."),
  ("Philosophy of Art: Aristotle's Catharsis", "In Poetics, Aristotle defended dramatic tragedy by asserting that it achieves 'Catharsis'. What does this aesthetic process entail?", "The healthy emotional cleansing or purgation of pity and fear in the audience.", ["The complete suppression of all emotional reactions through rational detachment.", "The passive memorization of ancient civic laws and religious edicts.", "The glorification of violent military conquest over neighbors."], "Aristotle argued that tragedy arouses pity and fear in order to purge or clarify these emotions, providing a healthy psychological and moral release."),
  ("Philosophy of Art: Kantian Disinterestedness", "In Critique of Judgment, Immanuel Kant asserts that genuine aesthetic judgment of beauty requires 'disinterested satisfaction'. This means the viewer:", "Appreciates an object purely for its contemplative perceptual form without desiring to possess, consume, or profit from it.", ["Feels completely bored and indifferent while observing an art gallery exhibition.", "Evaluates an artwork based entirely on its commercial auction price.", "Prefers artworks that directly promote partisan political propaganda."], "Kant's 'disinterestedness' means aesthetic appreciation is detached from personal appetite, utilitarian function, or financial interest."),
  ("Philosophy of Art: Tolstoy's Expressionism", "Leo Tolstoy in What is Art? argued that the essential defining condition of genuine art is:", "The infectious transmission of sincere emotions experienced by the artist to the audience.", ["The mathematical precision of Renaissance perspective and golden ratios.", "The creation of decorative objects reserved exclusively for royal courts.", "The complete absence of moral or spiritual themes in composition."], "Tolstoy proposed an emotional expressionist theory: art consciously infects others with feelings the artist has lived through."),
  ("Functions of Art: Physical vs Social Function", "Which of the following art forms primarily fulfills a 'Physical Function' by directly providing utilitarian shelter and ergonomic support?", "Architecture, urban planning, and industrial furniture design.", ["Elegiac lyric poetry written to express personal grief.", "Instrumental piano sonatas performed in concert halls.", "Non-objective abstract expressionist canvas paintings."], "Art serves physical functions when it provides utilitarian utility, shelter, tools, or ergonomic support."),
  ("Functions of Art: Social Function (Luna's Spoliarium)", "Juan Luna's Spoliarium (1884), depicting fallen Roman gladiators dragged into a dungeon, served a powerful social function by:", "Exposing the brutality, oppression, and suffering of Filipinos under Spanish colonial rule through classical allegory.", ["Promoting tourism and trade fairs for Madrid merchants.", "Providing architectural blueprints for Roman coliseums.", "Decorating the private salon of the Governor-General."], "Spoliarium used the allegory of dying gladiators to symbolize the oppression of Filipinos under Spanish imperial rule."),
  ("Art Elements: Analogous Color Harmony", "An artist paints a landscape using yellow, yellow-green, and green pigments adjacent to each other on the color wheel. Which harmony is utilized?", "Analogous color harmony, which produces visual unity and serene, natural transitions.", ["Complementary color scheme, which uses colors directly opposite each other.", "Monochromatic harmony, which uses only a single hue with tints and shades.", "Split-complementary harmony, which uses a base color and adjacent complements."], "Analogous colors sit next to each other on the color wheel, creating cohesive, harmonious palettes."),
  ("Art Elements: Chiaroscuro", "The artistic technique of 'Chiaroscuro', masterfully developed by Caravaggio and Rembrandt, refers to:", "The dramatic contrast between light and dark values to create volume, depth, and emotional tension.", ["The application of thick paint using a palette knife without blending.", "The strict geometric division of a canvas into primary flat color blocks.", "The creation of mosaic patterns using colored glass tesserae."], "Chiaroscuro uses strong tonal contrasts between light and dark to model volume and heighten drama."),
  ("Art Elements: Linear Perspective", "Filippo Brunelleschi's mathematical formulation of one-point linear perspective in early Renaissance Florence relied upon:", "A single vanishing point situated on the horizon line where parallel receding orthogonal lines converge.", ["Multiple unrelated focal points scattered across the borders of the painting.", "The depiction of sacred figures in disproportionately large hierarchical scale.", "The complete elimination of spatial depth in favor of decorative gold leaf."], "Linear perspective creates the illusion of three-dimensional depth using a horizon line and converging orthogonal lines."),
  ("Principles of Design: Emphasis & Focal Point", "An artist creates 'Emphasis' by placing a vibrant, saturated red circle against a vast field of muted grays. This relies on:", "Contrast in color saturation and value to immediately command viewer attention.", ["Symmetrical formal balance dividing the canvas into mirror halves.", "Radial rhythm repeating elements around a central axis.", "Atmospheric perspective fading background contours into blue haze."], "Emphasis draws the viewer's eye to a specific focal point through contrast in color, value, shape, or scale."),
  ("Art Elements: Actual vs Implied Texture", "The surface of a Vincent van Gogh oil painting featuring thick, raised, sculpted brushstrokes that can be physically felt is an example of:", "Actual (tactile) texture created through heavy impasto.", ["Implied (visual) texture that appears rough but is completely smooth to touch.", "Trompe l'oeil illusion of polished marble.", "Fresco secco applied to dry lime plaster."], "Actual texture is physically tactile (impasto), while implied texture is a visual illusion on a smooth surface."),
  ("Principles of Design: Asymmetrical Balance", "An artwork achieves 'Asymmetrical Balance' (informal balance) when:", "Different visual elements with equal visual weight balance each other without mirror-image symmetry.", ["Both left and right halves of the canvas are identical mirror images.", "All shapes radiate equally from a single central point.", "No visual weight is allocated to the foreground of the composition."], "Asymmetrical balance distributes visual weight unevenly across the axis while maintaining overall aesthetic equilibrium."),
  ("Pre-Colonial Philippine Art: Manunggul Jar", "The Manunggul Jar (890–710 BCE) of Palawan is a secondary burial vessel celebrated for its boat-shaped lid. What does this boat carving symbolize?", "The soul's maritime journey to the afterlife accompanied by a boatman.", ["Pre-colonial maritime trading pacts with the Majapahit Empire.", "Military naval conquests of early Visayan datu lineages.", "Agricultural rituals for abundant rice harvesting."], "The boat finial on the Manunggul Jar represents the early Filipino belief in the soul's voyage across the spirit sea to the afterlife."),
  ("Philippine Indigenous Weaving: T'nalak", "Why are T'boli master weavers of Lake Sebu, South Cotabato traditionally referred to as 'Dreamweavers'?", "The intricate geometric patterns are believed to be bestowed directly by the spirit goddess Fu Dalu in dreams.", ["They weave only while sleeping during nocturnal religious festivals.", "They use synthetic neon fibers to create modern abstract tapestries.", "The weaving technique was adapted from Spanish colonial lace embroidery."], "T'boli weavers believe patterns are sacred gifts revealed by Fu Dalu, the spirit of abaca, in their dreams."),
  ("Philippine Indigenous Weaving: Inabel", "The traditional handwoven cotton textile produced by the Ilocano people of Northern Luzon, known for its geometric binakol patterns, is called:", "Inabel (Abel Iloco).", ["T'nalak.", "Yakan Seputangan.", "Piña barong cloth."], "Inabel is the traditional handwoven cloth of Ilocos, celebrated for durability and optical binakol patterns.")
]
d.extend([
  ("Philippine Indigenous Art: Bulul", "The carved wooden human figures called 'Bulul' among the Ifugao people of the Cordilleras serve primarily as:", "Sacred animistic guardians of rice granaries and symbols of agricultural fertility and wealth.", ["Decorative furniture finials for modern tourist hotels.", "Children's toys used during tribal sports competitions.", "Weapons used in territorial tribal warfare."]),
  ("Philippine Indigenous Art: Okir Motif", "The flowing, curvilinear, vine-like woodcarving and brass-casting motif characteristic of Maranao and Maguindanao art is:", "Okir (Okir a Datu / Okir a Bay).", ["Binakol.", "Lingling-o.", "Pabalat."]),
  ("Philippine Indigenous Art: Sarimanok", "The mythical bird of Maranao folklore depicted holding a fish in its beak or talons is the:", "Sarimanok, symbolizing good fortune, wealth, and aristocratic prestige.", ["Tikling.", "Harpy eagle.", "Bakunawa."]),
  ("Philippine Sacred Architecture: Baroque Churches", "The four Spanish-era churches designated as a UNESCO World Heritage Site in the Philippines (Paoay, Santa Maria, San Agustin, Miagao) are examples of:", "Earthquake Baroque, characterized by massive buttresses and thick masonry to withstand seismic activity.", ["High Gothic, featuring soaring pointed spires and delicate flying buttresses.", "Neoclassical, featuring Greek Doric colonnades and white marble pediments.", "Brutalist, featuring raw poured concrete slabs without ornamentation."]),
  ("GAMABA National Living Treasures: Lang Dulay", "Lang Dulay (1998 GAMABA Awardee) was recognized for her supreme mastery in preserving which traditional indigenous art form?", "T'boli T'nalak dreamweaving.", ["Kalinga traditional tattooing (Batok).", "Hanunuo Mangyan Surat writing on bamboo.", "Ilocano Tabúngaw gourd hat making."]),
  ("GAMABA Awardees: Whang-Od", "Apo Whang-Od of Buscalan, Kalinga is the legendary master of 'Batok', which is:", "Traditional hand-tapped indigenous tattooing using a pomelo thorn and charcoal ink.", ["Brass gong casting for Cordillera peace pacts.", "Carving wooden bulul figures for rice granaries.", "Weaving geometric inabel blankets on backstrap looms."]),
  ("GAMABA Awardees: Teofilo Garcia", "Teofilo Garcia of San Quintin, Abra (2012 GAMABA Awardee) is celebrated for crafting the:", "Tabúngaw (functional, weatherproof all-weather hat crafted from a polished upo gourd).", ["Kudyapi (two-stringed fretted boat lute).", "Seputangan headcloth.", "Pis Syabit tapestry."]),
  ("GAMABA Awardees: Ginaw Bilog", "Ginaw Bilog (1993 GAMABA Awardee) of Mansalay, Oriental Mindoro was honored for preserving the:", "Ambahan, a poetic chant of the Hanunuo Mangyan etched on bamboo tubes using pre-colonial Surat script.", ["Epic chanting of the Darangen.", "Mat weaving of Laminusa, Sulu.", "Inabal textile weaving of the Bagobo."]),
  ("GAMABA Awardees: Samaon Sulaiman", "Samaon Sulaiman (1993 GAMABA Awardee) of Maguindanao was celebrated for his mastery of the:", "Kutyapi (two-stringed plucked boat lute of Mindanao).", ["Kulintang bronze gong ensemble.", "Gabbang bamboo xylophone.", "Kubing jaw harp."]),
  ("Philippine National Artists: Fernando Amorsolo", "Fernando Amorsolo, the first Philippine National Artist for Visual Arts (1972), is world-renowned for:", "Mastery in capturing the radiant golden tropical Philippine sunlight on rural pastoral landscapes.", ["Dark, expressionistic depictions of urban poverty and factory workers.", "Monumental abstract sculptures carved from raw volcanic adobe.", "Cubist fragmented portraits of mythological indigenous spirits."]),
  ("Philippine National Artists: Carlos 'Botong' Francisco", "Carlos 'Botong' Francisco, National Artist from Angono, Rizal, revived the art of:", "Monumental narrative mural painting depicting epic Philippine history, folklore, and rural traditions.", ["Miniature ivory icon carving for religious shrines.", "Ceramic porcelain glazing for export trade.", "Classical portrait painting for colonial governors."]),
  ("Philippine National Artists: Guillermo Tolentino", "Guillermo Tolentino (1973 National Artist for Sculpture) created which iconic neoclassical monuments in the Philippines?", "The Bonifacio Monument in Caloocan and the UP Oblation.", ["The People Power Monument on EDSA.", "The Transfiguration at the Eternal Gardens.", "The Pieta sculpture inside Manila Cathedral."]),
  ("Philippine National Artists: Napoleon Abueva", "Napoleon Abueva, recognized as the 'Father of Modern Philippine Sculpture', is celebrated for:", "Pioneering modernist, semi-abstract sculpture utilizing diverse Philippine hardwoods, metal, and marble.", ["Strictly replicating classical Greek and Roman marble busts without innovation.", "Designing wooden colonial galleons for maritime commerce.", "Painting monumental panoramic murals on canvas."]),
  ("Philippine National Artists: Vicente Manansala", "Vicente Manansala developed a signature Philippine modernist style known as:", "Transparent Cubism, where geometric overlapping forms and planes create layered spatial depth.", ["Hyper-realistic botanical watercolor illustration.", "Non-representational action painting with splattered pigments.", "Photorealistic oil portraiture of high-society figures."]),
  ("Philippine National Artists: Benedicto Cabrera (BenCab)", "National Artist BenCab created the iconic recurring figure 'Sabel', who represents:", "A scavenging, marginalized woman symbolizing social dislocation, resilience, and Philippine reality.", ["A mythological pre-colonial sea goddess of the Visayas.", "An aristocratic Spanish governess during the tobacco monopoly.", "A contemporary corporate executive in Makati."])
])
d.extend([
  ("Philippine National Artists: Ang Kiukok", "Ang Kiukok's distinct visual style is characterized by:", "Violent, aggressive expressionist and cubist imagery featuring fighting cocks, barking dogs, and agonized crucifictions.", ["Idyllic, peaceful pastoral harvests bathed in golden yellow light.", "Delicate, pastel floral arrangements in glass vases.", "Playful pop art cartoons celebrating commercial consumer products."]),
  ("Philippine Art: Spoliarium vs Hidalgo", "At the 1884 Madrid National Exposition of Fine Arts, Juan Luna won gold for Spoliarium, while Felix Resurreccion Hidalgo won silver for:", "Las Virgenes Cristianas Expuestas al Populacho (The Christian Virgins Exposed to the Populace).", ["España y Filipinas.", "El Asesinato del Gobernador Bustamante.", "Plantar Arroz."]),
  ("Art Movements: Renaissance Harmony", "Leonardo da Vinci's The Last Supper (1495–1498) exemplifies High Renaissance art through its:", "Mastery of one-point perspective converging on Christ's head, balanced symmetry, and psychological character study.", ["Flat, unmodeled figures enclosed in thick black stained-glass outlines.", "Violent, chaotic brushwork rejecting anatomical accuracy.", "Commercial advertising typography integrated into the background."]),
  ("Art Movements: Baroque Drama", "Gian Lorenzo Bernini's sculpture The Ecstasy of Saint Teresa (1652) is a defining masterpiece of the Baroque era because:", "It combines theatrical emotional drama, dynamic diagonal motion, and multimedia marble and gilded light.", ["It features static, rigid, upright posture characteristic of Egyptian pharaoh statues.", "It avoids all emotional expression in favor of mathematical cubic planes.", "It is carved from unpolished gray concrete slabs."]),
  ("Art Movements: Romanticism", "Eugène Delacroix's Liberty Leading the People (1830) embodies the Romantic movement by:", "Celebrating passionate revolutionary fervor, emotional heroism, and dynamic atmospheric drama over neoclassic restraint.", ["Depicting cold, detached geometric shapes without human figures.", "Glorifying royal monarchies through peaceful pastoral portraits.", "Focusing strictly on technological factory machinery."]),
  ("Art Movements: Impressionism", "Claude Monet's Impression, Sunrise (1872) gave name to Impressionism, a movement characterized by:", "Capturing fleeting effects of natural light and atmospheric color using short, broken brushstrokes painted en plein air.", ["Creating hyper-detailed, glazed photorealistic historical scenes in studio basements.", "Using heavy black outlines and flat gold foil backgrounds.", "Painting purely from geometric mathematical equations."]),
  ("Art Movements: Pointillism", "Georges Seurat developed 'Pointillism' (Divisionism), an aesthetic technique that involves:", "Applying small, distinct dots of pure color that blend optically in the viewer's eye.", ["Pouring diluted enamel paint directly onto unprimed canvas.", "Carving relief images into linoleum printing blocks.", "Dripping wax over cloth before dyeing in indigo vats."]),
  ("Art Movements: Post-Impressionism (Van Gogh)", "Vincent van Gogh's The Starry Night (1889) used swirling, rhythmic impasto lines and intense blues and yellows to:", "Express intense personal, psychological, and spiritual emotion rather than realistic visual recording.", ["Provide an accurate photographic map of astronomical constellations for navigators.", "Demonstrate proper industrial bricklaying architectural methods.", "Illustrate botanical species of French cypress trees for agriculture."]),
  ("Art Movements: Cubism", "Pablo Picasso's Les Demoiselles d'Avignon (1907) shattered traditional Western perspective by:", "Fragmenting human figures into multiple simultaneous geometric viewpoints and planar facets.", ["Using ultra-smooth sfumato blending to create realistic skin tones.", "Painting idyllic rural landscapes in natural golden sunlight.", "Strictly adhering to single vanishing-point linear perspective."]),
  ("Art Movements: Surrealism", "Salvador Dalí's The Persistence of Memory (1931), featuring melting pocket watches in a desolate dreamscape, exemplifies Surrealism's aim to:", "Unlock the unconscious mind and explore dream imagery inspired by Freudian psychoanalysis.", ["Promote industrial clock manufacturing and commercial efficiency.", "Document historical naval battles in the Mediterranean Sea.", "Replicate classical Greek architectural pediments."]),
  ("Art Movements: Dadaism", "Marcel Duchamp's Fountain (1917)—a standard porcelain urinal submitted as a sculpture—revolutionized modern art by introducing:", "The 'Readymade', asserting that an artist's conceptual choice defines art rather than manual craftsmanship.", ["A new method of industrial ceramic waterproofing for plumbing.", "A return to classical Michelangelo marble carving standards.", "A mathematical formula for calculating golden ratios in pottery."]),
  ("Art Movements: Abstract Expressionism", "Jackson Pollock's 'Action Painting' (drip painting) technique emphasized:", "The spontaneous physical act of painting, gestural mark-making, and non-representational canvas energy.", ["Meticulous, miniature botanical rendering with fine watercolor brushes.", "Creating political caricature cartoons for daily newspapers.", "Carving realistic marble portraits of political leaders."]),
  ("Art Movements: Pop Art", "Andy Warhol's Campbell's Soup Cans (1962) and Marilyn Diptych defined Pop Art by:", "Appropriating mass-media consumer imagery, commercial advertising, and silkscreen repetition to critique consumer culture.", ["Rejecting all forms of mechanical reproduction in favor of handcrafted oil glazes.", "Painting religious biblical narratives for cathedral altarpieces.", "Carving indigenous wooden bulul statues for rice harvests."]),
  ("Performing Arts: Kundiman", "The 'Kundiman' is a traditional Philippine lyrical art song genre whose melancholic melodies historically served to:", "Express veiled patriotic longing for national freedom and love of country beneath romantic metaphors.", ["Celebrate Spanish colonial military victories in Latin America.", "Provide upbeat dance rhythms for American jazz clubs.", "Accompany rapid harvest threshing in rice fields."]),
  ("Performing Arts: Sarswela", "The Sarswela, popularized in the Philippines by playwrights like Severino Reyes (Walang Sugat), is a theatrical form featuring:", "A musical play with alternating spoken dialogue and sung lyrical verses addressing contemporary social and romantic themes.", ["A silent pantomime performed exclusively by masked monks.", "A shadow puppetry play depicting ancient Indian epics.", "An acrobatic circus performance without narrative storyline."])
])
d.extend([
  ("Performing Arts: Senakulo", "The 'Senakulo' is a traditional Philippine community passion play staged during Holy Week that dramatizes:", "The life, passion, suffering, crucifixion, and resurrection of Jesus Christ.", ["The pre-colonial trade expeditions of Visayan sailors.", "The military skirmishes of the Philippine-American War.", "The romantic courtship rituals of Cordillera mountain tribes."]),
  ("Performing Arts: Moro-Moro (Komedya)", "The traditional Philippine theatrical 'Komedya' (Moro-Moro) historically depicted:", "Stylized, costumed conflicts between Christian and Muslim warriors, typically resolving in Christian conversion or victory.", ["Modern industrial labor union strikes in Manila factories.", "The life of national hero Jose Rizal in Dapitan exile.", "Ancient indigenous agricultural harvest rites."]),
  ("Sculpture: Additive vs Subtractive", "In classical sculpting, marble carving is classified as a 'Subtractive' process, whereas clay modeling and bronze casting are classified as:", "Additive processes, where material is built up, shaped, or cast.", ["Destructive processes that destroy the raw materials.", "Optical processes that rely strictly on mirrors.", "Chemical processes that eliminate physical mass."]),
  ("Sculpture: Relief Types", "A coin depicting a leader's profile with figures slightly raised from the flat background is an example of:", "Low relief (Bas-relief).", ["High relief (Haut-relief).", "Sunken relief (Intaglio).", "Freestanding sculpture in-the-round."]),
  ("Architecture: Post-and-Lintel System", "The ancient Greek Parthenon is a monumental example of which foundational structural architectural system?", "Post-and-lintel (trabeated) construction, where horizontal beams rest on vertical columns.", ["Cantilevered reinforced concrete slabs.", "Geodesic dome construction with tensile steel struts.", "Gothic pointed ribbed vaulting with flying buttresses."]),
  ("Architecture: The Arch and Vault", "The architectural breakthrough of the true round arch, barrel vault, and dome that enabled massive interior spaces like the Pantheon was perfected by:", "The ancient Romans.", ["The ancient Egyptians.", "The Byzantine iconographers.", "The French Impressionists."]),
  ("Art Criticism: Feldman's Analysis Step", "In Edmund Feldman's model of art criticism, which step involves identifying visual elements, principles of design, and formal organization?", "Analysis.", ["Description (identifying what is literally visible without interpretation).", "Interpretation (determining expressive meaning and psychological intent).", "Judgment / Evaluation (assessing artistic merit and historical significance)."]),
  ("Art Criticism: Interpretation Step", "When an art critic asks, 'What is the artist trying to communicate? What is the underlying theme, mood, or metaphor?', the critic is engaged in:", "Interpretation.", ["Description.", "Analysis.", "Census taking."]),
  ("Printmaking: Relief Printing (Woodcut)", "In relief printmaking techniques like woodcut and wood engraving, the printed image is created by:", "Inking the raised surface of the block while carved recessed areas remain un-inked.", ["Forcing ink through a fine mesh stencil screen using a squeegee.", "Etching lines into a copper plate using acid immersion.", "Drawing with greasy crayons on a polished Bavarian limestone slab."]),
  ("Printmaking: Intaglio (Etching)", "In intaglio printmaking (such as etching and engraving), the ink is transferred to paper from:", "The recessed grooves cut or acid-bitten below the plate's surface under high rolling-press pressure.", ["The raised wooden edges of an un-carved woodblock.", "A photographic digital transparency film.", "A stenciled silk screen mesh."]),
  ("Printmaking: Lithography", "Alois Senefelder invented Lithography in 1796 based on the chemical principle that:", "Oil (grease) and water do not mix naturally.", ["Acid burns through unprotected copper sheets.", "Wood swells when exposed to steam heat.", "Gelatin dissolves in cold water baths."]),
  ("Philippine Ceramic Art: Burnay Jars", "The 'Burnay' stoneware pottery of Vigan, Ilocos Sur, crafted from local clay and fired in dragon kilns (camarin), is traditionally used for:", "Fermenting sugarcane wine (basi), vinegar (sukang Iloko), and bagoong (fish paste).", ["Serving decorative European desserts in Manila hotels.", "Cremating deceased Spanish colonial priests.", "Exporting gold dust to the Americas."]),
  ("Philippine Folk Art: Pabalat", "The folk art of 'Pabalat' from San Miguel, Bulacan involves:", "Intricate paper-cutting of colorful Japanese papel de hapon into delicate wrappers for pastillas de leche.", ["Carving coconut shells into decorative ladles.", "Weaving palm fronds into decorative palaspas for Palm Sunday.", "Embroidering piña fibers into traditional barong tagalog."]),
  ("Philippine Folk Art: Kiping Decor", "The colorful, translucent, leaf-shaped rice wafers used to decorate houses during the Pahiyas Festival of Lucban, Quezon are known as:", "Kiping.", ["Inabel.", "Burnay.", "T'nalak."]),
  ("Philippine Folk Art: Taka Papermache", "The craft of 'Taka'—making vibrant, hand-painted paper-mâché folk art figures of horses, roosters, and dolls using carved wooden molds—originated in:", "Paete, Laguna.", ["Vigan, Ilocos Sur.", "Lucban, Quezon.", "Basey, Samar."])
])
d.extend([
  ("Philippine Monument: People Power Monument", "The dynamic bronze monument at EDSA and White Plains Avenue commemorating the 1986 People Power Revolution was sculpted by:", "Eduardo Castrillo.", ["Guillermo Tolentino.", "Fernando Amorsolo.", "Vicente Manansala."]),
  ("Art Aesthetics: Sublime vs Beautiful", "In 18th-century aesthetics (Edmund Burke and Immanuel Kant), the 'Sublime' is distinguished from the 'Beautiful' because the Sublime evokes:", "Awe, vastness, overwhelming power, and a thrilling sense of terror mixed with wonder.", ["Gentle harmony, delicate symmetry, and immediate sensory pleasure.", "Comedic amusement and playful irony.", "Practical utility and economic profitability."]),
  ("Visual Art: Sfumato Technique", "Leonardo da Vinci's signature technique of 'Sfumato' (applied famously in the Mona Lisa) refers to:", "Soft, imperceptible transitions between colors and tones without harsh outlines, creating a smoky, atmospheric quality.", ["Applying thick, rough impasto paint with a knife.", "Using pure unmixed primary colors side-by-side.", "Scratching dry paint off the surface with a needle."]),
  ("Visual Art: Foreshortening", "The optical illusion of 'Foreshortening' in figurative drawing and painting occurs when:", "An object or human limb is compressed visually to project directly toward or away from the viewer in space.", ["Figures are painted flatly against a gilded gold background.", "Colors fade into a uniform neutral gray in the foreground.", "All vertical lines are drawn tilted at 90-degree angles."]),
  ("Modern Art: Installation Art", "Installation art differs fundamentally from traditional pedestal sculpture because it:", "Transforms an entire architectural space into an immersive, multi-sensory environment that viewers enter and experience.", ["Must be small enough to be displayed in a glass jewelry case.", "Consists exclusively of oil paintings hung on white museum walls.", "Is designed purely for permanent outdoor bronze casting."]),
  ("Performance Art: Ephemerality", "Performance art is characterized by its 'ephemerality', meaning that the artwork:", "Exists temporarily in the live moment of execution and cannot be bought as a permanent physical object.", ["Is cast in indestructible stainless steel alloys.", "Can be mass-manufactured in automated commercial factories.", "Must follow strict musical notation written in medieval Latin."]),
  ("Photography as Art: Decisive Moment", "Henri Cartier-Bresson's concept of the 'Decisive Moment' in artistic photography refers to:", "Capturing an event at the precise instant when visual elements and emotional expression are in perfect harmony.", ["Setting the camera shutter speed to 10 minutes in total darkness.", "Editing photographic pixels in computer software for hours.", "Taking hundreds of random burst shots without looking through the viewfinder."]),
  ("Digital Art: NFT and Provenance", "In contemporary digital art, Non-Fungible Tokens (NFTs) utilize blockchain technology primarily to:", "Provide verifiable proof of digital ownership, authenticity, and scarcity for digital artworks.", ["Compress image files so they download faster on smartphones.", "Prevent computer screens from overheating during 3D rendering.", "Eliminate the need for digital graphic design software."]),
  ("Art Conservation: Repatriation of Cultural Heritage", "The ethical debate surrounding 'Repatriation of Cultural Property' involves demands by indigenous nations for:", "The return of sacred cultural artifacts, ancestral remains, and looted treasures held by foreign colonial museums.", ["The commercial privatization of all national public parks.", "The total destruction of ancient historical pottery collections.", "The mandatory sale of all museum artworks to private auction houses."]),
  ("Philippine Film: National Artists for Film", "Lino Brocka and Ishmael Bernal (National Artists for Cinema) are celebrated for directing films that:", "Exposed harsh social realities, systemic injustice, poverty, and human resilience under authoritarian martial law.", ["Produced lighthearted escapist Hollywood musical remakes.", "Promoted government political slogans uncritically.", "Focused exclusively on foreign fantasy landscapes."]),
  ("Philippine Music: Nicanor Abelardo", "Nicanor Abelardo elevated traditional Philippine music by transforming the folk Kundiman into:", "Art song masterworks featuring sophisticated classical European harmonic structures (e.g., Mutya ng Pasig).", ["American rock-and-roll guitar solos.", "Electronic synthesizer dance club tracks.", "Monophonic medieval Gregorian chants."]),
  ("Philippine Dance: Tinikling & Singkil", "The traditional Visayan 'Tinikling' and Maranao 'Singkil' folk dances both feature dancers skillfully maneuvering between:", "Rhythmically clapping bamboo poles, mimicking bird movements or royal legends.", ["Flaming metal torches swung on steel chains.", "Spinning ceramic water pots balanced on fingertips.", "Sharp brass swords in mock gladiator duels."]),
  ("Aesthetic Philosophy: Formalism (Clive Bell)", "Clive Bell's aesthetic theory of Formalism asserts that what provokes aesthetic emotion is:", "'Significant Form'—the harmonious combination of lines, colors, and forms, independent of subject matter or storytelling.", ["The moral and political ideology championed by the painter.", "The monetary price paid by an art collector at auction.", "The anatomical accuracy of medical pathology illustrations."]),
  ("Aesthetic Philosophy: Institutional Theory", "George Dickie and Arthur Danto's 'Institutional Theory of Art' argues that an object becomes art when:", "It is conferred candidate status for appreciation by members and gatekeepers of the established 'Artworld'.", ["It is carved by a licensed master mason from Italian marble.", "It receives a royal decree from a reigning monarch.", "It produces measurable economic profits in commercial trade fairs."]),
  ("Art Criticism: Monochromatic Color Harmony", "A monochromatic color scheme in an artwork is composed of:", "Variations of a single hue, using different tints (adding white), shades (adding black), and tones (adding gray).", ["All twelve colors of the spectral color wheel used simultaneously in equal amounts.", "Complementary opposite colors like purple and yellow.", "Neon primary colors with zero tonal variation."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This question assesses understanding in {item[0]}. {item[2]} represents standard aesthetic and art historical consensus."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('artAppreciationExams.ts', 'ART_APPRECIATION_EXAM_QUESTIONS', questions)
