import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Intellectual Revolutions: Copernican Revolution", "Nicolaus Copernicus published De revolutionibus orbium coelestium in 1543, sparking a scientific revolution by proposing the 'Heliocentric Model', which demonstrated that:", "The Sun is at the center of the solar system, and the Earth and other planets revolve around it.", ["The Earth is the stationary physical center of the universe (Geocentric Ptolemaic Model).", "The universe is enclosed in a rigid crystal dome with fixed stars.", "Planetary orbits are driven by angelic spiritual entities."]),
  ("Intellectual Revolutions: Darwinian Revolution", "Charles Darwin's 1859 On the Origin of Species revolutionized biological science by proposing that species evolve over generations through:", "Natural Selection, where organisms with favorable heritable traits are more likely to survive and reproduce.", ["The inheritance of acquired physical characteristics during an individual's lifetime (Lamarckism).", "Sudden catastrophic divine geological interventions.", "Pre-programmed transformation directed by celestial astrology."]),
  ("Intellectual Revolutions: Freudian Revolution", "Sigmund Freud's psychoanalytic revolution transformed human understanding of psychology by proposing that:", "Human behavior and conscious thoughts are profoundly influenced by unconscious drives, repressed desires, and childhood conflicts.", ["The human brain is a blank slate with zero emotional memory.", "Psychological distress is caused entirely by imbalances in bodily bile humors.", "All human mental processes operate with pure, transparent logical rationality."]),
  ("Intellectual Revolutions: Information Revolution (Turing)", "Alan Turing's foundational conceptualization of the 'Universal Turing Machine' in 1936 laid the mathematical groundwork for the Information Age by establishing:", "The theoretical principles of programmable modern digital computing and algorithmic processing.", ["The chemical composition of synthetic plastics.", "The atomic nuclear fission chain reaction.", "The geological plate tectonic theory of continental drift."]),
  ("Philosophy of Tech: Heidegger's 'Question Concerning Technology'", "In Martin Heidegger's philosophy, the modern essence of technology is 'Gestell' (Enframing), which dangerously reduces nature and human beings into:", "'Standing-Reserve' (Bestand)—mere resources, stock, and energy on standby for exploitation and optimization.", ["Sacred objects of aesthetic contemplation.", "Ethereal metaphysical forms of divine truth.", "Immutable mathematical axioms."]),
  ("Philosophy of Tech: Heidegger's Poiesis & Aletheia", "Heidegger reminds us that ancient Greek technology (techne) was originally a mode of 'Aletheia' (revealing truth) and 'Poiesis' (bringing-forth), meaning:", "Technology was an artful, respectful revealing of nature's potentials rather than an aggressive, challenging-forth extraction.", ["Technology existed solely for manufacturing military weapons.", "Ancient humans completely rejected toolmaking.", "Machines operated with autonomous artificial intelligence."]),
  ("Human Flourishing: Aristotle's Eudaimonia in STS", "In STS education, human flourishing (Eudaimonia) is connected to technological progress by asserting that technology should be evaluated by whether it:", "Enables genuine human flourishing, moral virtue, social justice, and well-being, rather than mere material consumption.", ["Maximizes corporate advertising profits regardless of ecological degradation.", "Replaces all human labor with automated surveillance systems.", "Forces citizens to spend 18 hours daily on digital smartphones."]),
  ("National Scientists: Fe Del Mundo (Pediatrics)", "National Scientist Fe Del Mundo (the first female student admitted to Harvard Medical School) is celebrated in Philippine science history for:", "Inventing an indigenous bamboo incubator for rural communities and pioneering Philippine public pediatric healthcare.", ["Discovering the chemical formula of synthetic rubber.", "Developing the first nuclear power reactor in Southeast Asia.", "Breeding the high-yield IR8 miracle rice variety."]),
  ("National Scientists: Ramon Barba (Horticulture)", "National Scientist Ramon Barba revolutionized Philippine agriculture and the mango export industry by:", "Discovering that spraying potassium nitrate (KNO3) induces year-round, off-season flowering and fruiting in mango trees.", ["Introducing genetic cloning for coconut palms.", "Inventing an automated robotic rice harvester.", "Developing synthetic nitrogen fertilizer from sugarcane waste."]),
  ("National Scientists: Angel Alcala (Marine Biology)", "National Scientist Angel Alcala pioneered marine conservation in the Philippines through the creation of:", "The first community-based Marine Protected Areas (MPAs) and artificial coral reefs in Apo Island and Sumilon.", ["Commercial deep-sea bottom-trawling fishing fleets.", "Nuclear-powered submarine research vessels.", "Synthetic plastic seawall barriers."]),
  ("National Scientists: Gavino Trono (Phycology)", "National Scientist Gavino Trono, known as the 'Father of Kappaphycus Farming', made groundbreaking scientific contributions to:", "The taxonomy, cultivation, and commercial farming of marine macrobenthic algae (seaweeds / carrageenan production).", ["Volcanic seismology and tsunami warning systems.", "Freshwater tilapia fish hatchery engineering.", "Forestry timber replanting in the Sierra Madre."]),
  ("National Scientists: Diosdado Banatao (Microchips)", "Filipino Silicon Valley innovator Diosdado Banatao revolutionized the global personal computer industry by developing:", "The first 10-Mbit Ethernet CMOS MAC/PHY chip and the first Windows Graphics Accelerator chip.", ["The first Apple iPhone touch interface.", "The global satellite GPS navigation constellation.", "The Microsoft Windows 95 operating system source code."]),
  ("Science & Nation Building: Harmonized National R&D Agenda (HNRDA)", "The Department of Science and Technology (DOST) formulates the Harmonized National R&D Agenda (HNRDA) to ensure that Philippine scientific research:", "Directly addresses national socio-economic priorities, disaster resilience, health security, and sustainable development.", ["Focuses exclusively on sending astronauts to Mars.", "Is conducted only in private foreign corporate laboratories.", "Is prohibited from receiving public government funding."]),
  ("Space Science: Philippine Space Agency (PhilSA)", "Established under Republic Act 11363 (Philippine Space Act of 2019), the Philippine Space Agency (PhilSA) coordinates space science, including the deployment of:", "Micro-satellites (such as Diwata-1, Diwata-2, and Maya nanosatellites) for disaster risk management, maritime surveillance, and agriculture.", ["Interplanetary deep-space colonization shuttles.", "Commercial space-tourism rocket launchpads for private billionaires.", "Orbital military laser defense shields."]),
  ("Disaster Science: Project NOAH", "Project NOAH (Nationwide Operational Assessment of Hazards), originally established by DOST and now at UP, was developed to:", "Provide high-resolution storm surge hazard maps, real-time flood monitoring, and landslide warnings for disaster mitigation.", ["Control tropical typhoons through cloud-seeding chemical injections.", "Predict exact earthquake days and times with absolute certainty.", "Eliminate all rainfall across the Philippine archipelago."])
]
d.extend([
  ("Biotechnology: Genetically Modified Organisms (GMOs)", "A 'Genetically Modified Organism' (GMO) is biologically defined as an organism whose genetic material (DNA) has been:", "Altered using modern recombinant DNA technology or genetic engineering to introduce desirable non-native traits.", ["Cross-pollinated through traditional agricultural grafting over centuries.", "Subjected to natural sunlight and organic manure fertilization.", "Grown exclusively in zero-gravity space laboratories."]),
  ("Biotechnology: Bt Corn & Bacillus thuringiensis", "Genetically modified 'Bt Corn' is engineered to express the Cry toxin protein from the soil bacterium Bacillus thuringiensis primarily to:", "Confer biological resistance against the devastating Asian corn borer pest without heavy synthetic chemical insecticides.", ["Make corn kernels glow with fluorescent yellow luminescence.", "Accelerate corn growth so that harvesting occurs in 3 days.", "Increase the sugar sweetness of corn syrup by 500%."]),
  ("Biotechnology: Golden Rice & Vitamin A Deficiency", "Golden Rice (GR2E) was genetically engineered by inserting beta-carotene biosynthesis genes (from daffodil/maize and Erwinia) to combat:", "Vitamin A Deficiency (VAD), which causes childhood blindness, immune failure, and mortality in developing nations.", ["Iron-deficiency anemia in elderly hospital patients.", "Chronic iodine deficiency in coastal fishing villages.", "Lactose intolerance in infant formula."]),
  ("Biotechnology: CRISPR-Cas9 Gene Editing", "The Nobel Prize-winning CRISPR-Cas9 technology revolutionized genetics because it functions as:", "Molecular scissors that allow scientists to edit, insert, or delete specific DNA sequences with unprecedented precision and low cost.", ["A high-powered optical microscope used to observe living viruses.", "A synthetic chemical fertilizer that doubles rice crop yields.", "A digital computer program that translates genetic code into spoken words."]),
  ("Biotechnology: Biosafety Regulations in Philippines", "In the Philippines, the commercial release of GM crops is regulated under the Joint Department Circular (JDC No. 1, s. 2021) by DA, DOST, DENR, DOH, and DILG to ensure:", "Rigorous scientific risk assessment regarding environmental safety, food and feed safety, and socio-economic impact.", ["Automatic approval of all foreign biotech patents within 24 hours.", "The total prohibition of all scientific agricultural research.", "Mandatory cultivation of GM crops in all public elementary school gardens."]),
  ("Environmental Science: The Greenhouse Effect", "The natural 'Greenhouse Effect' is an essential atmospheric process whereby greenhouse gases (such as CO2, CH4, H2O, N2O):", "Trap outgoing long-wave infrared thermal radiation emitted by Earth, keeping global average temperatures habitable (~15 deg C).", ["Block all incoming solar ultraviolet rays from reaching the upper stratosphere.", "Reflect 100% of visible light back into deep space.", "Produce ozone molecules through nuclear fusion in cloud layers."]),
  ("Environmental Science: Anthropogenic Climate Change", "Anthropogenic global warming is driven primarily by the rapid accumulation of greenhouse gases in the atmosphere caused by:", "The combustion of fossil fuels (coal, oil, gas), industrial deforestation, and large-scale industrial agriculture.", ["Natural volcanic ash eruptions in the Pacific Ring of Fire.", "Variations in the physical distance between Earth and Mars.", "Cosmic gamma ray bursts from distant exploding stars."]),
  ("Environmental Treaties: The Paris Agreement (2015)", "The central, legally binding international goal established under the 2015 Paris Climate Agreement (COP21) is to:", "Limit global average temperature increase to well below 2 deg C above pre-industrial levels, pursuing efforts to limit it to 1.5 deg C.", ["Completely ban the use of all motor vehicles worldwide by 2020.", "Force developing nations to pay carbon penalties to industrialized countries.", "Relocate all coastal cities to mountainous regions."]),
  ("Philippine Climate Legislation: RA 9729", "Republic Act 9729 (Climate Change Act of 2009) established the Climate Change Commission (CCC) to mainstream climate risk management into:", "National and Local Climate Change Action Plans (LCCAP) and disaster risk reduction frameworks across all government levels.", ["The national military defense strategic command.", "The international commercial banking stock market.", "Private corporate marketing campaigns."]),
  ("Philippine Environmental Laws: Clean Air Act (RA 8749)", "Republic Act 8749 (Philippine Clean Air Act of 1999) establishes comprehensive air pollution control, famously including:", "A nationwide ban on the incineration of municipal, bio-medical, and hazardous industrial wastes.", ["The mandatory conversion of all diesel jeepneys into horse-drawn calesas.", "A legal limit of only 5 cars per provincial municipality.", "The total shutdown of all electrical power generating plants."]),
  ("Philippine Environmental Laws: Ecological Solid Waste (RA 9003)", "Republic Act 9003 (Ecological Solid Waste Management Act of 2000) mandates that local government units must implement:", "Waste segregation at source, comprehensive recycling, composting, and the closure of open dumpsites in favor of sanitary landfills.", ["Dumping all municipal garbage into deep ocean trenches.", "The mandatory burning of plastic trash in residential backyards.", "Shipping provincial electronic waste to foreign overseas islands."]),
  ("Nanotechnology: Scale and Quantum Effects", "Nanotechnology involves manipulating matter at the nanoscale. What is the standard physical size range of a nanometer (nm)?", "1 to 100 nanometers (1 nm = 10^-9 meter, approximately 1 billionth of a meter).", ["1 to 100 millimeters (10^-3 meter).", "1 to 100 micrometers (10^-6 meter).", "1 to 100 picometers (10^-12 meter)."]),
  ("Nanotechnology: Applications in Medicine", "In biomedical engineering, 'Nanomedicine' uses engineered nanoparticles (such as liposomes or gold nanoshells) primarily for:", "Targeted drug delivery directly to cancer cells, minimizing damage to healthy surrounding tissues.", ["Replacing traditional surgical scalpels with iron magnets.", "Eliminating the need for all biological human red blood cells.", "Permanently altering human skeletal height."]),
  ("Artificial Intelligence: Machine Learning (ML)", "In computer science and STS, 'Machine Learning' is a subfield of artificial intelligence where algorithms:", "Learn patterns from large training datasets to improve performance on tasks without being explicitly programmed with rule-based code.", ["Physically transform computer hardware into biological brain tissue.", "Operate purely through mechanical gear and clockwork levers.", "Require human programmers to type every individual decision in advance."]),
  ("Artificial Intelligence: Generative AI & Large Language Models (LLMs)", "Generative AI models (such as LLMs like GPT or Gemini) generate human-like text by:", "Calculating statistical probability distributions of words (tokens) based on massive textual training data.", ["Possessing conscious human feelings, subjective empathy, and an immortal soul.", "Accessing secret government spy satellite telepathic networks.", "Searching a fixed dictionary database and copying sentences verbatim."])
])
d.extend([
  ("Ethics of AI: Algorithmic Bias in Hiring", "When an automated AI recruitment screening algorithm down-ranks candidates from women's colleges because the historical training data was predominantly male, this illustrates:", "Algorithmic bias, resulting from uncritical training on historically biased societal datasets.", ["Technological sentience, proving the computer has conscious gender animus.", "Digital sovereignty, reflecting national control over servers.", "Hardware overheating in computer data centers."]),
  ("Ethics of AI: The 'Black Box' Problem", "In high-stakes AI applications (such as criminal sentencing algorithms or medical diagnosis), the 'Black Box' problem poses an ethical dilemma because:", "The internal decision-making pathways of complex deep neural networks are unexplainable and opaque to human auditors.", ["Computer monitors emit low levels of radiation.", "Artificial intelligence programs run only during nighttime power grid off-peak hours.", "Servers cannot be legally registered under corporate copyright laws."]),
  ("Information Age: Data Privacy Act of 2012 (RA 10173)", "Under Republic Act 10173, the independent regulatory body established to administer and enforce the Data Privacy Act in the Philippines is the:", "National Privacy Commission (NPC).", ["National Telecommunications Commission (NTC).", "Department of Information and Communications Technology (DICT).", "Cybercrime Investigation and Coordinating Center (CICC)."]),
  ("Information Age: Surveillance Capitalism", "Shoshana Zuboff's critique of 'Surveillance Capitalism' describes a modern digital economic model where tech corporations:", "Extract behavioral data from human online experience to predict, modify, and monetize user behavior.", ["Provide free subsidized broadband access to all developing nations.", "Distribute open-source software code to public school classrooms.", "Protect user anonymity through decentralized encrypted networks."]),
  ("Information Age: Cybersecurity & Phishing", "In digital security, 'Phishing' refers to a social engineering cyber-attack where attackers:", "Impersonate legitimate institutions (e.g., banks or schools) via fraudulent emails to trick users into revealing sensitive credentials.", ["Physically steal hard drives from institutional data centers.", "Overheat computer processors by running complex mathematical algorithms.", "Broadcast high-frequency radio jamming signals."]),
  ("Renewable Energy: Solar Photovoltaic (PV) Technology", "Solar Photovoltaic (PV) cells generate clean electricity through the 'Photoelectric Effect', which occurs when:", "Photons of sunlight strike semiconductor materials (such as silicon), dislodging electrons and generating electrical current.", ["Sunlight boils underground magma chambers to turn steam turbines.", "Solar rays split heavy uranium atoms in nuclear containment vessels.", "Heat evaporates chemical refrigerants in residential cooling coils."]),
  ("Renewable Energy: Geothermal Energy in Philippines", "The Philippines is one of the world's top producers of geothermal energy (e.g., MakBan, Tiwi, Palinpinon plants) because of its location along:", "The Pacific Ring of Fire, featuring abundant volcanic thermal heat reservoirs beneath the Earth's crust.", ["The Arctic Polar Circle.", "The Great Rift Valley of East Africa.", "The Sahara Desert solar belt."]),
  ("Renewable Energy: Wind Energy (Bangui Windmills)", "The landmark Bangui Wind Farm in Ilocos Norte harnesses wind energy, an environmentally sustainable power source that:", "Generates zero greenhouse gas emissions during electrical operation and reduces national reliance on imported fossil fuels.", ["Requires the combustion of low-grade bunker fuel during cloudy weather.", "Consumes massive volumes of freshwater for cooling nuclear rods.", "Causes permanent disruption of global planetary rotational velocity."]),
  ("Historical Antecedents: Ancient Inventions (Cuneiform & Papyrus)", "In the ancient world, the Sumerians invented 'Cuneiform' (wedge-shaped writing on clay tablets), while the ancient Egyptians developed 'Papyrus' from reeds primarily to:", "Record agricultural transactions, trade contracts, temple inventories, and codified administrative laws.", ["Decorate modern tourist museums in European capitals.", "Build seawalls to prevent Mediterranean tsunamis.", "Send wireless electromagnetic telegraph messages."]),
  ("Historical Antecedents: Ancient Architecture (Roman Aqueducts)", "The ancient Romans engineered monumental 'Aqueducts' using volcanic pozzolana concrete and gravity flow primarily to:", "Transport fresh mountain spring water across vast distances to supply urban public baths, fountains, and private households.", ["Serve as fortified military boundary walls against barbarian invasions.", "Store combustible petroleum fuel for naval galleys.", "Drain toxic industrial radioactive waste away from cities."]),
  ("Historical Antecedents: Middle Ages Inventions (Gutenberg Press)", "Johannes Gutenberg's invention of the movable-type printing press in Mainz, Germany (circa 1440) democratized knowledge across Europe by:", "Dramatically lowering the cost of book production, accelerating literacy, and fueling the Protestant Reformation and Scientific Revolution.", ["Replacing all written languages with computer binary code.", "Allowing monarchs to completely eliminate public literacy.", "Preventing the dissemination of scientific manuscripts."]),
  ("Historical Antecedents: Middle Ages Inventions (Compass & Gunpowder)", "The 'Four Great Inventions' of ancient and medieval China (Papermaking, Printing, Gunpowder, and the Magnetic Compass) transformed world history by:", "Revolutionizing global maritime navigation, military warfare, cartography, and knowledge dissemination.", ["Creating the first automated steam locomotive railways.", "Introducing nuclear fusion energy to agricultural farming.", "Inventing digital microprocessor silicon chips."]),
  ("Industrial Revolution: James Watt's Steam Engine", "James Watt's perfected steam engine (1769) catalyzed the First Industrial Revolution by providing:", "A reliable, portable source of mechanical power that emancipated manufacturing and transportation from reliance on human/animal muscle and watermills.", ["Clean renewable electrical energy generated from solar panels.", "Automated digital microcomputers for textile factory payrolls.", "Synthetic petroleum plastics for automotive manufacturing."]),
  ("Industrial Revolution: Public Health & Sanitation", "The rapid urbanization of the Industrial Revolution caused severe cholera outbreaks until John Snow and Edwin Chadwick established that:", "Diseases are transmitted through contaminated municipal drinking water and poor sanitation, leading to modern public water engineering.", ["Cholera is caused by inhaling cold evening moonlight.", "Diseases result from spiritual moral defects in factory workers.", "Inhaling coal factory soot strengthens biological lung tissue."]),
  ("Science & Society: The Green Revolution (Norman Borlaug)", "The 'Green Revolution' (1960s-1970s), pioneered by Nobel Laureate Norman Borlaug and IRRI in Los Banos, Laguna, saved over a billion people from starvation by:", "Breeding semi-dwarf, high-yield, disease-resistant crop varieties (e.g., IR8 'Miracle Rice') combined with modern irrigation and agronomy.", ["Replacing all grain crops with synthetic chemical food tablets.", "Banning the use of water in agricultural farming.", "Converting all arable land into industrial manufacturing factories."])
])
d.extend([
  ("Biotechnology: Human Cloning & Stem Cell Ethics", "In bioethics, the sharp ethical distinction between 'Therapeutic Cloning' and 'Reproductive Cloning' is that therapeutic cloning aims to:", "Generate stem cells genetically matched to a patient for regenerative medicine without creating a cloned baby.", ["Clone identical human babies for military armed battalions.", "Manufacture genetically modified pets for commercial pet stores.", "Eliminate all human genetic diversity across global populations."]),
  ("Biotechnology: Somatic vs Germline Gene Editing", "In genetic engineering ethics, 'Germline Gene Editing' is subject to intense international regulatory scrutiny because:", "Genetic modifications made to eggs, sperm, or early embryos are heritable and passed down permanently to all future generations.", ["It affects only the treated somatic cells of a single living patient without inheritance.", "It requires the use of radioactive uranium isotopes.", "It is 100% risk-free and carries zero off-target mutation risks."]),
  ("Environmental Issues: Microplastics in Marine Ecosystems", "Microplastics (plastic particles smaller than 5 mm) pose a catastrophic environmental and human health hazard because they:", "Persist for centuries, adsorb toxic chemical pollutants, and bioaccumulate up the marine food chain into human seafood.", ["Dissolve into harmless drinking water within 24 hours.", "Enhance the reproductive fertility of coral reef polyps.", "Filter excess carbon dioxide out of ocean surface waters."]),
  ("Environmental Issues: Ocean Acidification", "As the global oceans absorb approximately 30% of anthropogenic CO2 emissions, chemical reactions reduce seawater pH, causing 'Ocean Acidification' which:", "Corrodes calcium carbonate shells and skeletons of coral reefs, mollusks, and pteropods, threatening marine biodiversity.", ["Increases ocean salinity so that ships float higher in the water.", "Transforms seawater into potable fresh drinking water.", "Causes volcanic eruptions along tectonic ocean ridges."]),
  ("Environmental Issues: Deforestation & Zoonotic Diseases", "Ecological science demonstrates that rampant tropical deforestation and wildlife habitat destruction significantly increase the risk of:", "Zoonotic spillover events, where novel viral pathogens jump from wild animals to human populations (e.g., SARS-CoV-2, Ebola).", ["The spontaneous cooling of regional atmospheric weather patterns.", "The complete eradication of all insect species globally.", "The immediate transformation of barren soils into lush farmland."]),
  ("Information Age: The Digital Divide", "In STS, the 'Digital Divide' refers to:", "The socio-economic gap between demographics and regions that have access to modern ICT infrastructure and those that do not.", ["The physical space between two computer server racks in a data center.", "The mathematical difference between 32-bit and 64-bit microprocessors.", "The legal separation of computer software and hardware patents."]),
  ("Information Age: E-Waste Hazards", "Improper disposal and informal recycling of Electronic Waste (E-waste) poses grave public health hazards because electronic components contain:", "Toxic heavy metals such as lead, mercury, cadmium, and brominated flame retardants that leach into groundwater.", ["High concentrations of edible organic plant proteins.", "Harmless pure distilled water that evaporates quickly.", "Radioactive medical plutonium isotopes in consumer smartphones."]),
  ("Philosophy of Tech: Technological Determinism vs Social Constructivism", "While 'Technological Determinism' claims that technology develops autonomously and dictates social change, 'Social Constructivism' (SCOT) argues that:", "Human actions, cultural values, social institutions, and economic choices shape how technologies are developed and used.", ["Technology has zero impact on human civilization.", "Machines possess independent biological conscious desires.", "All technologies are created exclusively by government military decrees."]),
  ("Philosophy of Tech: Langdon Winner's 'Do Artifacts Have Politics?'", "Political theorist Langdon Winner argued that technical artifacts can embody political properties, famously citing Robert Moses' low highway overpasses in New York which:", "Deliberately prevented public buses carrying low-income and minority citizens from accessing Long Island beaches.", ["Were designed to improve the aerodynamic speed of electric sports cars.", "Generated renewable solar power for municipal subway systems.", "Allowed cargo ships to navigate urban river canals."]),
  ("Science & Society: The Precautionary Principle", "The Precautionary Principle in STS governance dictates that when human activities carry potential threats of serious or irreversible harm:", "Lack of full scientific certainty should not be used as a reason to postpone cost-effective measures to prevent harm.", ["Governments must wait for 100% unanimous scientific agreement before acting.", "Technological innovation should proceed with zero safety regulations.", "Industrial companies are exempt from all environmental liabilities."]),
  ("Space Science: Space Debris (Kessler Syndrome)", "The 'Kessler Syndrome' in orbital astronautics describes a catastrophic scenario where the density of space debris in Low Earth Orbit (LEO) becomes so high that:", "Collisions between objects create a cascading chain reaction of fragments, rendering orbital space unusable for generations.", ["Satellites fall simultaneously onto major world capital cities.", "The Earth's gravitational pull reverses its physical polarity.", "Rocket engines consume all atmospheric oxygen in the stratosphere."]),
  ("Energy Science: Nuclear Fission vs Fusion", "While existing commercial nuclear power plants generate electricity through Nuclear FISSION (splitting heavy uranium nuclei), experimental fusion reactors (like ITER) aim to generate clean energy through:", "Nuclear FUSION (combining light hydrogen isotopes like deuterium and tritium at extreme temperatures, mimicking the Sun).", ["Burning pulverized coal inside magnetic containment fields.", "Splitting water molecules using household electrical batteries.", "Extracting petroleum oil from geothermal volcanic geysers."]),
  ("Energy Science: Advantages of Nuclear Fusion", "If commercialized, Nuclear Fusion offers transformative advantages over fossil fuels and fission because it produces:", "Abundant energy from seawater isotopes with zero long-lived radioactive waste, zero greenhouse gases, and zero risk of meltdown.", ["Harmful acid rain that dissolves limestone buildings.", "Massive volumes of greenhouse methane gas.", "Permanent radioactive air pollution."]),
  ("Emerging Tech: Quantum Computing", "Unlike classical computers that process information in binary bits (0 or 1), Quantum Computers process 'Qubits' utilizing quantum superposition and entanglement to:", "Perform complex calculations (such as molecular drug simulation and cryptography breaking) exponentially faster than supercomputers.", ["Replace the need for electrical power supplies.", "Store physical paper books inside microscopic laser beams.", "Connect directly to human telepathic thought waves."]),
  ("Emerging Tech: Synthetic Biology & Biobricks", "In modern synthetic biology, the use of standardized genetic parts called 'BioBricks' allows bioengineers to:", "Design and construct novel artificial biological pathways, microbes, and enzymes for medicine, biofuels, and bioremediation.", ["Manufacture plastic children's building blocks in factories.", "Clone prehistoric dinosaurs for public entertainment parks.", "Replace all natural agricultural plants with synthetic concrete."])
])
d.extend([
  ("Science & Society: Citizen Science", "In contemporary environmental monitoring, 'Citizen Science' refers to:", "The active participation of the general public and non-professional volunteers in scientific research, data collection, and biodiversity tracking.", ["Mandatory laboratory testing conducted on military recruits.", "Censoring scientific discoveries that contradict state propaganda.", "Replacing all professional university researchers with automated software."]),
  ("Indigenous Science: Traditional Ecological Knowledge (TEK)", "Traditional Ecological Knowledge (TEK) developed over centuries by indigenous communities (such as Ifugao terrace irrigation and herbal ethnobotany):", "Provides invaluable, time-tested insights into local biodiversity conservation, sustainable agriculture, and climate adaptation.", ["Is completely unscientific folklore that should be eliminated.", "Conflicts with all modern biological classification systems.", "Is legally copyrighted by multinational pharmaceutical monopolies."]),
  ("Philippine Science Policy: Balik Scientist Program (RA 11035)", "Republic Act 11035 (Balik Scientist Act) provides incentives and fellowships to encourage Filipino scientists and technologists abroad to:", "Return to the Philippines and share their advanced expertise to accelerate national R&D and technological capacity.", ["Permanently surrender their foreign university degrees.", "Work exclusively in non-technical administrative office roles.", "Relinquish their Philippine citizenship."]),
  ("Public Health: Antimicrobial Resistance (AMR)", "Antimicrobial Resistance (AMR)—the evolution of bacteria and viruses that survive standard antibiotic treatments—is driven primarily by:", "The over-prescription of antibiotics in human medicine and widespread misuse in industrial livestock growth promotion.", ["Drinking unboiled tap water in rural communities.", "The natural rotation of planetary seasonal weather patterns.", "The complete avoidance of all pharmaceutical drugs."]),
  ("Public Health: One Health Approach", "The World Health Organization's 'One Health' framework recognizes that human health is inextricably linked to:", "The health of animals and the shared physical environment/ecosystem.", ["The financial profitability of private health insurance corporations.", "The number of hospitals built in major metropolitan centers.", "The chronological age of university medical professors."]),
  ("Energy Transition: Battery Storage & Lithium-Ion", "The global transition to electric vehicles (EVs) and intermittent renewable grids relies heavily on Lithium-Ion batteries, raising STS challenges regarding:", "The environmental, human rights, and geopolitical impacts of mining critical minerals like lithium, cobalt, and nickel.", ["The excessive weight of batteries causing highway bridges to collapse.", "The high risk of nuclear radiation leaks from lithium atoms.", "The total absence of electrical recharging infrastructure."]),
  ("Ethics of Tech: Autonomous Vehicles (The Trolley Problem)", "In autonomous vehicle safety engineering, programming self-driving cars to make split-second decisions in unavoidable fatal crashes is a modern application of:", "The Trolley Problem in applied ethics and moral philosophy.", ["Newton's First Law of Gravitational Motion.", "The Pythagorean Theorem in planar geometry.", "The Ideal Gas Law in chemical thermodynamics."]),
  ("Ethics of Tech: Deepfakes & Information Integrity", "Deepfake technology—using deep neural generative adversarial networks (GANs) to synthesize realistic fake audio/video—poses severe STS threats to:", "Democratic trust, electoral integrity, judicial evidence reliability, and personal privacy/reputation.", ["The storage capacity of computer hard drives.", "The transmission speed of fiber-optic internet cables.", "The physical power output of solar photovoltaic panels."]),
  ("Philosophy of Science: Thomas Kuhn's Paradigm Shifts", "In The Structure of Scientific Revolutions (1962), Thomas Kuhn argued that scientific progress occurs not by steady accumulation, but through:", "'Paradigm Shifts', where accumulated anomalies trigger a revolutionary replacement of a dominant scientific framework.", ["Unchanging adherence to ancient Aristotelian physics.", "Daily random revisions of chemical periodic tables.", "The complete elimination of peer-reviewed scientific journals."]),
  ("Philosophy of Science: Karl Popper's Falsificationism", "Philosopher of science Karl Popper argued that the defining criterion of a genuinely scientific theory is its 'Falsifiability', meaning:", "It must make specific empirical predictions that could, in principle, be proven false by observation or experiment.", ["It must be endorsed by a majority vote of political legislators.", "It must be 100% mathematically proven to be infallible for all eternity.", "It must be impossible to test or criticize in a laboratory."]),
  ("History of Science: The Scientific Revolution (Bacon & Galileo)", "Francis Bacon's development of the empirical inductive method and Galileo Galilei's telescopic observations established the foundation of modern science by:", "Insisting that scientific knowledge must be based on systematic observation, experimentation, and mathematical evidence rather than dogma.", ["Relying exclusively on theological authority and medieval scholastic disputation.", "Banning all physical experiments in European universities.", "Rejecting all mathematical measurements in astronomical studies."]),
  ("Science & Society: The Tragedy of the Commons (Hardin)", "Garrett Hardin's 'Tragedy of the Commons' illustrates that without shared governance or regulation, individuals acting rationally in self-interest will:", "Overexploit and deplete finite shared common-pool resources (e.g., fisheries, pastures, clean atmosphere), causing collective ruin.", ["Automatically preserve all natural resources in perfect ecological harmony.", "Increase the economic wealth of every citizen equally.", "Eliminate all forms of industrial air pollution."]),
  ("Science & Society: Dual-Use Research", "In biological science governance, 'Dual-Use Research of Concern' (DURC) refers to legitimate research that:", "Could be directly misapplied to create dangerous biological weapons or devastating pandemic pathogens.", ["Requires funding from two separate government departments.", "Is written in both English and Filipino languages.", "Is conducted using both microscopes and telescopes."]),
  ("Science & Society: Epistemic Injustice", "In STS and social philosophy, 'Epistemic Injustice' occurs when a person's testimony or knowledge is unfairly discounted because of:", "Prejudices and biases related to their social identity, gender, race, or marginalized status.", ["Their lack of a high-speed broadband internet subscription.", "Their inability to solve complex calculus equations.", "Their physical geographic distance from government capital buildings."]),
  ("STS Synthesis: Responsible Research and Innovation (RRI)", "The European and global framework of 'Responsible Research and Innovation' (RRI) mandates that scientists and policymakers must:", "Anticipate societal impacts, engage public stakeholders openly, and align R&D with human values, sustainability, and ethics.", ["Prioritize short-term military weapon development above all else.", "Conceal all scientific data from public oversight and review.", "Maximize commercial shareholder profits regardless of ethical risks."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item evaluates scientific literacy and STS competence in {item[0]}. {item[2]} represents standard scientific and philosophical consensus."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('stsExams.ts', 'STS_EXAM_QUESTIONS', questions)
