import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Morality vs Law & Conventions", "A citizen shelters political refugees in defiance of an authoritarian ordinance mandating their immediate arrest. From an ethical standpoint, this demonstrates that:", "An act may be legally prohibited by positive law yet ethically justifiable under universal moral principles.", ["Civil statutes are the ultimate foundation and source of all moral truth.", "Etiquette and local social customs supersede fundamental human dignity.", "Moral obligations are strictly determined by state police power."], "Law and morality are distinct normative systems; positive law can be unjust, whereas morality is grounded in human dignity and universal principles."),
  ("Moral Dilemmas: Organizational Level", "A hospital administrator must choose between enforcing an austerity policy that cuts critical nursing staff or maintaining safe staffing at the risk of insolvency. At what level is this dilemma situated?", "Organizational dilemma, as it involves institutional policies, operational mandates, and business survival.", ["Individual dilemma, as it only impacts the personal conscience of the hospital director.", "Structural dilemma, as it stems exclusively from international trade treaties.", "Pre-conventional dilemma, as it is determined strictly by physiological needs."], "Organizational dilemmas occur within institutions and corporate systems involving conflicting operational policies, economic viability, and ethical duties."),
  ("Cultural Relativism vs Moral Objectivism", "Cultural relativism asserts that moral rightness is solely defined by the prevailing norms of a specific society. Which of the following is the most substantial philosophical objection to this theory?", "It deprives society of any moral basis to condemn grave historical atrocities like slavery or apartheid in other cultures.", ["It assumes that physical nature is governed by immutable mathematical laws.", "It forces all individuals to adopt Western democratic governance frameworks.", "It eliminates the psychological distinction between conscious ego and the collective unconscious."], "If cultural relativism were strictly true, no culture could ever be objectively criticized for practices like torture, slavery, or genocide."),
  ("Kohlberg: Pre-Conventional", "A primary pupil refrains from taking a classmate's crayons exclusively out of fear of being scolded by the teacher. What stage of moral reasoning is this child demonstrating?", "Stage 1: Punishment and Obedience Orientation.", ["Stage 3: Good Boy / Nice Girl Interpersonal Conformity.", "Stage 4: Law and Order Social System Maintenance.", "Stage 5: Social Contract and Individual Rights Orientation."], "Stage 1 reasoning is governed purely by fear of physical punishment and obedience to power."),
  ("Kohlberg: Law and Order", "A civil servant refuses an improper expedited request from a close relative, explaining that rules must apply equally to all citizens to maintain social order. Which Kohlberg stage is illustrated?", "Stage 4: Social System and Conscience (Law and Order).", ["Stage 2: Individualism, Instrumental Purpose, and Exchange.", "Stage 6: Universal Ethical Principles.", "Stage 1: Punishment and Obedience Orientation."], "Stage 4 emphasizes duty, law, social order, and maintaining institutional integrity for the common good."),
  ("Kohlberg: Universal Principles", "During a civil rights movement, activists peacefully break an unconstitutional segregation ordinance, accepting arrest to bear witness to universal human equality. Which Kohlberg stage does this represent?", "Stage 6: Universal Ethical Principles.", ["Stage 2: Instrumental Relativist Orientation.", "Stage 3: Interpersonal Concordance.", "Stage 1: Punishment-Obedience."], "Stage 6 is grounded in self-chosen universal ethical principles of justice and human dignity."),
  ("Aristotle: Golden Mean", "In Aristotelian virtue ethics, how is the virtue of Temperance (moderation) defined in relation to physical appetites?", "The golden mean between the deficiency of Insensibility and the excess of Self-Indulgence.", ["The complete eradication of all physical desires and sensory experiences.", "The unrestricted pursuit of luxury tempered by occasional charitable acts.", "The stoic suppression of all emotional expressions in community interactions."], "Virtue is the mean between deficiency and excess; temperance balances insensibility and self-indulgence."),
  ("Aristotle: Courage vs Extremes", "A bystander observes an armed robbery and, without weapons, training, or tactical assessment, charges the gunman directly. Aristotle would classify this action as:", "Rashness (an excess of boldness), which is a vice rather than true courage.", ["Genuine Aristotelian courage guided by practical wisdom.", "Virtuous fortitude demonstrating moral mastery.", "Moral cowardice resulting from intellectual deficiency."], "Courage is the mean between cowardice and rashness; charging without phronesis is reckless rashness."),
  ("Aristotle: Eudaimonia", "According to Aristotle's Nicomachean Ethics, what constitutes Eudaimonia, the ultimate end (telos) of human life?", "An active life of rational activity in accordance with complete virtue.", ["The passive accumulation of sensory pleasure and hedonistic ease.", "The attainment of hereditary political titles and sovereign rule.", "The accumulation of financial capital through aggressive commerce."], "Eudaimonia is human flourishing achieved through a lifetime of virtuous activity guided by reason."),
  ("Aristotle: Habituation", "How does an individual acquire moral virtues according to classical Aristotelian ethics?", "Through repeated practice and habituation (ethos) of virtuous acts until they become second nature.", ["Through genetic inheritance from aristocratic ancestors.", "Through theoretical memorization of ethical rulebooks without practice.", "Through involuntary state conditioning and physical punishments."], "Moral virtues are acquired by habituation—doing virtuous acts repeatedly until they become stable character traits."),
  ("Kantian Deontology: Universal Law", "Immanuel Kant's First Formulation of the Categorical Imperative requires that an agent must:", "Act only according to that maxim whereby you can at the same time will that it should become a universal law.", ["Act in a manner that guarantees the greatest economic return for your family.", "Follow the majority opinion of your local civic community.", "Obey all legal statutes regardless of their justice or fairness."], "The Formula of Universal Law tests moral maxims by asking whether a world where everyone acted on that maxim would be logically coherent."),
  ("Kantian Deontology: Formula of Humanity", "A department head takes sole credit for a junior faculty member's breakthrough curriculum design to secure a promotion. Kantian ethics condemns this primarily because:", "It treats the junior colleague merely as a means to an end rather than as an end in themselves.", ["It fails to follow the standard administrative citation format.", "It causes temporary emotional distress to the department's staff.", "It reduces the financial grant allocated to the academic division."], "Kant's second formulation dictates that humanity must always be treated as an end in itself and never merely as an instrument for personal gain."),
  ("Kantian Ethics: The Good Will", "According to Kant, what is the only thing that can be regarded as good without qualification in the entire world?", "A Good Will, which acts purely out of duty and respect for moral law.", ["High intelligence and analytical sharpness.", "Abundant financial wealth used for public philanthropy.", "Natural good temper and emotional sympathy."], "Kant asserts that talents and gifts of fortune can become harmful if the underlying will is corrupt. Only a Good Will acting from duty is unconditionally good."),
  ("Utilitarianism: Greatest Happiness Principle", "Jeremy Bentham and John Stuart Mill formulate the core principle of Utilitarianism as holding that actions are right in proportion as they:", "Promote the greatest happiness/well-being for the greatest number of people.", ["Conform strictly to ancient religious and cultural dogmas.", "Maximize the private profits of corporate shareholders.", "Uphold the divine right of executive magistrates."], "Utilitarianism evaluates actions based on their consequences: maximizing aggregate pleasure/happiness and minimizing aggregate pain/suffering."),
  ("Mill: Higher vs Lower Pleasures", "John Stuart Mill distinguished himself from Jeremy Bentham's purely quantitative utilitarianism by arguing that:", "Intellectual, artistic, and moral pleasures possess a qualitatively higher value than mere bodily sensations.", ["All pleasures, whether pushpin or poetry, are equal if intensity and duration match.", "Consequences are completely irrelevant to determining moral rightness.", "Physical pleasure is the sole legitimate criterion of moral virtue."], "Mill famously declared that intellectual and moral pleasures are qualitatively superior to base sensory pleasures.")
]
d.extend([
  ("Act vs Rule Utilitarianism", "A physician has five dying patients needing organs and one healthy visitor. Rule Utilitarianism forbids killing the visitor because:", "A general societal rule permitting doctors to harvest patients would destroy trust in medicine, causing catastrophic social harm.", ["The sum of five lives saved outweighs one life lost in this specific calculation.", "The physician lacks specialized transplant credentials.", "The healthy patient has a higher socioeconomic net worth."]),
  ("Aquinas: Natural Law & Synderesis", "In the Thomistic philosophy of Natural Law, what is the foundational first principle of practical reason (synderesis)?", "Good is to be done and pursued, and evil is to be avoided.", ["Might makes right in human political governance.", "Every individual must prioritize private self-interest above all.", "Physical pleasure is the only verifiable truth."]),
  ("Aquinas: Principle of Double Effect", "Under the Principle of Double Effect, an act with both good and bad effects is permissible only if:", "The act itself is morally good or neutral, the intention is strictly directed to the good effect, and the bad effect is not the means.", ["The bad effect is actively desired as a direct instrument to produce the good result.", "The individual receives formal permission from a municipal council.", "The monetary benefits of the action exceed its operational expenses."]),
  ("Care Ethics: Relationality & Empathy", "Nel Noddings and Carol Gilligan criticize traditional moral frameworks for:", "Overemphasizing abstract, detached rules while ignoring the moral significance of personal relationships and empathy.", ["Failing to apply advanced mathematical calculations to moral scenarios.", "Being too focused on family obligations and maternal care.", "Rejecting all forms of legal codification in democratic societies."]),
  ("Rawls: The Original Position", "John Rawls' thought experiment of the 'Original Position' behind the 'Veil of Ignorance' is designed to establish principles of justice that are:", "Fair and unbiased, because decision-makers are unaware of their own social standing, wealth, or abilities.", ["Tailored specifically to favor the most educated and wealthy elites.", "Based entirely on traditional religious doctrines and ecclesiastical law.", "Designed to eliminate all competition and private enterprise completely."]),
  ("Rawls: Difference Principle", "In Rawls' Justice as Fairness, the Difference Principle allows economic inequalities only if they:", "Work to the greatest benefit of the least advantaged members of society.", ["Are approved by a majority of corporate executives.", "Guarantee identical salaries for all workers regardless of role.", "Arise from completely unregulated market monopolies."]),
  ("Filipino Values: Utang na Loob", "In Philippine public administration, 'Utang na Loob' (debt of gratitude) becomes ethically problematic when:", "A public official awards an unvetted government contract to a political patron out of personal indebtedness.", ["A professional daughter supports her parents in their retirement.", "A student sends a thank-you letter to a former mentor.", "A neighborhood coordinates a voluntary disaster relief drive."]),
  ("Filipino Values: Pakikisama vs Pakikipagkapwa", "According to Filipino psychology (Sikolohiyang Pilipino), why is 'Pakikipagkapwa' a higher ethical value than 'Pakikisama'?", "Pakikipagkapwa is rooted in shared human dignity (kapwa), whereas Pakikisama can lead to uncritical peer conformity.", ["Pakikisama applies only to international diplomatic treaties.", "Pakikipagkapwa requires commercial transactions in every family gathering.", "Pakikisama is legally mandated under the Local Government Code."]),
  ("Bioethics: Principle of Autonomy", "A competent 60-year-old patient diagnosed with kidney failure refuses dialysis after full medical briefing. The medical team's ethical duty to honor this refusal is grounded in:", "The principle of Autonomy, which protects a patient's right to self-determination in medical care.", ["The principle of Medical Paternalism, which allows doctors to override patient choices.", "The principle of Coercion, which forces treatments for institutional efficiency.", "The principle of Utilitarian triage based on age."]),
  ("Bioethics: Beneficence vs Non-Maleficence", "The bioethical principle of 'Beneficence' obligates healthcare professionals to:", "Actively promote the well-being and positive health outcomes of patients.", ["Avoid inflicting any intentional harm or injury on patients.", "Charge maximum fees to support hospital research infrastructure.", "Withhold diagnostic test results from patients to prevent anxiety."]),
  ("Bioethics: Informed Consent", "For informed consent to be ethically and legally valid, it must include which three essential elements?", "Adequate information disclosure, patient competence/comprehension, and voluntary choice without coercion.", ["A notarized payment guarantee, hospital board approval, and police clearance.", "A non-disclosure agreement, witness signatures from three physicians, and municipal registration.", "Full surrender of legal rights, mandatory laboratory testing, and familial co-signatures."]),
  ("Environmental Ethics: Anthropocentrism", "An urban developer argues that a pristine wetland has value only as real estate for shopping malls and residential towers. This perspective exemplifies:", "Anthropocentrism, which views non-human nature strictly as an instrumental resource for human use.", ["Biocentrism, which attributes intrinsic value to all living organisms.", "Ecocentrism, which values the integrity of entire ecological systems.", "Deep Ecology, which advocates ecological egalitarianism."]),
  ("Environmental Ethics: Biocentrism", "Paul Taylor's 'Respect for Nature' advocates Biocentrism, which holds that:", "All living organisms are teleological centers of life with intrinsic moral worth.", ["Only human beings possess moral standing due to their rational souls.", "Rocks and minerals have higher moral priority than biological species.", "Economic growth should always override biological conservation."]),
  ("Environmental Ethics: Ecocentrism & Land Ethic", "Aldo Leopold's 'Land Ethic' famously summarized the core ecocentric standard of right action as:", "'A thing is right when it tends to preserve the integrity, stability, and beauty of the biotic community.'", ["'An action is right if it produces the maximum short-term timber harvest.'", "'A policy is just if approved by a majority of mining shareholders.'", "'An action is good only if it eliminates all predatory animal species.'"]),
  ("Environmental Ethics: Intergenerational Justice", "The concept of 'Intergenerational Justice' in environmental ethics dictates that:", "Present generations hold the Earth in trust and have a moral duty to preserve its health for future generations.", ["Current generations should exploit all fossil fuel reserves before technology advances.", "Future human beings have zero legitimate moral claims on present policies.", "Developing nations must bear the entire financial burden of climate mitigation."])
])
d.extend([
  ("Code of Ethics for Teachers: Professional Competence", "Under Article IV of the Code of Ethics for Professional Teachers, every teacher is obligated to:", "Commit to continuous professional growth, study, and research to improve pedagogical competence.", ["Focus solely on classroom duties and avoid all post-graduate studies.", "Rely exclusively on outdated textbook editions to ensure uniformity.", "Delegate lesson planning entirely to student teacher interns."]),
  ("Code of Ethics: Relationship with Students", "Under Article VIII of the Code of Ethics, a teacher who falls in love with a student must:", "Exercise utmost professional discretion and transfer the student to another teacher's class to avoid bias.", ["Immediately publicize the relationship in the school paper.", "Award the student top academic honors to show affection.", "Demand financial assistance from the student's family."]),
  ("Code of Ethics: Private Tutorials & Conflict", "A public high school teacher requires her failing students to attend paid evening tutorials at her home to pass the subject. This directly violates:", "Article VIII, Section 5, which prohibits accepting remuneration for tutorials for one's own students.", ["Article II, Section 2 on participation in local municipal sports leagues.", "Article V, Section 4 on authoring curriculum research papers.", "Article X, Section 1 on investing in educational software."]),
  ("Code of Ethics: Relationship with Associates", "Under Article V of the Code of Ethics, when a teacher discovers confidential derogatory information regarding a colleague, the teacher must:", "Submit the matter formally to the proper school authority without spreading gossip.", ["Broadcast the allegations immediately on public social media channels.", "Confront the colleague during an all-school student assembly.", "Ignore severe violations of child safety to preserve camaraderie."]),
  ("Code of Ethics: The Teacher and the State", "Article II of the Code of Ethics emphasizes that schools are the nurseries of the future citizens of the state. Therefore, the teacher must:", "Transmit cultural heritage, promote national pride, and instill obedience to the laws of the state.", ["Promote partisan political agendas during classroom hours.", "Discourage students from learning about national history and civic duties.", "Refuse participation in national democratic election duties."]),
  ("Ethics of AI: Algorithmic Bias", "An automated facial recognition system used in hiring shows significantly higher error rates for racial minorities. This is an example of:", "Algorithmic bias stemming from unrepresentative, biased historical training datasets.", ["Technological sentience, showing the software possesses independent malice.", "Digital sovereignty, reflecting national control over software servers.", "Hardware obsolescence caused by electrical fluctuations."]),
  ("Ethics of AI: The Explainability Problem", "In medical AI diagnostics, the 'Black Box' problem creates an ethical dilemma because:", "Clinicians cannot verify or explain the underlying mathematical reasoning behind a high-stakes prediction.", ["Computer screens emit low levels of blue light in hospital wards.", "Algorithms operate only during nighttime server update cycles.", "Artificial intelligence programs cannot connect to local power grids."]),
  ("Ethics of AI: Autonomous Weapons", "The primary ethical objection raised by international human rights organizations against Lethal Autonomous Weapons (LAWS) is that:", "Machines lack human empathy, moral judgment, and the capacity for moral accountability.", ["They are more expensive to manufacture than standard rifles.", "They calculate ballistic trajectories with excessive mathematical precision.", "They require satellite communications and electrical batteries."]),
  ("Business Ethics: Corporate Social Responsibility", "Archie Carroll's Pyramid of Corporate Social Responsibility (CSR) arranges corporate duties in which ascending order?", "Economic (base), Legal, Ethical, and Philanthropic (top).", ["Philanthropic (base), Economic, Legal, and Ethical (top).", "Legal (base), Philanthropic, Economic, and Ethical (top).", "Ethical (base), Legal, Philanthropic, and Economic (top)."]),
  ("Business Ethics: Whistleblowing Justification", "According to standard business ethics, an employee is morally justified in blowing the whistle externally when:", "Internal channels have failed, clear evidence exists of serious public harm, and external disclosure can prevent it.", ["The employee wants to retaliate against a supervisor over a minor dispute.", "The employee wishes to leak proprietary trade secrets for personal payment.", "The company introduces a new dress code that the employee dislikes."]),
  ("Meta-Ethics: Emotivism", "In meta-ethics, A.J. Ayer's Emotivism (the Boo/Hurrah theory) claims that ethical statements like 'Murder is wrong' are:", "Emotional expressions of personal disapproval rather than factual truth-claims.", ["Empirical descriptions of physical biological facts.", "Mathematical proofs of social utility.", "Universal metaphysical truths written into the cosmos."]),
  ("Meta-Ethics: Moral Realism vs Anti-Realism", "Moral Realism is the philosophical stance asserting that:", "There are objective moral facts that exist independently of human opinions and cultural conventions.", ["Morality is an illusion created solely by ruling political classes.", "All moral statements are completely meaningless nonsense.", "Ethical values change randomly with daily economic market fluctuations."]),
  ("Moral Psychology: Bandura's Moral Disengagement", "A corporate executive justifies polluting a local river by claiming that competitor companies pollute even more. In Albert Bandura's framework, this is:", "Advantageous Comparison, a mechanism of moral disengagement.", ["Dehumanization of the victim.", "Displacement of responsibility to subordinates.", "Attribution of blame to regulatory agencies."]),
  ("Moral Psychology: Diffusion of Responsibility", "In the bystander effect, individuals fail to intervene in an ongoing assault because many other witnesses are present. This illustrates:", "Diffusion of responsibility, where the presence of others dilutes perceived individual obligation.", ["Kantian good will acting out of categorical duty.", "Aristotelian phronesis guiding courageous action.", "Rule utilitarianism maximizing collective happiness."]),
  ("Philosophy of Law: Legal Positivism", "Legal Positivism, as formulated by John Austin and H.L.A. Hart, fundamentally separates:", "Law as it is (posited legal facts) from law as it ought to be (moral evaluation).", ["Civil litigation from corporate contractual agreements.", "Criminal offenses from administrative traffic citations.", "Statutory codification from judicial precedent."])
])
d.extend([
  ("Philosophy of Law: Natural Law Theory", "In contrast to Legal Positivism, classical Natural Law jurisprudence (e.g., St. Augustine, Martin Luther King Jr.) maintains that:", "'An unjust law is no law at all' (Lex iniusta non est lex) and lacks moral binding force.", ["All codified state statutes are morally infallible and must be obeyed without exception.", "Laws exist solely to protect the economic monopolies of ruling elites.", "Legal statutes have no relevance to human social organization."]),
  ("Ethics of War: Jus ad Bellum", "Under Just War Theory, which of the following is a necessary condition of 'Jus ad Bellum' (justice of resorting to war)?", "War must be waged with right intention, declared by legitimate authority, and used as a last resort.", ["Military forces may invade foreign nations to seize mineral reserves.", "Preemptive strikes are mandatory whenever domestic election polls decline.", "The primary objective must be the total eradication of civilian infrastructure."]),
  ("Ethics of War: Jus in Bello (Discrimination)", "The 'Jus in Bello' principle of discrimination (non-combatant immunity) strictly requires that:", "Combatants must distinguish between enemy soldiers and innocent civilians, targeting only military objectives.", ["Any citizen of an opposing nation is automatically classified as a legitimate military target.", "Weapons of mass destruction may be deployed to expedite victory.", "Captured prisoners of war must be executed to conserve rations."]),
  ("Bioethics: Organ Transplantation Ethics", "The Dead Donor Rule in organ transplantation bioethics establishes that:", "Vital organs may only be harvested after the formal declaration of death, and harvesting must not cause death.", ["Organs should be auctioned to the highest private bidder.", "Prisoners automatically forfeit organ ownership upon incarceration.", "Physicians may terminate terminally ill patients to retrieve organs for younger recipients."]),
  ("Bioethics: Human Subjects Research (Nuremberg Code)", "The 1947 Nuremberg Code was established primarily in response to Nazi medical atrocities to ensure that:", "Voluntary, fully informed consent of human subjects is absolutely essential in all biomedical research.", ["Military commanders have absolute authority to subject soldiers to scientific testing.", "Scientific researchers are legally immune from criminal prosecution.", "Unapproved experimental drugs can be tested on vulnerable prison populations."]),
  ("Ethics of Technology: Surveillance & Privacy", "A tech platform secretly tracks users' offline geolocation and microphone data to target commercial ads. This practice ethically infringes upon:", "Informational privacy, user autonomy, and transparent consent.", ["Hardware manufacturing intellectual property.", "International telecommunication bandwidth quotas.", "Federal antitrust taxation formulas."]),
  ("Ethics of Journalism: Truthfulness & Verification", "The Society of Professional Journalists (SPJ) Code of Ethics establishes as its primary foundational pillar:", "Seek Truth and Report It—ensuring accuracy, thorough verification, and avoiding misleading framing.", ["Maximize advertising sponsorship revenue at all costs.", "Publish unverified sensational rumors to boost web traffic.", "Shield government officials from critical investigative reporting."]),
  ("Ethics of Public Service: RA 6713", "Republic Act 6713 (Code of Conduct and Ethical Standards for Public Officials) explicitly mandates that public servants must:", "Live modestly, lead modest lives appropriate to their income, and prioritize public interest over personal gain.", ["Display opulent jewelry and luxury vehicles during official functions.", "Accept private corporate gifts in exchange for expedited permits.", "Maintain absolute secrecy regarding all public government expenditures."]),
  ("Ethics of Research: Plagiarism & Fabrication", "A doctoral candidate fabricates laboratory survey results to confirm her hypothesis. This is an egregious violation of:", "Scientific veracity, intellectual integrity, and research honesty.", ["University athletic department dress codes.", "Municipal library book checkout time limits.", "Postal mail packaging regulations."]),
  ("Ethics of Intellectual Property: Fair Use", "Under copyright law and ethical scholarship, the 'Fair Use' doctrine permits the limited use of copyrighted material without permission for:", "Criticism, comment, news reporting, teaching, scholarship, or research.", ["Commercial reproduction and sale of complete textbooks for profit.", "Creating counterfeit commercial merchandise for retail distribution.", "Claiming original authorship over an entire foreign publication."]),
  ("Ethics of Free Speech: Harm Principle", "John Stuart Mill's 'Harm Principle' in On Liberty asserts that the only purpose for which state power can be rightfully exercised over any individual against his will is to:", "Prevent harm to others.", ["Enforce religious conformity across all citizens.", "Promote state economic dominance in foreign markets.", "Shield political leaders from public criticism."]),
  ("Ethics of Climate Change: Precautionary Principle", "The Precautionary Principle in international environmental law and ethics states that:", "Where there are threats of serious or irreversible environmental damage, lack of full scientific certainty should not delay cost-effective preventive measures.", ["Governments must wait for 100% scientific consensus before taking any climate actions.", "Economic industrial growth must never be constrained by environmental regulations.", "Developing nations should bear all costs of rising ocean levels."]),
  ("Ethics of Taxation: Distributive Justice", "From the standpoint of distributive justice, a progressive taxation system is morally justified because:", "Those with greater economic capacity contribute more to support public goods and basic welfare services.", ["It punishes productive citizens to enrich bureaucratic corruption.", "It guarantees that the wealthiest pay zero taxes through corporate loopholes.", "It imposes identical flat peso amounts on the rich and the impoverished."]),
  ("Ethics of Pedagogy: Inclusive Education", "A teacher who adapts instruction, materials, and assessments to accommodate students with diverse physical and cognitive abilities upholds:", "Educational justice, equity, and the universal right of all children to learn.", ["Academic elitism, by lowering standards for the entire class.", "Standardized uniformity, which ignores individual differences.", "Institutional convenience, to reduce grading workload."]),
  ("Ethics of Leadership: Servant Leadership", "Robert Greenleaf's model of 'Servant Leadership' defines the ethical leader as one whose primary motivation is to:", "Serve the legitimate needs of followers and empower them to develop their full potential.", ["Accumulate authoritarian power and demand uncritical personal loyalty.", "Maximize executive bonuses while cutting employee healthcare.", "Protect personal political prestige at all costs."])
])
d.extend([
  ("Ethics of Digital Citizenship: Data Privacy Act", "In the Philippines, Republic Act 10173 (Data Privacy Act of 2012) protects individuals by requiring that personal data processing must adhere to:", "Transparency, Legitimate Purpose, and Proportionality.", ["Secrecy, Commercial Monopolization, and Unlimited Storage.", "Unrestricted Commercial Sale without Consent.", "Mandatory Public Broadcast of Private Financial Records."]),
  ("Ethics of Public Health: Quarantine vs Liberty", "During a deadly pandemic outbreak, mandatory quarantine measures that temporarily restrict individual freedom of movement are ethically justified under:", "The Harm Principle and the collective duty to protect public health and vulnerable lives.", ["The Divine Right of reigning provincial governors.", "The economic profit mandates of commercial pharmaceutical companies.", "The personal convenience of municipal administrative staff."]),
  ("Ethics of Animal Welfare: Peter Singer's Utilitarianism", "Peter Singer argues in Animal Liberation that non-human animals have moral standing because:", "They possess sentience—the capacity to experience pain and pleasure.", ["They possess the ability to read and write formal legal contracts.", "They have immortal souls recognized by civil law.", "They contribute to industrial agricultural gross domestic product."]),
  ("Ethics of Technology: Digital Footprint & Deletion", "The 'Right to be Forgotten' in digital ethics grants individuals the right to:", "Request the removal of outdated, inaccurate, or irrelevant personal information from internet search engines.", ["Erase all national criminal records without judicial review.", "Demand total immunity from all financial credit rating reports.", "Delete public historical records from national archives."]),
  ("Ethics of Pedagogy: Assessment Integrity", "A teacher intentionally alters test scores to make her class appear higher-performing in a division evaluation. This is a violation of:", "Professional integrity, truthfulness, and valid assessment standards.", ["Classroom ventilation architectural regulations.", "Standard school sports uniform color codes.", "Canteen sanitation food preparation guidelines."]),
  ("Moral Philosophy: Psychological Egoism", "Psychological Egoism is an empirical descriptive claim asserting that:", "All human actions are ultimately motivated by self-interest, even acts that appear altruistic.", ["Humans are morally required to sacrifice themselves for strangers at all times.", "Moral virtues are genetically determined by blood type.", "Human actions are guided exclusively by celestial astrological movements."]),
  ("Ethics of AI: Deepfakes & Misinformation", "The creation and distribution of malicious 'Deepfakes' (synthetic media mimicking real people) violates ethics primarily because:", "It manufactures false realities, deceives the public, and severely harms individual reputations without consent.", ["It increases the file size of digital video streaming platforms.", "It uses older computer processors that generate excess heat.", "It consumes standard electrical power from municipal energy grids."]),
  ("Ethics of Education: Teacher as Loco Parentis", "The legal and ethical doctrine of 'In Loco Parentis' imposes upon teachers and school administrators the duty to:", "Exercise parental care, custody, and supervision over students while in their charge.", ["Dictate students' adult career choices and religious affiliations.", "Claim financial ownership over students' family properties.", "Refuse all communication with biological parents regarding student progress."]),
  ("Ethics of Medicine: Palliative Care & Futility", "When further aggressive medical treatment is clinically futile for a dying patient, ethical palliative care focuses on:", "Maximizing comfort, dignity, and pain relief rather than prolonging the dying process.", ["Administering lethal injections to speed up hospital bed turnover.", "Abandoning the patient completely without medical oversight.", "Performing unnecessary high-cost surgeries to increase billing."]),
  ("Ethics of Social Justice: Equity vs Equality", "In public education policy, the ethical difference between 'Equality' and 'Equity' is that:", "Equality provides everyone the exact same resources, while Equity allocates resources based on specific needs to achieve fair outcomes.", ["Equality favors marginalized groups, while Equity treats everyone identically.", "Equality applies only to financial budgets, while Equity applies only to sports.", "Equality is illegal, while Equity is strictly voluntary."]),
  ("Virtue Ethics: Phronesis (Practical Wisdom)", "In Aristotelian philosophy, 'Phronesis' (practical wisdom) is essential for virtuous living because:", "It enables a person to discern the appropriate moral action in complex, concrete situations.", ["It guarantees the automatic accumulation of immense financial wealth.", "It allows an individual to predict future astronomical events with certainty.", "It eliminates the need for human relationships and community life."]),
  ("Ethics of Science: Dual-Use Research", "In bioethics, 'Dual-Use Research of Concern' (DURC) refers to scientific research that:", "Provides legitimate scientific knowledge but could also be directly misapplied to cause severe public health threats.", ["Requires simultaneous funding from both private and public universities.", "Is published in two different languages simultaneously.", "Uses both digital computers and analog microscopes."]),
  ("Professional Ethics: Conflict of Interest Disclosure", "When a member of a curriculum evaluation committee has authored one of the commercial textbooks being evaluated, the ethical protocol is to:", "Disclose the financial conflict of interest and recuse oneself from the evaluation and voting process.", ["Vote aggressively in favor of one's own textbook while concealing authorship.", "Demand that competitors' textbooks be banned without review.", "Resign from the teaching profession permanently."]),
  ("Ethics of Digital Rights: Net Neutrality", "The ethical principle of 'Net Neutrality' asserts that Internet Service Providers (ISPs) must:", "Treat all internet communications and websites equally, without discriminating or charging differently by user or content.", ["Block access to educational websites that offer free tutoring.", "Prioritize traffic only to commercial companies that pay premium fees.", "Censor all political opinions that disagree with telecommunication executives."]),
  ("Virtue Ethics: Eudaimonism vs Hedonism", "Aristotelian Eudaimonism differs from pure Hedonism because Eudaimonism defines a good life by:", "The active realization of rational and moral human excellence, rather than the mere accumulation of bodily pleasures.", ["The total duration of continuous sensory stimulation.", "The avoidance of all intellectual effort and civic duties.", "The accumulation of luxury consumer goods."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item assesses competence in {item[0]}. {item[2]} represents standard ethical analysis and philosophical consensus."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('ethicsExams.ts', 'ETHICS_EXAM_QUESTIONS', questions)
