import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Piaget's Cognitive Stages: Sensorimotor Stage (0-2 years)", "According to Jean Piaget, the hallmark cognitive milestone achieved during the 'Sensorimotor Stage' is:", "Object Permanence (understanding that objects continue to exist even when they cannot be seen, heard, or touched).", ["Conservation of volume and mass.", "Abstract deductive hypothesis testing.", "Animistic thinking and egocentric perspective."]),
  ("Piaget's Cognitive Stages: Preoperational Stage (2-7 years)", "A 4-year-old child believes that the moon follows her when she walks and thinks that pouring water from a wide cup into a tall, thin glass creates 'more water'. This exemplifies:", "Preoperational Stage thinking (Egocentrism, Animism, Centration, and Lack of Conservation).", ["Sensorimotor sensory reflexes.", "Concrete Operational reversibility.", "Formal Operational abstract reasoning."]),
  ("Piaget's Cognitive Stages: Concrete Operational Stage (7-11 years)", "A 9-year-old pupil can correctly order wooden sticks from shortest to longest (Seriation) and understands that flattening a ball of clay does not change its mass (Conservation). Piaget classifies this child in the:", "Concrete Operational Stage (Conservation, Decentration, Reversibility, Seriation, Classification).", ["Preoperational Stage.", "Formal Operational Stage.", "Sensorimotor Stage."]),
  ("Piaget's Cognitive Stages: Formal Operational Stage (11+ years)", "An adolescent student in high school physics designs an experiment to systematically test hypotheses regarding the period of a pendulum, isolating variables logically. Piaget classifies this thinking as:", "Formal Operational Stage (Hypothetico-Deductive Reasoning and Abstract Systematic Logic).", ["Concrete Operational thinking.", "Preoperational thinking.", "Sensorimotor thinking."]),
  ("Piagetian Concepts: Schema, Assimilation, Accommodation, Equilibration", "A toddler sees a four-legged horse for the first time and calls it a 'big doggie'. When her mother explains it is a horse because it has hooves and neighs, the toddler creates a new category for horses. This mental restructuring is:", "Accommodation (modifying existing cognitive schemas or creating new ones to fit novel information).", ["Assimilation (fitting new information into existing unchanged schemas).", "Animism.", "Centration."]),
  ("Vygotsky's Socio-Cultural Theory: Zone of Proximal Development (ZPD)", "Lev Vygotsky defined the 'Zone of Proximal Development' (ZPD) as the distance between:", "What a learner can accomplish independently and what they can achieve with guidance and collaboration from a More Knowledgeable Other (MKO).", ["A child's chronological age and their biological physical height.", "A student's raw test score and the class mean score.", "The physical distance between the teacher's desk and the student's chair."]),
  ("Vygotskian Concepts: Scaffolding (Wood, Bruner, Ross)", "In Vygotskian pedagogy, instructional 'Scaffolding' is best exemplified when a teacher:", "Provides temporary cues, prompts, modeling, and structured hints that are gradually faded out as the learner develops autonomous mastery.", ["Gives the student the complete answer key before the test begins.", "Leaves a struggling student completely alone with zero support.", "Forces all students to listen to an uninterrupted 60-minute lecture."]),
  ("Vygotsky: Private Speech & Internalization", "According to Lev Vygotsky, when young children engage in 'Private Speech' (talking aloud to themselves while solving a difficult puzzle), this speech functions as:", "An essential cognitive self-regulatory tool used to guide their own thinking, planning, and behavior before becoming internalized inner speech.", ["A symptom of severe emotional psychiatric disorder.", "A meaningless biological vocal reflex.", "An act of intentional classroom defiance."]),
  ("Erikson's Psychosocial Stages: Trust vs Mistrust (Infancy)", "According to Erik Erikson's Psychosocial Theory, an infant whose caregivers respond consistently, warmly, and reliably to cries develops the basic virtue of:", "Hope / Basic Trust (feeling safe, secure, and trusting of the world).", ["Autonomy.", "Industry.", "Identity."]),
  ("Erikson's Psychosocial Stages: Autonomy vs Shame and Doubt (Toddlerhood)", "A 2-year-old insists on dressing himself, choosing his own shoes, and feeding himself. Erikson advises parents to support this exploration to develop:", "Autonomy (independence and self-will), avoiding feelings of Shame and Doubt.", ["Basic Mistrust.", "Role Confusion.", "Stagnation."]),
  ("Erikson's Psychosocial Stages: Initiative vs Guilt (Preschool)", "A preschooler loves taking the initiative to plan pretend games, build block towers, and ask countless questions. If harshly scolded and punished for exploring, the child is likely to develop:", "Guilt and fear of taking purposeful initiative.", ["Basic Trust.", "Ego Integrity.", "Generativity."]),
  ("Erikson's Psychosocial Stages: Industry vs Inferiority (Elementary / School Age)", "During elementary school years (ages 6-12), children strive to master academic, social, and physical skills. Experiencing repeated failure, severe criticism, and lack of recognition leads to:", "Feelings of Inferiority (believing oneself to be inadequate and incompetent).", ["Role Confusion.", "Isolation.", "Despair."]),
  ("Erikson's Psychosocial Stages: Identity vs Role Confusion (Adolescence)", "During adolescence, teenagers experiment with different social roles, values, career aspirations, and philosophical beliefs. Successfully resolving this crisis produces:", "A clear, integrated personal Identity and the virtue of Fidelity (loyalty to one's core values).", ["Generativity.", "Basic Mistrust.", "Stagnation."]),
  ("Erikson's Psychosocial Stages: Intimacy vs Isolation (Young Adulthood)", "In young adulthood, individuals face the psychosocial crisis of Intimacy vs Isolation, where success leads to:", "The capacity to form deep, loving, mutually committed, and authentic interpersonal relationships.", ["Total emotional self-absorption and isolation.", "Career burnout and early retirement.", "A complete loss of personal identity."]),
  ("Kohlberg's Moral Development: Level 1 (Pre-Conventional Morality)", "A child says: 'I will not steal the cookie from the jar because if Teacher catches me, I will get sent to time-out.' Kohlberg classifies this reasoning as:", "Pre-Conventional Stage 1: Obedience and Punishment Orientation (avoiding physical punishment).", ["Conventional Stage 3: Good Boy / Nice Girl Orientation.", "Conventional Stage 4: Law and Order Orientation.", "Post-Conventional Stage 6: Universal Ethical Principles."])
]
d.extend([
  ("Kohlberg's Moral Development: Stage 2 (Instrumental Relativist)", "A student agrees to share his coloring markers with a peer only because 'He promised to let me borrow his robot toy later.' This reflects Kohlberg's:", "Pre-Conventional Stage 2: Individualism, Instrumental Purpose, and Exchange ('You scratch my back, I scratch yours').", ["Stage 1: Punishment and Obedience.", "Stage 4: Social-Order Maintaining Morality.", "Stage 5: Social Contract."]),
  ("Kohlberg's Moral Development: Stage 3 (Interpersonal Concordance)", "A teenager refuses to join a shoplifting dare because: 'I want my parents and friends to think I am a good and trustworthy person.' This reasoning exemplifies:", "Conventional Stage 3: 'Good Boy / Good Girl' (Interpersonal Concordance / Conformity to social approval).", ["Stage 1: Punishment.", "Stage 2: Instrumental Exchange.", "Stage 6: Universal Ethical Principles."]),
  ("Kohlberg's Moral Development: Stage 4 (Law and Order)", "A citizen stops at a red traffic light at 3:00 AM on an empty street because: 'Rules and traffic laws must be obeyed by everyone to maintain social order and prevent chaos.' This is:", "Conventional Stage 4: Law and Order / Social System Maintenance Orientation.", ["Stage 2: Instrumental Relativist.", "Stage 3: Good Boy / Good Girl.", "Stage 5: Social Contract."]),
  ("Kohlberg's Moral Development: Level 3 (Post-Conventional / Stage 5)", "In the Heinz Dilemma, a person argues: 'Heinz was justified in stealing the life-saving drug because the human right to life supersedes a commercial patent law, and laws should be amended when they harm basic rights.' This represents:", "Post-Conventional Stage 5: Social Contract and Individual Rights Orientation.", ["Pre-Conventional Stage 1: Punishment.", "Conventional Stage 4: Law and Order.", "Pre-Conventional Stage 2: Market Exchange."]),
  ("Kohlberg's Stage 6: Universal Ethical Principles", "A civil rights activist engages in non-violent civil disobedience against an unjust segregation law, willingly accepting imprisonment because the law violates universal human dignity and justice. This is:", "Post-Conventional Stage 6: Universal Ethical Principles Orientation (Kantian categorical morality).", ["Stage 1: Punishment and Obedience.", "Stage 3: Interpersonal Conformity.", "Stage 4: Fixed Authority."]),
  ("Carol Gilligan's Critique of Kohlberg: Ethic of Care", "Carol Gilligan (*In a Different Voice*) criticized Kohlberg's moral development model for gender bias, proposing that women's moral reasoning is often centered on:", "An 'Ethic of Care' emphasizing interpersonal relationships, empathy, compassion, and preventing harm, rather than abstract justice/rights alone.", ["The pursuit of individual economic dominance.", "Strict military obedience to authoritarian rules.", "Pure mathematical logic without human empathy."]),
  ("Bronfenbrenner's Bioecological Systems: Microsystem", "In Urie Bronfenbrenner's Bioecological Systems Theory, the 'Microsystem' comprises:", "The immediate direct environments that the child interacts with face-to-face daily (family, classroom, peer group, neighborhood).", ["The interactions between two different microsystems (Mesosystem).", "Broad cultural values, laws, and societal ideologies (Macrosystem).", "External settings that indirectly affect the child (Exosystem)."]),
  ("Bronfenbrenner's Bioecological Systems: Mesosystem", "A parent-teacher conference where the teacher and parents collaborate to support a struggling child is an example of which ecological system level?", "Mesosystem (connections, linkages, and interactions between the child's microsystems, such as home and school).", ["Microsystem.", "Exosystem.", "Macrosystem."]),
  ("Bronfenbrenner's Bioecological Systems: Exosystem", "A mother's workplace announces flexible working hours and paid parental leave, which reduces family stress and positively impacts her child's emotional well-being at home. In Bronfenbrenner's model, this is the:", "Exosystem (external environmental settings that the child does not inhabit directly but that profoundly influence their development).", ["Microsystem.", "Mesosystem.", "Chronosystem."]),
  ("Bronfenbrenner's Bioecological Systems: Macrosystem", "The overarching cultural values, national educational legislation (e.g., K to 12 Law), socioeconomic structures, and religious beliefs of a society constitute the:", "Macrosystem (the cultural blueprint and overarching societal ideologies).", ["Microsystem.", "Mesosystem.", "Exosystem."]),
  ("Bronfenbrenner's Bioecological Systems: Chronosystem", "The socio-historical events, technological revolutions (e.g., the rise of the digital smartphone era), and life transitions across the dimension of time represent the:", "Chronosystem (the socio-historical context and temporal dimension of development).", ["Microsystem.", "Exosystem.", "Macrosystem."]),
  ("Freud's Psychosexual Stages: Five Stages in Order", "Sigmund Freud's Psychosexual Theory outlines five developmental stages in which correct chronological sequence?", "Oral (0-1), Anal (1-3), Phallic (3-6), Latency (6-12), and Genital (12+).", ["Anal, Oral, Genital, Phallic, and Latency.", "Sensorimotor, Preoperational, Concrete, and Formal.", "Trust, Autonomy, Initiative, Industry, and Identity."]),
  ("Freud's Phallic Stage: Oedipus & Electra Complexes", "During Freud's Phallic Stage (ages 3-6), the child's primary psychological task is resolving unconscious attachment to the opposite-sex parent and rivalries, resolved through:", "Identification with the same-sex parent (internalizing their values, gender role, and Superego).", ["Fixation on oral thumb-sucking.", "Rigid toilet training battles.", "Sublimating energy into school academics."]),
  ("Howard Gardner's Multiple Intelligences: Bodily-Kinesthetic", "A student who excels in dance choreography, athletic sports, surgical dexterity, and learning best through hands-on physical manipulation of tools possesses high:", "Bodily-Kinesthetic Intelligence.", ["Visual-Spatial Intelligence.", "Musical Intelligence.", "Interpersonal Intelligence."]),
  ("Howard Gardner's Multiple Intelligences: Interpersonal vs Intrapersonal", "While 'Interpersonal Intelligence' involves understanding and effectively interacting with OTHER people's moods and intentions, 'Intrapersonal Intelligence' involves:", "Deep self-awareness of one's own inner emotions, metacognitive strengths, values, and personal goals.", ["Composing complex musical symphonies.", "Navigating geographical topographical maps.", "Solving differential calculus equations."])
])
d.extend([
  ("Gardner's Multiple Intelligences: Naturalist Intelligence", "A student who is fascinated by classifying flora and fauna, recognizing cloud patterns, and understanding ecological interrelationships possesses high:", "Naturalist Intelligence.", ["Linguistic-Verbal Intelligence.", "Logical-Mathematical Intelligence.", "Spatial Intelligence."]),
  ("Robert Sternberg's Triarchic Theory of Intelligence", "Robert Sternberg's Triarchic Theory of Successful Intelligence encompasses which three fundamental components?", "Analytical Intelligence (Componential), Creative Intelligence (Experiential), and Practical Intelligence (Contextual / 'Street Smarts').", ["Fluid Intelligence, Crystallized Intelligence, and General Intelligence.", "Verbal, Mathematical, and Spatial Intelligence.", "Sensorimotor, Preoperational, and Formal Intelligence."]),
  ("Sternberg's Triarchic Theory: Practical Intelligence", "A student who is adept at adapting to new environments, navigating complex social situations, solving real-world everyday problems, and shaping their surroundings exhibits high:", "Practical Intelligence (Contextual dimension / tacit knowledge).", ["Analytical Intelligence.", "Creative Intelligence.", "Fluid Intelligence."]),
  ("Information Processing Theory: Atkinson-Shiffrin Multi-Store Model", "The Atkinson-Shiffrin model of human memory structures information flow through which three memory stores?", "Sensory Memory -> Short-Term / Working Memory -> Long-Term Memory.", ["Input Memory -> Processing Memory -> Output Memory.", "Implicit Memory -> Explicit Memory -> Declarative Memory.", "Sensory Stage -> Concrete Stage -> Formal Stage."]),
  ("Information Processing: Working Memory & Cognitive Load (Sweller)", "John Sweller's Cognitive Load Theory reminds educators that 'Working Memory' has limited capacity (typically $7 \pm 2$ chunks, George Miller). Therefore, effective teachers:", "Break complex lessons into bite-sized 'chunks', eliminate extraneous visual/auditory clutter, and use dual visual-verbal modalities.", ["Present 50 new abstract vocabulary terms in a single continuous 45-minute slide.", "Play loud rock music while showing dense walls of unorganized text.", "Force students to memorize 1,000 pages of text in one night."]),
  ("Information Processing: Long-Term Memory (LTM) Types", "In cognitive psychology, 'Semantic Memory' stores general factual knowledge (e.g., 'Manila is the capital of the Philippines'), while 'Episodic Memory' stores:", "Personally experienced autobiographical events, memories, and life episodes tied to specific times and places.", ["Procedural motor skills like riding a bicycle.", "Sensory retinal visual after-images.", "Short-term phone number rehearsals."]),
  ("Information Processing: Procedural Memory (Implicit)", "Riding a bicycle, typing on a keyboard, or swimming across a pool without conscious step-by-step thinking relies on:", "Procedural Memory (implicit motor skills and conditioned physical habits).", ["Declarative Semantic Memory.", "Episodic Memory.", "Sensory Icon Memory."]),
  ("Metacognition: Flavell's Metacognitive Knowledge", "John Flavell divided Metacognition ('thinking about one's own thinking') into Person Knowledge, Task Knowledge, and:", "Strategy Knowledge (knowing which learning strategies are most effective for solving a specific task and monitoring their use).", ["Curriculum Knowledge.", "Administrative Knowledge.", "Legal Knowledge."]),
  ("Metacognitive Regulation: Planning, Monitoring, Evaluating", "A student reading a biology chapter stops periodically, asks herself: 'Did I understand what that paragraph meant?', and re-reads confusing sections. This student is practicing:", "Metacognitive Monitoring / Self-Regulation of Comprehension.", ["Passive rote memorization.", "Operant behavioral conditioning.", "Sensory decay."]),
  ("Motivation Theories: Maslow's Hierarchy of Needs", "According to Abraham Maslow's Hierarchy of Needs, before a student can focus on intellectual self-actualization, cognitive growth, and academic achievement, the school must ensure:", "Deficiency Needs (Physiological needs for food/sleep, Safety, and Belongingness/Love) are adequately satisfied.", ["The student has purchased an expensive laptop computer.", "The student has won a gold medal in sports.", "The student is ranked first in the class."]),
  ("Motivation Theories: Self-Determination Theory (Deci & Ryan)", "Deci and Ryan's Self-Determination Theory (SDT) asserts that intrinsic motivation and psychological well-being flourish when three basic psychological needs are met:", "Autonomy (choice/agency), Competence (feeling effective), and Relatedness (feeling connected/cared for).", ["Money, Power, and Luxury.", "Rewards, Punishments, and Grades.", "Food, Shelter, and Clothing."]),
  ("Motivation Theories: Weiner's Attribution Theory", "Bernard Weiner's Attribution Theory posits that students maintain high motivation and resilience when they attribute academic failure to:", "Internal, Unstable, and Controllable factors (e.g., 'I need to use more effective study strategies and put in more targeted effort').", ["Internal, Stable, and Uncontrollable factors (e.g., 'I am genetically stupid').", "External, Stable, and Uncontrollable factors (e.g., 'The teacher hated me and the test was impossible').", "Pure random luck and bad horoscope."]),
  ("Motivation Theories: Carol Dweck's Mindset Theory", "A student with a 'Fixed Mindset' believes that intelligence is static and unchangeable, leading to a desire to look smart and avoid challenges. In contrast, a 'Growth Mindset' believes:", "Intelligence and ability can be developed and strengthened through dedication, effective strategies, effort, and learning from mistakes.", ["Talent is 100% determined at birth and can never change.", "Effort is a sign of weakness and stupidity.", "Failure means one should give up immediately."]),
  ("Learning Theories: Bandura's Social Learning Theory (Observational Learning)", "Albert Bandura's famous Bobo Doll experiments established that learning occurs through:", "Observational learning (modeling and imitation) within a social context, involving Attention, Retention, Reproduction, and Motivation.", ["Direct stimulus-response biological conditioning without mental cognition.", "Pure genetic instinctual reflexes.", "Operant trial-and-error physical punishment."]),
  ("Bandura's Triadic Reciprocal Determinism", "In Bandura's Social Cognitive Theory, 'Triadic Reciprocal Determinism' asserts that human functioning is shaped by the continuous dynamic interaction of which three factors?", "Behavior, Personal Cognitive Factors, and the Environmental Context.", ["Id, Ego, and Superego.", "Sensory, Short-Term, and Long-Term Memory.", "Physiological, Safety, and Self-Actualization needs."])
])
d.extend([
  ("Physical Development: Cephalocaudal vs Proximodistal Trends", "In prenatal and infant motor development, the 'Cephalocaudal Trend' describes growth progressing from:", "Head to Tail / Foot (the head and upper body develop control before the lower limbs).", ["Center of the body outward to the extremities (Proximodistal).", "Feet upward to the forehead.", "Left hand to right hand."]),
  ("Physical Development: Proximodistal Trend", "The 'Proximodistal Trend' in child motor development explains why infants can control:", "Their trunk and arm movements before they develop precise fine-motor pincer grasp with their fingers.", ["Their toes before their head.", "Their speech vocal cords before their heart.", "Their ears before their eyes."]),
  ("Adolescent Development: Puberty and Brain Development", "Neuroscientific research shows that during adolescence, the emotional/limbic system (amygdala) matures earlier than the:", "Prefrontal Cortex (responsible for executive function, impulse control, long-term risk evaluation, and planning), explaining adolescent risk-taking.", ["Occipital visual lobe.", "Cerebellar balance center.", "Brainstem respiratory reflex."]),
  ("Adolescent Egocentrism: Imaginary Audience (David Elkind)", "A 14-year-old girl gets a tiny ink stain on her shirt and refuses to attend class, convinced that 'everyone in the school is staring at me and judging me.' This illustrates:", "The 'Imaginary Audience' phenomenon in adolescent egocentrism (David Elkind).", ["The 'Personal Fable'.", "Sensorimotor reflexes.", "Formal operational adult maturity."]),
  ("Adolescent Egocentrism: Personal Fable (David Elkind)", "A teenage boy drives a motorcycle at extreme speeds without a helmet, thinking: 'Accidents happen to other careless people, but I am uniquely special and indestructible.' This exemplifies:", "The 'Personal Fable' (the belief in one's unique invulnerability and distinct destiny).", ["The 'Imaginary Audience'.", "Preoperational animism.", "Concrete operational conservation."]),
  ("Language Development: Noam Chomsky's Nativist Theory (LAD)", "Linguist Noam Chomsky argued that humans are biologically pre-wired for language acquisition through an innate mental mechanism known as the:", "Language Acquisition Device (LAD) and Universal Grammar.", ["Behaviorist Stimulus-Response Habit Loop.", "Operant Reinforcement Conditioning chamber.", "Mechanical Typewriter Keyboard."]),
  ("Language Development: B.F. Skinner's Behaviorist Theory", "In contrast to Chomsky, B.F. Skinner (*Verbal Behavior*) argued that language is acquired primarily through:", "Operant conditioning, environmental reinforcement, imitation, and shaping of vocal sounds.", ["Innate biological genetic language modules.", "Spontaneous divine inspiration.", "Universal Grammar switches in the cerebrum."]),
  ("Language Development: Critical / Sensitive Period Hypothesis (Lenneberg)", "Eric Lenneberg's 'Critical Period Hypothesis' suggests that if a child is not exposed to language during the optimal neurodevelopmental window (infancy to puberty):", "The child will experience severe and potentially permanent deficits in acquiring native grammatical syntax and fluency (as seen in feral children).", ["The child will automatically speak fluent ancient Greek at age 20.", "The child will become a mathematical genius.", "Language acquisition will be unaffected."]),
  ("Language Development Stages: Babbling to Telegraphic Speech", "A 20-month-old toddler points to her mother and says: 'Mommy milk!' and 'Daddy go!' This two-word grammatical utterance is known in child development as:", "Telegraphic Speech (omitting non-essential grammatical words while preserving core meaning).", ["Cooing.", "Canonical Babbling.", "Holophrastic single-word speech."]),
  ("Attachment Theory: John Bowlby & Mary Ainsworth (Strange Situation)", "In Mary Ainsworth's 'Strange Situation' study, an infant with a 'Secure Attachment' typically:", "Explores the room freely in the parent's presence, shows distress when the parent leaves, and is quickly comforted and joyfully re-engages upon the parent's return.", ["Ignores the parent completely and shows zero emotion upon reunion (Insecure-Avoidant).", "Shows intense angry clinging, distress, and resists comfort upon reunion (Insecure-Resistant/Ambivalent).", "Displays disoriented, fearful, freezing behaviors (Disorganized)."]),
  ("Parenting Styles: Diana Baumrind's Four Typologies", "According to Diana Baumrind, which parenting style is characterized by high warmth, open communication, high expectations, and firm, democratic boundary setting?", "Authoritative Parenting (produces the most socially competent, confident, and academically successful children).", ["Authoritarian Parenting (high control, low warmth / 'Because I said so!').", "Permissive / Indulgent Parenting (high warmth, low control / few boundaries).", "Uninvolved / Neglectful Parenting (low warmth, low control)."]),
  ("Parenting Styles: Authoritarian vs Permissive", "A parent who demands absolute obedience, punishes without explanation, and shows little emotional warmth is __________, whereas a parent who is extremely loving but sets zero rules is __________.", "Authoritarian; Permissive.", ["Authoritative; Neglectful.", "Permissive; Authoritative.", "Democratic; Autocratic."]),
  ("Behavioral Learning: Classical Conditioning (Ivan Pavlov)", "In Pavlov's classic conditioning experiments, the ringing bell that initially produced no response, but after repeated pairing with food came to elicit salivation, is the:", "Conditioned Stimulus (CS).", ["Unconditioned Stimulus (UCS / the meat powder).", "Unconditioned Response (UCR / natural salivation to meat).", "Conditioned Response (CR / salivation to the bell)."]),
  ("Behavioral Learning: Operant Conditioning (B.F. Skinner)", "In Operant Conditioning, 'Negative Reinforcement' occurs when a behavior is strengthened and increases in frequency because:", "An unpleasant, aversive stimulus is REMOVED or avoided following the behavior (e.g., buckling a seatbelt to stop an annoying beeping sound).", ["A pleasant reward is added (Positive Reinforcement).", "An unpleasant punishment is administered to decrease behavior (Positive Punishment).", "A privilege is taken away to decrease behavior (Negative Punishment)."]),
  ("Operant Conditioning: Positive vs Negative Punishment", "A teacher assigns a student 30 minutes of campus cleanup duty for cursing (Positive Punishment), and suspends the student's playground recess privileges for talking back (Negative Punishment). The goal of BOTH punishments is to:", "DECREASE the occurrence of the undesired target behavior.", ["Increase the frequency of the behavior.", "Reinforce the behavior positively.", "Build intrinsic motivation."])
])
d.extend([
  ("Schedules of Reinforcement: Skinner's Intermittent Schedules", "Which schedule of intermittent reinforcement produces the highest and most steady rate of response, with the greatest resistance to extinction (as seen in slot machines and unpredictable pop quizzes)?", "Variable Ratio (VR) Schedule.", ["Fixed Interval (FI) Schedule.", "Fixed Ratio (FR) Schedule.", "Variable Interval (VI) Schedule."]),
  ("Thorndike's Laws of Learning: Law of Effect", "Edward Thorndike's 'Law of Effect' states that:", "Behaviors followed by satisfying, positive consequences tend to be repeated, while behaviors followed by discomfort or unpleasant consequences are weakened.", ["Practice alone without feedback makes perfect.", "Learning requires instantaneous biological maturity.", "Students learn best during nighttime sleep."]),
  ("Thorndike's Laws of Learning: Law of Exercise and Readiness", "Thorndike's 'Law of Exercise' asserts that connections between stimulus and response are strengthened with practice, while the 'Law of Readiness' states that:", "Learning is effective only when the learner is biologically, cognitively, and emotionally ready and prepared to act.", ["Learning can be forced onto unprepared students through physical threats.", "Exercise should replace all academic classroom reading.", "Readiness is measured solely by chronological height."]),
  ("Social Development: Parten's Stages of Play in Children", "Mildred Parten identified six stages of social play in early childhood. 'Parallel Play' is when children:", "Play side-by-side with similar toys and materials, observing each other, but without direct interactive collaboration or shared goals.", ["Engage in organized group play with defined rules (Cooperative Play).", "Share materials and converse while working on individual projects (Associative Play).", "Watch other children play without joining in (Onlooker Behavior)."]),
  ("Parten's Stages: Cooperative Play (Highest Level)", "When 5-year-old children work together to build a complex sandcastle, assigning specific roles ('You get the water, I'll build the tower'), they are engaged in:", "Cooperative Play (organized group play with shared goals, rules, and division of labor).", ["Solitary Independent Play.", "Parallel Play.", "Unoccupied Behavior."]),
  ("Emotional Development: Emotional Intelligence (Salovey & Mayer / Goleman)", "Daniel Goleman defines 'Emotional Intelligence' (EQ) as the capacity for:", "Recognizing our own feelings and those of others, motivating ourselves, and managing emotions well in ourselves and our relationships.", ["Manipulating others through false flattery.", "Repressing all feelings to think like a mechanical computer.", "Scoring above 150 on standard Raven's Progressive Matrices."]),
  ("Adolescent Identity: James Marcia's Identity Statuses", "James Marcia categorized adolescent identity formation based on the presence/absence of 'Crisis/Exploration' and 'Commitment'. An adolescent who has explored various career options and made a firm personal commitment is in:", "Identity Achievement.", ["Identity Foreclosure (commitment without personal exploration, adopting parents' wishes blindly).", "Identity Moratorium (active exploration in crisis, but no firm commitment yet).", "Identity Diffusion (no exploration and no commitment; apathy)."]),
  ("Marcia's Identity Statuses: Identity Foreclosure", "A high school graduate enrolls in law school simply because 'My father and grandfather are lawyers, so I was always expected to be one,' without ever exploring her own personal interests. This status is:", "Identity Foreclosure (premature commitment without personal crisis/exploration).", ["Identity Achievement.", "Identity Moratorium.", "Identity Diffusion."]),
  ("Cognitive Development: Jerome Bruner's Three Modes of Representation", "Jerome Bruner proposed that children represent knowledge through three sequential modes:", "Enactive (action-based / hands-on movement), Iconic (image-based / visual graphics), and Symbolic (language / mathematical symbols).", ["Sensory, Motor, and Abstract.", "Concrete, Operational, and Formal.", "Oral, Anal, and Phallic."]),
  ("Bruner: The Spiral Curriculum & Readiness", "Jerome Bruner famously asserted that 'any subject can be taught effectively in some intellectually honest form to any child at any stage of development' through:", "A Spiral Curriculum that introduces basic intuitive concepts enactively/iconically and revisits them later with greater symbolic rigor.", ["Standardized high-stakes multiple-choice testing in kindergarten.", "Forcing elementary pupils to read university graduate dissertations.", "Rote memorization drills with zero visual models."]),
  ("Gestalt Psychology: Principles of Perceptual Organization", "The Gestalt principle of 'Pragnanz' (Law of Simplicity/Good Figure) and closure posits that the human mind naturally:", "Organizes visual sensory perceptions into the simplest, most complete, unified, and coherent whole structures possible ('The whole is greater than the sum of its parts').", ["Processes every single pixel in isolation without connecting patterns.", "Disregards visual boundaries and perceives total chaos.", "Separates colors into chemical molecular compounds."]),
  ("Gestalt Psychology: Wolfgang Kohler's Insight Learning", "In his famous experiments with Sultan the chimpanzee solving problems using suspended bananas and bamboo sticks, Wolfgang Kohler demonstrated 'Insight Learning', which is:", "The sudden, spontaneous cognitive understanding of relationships leading directly to a problem solution ('Aha!' moment).", ["Gradual mechanical trial-and-error stimulus conditioning over 1,000 trials.", "Instinctual genetic reflexes.", "Rote imitation of a trainer."]),
  ("Transfer of Learning: Positive vs Negative Transfer", "When previous learning of the Latin alphabet facilitates learning Spanish vocabulary, it is 'Positive Transfer'; when previous knowledge of driving on the right in the Philippines causes dangerous confusion when driving on the left in Japan, it is:", "Negative Transfer (prior learning interferes with the performance or learning of a new task).", ["Zero Transfer.", "Vertical Transfer.", "Lateral Transfer."]),
  ("Transfer of Learning: Near vs Far Transfer", "Applying basic classroom arithmetic to calculate the cost of groceries at the local sari-sari store is __________, while applying physics momentum principles to design a financial risk algorithm is __________.", "Near Transfer (similar context); Far Transfer (dissimilar, novel context).", ["Far Transfer; Near Transfer.", "Negative Transfer; Positive Transfer.", "Zero Transfer; Absolute Transfer."]),
  ("Child and Adolescent Learner Synthesis: The Holistic Developing Child", "Ultimately, understanding child and adolescent development requires teachers to recognize that learning is:", "An integrated, dynamic process where physical health, cognitive schemas, emotional regulation, and socio-cultural relationships continuously influence one another.", ["A mechanical process of downloading static data into an empty brain.", "Completely determined by genetics with zero environmental influence.", "Identical across all children regardless of culture, age, or readiness."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This question assesses foundational mastery in {item[0]}. {item[2]} represents standard developmental psychology, cognitive science, and child learning principles."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('childAdolescentExams.ts', 'CHILD_ADOLESCENT_EXAM_QUESTIONS', questions)
