import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("21st Century Literacies: Traditional vs Modern Concept of Literacy", "While traditional literacy focused strictly on the basic ability to read, write, and calculate (the 3Rs), 21st-century literacy is reconceptualized as:", "A multimodal, dynamic set of cognitive, digital, socio-cultural, and ethical competencies needed to thrive in a complex, interconnected world.", ["The physical speed of mechanical typing on a keyboard.", "The ability to memorize dictionary definitions word-for-word in silence.", "Strict compliance with ancient monastic recitation codes."]),
  ("Financial Literacy: Core Pillars and Budgeting", "In financial literacy education, what is the foundational rule of sound personal financial management encapsulated in the 'Pay Yourself First' principle?", "Setting aside a fixed percentage of income for savings and emergency investments BEFORE allocating money for living expenses and discretionary spending.", ["Spending entire salary on luxury consumer goods and saving whatever spare coins remain.", "Borrowing high-interest payday loans to finance international vacations.", "Relying entirely on credit card cash advances for daily grocery purchases."]),
  ("Financial Literacy: The 50-30-20 Budgeting Rule (Elizabeth Warren)", "According to the popular 50-30-20 budgeting framework, how should an individual's net income be systematically allocated?", "50% for Needs (essential living costs), 30% for Wants (lifestyle/entertainment), and 20% for Savings, debt repayment, and investments.", ["50% for Luxury Wants, 30% for Gambling, and 20% for Taxes.", "50% for Savings, 30% for Loans, and 20% for Food.", "50% for Housing, 30% for Utilities, and 20% for Clothing only."]),
  ("Financial Literacy: Assets vs Liabilities (Robert Kiyosaki)", "In financial education, how does Robert Kiyosaki (*Rich Dad Poor Dad*) distinguish an 'Asset' from a 'Liability' in practical terms?", "An Asset puts money INTO your pocket (generates passive cash flow/appreciation), while a Liability takes money OUT of your pocket (incurs ongoing expenses).", ["An Asset is anything you purchase on credit, while a Liability is physical cash.", "An Asset is always a brand-new luxury sports car, while a Liability is a university diploma.", "An Asset is cash held in a piggy bank with zero interest."]),
  ("Financial Literacy: Inflation and Purchasing Power", "Why is it financially unwise to keep large sums of long-term savings exclusively in cash or non-interest-bearing checking accounts?", "Because Inflation continuously erodes the real purchasing power of money over time, meaning the cash buys fewer goods in the future.", ["Because commercial paper bank notes decompose into dust within 12 months.", "Because national banks automatically confiscate cash savings annually.", "Because cash money loses its physical weight over time."]),
  ("Financial Literacy: Compound Interest (The Rule of 72)", "The 'Rule of 72' in financial literacy is a rapid mathematical heuristic used to estimate:", "The number of years required to DOUBLE an investment at a given annual fixed compound interest rate (Years = 72 / Interest Rate).", ["The exact monetary price of national real estate properties.", "The percentage of income an individual must pay in income taxes.", "The total number of credit cards a consumer should own."]),
  ("Financial Literacy: Good Debt vs Bad Debt", "In consumer financial literacy, 'Good Debt' differs from 'Bad Debt' because good debt:", "Is an investment that finances an asset or opportunity with potential to increase future net worth or income (e.g., student education, affordable business loan).", ["Carries an annual percentage interest rate exceeding 50% on luxury fashion purchases.", "Is used exclusively to fund impulsive consumer shopping sprees.", "Is borrowed from unregulated illegal loan sharks."]),
  ("Financial Literacy: Ponzi & Pyramid Schemes (Scam Detection)", "A financial investment opportunity promises guaranteed returns of '30% profit every month with zero risk!' A financially literate teacher recognizes this as a classic red flag for:", "A Ponzi / Pyramid Scheme, which relies on funds from newer investors to pay fictitious returns to older investors before inevitable collapse.", ["A secure, legitimate government sovereign treasury bond.", "A standard conservative mutual index fund.", "An accredited commercial savings bank account."]),
  ("Digital / Cyber Literacy: Information Evaluation (CRAAP Test)", "When teaching students to evaluate the credibility of online sources, the 'CRAAP' test evaluates which five core criteria?", "Currency (timeliness), Relevance (importance), Authority (source credentials), Accuracy (verifiability), and Purpose (reason for existence).", ["Clickbait, Resolution, Animation, Audio, and Performance.", "Cost, Revenue, Advertising, Audience, and Profit.", "Cybersecurity, Routing, Algorithms, Analytics, and Programming."]),
  ("Digital Literacy: Online Disinformation vs Misinformation", "In digital media studies, what is the critical distinction between 'Misinformation' and 'Disinformation'?", "Misinformation is false information shared WITHOUT harmful intent, whereas Disinformation is false information DELIBERATELY manufactured to deceive, manipulate, or harm.", ["Misinformation is published in printed books; Disinformation is published online.", "Misinformation is legally permitted; Disinformation is created only by computers.", "Misinformation relates to sports; Disinformation relates to weather."]),
  ("Digital Literacy: Phishing and Social Engineering", "A student receives an SMS message claiming: 'Congratulations! You won Php 500,000 in the DepEd National Raffle! Click this link and send Php 1,000 processing fee to claim.' This is:", "Smishing / Social Engineering fraud designed to steal money and personal credentials.", ["A legitimate scholarship grant notification from the government.", "An authentic promotional lottery from a commercial telecommunication provider.", "A mandatory administrative school fee announcement."]),
  ("Digital Literacy: Two-Factor Authentication (2FA)", "Why is enabling 'Two-Factor Authentication' (2FA) essential for securing educational, banking, and professional email accounts?", "It provides an extra layer of defense by requiring both a password AND a secondary verification method (e.g., SMS code, authenticator app), preventing unauthorized access.", ["It doubles the download speed of broadband internet routers.", "It eliminates the need to remember any password.", "It automatically deletes spam emails from the inbox."]),
  ("Media Literacy: Core Concepts (Center for Media Literacy - CML)", "According to the Center for Media Literacy, which foundational concept reminds students that all media messages are NOT objective reality?", "'All media messages are constructed'—they are carefully crafted by creators using specific codes, conventions, and commercial motives.", ["'Media messages are direct, unfiltered reflections of pure truth.'", "'Television broadcasts are generated entirely by nature without human input.'", "'All news broadcasts are 100% free from any political or economic perspective.'"]),
  ("Media Literacy: Target Audience and Deconstruction", "When media-literate learners 'Deconstruct' a commercial advertisement, they critically analyze:", "Who created the message, what creative techniques were used to capture attention, what values/lifestyles are represented, and what is omitted.", ["Only the physical pixel resolution of the digital video file.", "The type of printing ink used on the magazine cover.", "The brand name of the television monitor displaying the ad."]),
  ("Media Literacy: Algorithmic Filter Bubbles & Echo Chambers", "How do engagement-driven social media recommendation algorithms contribute to political polarization and 'Echo Chambers'?", "By repeatedly feeding users content that reinforces their existing biases and preconceptions, while filtering out opposing, diverse viewpoints.", ["By displaying completely random, neutral international news broadcasts to all users.", "By disconnecting users from the internet after 30 minutes of browsing.", "By forcing all users to read academic peer-reviewed journal articles."])
]
d.extend([
  ("Ecoliteracy: David Orr's Ecological Literacy", "David Orr defined 'Ecological Literacy' (Ecoliteracy) as:", "The fundamental understanding of how Earth's natural life-support systems function, creating citizens who live sustainably within ecological limits.", ["The ability to memorize the Latin taxonomy of 5,000 insect species.", "The commercial extraction of timber from national protected rainforests.", "The construction of concrete parking lots over natural wetlands."]),
  ("Ecoliteracy: Fritjof Capra's Principles of Ecology", "According to physicist Fritjof Capra (Center for Ecoliteracy), which of the following is a core organizational principle of living ecosystems that should guide sustainable human communities?", "Interdependence, Recycling of matter (Zero Waste), Solar Energy, Diversity, and Flexibility/Dynamic Balance.", ["Linear extraction, Monoculture uniformity, and Fossil fuel exploitation.", "Unlimited exponential growth and resource depletion.", "Total isolation of individual biological species."]),
  ("Ecoliteracy: Ecological Footprint (Wackernagel & Rees)", "In environmental education, an individual's 'Ecological Footprint' measures:", "The total amount of biologically productive land and water area required to produce the resources consumed and absorb the wastes generated by that person.", ["The physical size of a person's hiking boots.", "The distance walked by a student between home and school.", "The number of trees planted in a private residential backyard."]),
  ("Ecoliteracy: The 7Rs of Waste Management", "Beyond the traditional '3Rs' (Reduce, Reuse, Recycle), modern ecoliteracy incorporates comprehensive sustainability habits including:", "Rethink, Refuse, Reduce, Reuse, Repurpose, Recycle, and Rot (Compost).", ["Run, Rest, Read, Review, Repeat, Recite, and Reward.", "Rent, Rebuy, Resell, Refund, Reloan, Reinvest, and Redeem.", "React, Reorganize, Restructure, Realign, Re-evaluate, Re-elect, and Reform."]),
  ("Ecoliteracy: Anthropocene & Climate Literacy", "In ecoliteracy curriculum integration, 'Climate Literacy' empowers learners to:", "Understand the human drivers of climate change, evaluate climate risks, and take collective, evidence-based mitigation and adaptation actions in their communities.", ["Deny all meteorological and oceanic scientific data.", "Wait passively for foreign nations to solve local environmental disasters.", "Increase personal consumption of single-use plastic packaging."]),
  ("Multicultural & Global Literacy: Cultural Relativism vs Ethnocentrism", "A globally and multiculturally literate teacher avoids 'Ethnocentrism' by demonstrating that:", "Different cultural traditions, beliefs, and practices must be understood within their own cultural context, treating all cultural identities with dignity and mutual respect.", ["Western European cultures are inherently superior to all indigenous Asian cultures.", "All traditional languages should be replaced by a single global dialect.", "Minority students must completely abandon their cultural heritage to assimilate."]),
  ("Multicultural Literacy: James Banks' Dimensions of Multicultural Education", "James Banks identifies five dimensions of multicultural education. 'Content Integration' involves:", "Using examples and content from a variety of cultures and groups to illustrate key concepts, principles, and theories across subject areas.", ["Teaching about ethnic minorities only during one single holiday week each year.", "Grouping students strictly according to their socioeconomic class.", "Separating classrooms into distinct linguistic tribal divisions."]),
  ("Multicultural Literacy: Banks' Equity Pedagogy", "According to James Banks, 'Equity Pedagogy' exists when teachers:", "Modify their teaching styles and instructional methods to facilitate the academic achievement of students from diverse racial, cultural, gender, and social-class groups.", ["Apply a single, rigid, unbending teaching style that favors only mainstream pupils.", "Lower all academic standards to zero for marginalized learners.", "Assign failing grades automatically to students from minority communities."]),
  ("Global Literacy: Global Competence (PISA / OECD)", "The OECD-PISA Global Competence framework assesses a 21st-century learner's capacity to:", "Examine local and global issues, understand multiple worldviews, engage in respectful intercultural interactions, and take action for collective well-being.", ["Memorize the capital cities and flags of 200 nations without understanding geopolitical relations.", "Speak fluent English with an American accent.", "Win commercial business marketing contracts in overseas markets."]),
  ("Social-Emotional Literacy (SEL): CASEL's Five Core Competencies", "The Collaborative for Academic, Social, and Emotional Learning (CASEL) framework structures SEL around which five interrelated competencies?", "Self-Awareness, Self-Management, Social Awareness, Relationship Skills, and Responsible Decision-Making.", ["Reading, Writing, Mathematics, Science, and Social Studies.", "Id, Ego, Superego, Libido, and Thanatos.", "Speed, Agility, Strength, Endurance, and Flexibility."]),
  ("Social-Emotional Literacy: Social Awareness (Empathy)", "Under the CASEL framework, a student who demonstrates 'Social Awareness' is able to:", "Understand the perspectives of and empathize with others, including those from diverse backgrounds, cultures, and contexts.", ["Manipulate peers' emotions to win classroom elections.", "Avoid all social interaction and isolate oneself in the library.", "Judge classmates strictly based on their physical appearance."]),
  ("Social-Emotional Literacy: Responsible Decision-Making", "When a student faces peer pressure to cheat on an exam, pauses to evaluate ethical standards, safety concerns, and the long-term consequences of his actions before refusing, he demonstrates:", "Responsible Decision-Making (evaluating consequences and ethical considerations).", ["Impulsive reactive behavior.", "Social conformity compliance.", "Moral disengagement."]),
  ("Arts and Creative Literacy: Divergent vs Convergent Thinking (Guilford)", "J.P. Guilford's research on creativity distinguishes 'Divergent Thinking' from 'Convergent Thinking' because divergent thinking involves:", "Generating multiple, unique, varied, and innovative solutions, ideas, or pathways in response to an open-ended challenge.", ["Arriving at a single, predetermined, standardized correct answer.", "Copying an existing artwork brushstroke for brushstroke in complete silence.", "Memorizing mathematical algorithms without understanding."]),
  ("Arts Literacy: The Four Creative Domains (Fluency, Flexibility, Originality, Elaboration - Torrance)", "In E. Paul Torrance's framework of creative thinking, 'Flexibility' is demonstrated when a student:", "Shifts perspectives effortlessly and generates diverse categories of ideas from varied conceptual angles.", ["Generates a large quantity of nearly identical ideas.", "Adds intricate, fine decorative details to an existing drawing.", "Copies an idea directly from a peer's notebook."]),
  ("Functional Literacy: Meaning and Societal Impact", "According to UNESCO, 'Functional Literacy' is defined as the capability of an individual to:", "Engage in all those activities in which literacy is required for effective functioning in one's group, workplace, and community, and for continuing personal development.", ["Sign one's name on an identification card but be unable to read instructions on a medicine bottle.", "Read simple nursery rhymes aloud without understanding the meaning.", "Memorize the letters of the alphabet in order."])
])
d.extend([
  ("Critical Literacy: Paulo Freire's 'Reading the Word and the World'", "Paulo Freire (*Pedagogy of the Oppressed*) founded 'Critical Literacy', asserting that true literacy involves:", "'Reading the world'—critically analyzing underlying power dynamics, systemic inequalities, ideologies, and biases embedded in texts, and taking action for social justice.", ["Passively absorbing printed words as unquestionable sacred facts ('Banking Concept').", "Memorizing grammar rules without ever discussing societal problems.", "Pronouncing words with perfect phonetic precision while ignoring the meaning."]),
  ("Critical Literacy: Questioning Authorial Stance", "When critically literate students read a historical newspaper report on a labor union strike, they ask:", "'Whose voices and perspectives are centered, whose voices are silenced, what interests are served by this framing, and what is the underlying ideology?'", ["'How many adjectives are in the first sentence?'", "'What is the price of the newspaper at the newsstand?'", "'What font size was used by the graphic typesetter?'"]),
  ("Information Literacy: The Big6 Information Problem-Solving Model (Eisenberg & Berkowitz)", "The 'Big6' information literacy model structures research skills into six stages: Task Definition, Information Seeking Strategies, Location and Access, Use of Information, Synthesis, and:", "Evaluation (assessing the product's effectiveness and the research process).", ["Distribution to commercial bookstores.", "Printing on high-gloss photo paper.", "Deleting all source files from computers."]),
  ("Media Literacy: Clickbait & Sensation Detection", "An online headline reads: 'Shocking! You Will Never Believe What This Celebrity Did!' A media-literate person identifies this as:", "Clickbait—sensationalized, hyperbolic phrasing designed to exploit emotional curiosity and generate advertising pageviews, often with low-substance content.", ["An objective, verified investigative journalism report.", "A legally certified national court announcement.", "A peer-reviewed scientific discovery paper."]),
  ("Cyber Literacy: Cyberbullying & Online Harassment", "Under Republic Act 10627 (Anti-Bullying Act of 2013), 'Cyberbullying' in school contexts is defined as:", "Any bullying done through the use of technology or any electronic means (social media, messaging, texting) that causes physical, emotional, or psychological harm.", ["Playing an online educational multiplayer math game with friends.", "Submitting an assignment via email to a teacher before the deadline.", "Sending a calendar invite for a school club meeting."]),
  ("Ecoliteracy: Biodiversity & Biophilic Design in Schools", "Integrating 'Biophilic Design' and school garden ecosystems into the campus environment enhances ecoliteracy by:", "Fostering students' innate biological connection to nature (Biophilia), improving mental well-being, and providing hands-on experiential science labs.", ["Replacing all green grass with synthetic asphalt parking spaces.", "Cutting down all campus shade trees to build billboard structures.", "Confining all students to windowless concrete classrooms."]),
  ("Financial Literacy: Emergency Fund Essentials", "In personal financial literacy, financial planners recommend that an individual build an 'Emergency Fund' consisting of:", "3 to 6 months' worth of essential living expenses kept in a liquid, easily accessible savings account for unexpected crises (e.g., medical emergency, job loss).", ["100% of all life savings invested in volatile cryptocurrency meme tokens.", "Buying 10 lottery tickets every morning.", "Purchasing luxury jewelry with high-interest credit card debt."]),
  ("Financial Literacy: Credit Card Literacy (APR & Minimum Due)", "Paying ONLY the 'Minimum Amount Due' on a credit card statement each month is a dangerous financial mistake because:", "The remaining unpaid balance incurs high compounding interest charges, prolonging debt repayment for decades and multiplying total costs exponentially.", ["The credit card company will immediately cancel all bank accounts.", "The bank will confiscate the consumer's university diploma.", "The credit card becomes physically heavier in one's wallet."]),
  ("Multicultural Literacy: Microaggressions in the Classroom", "In multicultural education, 'Microaggressions' refer to:", "Subtle, brief, often unintentional everyday verbal, behavioral, or environmental indignities that communicate hostile or derogatory slights to marginalized groups.", ["Physical fistfights between large gangs of students.", "Formal academic debates organized by the school debate society.", "Standardized written examination scoring errors."]),
  ("Multicultural Literacy: Culturally Sustaining Pedagogy (Paris)", "Django Paris' 'Culturally Sustaining Pedagogy' builds beyond culturally relevant teaching by arguing that schools must:", "Explicitly sustain and foster linguistic, cultural, and artistic practices of communities of color and indigenous peoples, rather than merely using culture as a bridge to assimilate.", ["Force all students to adopt a single standardized corporate dialect.", "Eradicate all indigenous cultural practices from classroom curricula.", "Teach only the history of Western European imperial empires."]),
  ("Social-Emotional Literacy: Restorative Circles in SEL", "Implementing 'Restorative Circles' in the classroom fosters social-emotional literacy by:", "Providing a safe, structured, egalitarian space where every student has a voice to build community, share feelings, resolve conflicts, and repair relational harm.", ["Publicly shaming and isolating students who receive low quiz scores.", "Allowing the loudest students to shout down quieter peers.", "Administering silent individual multiple-choice exams."]),
  ("Social-Emotional Literacy: Growth Mindset & Neuroplasticity (Dweck)", "Teaching students that the human brain can form new neural connections through effort, practice, and learning from failure (Neuroplasticity) fosters:", "A Growth Mindset, boosting resilience, self-efficacy, and academic persistence.", ["A Fixed Mindset of permanent personal helplessness.", "Instantaneous photographic memory without studying.", "The complete elimination of the need for classroom instruction."]),
  ("Arts and Creative Literacy: Design Thinking Process (Stanford d.school)", "The five iterative stages of the 'Design Thinking' problem-solving process in creative literacy are:", "Empathize (understand user needs), Define (state problem), Ideate (brainstorm solutions), Prototype (create sample), and Test (evaluate with users).", ["Memorize, Recite, Write, Grade, and Dismiss.", "Plan, Budget, Hire, Build, and Terminate.", "Lecture, Drill, Quiz, Exam, and Graduate."]),
  ("Creative Literacy: Cross-Disciplinary STEAM Education", "STEAM education integrates 'Arts' (A) into traditional STEM (Science, Technology, Engineering, Math) subjects primarily to:", "Foster creative divergent problem-solving, aesthetic human-centered design, and innovation in scientific and technological applications.", ["Eliminate all science experiments in favor of watercolor painting only.", "Make math exams easier by removing all numbers.", "Replace engineering blueprints with abstract finger paintings."]),
  ("Critical Media Literacy: Deepfakes and Algorithmic Manipulation", "To prepare students for an era of generative AI and 'Deepfakes', critical media literacy curricula must train learners to:", "Triangulate information across multiple independent, verified sources, inspect metadata, examine provenance, and practice lateral reading.", ["Believe every video seen on social media as unquestionable proof.", "Completely stop using all forms of technology and internet.", "Assume that all news from all sources in world history is 100% fake."])
])
d.extend([
  ("Digital Literacy: Lateral Reading (Wineburg & McGrew)", "Sam Wineburg's research at Stanford showed that professional fact-checkers evaluate online information using 'Lateral Reading', which means:", "Immediately opening multiple new browser tabs to research the credibility, funding, and reputation of the source BEFORE reading the article.", ["Reading the article from top to bottom very slowly and carefully on a single tab (Vertical Reading).", "Checking the graphic beauty and color scheme of the website's logo.", "Trusting the website because it has an official-sounding '.org' domain."]),
  ("Digital Literacy: Netiquette & Professional Online Boundaries", "A teacher who maintains professional digital boundaries and adheres to netiquette will:", "Use official school communication channels (e.g., DepEd email, Google Classroom) for academic interactions and avoid informal private messaging with pupils on personal social accounts.", ["Add all students as personal friends on private social media accounts to gossip.", "Share confidential faculty room meetings on public TikTok videos.", "Post negative personal complaints about struggling students online."]),
  ("Ecoliteracy: Circular Economy vs Linear Economy", "In modern sustainability literacy, how does a 'Circular Economy' fundamentally differ from a traditional 'Linear Economy' (Take-Make-Waste)?", "A Circular Economy designs out waste and pollution, keeps products and materials in high-value use through repair/recycling, and regenerates natural systems.", ["A Circular Economy produces 100% single-use plastic waste that is thrown into rivers.", "A Circular Economy requires burning all industrial machinery every 5 years.", "A Circular Economy is restricted to circular wooden buildings."]),
  ("Ecoliteracy: Indigenous Knowledge Systems and Practices (IKSP)", "Recognizing IKSP in ecoliteracy acknowledges that indigenous communities (such as the Bontoc/Ifugao *payyo* rice terrace stewards or Mangyan foresters):", "Possess sophisticated, time-tested ecological knowledge, sustainable resource management practices, and deep cultural reverence for ecosystems.", ["Lack any understanding of nature and must be taught from scratch.", "Destroy biodiversity through unsustainable commercial clear-cutting.", "Never interact with natural biological resources."]),
  ("Financial Literacy: Insurance & Risk Management", "In personal finance, the primary economic purpose of purchasing Life, Health, or Property 'Insurance' is to:", "Transfer the financial risk of catastrophic, unpredictable loss to an insurance company in exchange for regular premium payments, protecting family financial security.", ["Guarantee that a person will never suffer a physical illness.", "Make an individual instantly wealthy like winning a lottery.", "Evade all municipal property taxes legally."]),
  ("Financial Literacy: Investment Diversification (Asset Allocation)", "The fundamental investment principle 'Do not put all your eggs in one basket' refers to:", "Diversification—spreading investments across diverse asset classes (stocks, bonds, real estate, cash) to minimize overall portfolio risk.", ["Buying stock shares in only one single company with 100% of savings.", "Hiding physical cash in multiple locations inside a mattress.", "Investing exclusively in one speculative startup business."]),
  ("Financial Literacy: PhilHealth, SSS, and GSIS in the Philippines", "In the Philippine workforce, public school teachers are mandatorily covered by the Government Service Insurance System (GSIS) and PhilHealth, which provide:", "Social security protections including retirement pensions, disability compensation, life insurance, and universal health coverage subsidies.", ["Free luxury international travel flights annually.", "Private corporate stock options in foreign multinational tech firms.", "Automatic exemptions from all electricity utility bills."]),
  ("Multicultural Literacy: Acculturation vs Assimilation", "In cultural anthropology and literacy education, 'Acculturation' differs from 'Assimilation' because acculturation involves:", "Adopting aspects of a new culture while maintaining one's original cultural identity and heritage (cultural biculturalism / synthesis).", ["Completely abandoning and erasing one's native cultural heritage, language, and customs to blend indistinguishably into the dominant culture.", "Refusing to interact with any other human beings outside one's village.", "Living in complete geographical isolation."]),
  ("Multicultural Literacy: Culturally Responsive Assessment", "When designing assessments for a culturally diverse classroom, a teacher demonstrates multicultural literacy by:", "Using authentic scenarios, diverse cultural contexts, and multiple expression formats that do not penalize students for cultural or linguistic differences.", ["Using standardized testing questions based exclusively on high-income elite urban lifestyle experiences.", "Docking points whenever a student mentions their indigenous heritage.", "Requiring all students to answer questions in 18th-century Elizabethan English."]),
  ("Social-Emotional Literacy: Emotional Regulation (The RULER Approach)", "The Yale Center for Emotional Intelligence 'RULER' approach to social-emotional literacy teaches students to:", "Recognize, Understand, Label, Express, and Regulate emotions effectively in personal and academic life.", ["Repress, Underestimate, Lock away, Eliminate, and Reject all emotions.", "React, Utter, Lash out, Escalate, and Repeat anger.", "Read, Underline, Learn, Examine, and Recite vocabulary."]),
  ("Social-Emotional Literacy: Fixed vs Growth Mindset in Failure", "When an eighth-grade student receives a low score on a science project, a teacher cultivating a Growth Mindset responds by saying:", "'This project was challenging, but mistakes show where we can learn. Let's analyze what strategies didn't work and try a new approach.'", ["'You are just not naturally smart at science; maybe you should give up.'", "'Don't worry, some people are born geniuses and others are not.'", "'This low score proves you will never succeed in high school.'"]),
  ("Arts Literacy: Aesthetic Experience (Maxine Greene)", "Philosopher Maxine Greene (*Releasing the Imagination*) argued that arts literacy and aesthetic education are essential because they:", "Awaken the human imagination to perceive the world 'as if it could be otherwise', fostering empathy, social critique, and transformation.", ["Teach students how to manufacture cheap commercial wall decorations.", "Force students to memorize rigid classical drawing formulas without personal expression.", "Prepare students to work in automated manufacturing assembly lines."]),
  ("Creative Literacy: SCAMPER Brainstorming Technique (Eberle)", "The 'SCAMPER' creative thinking mnemonic for generating innovative ideas stands for:", "Substitute, Combine, Adapt, Modify/Magnify, Put to other uses, Eliminate, and Reverse/Rearrange.", ["Standardize, Calculate, Analyze, Measure, Program, Execute, and Review.", "Structure, Create, Align, Manage, Protect, Evaluate, and Record.", "Study, Copy, Apply, Memorize, Practice, Examine, and Repeat."]),
  ("Critical Literacy: Unpacking Dominant Ideologies", "Critical literacy empowers learners to recognize that texts (such as history textbooks or corporate advertisements) often:", "Reflect the dominant ideological perspectives, political interests, and socioeconomic priorities of the groups that created them.", ["Are direct, neutral transmissions of divine absolute truth.", "Are generated automatically by physical atmospheric weather patterns.", "Contain zero perspective, bias, or subjective point of view."]),
  ("Functional Literacy in 21st Century Society: Multiliteracies Pedagogy", "The New London Group's 'Pedagogy of Multiliteracies' asserts that 21st-century education must equip learners to navigate:", "Multiple modes of meaning-making (linguistic, visual, audio, gestural, spatial, and multimodal) across diverse cultural contexts.", ["Only traditional printed monospaced black-and-white text.", "Solely mechanical oral pronunciation drills.", "Purely silent individual memorization of Latin vocabulary lists."])
])
d.extend([
  ("Global Literacy: Global Interdependence and Supply Chains", "A globally literate student analyzing why an international maritime disruption in the Suez Canal increases local food prices in Manila understands the concept of:", "Global Interdependence (the complex, interconnected economic, environmental, and trade linkages binding all nations).", ["Total National Economic Isolationism.", "Magical Mystical Synchronicity.", "Unrelated Random Coincidence."]),
  ("Digital Citizenship: Cyber Hygiene Habits", "Practicing robust 'Cyber Hygiene' includes which of the following essential daily habits?", "Using strong, unique passwords with a password manager, updating software/patches regularly, and recognizing unverified links/attachments.", ["Using the password '123456' for all banking and email accounts.", "Connecting to unencrypted public Wi-Fi to enter credit card details without VPN.", "Sharing master login passwords on social media message boards."]),
  ("Ecoliteracy: Climate Justice and Vulnerability", "In environmental literacy, the concept of 'Climate Justice' highlights the moral reality that:", "Vulnerable developing nations (like the Philippines) contribute the least to global greenhouse gas emissions yet suffer the most severe climate disasters.", ["Developed nations should be exempt from all international environmental treaties.", "Small island states are physically responsible for 100% of global industrial carbon smog.", "Climate change is an economic myth invented by renewable energy companies."]),
  ("Financial Literacy: The Time Value of Money (TVM)", "The foundational financial concept 'Time Value of Money' (TVM) establishes that:", "A peso available today is worth MORE than the identical peso received in the future, because today's peso can earn interest or be invested to grow.", ["Money loses 100% of its value every 24 hours.", "Money received in 50 years is always worth ten times more than money today.", "Time and money have zero mathematical relationship."]),
  ("Multicultural Literacy: Language Rights and Mother Tongue", "Under international human rights conventions and multicultural literacy frameworks, preserving and validating a child's indigenous home language in school is essential because:", "Language is the living vessel of culture, identity, and cognitive heritage; respecting it validates the child's humanity and boosts academic success.", ["Children should be punished whenever they speak their native dialect.", "Indigenous languages must be eliminated to achieve national uniformity.", "Speaking multiple languages causes brain damage."]),
  ("Social-Emotional Literacy: Relationship Skills (Active Empathy)", "When resolving a bitter peer dispute between two classmates, a student demonstrating high 'Relationship Skills' will:", "Listen attentively to both perspectives without interrupting, validate feelings, communicate clearly, and seek a collaborative win-win compromise.", ["Take sides immediately based on who is more physically popular.", "Encourage the students to engage in a physical fight.", "Ignore the conflict completely and walk away laughing."]),
  ("Arts and Creative Literacy: Creative Risk-Taking and Safe Failure", "A classroom climate that nurtures arts and creative literacy is one where:", "Mistakes and failed prototypes are celebrated as natural, necessary stepping stones for learning, iteration, and breakthrough innovation.", ["Any mistake is immediately met with harsh public humiliation and grade deductions.", "Students are forced to strictly copy the teacher's artwork with zero personal variation.", "Creativity is strictly banned in favor of silent textbook transcription."]),
  ("Critical Literacy: Recognizing Bias and Stereotyping in Media", "When reading a textbook that depicts women exclusively in subordinate domestic cleaning roles and men exclusively in executive corporate roles, a critically literate student will:", "Critique the gender stereotyping and historical bias, questioning why diverse real-world roles are omitted.", ["Accept the depiction as the only natural and eternal truth of human society.", "Assume that women are legally prohibited from holding executive positions.", "Ignore the text because pictures have no meaning."]),
  ("Information Literacy: Primary Source Triangulation", "In academic research, 'Triangulation' involves:", "Cross-verifying factual claims, data, and evidence across multiple independent, diverse primary and secondary sources to ensure accuracy and objectivity.", ["Drawing a physical three-sided geometric triangle on the title page of a thesis.", "Relying exclusively on a single unverified blog post for an entire dissertation.", "Deleting all sources that disagree with one's personal preconceived opinion."]),
  ("Functional Literacy: Document Literacy (Interpreting Charts & Graphs)", "In functional literacy assessments (e.g., adult literacy surveys), 'Document Literacy' specifically tests the ability to:", "Locate, interpret, and use information contained in complex non-prose formats such as tables, schedules, maps, pay slips, and nutritional labels.", ["Memorize Shakespearean sonnets word-for-word in old English.", "Write calligraphy with a fountain pen.", "Calculate the speed of light in a vacuum."]),
  ("Media Literacy: The Power of Visual Rhetoric (Framing and Cropping)", "A photograph of a public rally cropped closely on three shouting individuals makes the event appear violent, whereas a wide-angle shot shows 10,000 peaceful citizens holding candles. A media-literate person realizes:", "Visual framing, cropping, and camera angles are deliberate rhetorical choices that construct specific narratives and emotional impressions.", ["Photographs are always 100% objective and can never mislead the viewer.", "The wide-angle photograph is illegal under copyright law.", "Camera lenses physically alter the reality of human nature."]),
  ("Digital Literacy: Net Neutrality and Digital Equity", "Why is the preservation of 'Net Neutrality' a critical digital literacy and social justice issue?", "Because it ensures Internet Service Providers must treat all data equally, preventing wealthy corporations from monopolizing high-speed digital access over public educational content.", ["Because it makes the internet physically free of charge for all commercial banks.", "Because it blocks all educational websites permanently.", "Because it limits daily internet access to 10 minutes per household."]),
  ("Ecoliteracy: Sustainable Consumption and Zero Waste Lifestyle", "A school community practicing ecoliteracy initiates a 'Zero-Waste Campus' by:", "Banning single-use plastics, institutionalizing waste segregation, establishing organic composting, and maintaining drinking water refill stations.", ["Burning all plastic wrappers in open bonfires behind classrooms.", "Dumping all school cafeteria food waste into the local municipal river.", "Purchasing 5,000 disposable plastic cups every morning."]),
  ("Financial Literacy: Understanding Credit Scores and FICO", "In modern financial systems, maintaining a high 'Credit Score' is important because it:", "Demonstrates a reliable history of debt repayment, enabling an individual to qualify for lower interest rates on home mortgages and business loans.", ["Proves that an individual has zero money in any bank account.", "Automatically exempts the consumer from all income tax liabilities.", "Guarantees a permanent government employment position."]),
  ("21st Century Literacy Synthesis: The Empowered Global Citizen", "Ultimately, building and enhancing new literacies across the curriculum aims to develop learners who are:", "Critically conscious, financially prudent, digitally responsible, ecologically mindful, multiculturally empathetic, and creatively empowered lifelong citizens.", ["Passive, unquestioning consumers of commercial marketing and political propaganda.", "Rote memorizers who can only repeat textbook definitions without real-world application.", "Isolated individuals with zero empathy for their communities or the planet."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item evaluates competence in {item[0]}. {item[2]} represents established 21st-century literacies theory, digital citizenship standards, and evidence-based educational practice."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('buildingLiteraciesExams.ts', 'BUILDING_LITERACIES_EXAM_QUESTIONS', questions)
