import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Sociological Theories: Structural-Functionalism (Durkheim & Parsons)", "According to Structural-Functionalism, education serves society primarily by:", "Transmitting shared social values, maintaining social order and equilibrium, and sorting individuals into occupational roles based on merit.", ["Perpetuating class conflict and economic exploitation of the working class (Conflict Theory).", "Constructing subjective personal realities through micro-level daily labeling.", "Overthrowing the constitutional government through revolution."], "Structural-Functionalism (Emile Durkheim, Talcott Parsons) views society as an interrelated system where schools function to socialize youth, transmit shared norms, and preserve societal stability."),
  ("Sociological Theories: Conflict Theory (Marx & Bowles/Gintis)", "Conflict theorists (such as Karl Marx, Samuel Bowles, and Herbert Gintis in Schooling in Capitalist America) argue that schools:", "Reproduce socioeconomic inequalities, maintain the dominance of the ruling elite, and reinforce capitalist class stratification through unequal schooling.", ["Provide equal, unbiased meritocratic opportunities for all citizens to rise equally.", "Function in complete harmony with zero social tensions or power struggles.", "Exist solely to teach ancient classical Latin literature."], "Conflict Theory posits that educational institutions reflect and reproduce societal power imbalances, unequal wealth distribution, and capitalist class structures through the hidden curriculum and tracking."),
  ("Sociological Theories: Symbolic Interactionism (Mead & Blumer)", "Symbolic Interactionism analyzes education at the micro-level, focusing on how:", "Daily social interactions, interpersonal symbols, language, teacher expectations, and labeling shape students' self-concept and academic behavior.", ["Macro-economic international trade agreements dictate school building construction.", "Biological genetic instincts control 100% of human classroom behavior.", "Global climate change alters textbook printing machinery."], "Symbolic Interactionism (George Herbert Mead, Herbert Blumer) examines micro-level face-to-face interactions, meaning-making, shared symbols, and the powerful psychological effects of teacher labeling and expectations."),
  ("Sociological Concepts: The Pygmalion Effect (Self-Fulfilling Prophecy)", "In classroom sociology, the 'Pygmalion Effect' (Rosenthal & Jacobson) demonstrates that when teachers hold high academic expectations for their students:", "Students internalize these positive expectations, resulting in significantly higher academic achievement and enhanced self-efficacy.", ["Students rebel and intentionally fail their examinations.", "Students develop severe physical illnesses.", "Teacher expectations have zero measurable effect on student outcomes."], "The Pygmalion Effect proves that teacher expectations act as self-fulfilling prophecies—students tend to perform in alignment with the positive or negative expectations communicated by their teachers."),
  ("Sociological Concepts: Cultural Capital (Pierre Bourdieu)", "French sociologist Pierre Bourdieu introduced the concept of 'Cultural Capital' to describe:", "The non-financial social assets (e.g., academic knowledge, language codes, cultural tastes, mannerisms, aesthetic credentials) that give elite students educational advantages.", ["The total physical monetary currency stored in a family's safe.", "The physical weight of machinery in an industrial manufacturing plant.", "The real estate property title deeds of school campuses."], "Cultural Capital refers to cultural knowledge, linguistic fluency, prestigious cultural habits, and educational credentials inherited from families that schools reward and validate, perpetuating social reproduction."),
  ("Sociological Concepts: Social Capital (James Coleman & Putnam)", "In educational sociology, 'Social Capital' refers to:", "The social networks, relationships of mutual trust, community reciprocity, and institutional connections that support a student's learning and opportunities.", ["The financial cash balance in a student's bank account.", "The speed of a computer processor in the school library.", "The physical strength of classroom desks and chairs."], "Social Capital refers to the valuable social resources, supportive interpersonal networks, trust, and shared norms embedded in family, school, and community relationships that facilitate achievement."),
  ("School Culture vs School Climate", "While 'School Climate' refers to the current, felt psychological atmosphere and morale of the school ('the school's personality/mood'), 'School Culture' refers to:", "The deep-seated, enduring values, beliefs, traditions, rituals, and unwritten shared assumptions that shape institutional behavior over time.", ["The daily meteorological weather and temperature outside the school building.", "The physical paint color of the administrative office walls.", "The specific brand of computers purchased by the school."], "School Climate is the immediate, experiential tone and morale of the school; School Culture consists of the deeper, historically rooted shared norms, values, traditions, and core beliefs that guide daily school life."),
  ("Organizational Leadership: Transformational Leadership (Bass & Burns)", "A school principal who inspires teachers with a shared moral vision, encourages intellectual innovation, models integrity, and provides individualized coaching is practicing:", "Transformational Leadership (Idealized Influence, Inspirational Motivation, Intellectual Stimulation, Individualized Consideration).", ["Transactional Leadership (strictly trading rewards and punishments for routine compliance).", "Laissez-Faire Leadership (completely abandoning all leadership responsibility).", "Authoritarian Autocratic Leadership (ruling through fear and strict command)."], "Transformational Leadership (Bernard Bass, James MacGregor Burns) elevates and inspires followers to achieve extraordinary outcomes by transforming their values, vision, and intrinsic commitment."),
  ("Organizational Leadership: Instructional Leadership (Hallinger)", "An 'Instructional Leader' (such as an effective master teacher or school head) focuses primarily on:", "Directly improving classroom teaching and learning, supervising curriculum delivery, analyzing student assessment data, and fostering teacher professional development.", ["Sitting in an air-conditioned office signing administrative purchase orders all day.", "Managing exclusively the physical security gates and cafeteria supply logistics.", "Punishing students publicly during morning flag assemblies."], "Instructional Leadership directly focuses on the core business of schooling: curriculum implementation, pedagogical quality, classroom observation, data analysis, and teacher coaching."),
  ("Organizational Leadership: Distributed Leadership (Spillane)", "James Spillane's 'Distributed Leadership' framework conceptualizes school leadership not as the heroic act of a single individual, but as:", "A dynamic, shared practice distributed across multiple leaders (principals, master teachers, department chairs) interacting in complex school situations.", ["A rigid dictatorship where only the principal makes every single decision.", "A complete absence of any leadership, resulting in total organizational chaos.", "Hiring private commercial corporations to manage public schools."], "Distributed Leadership recognizes that leadership practice is stretched across multiple individuals, tools, and social situations throughout the school organization."),
  ("Organizational Leadership: Servant Leadership (Robert Greenleaf)", "Robert Greenleaf's 'Servant Leadership' philosophy asserts that the great leader is one who:", "Prioritizes serving the needs of others (teachers, students, community) first, empowering their growth, well-being, and autonomy.", ["Demands absolute obedience and personal praise from all subordinates.", "Maximizes personal wealth and executive prestige above all else.", "Exercises authoritarian police control over the faculty room."], "Servant Leadership flips the traditional pyramid: the leader's primary motivation is to serve others, cultivate trust, listen empathetically, and foster the holistic growth of community members."),
  ("Governance of Basic Education: Republic Act 9155", "Republic Act 9155 (Governance of Basic Education Act of 2001) fundamentally restructured Philippine education governance by:", "Institutionalizing the principle of 'School-Based Management' (SBM), decentralizing decision-making authority to the school level where learning actually happens.", ["Centralizing all daily classroom lesson decisions in the national cabinet secretary's office.", "Abolishing all local school divisions and regional offices.", "Privatizing all public basic education schools in the country."], "RA 9155 decentralizes educational management, establishing the school as the core educational unit and empowering School Heads with instructional and administrative leadership under School-Based Management (SBM)."),
  ("School-Based Management (SBM) & School Governing Council (SGC)", "Under DepEd's School-Based Management (SBM) framework, the School Governing Council (SGC) functions as:", "A multi-stakeholder advisory body (teachers, parents, local government, community leaders, alumni) that collaboratively plans and monitors the School Improvement Plan (SIP).", ["A judicial court that prosecutes teachers in criminal trials.", "A private business corporation that charges admission fees to school events.", "A partisan political party campaign committee."], "The SGC serves as a collaborative, democratic platform uniting internal and external stakeholders to formulate the School Improvement Plan (SIP) and ensure transparency and community ownership."),
  ("Child Protection Policy: DepEd Order 40, s. 2012", "Under DepEd Order 40, s. 2012 (DepEd Child Protection Policy), which of the following is strictly and absolutely prohibited in all Philippine schools?", "Corporal punishment, cruel/degrading humiliation, bullying, exploitation, and any form of physical, sexual, or emotional violence against children.", ["Giving constructive formative feedback on written essay assignments.", "Rewarding students with certificates of academic excellence.", "Conducting parent-teacher conferences to discuss student attendance."], "DepEd Order 40, s. 2012 mandates a zero-tolerance policy against corporal punishment, physical violence, verbal/psychological abuse, bullying, and sexual exploitation of learners."),
  ("Child Protection: Corporal Punishment Prohibition", "A teacher makes a Grade 6 pupil stand under the scorching midday sun for 45 minutes with arms raised while holding heavy books because the pupil was talking in class. This action is:", "An illegal act of severe Corporal Punishment and Child Abuse, violating DepEd Order 40, s. 2012 and RA 7610, subjecting the teacher to administrative and criminal liability.", ["A valid and commendable traditional disciplinary technique.", "A standard physical education conditioning exercise.", "Permitted if the teacher notified the parent via text message."])
]
d.extend([
  ("Code of Ethics for Professional Teachers: Legal Authority (RA 7836 & Board Res. 435)", "The Code of Ethics for Professional Teachers was promulgated by the Board for Professional Teachers pursuant to the provisions of:", "Republic Act 7836 (Philippine Teachers Professionalization Act of 1994), as amended by RA 9293.", ["Republic Act 6713 (Code of Conduct and Ethical Standards for Public Officials).", "Republic Act 10533 (Enhanced Basic Education Act).", "Presidential Decree 1006 (Decree Professionalizing Teaching)."]),
  ("Code of Ethics: Article II (The Teacher and the State)", "Under Article II, Section 5 of the Code of Ethics, a teacher as an individual citizen has the full constitutional right to vote and exercise political rights, BUT:", "Shall not use one's official position or authority to influence, coerce, or solicit political support for any partisan political candidate.", ["Must run for public political office every 3 years.", "Is prohibited from voting in national presidential elections.", "Must force all enrolled students to join a specific political party."]),
  ("Code of Ethics: Article III (The Teacher and the Community)", "Article III mandates that the teacher is a facilitator of learning and the development of the youth; therefore, the teacher shall:", "Actively participate in community civic activities, maintain harmonious community linkages, and serve as an intellectual and moral leader in the community.", ["Refuse to speak to any community members outside classroom hours.", "Live in complete geographical isolation from the local community.", "Use school community meetings to sell personal commercial merchandise."]),
  ("Code of Ethics: Article IV (The Teacher and the Profession)", "Under Article IV, Section 1, every teacher shall actively help insure that teaching is the noblest profession, and shall manifest genuine pride in it by:", "Upholding highest professional standards, pursuing continuous personal and professional development (CPD), and honoring professional commitments.", ["Discouraging young people from ever becoming teachers.", "Publicly criticizing and defaming the teaching profession in the media.", "Selling pirated lesson plans for personal financial profit."]),
  ("Code of Ethics: Article V (The Teacher and the Higher Authorities)", "Under Article V, a teacher shall maintain a professional relationship with higher authorities in the Philippines. In expressing professional grievances, the teacher shall:", "Channel grievances through established, formal administrative procedures and official hierarchy rather than through anonymous slander or public malice.", ["Post defamatory insults against school heads on public social media forums.", "Stage violent protests inside school classrooms during instructional hours.", "Refuse to communicate with any school supervisor permanently."]),
  ("Code of Ethics: Article VI (The Teacher and the Higher Authorities/Colleagues)", "Under Article VI, a teacher shall hold inviolate all confidential information concerning associates and the school, and shall:", "Refuse to make false claims, spread malicious gossip, or undermine a colleague's professional standing or opportunities for advancement.", ["Steal a colleague's lesson materials and present them as one's own.", "Report false administrative complaints against peers to get a promotion.", "Spread unverified rumors about a colleague's private personal life."]),
  ("Code of Ethics: Article VIII (The Teacher and the Learners)", "Under Article VIII, Section 1, a teacher has the professional duty to recognize that the interest and welfare of learners are of first and primary concern, and shall:", "Deal justly and impartially with each student, avoiding favoritism, prejudice, or discrimination based on gender, race, or socioeconomic status.", ["Give highest grades only to students whose parents give expensive gifts.", "Show favoritism to students who share the teacher's religious affiliation.", "Refuse to teach students from low-income families."]),
  ("Code of Ethics: Article VIII (Financial Transactions with Learners)", "Article VIII, Section 4 explicitly dictates that a teacher shall NOT:", "Accept gifts, favors, or compensation from learners or their parents in exchange for requested concessions, higher grades, or academic favors.", ["Conduct free after-school remedial tutoring for struggling learners.", "Provide constructive feedback on student project drafts.", "Congratulate students on academic achievements during class."]),
  ("Code of Ethics: Article VIII (Romantic Relationships with Learners)", "Under Article VIII, Section 7, if mutual attraction and subsequent romantic love develop between a teacher and a student, what is the teacher's ethical duty?", "Exercise utmost professional discretion, avoid all favoritism or scandal, and transfer the student to another class/teacher to maintain professional objectivity.", ["Date the student openly inside the classroom during instructional hours.", "Give the student an automatic grade of 100% on all exams.", "Force the student to keep the relationship a secret under threat of failing grades."]),
  ("Code of Ethics: Article X (The Teacher and Business)", "Article X, Section 1 permits a teacher to engage in legitimate business activities, PROVIDED that:", "Such business endeavors do not conflict with or impair the teacher's official duties and efficiency, and school hours are strictly observed.", ["The teacher forces students to buy snacks and school supplies directly from the teacher's personal store.", "The teacher sells commercial beauty products during official classroom teaching hours.", "The teacher uses school laboratory equipment for private manufacturing businesses."]),
  ("Code of Ethics: Article XI (The Teacher as a Person)", "Article XI, Section 1 states that a teacher is, above all, a human being endowed with life for which it is the highest obligation to live with:", "Dignity, moral integrity, self-respect, and temperance, serving as a role model of noble character in both private and public life.", ["Flamboyant luxury, reckless spending, and public drunkenness.", "Arrogant superiority over non-educated community members.", "Complete indifference to societal moral standards."]),
  ("Gender and Development (GAD) in Education", "The Philippine Gender and Development (GAD) policy in basic education (mandated under RA 9710 Magna Carta of Women) aims to:", "Promote gender equality, eliminate sexist stereotypes in textbooks and curricula, and ensure equal educational opportunities for all genders.", ["Enforce rigid traditional gender roles in vocational classes (e.g., girls in cooking, boys in carpentry).", "Exclude women from taking leadership roles in student government.", "Abolish all sports programs for female learners."]),
  ("Gender Sensitivity in Classroom Pedagogy", "Which of the following teacher practices reflects 'Gender-Responsive and Sensitive Pedagogy'?", "Using gender-fair language, encouraging both boys and girls to pursue STEM careers, and ensuring equal participation and leadership in all class activities.", ["Calling only on male students to answer challenging math problems while asking female students to clean the board.", "Telling a crying male student: 'Stop crying like a girl!'", "Assuming female students are naturally bad at physical sports."]),
  ("Peace Education: Pillars of Positive Peace (Johan Galtung)", "Renowned peace scholar Johan Galtung distinguishes 'Negative Peace' (the mere absence of direct physical violence/war) from 'Positive Peace', which is:", "The presence of social justice, equity, human rights, ecological sustainability, and the structural absence of systemic oppression.", ["The complete military conquest and subjugation of a neighboring country.", "A society ruled by fear under an authoritarian military police regime.", "A temporary 24-hour ceasefire during an active civil war."]),
  ("Peace Education: Conflict Resolution in Schools", "Teaching 'Conflict Resolution' and peer mediation skills in school empowers students to:", "De-escalate interpersonal conflicts constructively through active listening, non-violent communication, empathy, and collaborative problem solving.", ["Engage in physical fistfights behind the school gymnasium.", "Use online cyberbullying to retaliate against disagreements.", "Conform blindly to peer pressure without expressing thoughts."])
])
d.extend([
  ("Community Linkages: Brigada Eskwela & Adopt-a-School Program (RA 8525)", "The annual DepEd 'Brigada Eskwela' (National Schools Maintenance Week) exemplifies authentic community engagement by:", "Mobilizing parents, alumni, local businesses, civic groups, and LGUs to volunteer time, labor, and resources to prepare school facilities safely before classes open.", ["Forcing parents to pay mandatory monetary cash penalties if they do not attend.", "Hiring expensive private multinational construction contractors.", "Using student child labor during class hours to build school buildings."]),
  ("Community Linkages: Parent-Teacher Associations (PTA)", "Under DepEd Order 54, s. 2009, the Parent-Teacher Association (PTA) is organized primarily to:", "Foster collaborative partnerships between parents and teachers to support school programs, student welfare, and academic achievement.", ["Act as a commercial profit-generating business enterprise.", "Interfere directly with teacher hiring, promotional rankings, and professional curriculum choices.", "Collect unauthorized, exorbitant membership dues by withholding student report cards."]),
  ("Local Government Code: Special Education Fund (SEF)", "Under Republic Act 7160 (Local Government Code of 1991), the 'Special Education Fund' (SEF) is generated from an additional 1% tax on real property and allocated by the Local School Board (LSB) to:", "Finance school building construction/repair, instructional materials, educational research, and sports development in local public schools.", ["Fund partisan political campaign election rallies for municipal mayors.", "Pay luxury travel bonuses for city councilors.", "Subsidize private commercial shopping malls."]),
  ("Local School Board (LSB) Composition (RA 7160)", "In a municipality, the Local School Board (LSB) is co-chaired by the Municipal Mayor and the:", "District Supervisor (DepEd).", ["Chief of Police.", "Municipal Health Officer.", "President of the Chamber of Commerce."]),
  ("School Culture: Professional Learning Communities (PLCs)", "In a school with a strong culture of collaboration, teachers participate in 'Professional Learning Communities' (PLCs / LAC Sessions) to:", "Collaboratively analyze student learning data, share effective pedagogical strategies, reflect on classroom challenges, and improve student achievement.", ["Complain about administrative salaries and spread faculty gossip.", "Grade standardized test sheets in complete isolation without speaking.", "Plan partisan political campaigns for local elections."]),
  ("DepEd Learning Action Cells (LAC): DepEd Order 35, s. 2016", "Under DepEd Order 35, s. 2016, a School-Based Learning Action Cell (LAC) functions as:", "A continuous professional development strategy where groups of teachers engage in collaborative learning sessions to address specific pedagogical and learner needs.", ["A formal disciplinary tribunal that punishes underperforming teachers.", "A social dining club for faculty celebrations.", "A standardized testing center for student licensure."]),
  ("Teacher Leadership: Teacher as a Community Change Agent", "A teacher who organizes an adult literacy and livelihood training workshop for out-of-school youth in the local barangay on weekends exemplifies:", "The teacher as a community leader and transformational social change agent.", ["A teacher violating professional workload boundaries.", "An unauthorized commercial business vendor.", "A teacher neglecting official classroom instructional duties."]),
  ("Indigenous Peoples Education (IPEd): DepEd Order 62, s. 2011", "Under the National Indigenous Peoples Education Policy Framework (DepEd Order 62, s. 2011), basic education in IP communities must:", "Respect, protect, and fulfill indigenous peoples' rights to culturally rooted, mother-tongue-based, and community-partnered education that preserves cultural heritage.", ["Eradicate indigenous languages and force immediate assimilation into urban Western culture.", "Exclude indigenous elders from having any voice in the school curriculum.", "Ban traditional indigenous dress and music from school grounds."]),
  ("Multiculturalism in Schools: Combating Xenophobia & Prejudice", "When a newly transferred ethnic minority student is bullied by peers for wearing traditional cultural clothing, the teacher's immediate and pedagogical response should be to:", "Enforce the Anti-Bullying Policy, support the targeted student, and use the opportunity to teach the entire class about cultural diversity, empathy, and mutual respect.", ["Tell the minority student to stop wearing traditional clothes to avoid trouble.", "Ignore the bullying because teasing is a natural part of childhood.", "Blame the minority student for provoking classmates."]),
  ("Sociological Concepts: Social Stratification & Social Mobility", "In the sociology of education, 'Social Mobility' refers to:", "The movement of individuals or families between different socioeconomic strata or social classes, often facilitated by access to quality education.", ["The physical movement of students walking between classrooms.", "The relocation of a school building to a different province.", "The daily transportation of pupils on school buses."]),
  ("Sociological Concepts: Meritocracy in Education", "A 'Meritocratic' education system is theoretically based on the ideal that:", "Educational rewards, academic advancement, and opportunities are distributed strictly based on an individual's demonstrated talent, effort, and achievement.", ["Grades and graduation honors are inherited through aristocratic family wealth.", "Students are tracked into careers based on their skin color or gender.", "Academic degrees are purchased through monetary bribes."]),
  ("School Culture: Toxic vs Positive School Culture (Peterson & Deal)", "According to Kent Peterson and Terrence Deal, a 'Toxic School Culture' is characterized by:", "Fragmented relationships, blame, cynicism, resistance to change, lack of shared mission, and low expectations for student achievement.", ["High teacher collaboration, joyful celebration of student growth, and continuous innovation.", "Supportive mentoring for new teachers and strong community partnerships.", "Transparent communication and shared instructional vision."]),
  ("Leadership Styles: Situational Leadership (Hersey & Blanchard)", "Paul Hersey and Kenneth Blanchard's 'Situational Leadership' theory posits that effective leaders adapt their leadership style based on:", "The Readiness and Developmental Maturity level of the followers (competence and commitment) for a specific task.", ["The physical height and age of the school principal.", "The astrological zodiac signs of faculty members.", "The monetary market price of national government bonds."]),
  ("Organizational Change: Kotter's 8-Step Change Model", "In John Kotter's 8-Step Process for Leading Change in organizations, what is the very FIRST crucial step?", "Create a Sense of Urgency (highlighting the pressing need for change and the risks of inaction).", ["Form a strategic vision.", "Celebrate short-term wins.", "Anchor new approaches in the culture."]),
  ("Code of Ethics: Professional Dignity and Social Media Ethics", "Under the Code of Ethics and Civil Service rules, a professional teacher on social media must:", "Maintain professional decorum, uphold the dignity of the profession, protect student privacy, and avoid spreading unverified fake news or defamatory attacks.", ["Post confidential student report cards and test failure lists on public Facebook walls.", "Engage in vulgar, abusive arguments with parents in public comments.", "Use school time to create monetized dance videos inside classrooms with students."])
])
d.extend([
  ("Magna Carta for Public School Teachers: Republic Act 4670", "Under Section 13 of Republic Act 4670 (Magna Carta for Public School Teachers), a teacher engaged in actual classroom instruction shall NOT be required to render more than:", "Six (6) hours of actual classroom teaching a day (the remaining 2 hours devoted to lesson prep, grading, and administrative duties).", ["Eight (8) hours of non-stop classroom lecturing without any breaks.", "Twelve (12) hours of continuous teaching per day.", "Fourteen (14) hours including mandatory weekend manual labor."]),
  ("RA 4670: Additional Compensation for Overtime", "Under Section 14 of RA 4670, if a public school teacher renders more than six hours of actual classroom teaching per day, the teacher is entitled to:", "Additional compensation of at least 25% of their regular remuneration for the excess hours.", ["A Certificate of Recognition without any monetary compensation.", "Free lunch in the school cafeteria for 1 week.", "An automatic promotion to school principal within 24 hours."]),
  ("RA 4670: Study Leave Privileges", "Under Section 24 of RA 4670, public school teachers who have rendered at least seven years of continuous service are entitled to a 'Study Leave' for up to:", "One school year with at least 60% of their regular monthly salary.", ["Five continuous years with 100% full pay and travel allowances.", "One month with zero pay.", "Two weeks during summer vacation only."]),
  ("RA 4670: Indefinite Sick Leave", "Section 25 of RA 4670 guarantees that when the nature of a teacher's illness demands a long treatment exceeding one year, the teacher shall be entitled to:", "An Indefinite Leave of Absence with job security and health protections.", ["Immediate termination of employment without medical benefits.", "An immediate fine deducted from remaining salary.", "Mandatory transfer to a remote mountain school."]),
  ("RA 4670: Academic Freedom in Higher Education", "Under Section 12 of RA 4670 and the 1987 Philippine Constitution, teachers in higher education institutions are guaranteed 'Academic Freedom', which protects their right to:", "Conduct research, teach, and publish scholarly findings without fear of political censorship, reprisal, or ideological interference.", ["Refuse to teach any classes while demanding full salary.", "Impose personal religious dogma on students without academic foundation.", "Cancel all student examinations permanently."]),
  ("Code of Ethics: Teachers and Remedial Classes for Fee", "Under Article VIII, Section 5 of the Code of Ethics, a teacher shall NOT:", "Accept remuneration or fees for tutoring or remedial teaching of one's OWN regular students.", ["Provide free after-school remedial help to struggling pupils in one's class.", "Refer a student to professional medical specialists when needed.", "Encourage students to form peer study groups."]),
  ("Code of Ethics: Professional Evaluation of Student Work", "Under Article VIII, Section 6, the evaluation of the learner's work and achievement shall be based on:", "Merit, quality of performance, and objective academic standards, free from personal bias or external pressure.", ["The social status and political influence of the student's family.", "The amount of financial donations the student's parents make to the school.", "The teacher's personal subjective mood on the day of grading."]),
  ("Code of Ethics: Intellectual Honesty & Plagiarism in Teaching", "Under the Code of Ethics and professional standards, a teacher who submits an action research paper copied entirely from a colleague's thesis commits:", "Gross intellectual dishonesty and professional misconduct, violating ethics and subjecting the teacher to revocation of license (PRC).", ["A minor clerical oversight with zero consequences.", "A legitimate application of open educational resources.", "An act of commendable professional efficiency."]),
  ("DepEd Child Protection: Positive and Non-Violent Discipline", "In contrast to corporal punishment, DepEd's 'Positive and Non-Violent Discipline' framework teaches children self-control and responsibility through:", "Clear expectations, age-appropriate logical consequences, emotional coaching, problem-solving dialogue, and reinforcing positive behaviors.", ["Screaming insults, public humiliation, and isolation in dark rooms.", "Physical slapping, pinching, and forced kneeling on salt.", "Depriving pupils of water, food, and restroom access."]),
  ("Anti-Bullying Act: Republic Act 10627", "Under RA 10627 (Anti-Bullying Act of 2013), all elementary and secondary schools are legally mandated to:", "Adopt and implement comprehensive anti-bullying policies, establish a Child Protection Committee, and investigate and address all bullying incidents.", ["Expel 100% of all students involved in any verbal dispute without investigation.", "Cover up and conceal all bullying incidents from parents and DepEd authorities.", "Encourage victims of bullying to retaliate with physical violence."]),
  ("Safe Spaces Act: Republic Act 11313", "Under Republic Act 11313 (Safe Spaces Act / Bawal Bastos Law), gender-based sexual harassment in educational and training institutions is strictly prohibited, holding school heads liable if they:", "Fail to promptly investigate, act upon, and address reported sexual harassment complaints in the institution.", ["Report sexual harassment cases to law enforcement agencies.", "Provide counseling and psychological support to victims.", "Establish transparent grievance mechanisms."]),
  ("Peace Education: Non-Violent Communication (Marshall Rosenberg)", "Marshall Rosenberg's 'Non-Violent Communication' (NVC) framework trains educators and students to communicate through four components:", "Observations (concrete facts), Feelings (emotional state), Needs (universal human values), and Requests (actionable, clear asks).", ["Accusations, Demands, Threats, and Punishments.", "Opinions, Judgments, Labels, and Demands.", "Silent treatment, Sarcasm, Gossip, and Passive-aggression."]),
  ("School Culture: Rituals, Traditions, and Ceremonies", "School traditions such as graduation commencement, moving-up ceremonies, foundation day celebrations, and awards convocations build positive school culture by:", "Reinforcing shared institutional values, building community pride, celebrating growth, and creating a sense of collective belonging.", ["Wasting valuable instructional time with zero educational value.", "Forcing parents to spend all their life savings on luxury costumes.", "Creating opportunities for teachers to publicly insult struggling students."]),
  ("Community Engagement: School-Community Partnerships (Epstein's Framework)", "Joyce Epstein's framework identifies six types of family-community involvement: Parenting, Communicating, Volunteering, Learning at Home, Decision Making, and:", "Collaborating with the Community (coordinating resources and services with community businesses, agencies, and civic groups).", ["Collecting commercial tuition taxes from local markets.", "Replacing school administrators with barangay councilors.", "Banning community members from ever stepping foot on campus."]),
  ("Organizational Climate: Halpin and Croft's Open vs Closed Climate", "In Andrew Halpin and Don Croft's classic organizational climate framework, an 'Open School Climate' is characterized by:", "High teacher morale, high professional intimacy, supportive/open principal leadership, and low hindrance/bureaucratic frustration.", ["High teacher disengagement, high aloofness of the principal, suspicion, and low morale (Closed Climate).", "Strict military authoritarian rule where teachers cannot speak.", "Total absence of any educational goals or structure."])
])
d.extend([
  ("School Culture: Schein's Three Levels of Organizational Culture", "Edgar Schein conceptualizes organizational culture across three levels: Artifacts (visible structures/processes), Espoused Beliefs and Values, and:", "Basic Underlying Assumptions (unconscious, taken-for-granted beliefs, habits of perception, and deep values).", ["Written Lesson Plans.", "Classroom Whiteboards.", "School Building Bricks."]),
  ("Teacher Accountability: Public Accountability & Transparency", "Under RA 6713 and professional standards, a teacher demonstrates public accountability by:", "Managing school resources ethically, grading transparently, communicating student progress honestly, and rendering public service with integrity.", ["Keeping all grading calculations secret from students and parents.", "Using school supplies for personal home use.", "Refusing to explain curriculum goals to community members."]),
  ("Leadership in Education: Democratic vs Autocratic Leadership (Lewin)", "Kurt Lewin's classic leadership experiments demonstrated that 'Democratic Leadership' in schools produces:", "Higher group morale, stronger long-term commitment, collaborative problem solving, and sustained engagement even in the leader's absence.", ["Immediate rebellion and chaos in 100% of cases.", "Lower academic achievement than strict military dictatorship.", "A complete collapse of all organizational communication."]),
  ("Educational Sociology: The Role of Mass Media in Socialization", "In contemporary educational sociology, mass media and social media act as powerful secondary socializing agents that:", "Influence values, shape youth identity, disseminate cultural trends, and impact political awareness both constructively and critically.", ["Have zero psychological or cognitive effect on youth development.", "Completely replace the biological need for human families.", "Operate purely as passive radio transmitters without societal influence."]),
  ("Community Linkages: Disaster Risk Reduction and Management (DRRM)", "Under Republic Act 10121 (Philippine Disaster Risk Reduction and Management Act), schools must establish a School DRRM Committee to:", "Conduct earthquake/fire drills, maintain contingency plans, ensure student physical safety, and coordinate with the Barangay DRRM Council during disasters.", ["Refuse to evacuate during severe volcanic eruptions.", "Prohibit students from learning about typhoon safety.", "Use school disaster funds to purchase personal luxury gifts."]),
  ("School Environment: Child-Friendly School System (CFSS)", "DepEd's 'Child-Friendly School System' (CFSS) is founded on which core characteristics?", "Gender-sensitive, child-centered, inclusive, safe and protective, promoting child health and community participation.", ["Strictly punitive, authoritarian, competitive, and exclusionary.", "High-cost, elitist, private, and profit-driven.", "Standardized, rigid, monotonous, and teacher-centric."]),
  ("Code of Ethics: Professional Growth (CPD Act of 2016 - RA 10912)", "Under Republic Act 10912 (Continuing Professional Development Act of 2016), professional teachers are required to earn CPD credit units to:", "Continuously upgrade competencies, stay abreast of modern educational research, and maintain professional licensure with the PRC.", ["Pay luxury taxes directly to private commercial corporations.", "Purchase expensive real estate properties.", "Qualify for early retirement at age 25."]),
  ("Social Dimensions: Globalization and Global Education", "In the social dimensions of education, 'Global Education' seeks to develop learners who understand:", "Global interconnectedness, ecological stewardship, cultural empathy, international peace, and human rights in an interdependent world.", ["Only the narrow tribal politics of their immediate village.", "How to exploit developing nations for commercial corporate profit.", "Why foreign languages should be banned from all schools."]),
  ("Teacher-Parent Communication: Effective Conferences", "During a parent-teacher conference regarding a struggling student, an ethical and effective teacher will:", "Begin with the student's positive strengths, share objective assessment data clearly, listen empathetically to parents, and co-create an action plan for support.", ["Attack and blame the parents for the student's low test scores.", "Compare the student unfavorably to high-performing classmates.", "Demand cash payment from parents before discussing the report card."]),
  ("School Leadership: Emotional Intelligence in Leadership (Goleman)", "Daniel Goleman's research on leadership demonstrates that highly effective school leaders possess high 'Emotional Intelligence' (EQ), characterized by:", "Self-awareness, self-regulation, motivation, empathy, and adept social relationship management.", ["Authoritarian aggression and cold emotional detachment.", "An IQ score above 200 without any empathy for human feelings.", "Physical intimidating dominance during faculty meetings."]),
  ("Sociology of Education: Education as an Agent of Social Change", "How does education function as an 'Agent of Social Change' rather than merely an agent of social preservation?", "By fostering critical consciousness, challenging oppressive status quos, promoting scientific innovation, and cultivating democratic values.", ["By forcing all citizens to obey outdated superstitious traditions without questioning.", "By preventing any technological or scientific advancement.", "By preserving feudal class exploitation forever."]),
  ("Professional Teacher Identity: Professionalism and Dedication", "A licensed professional teacher demonstrates true 'Professionalism' when she:", "Consistently exhibits competence, moral integrity, ethical conduct, dedication to student learning, and continuous self-reflection in all endeavors.", ["Teaches only when a school supervisor is watching inside the room.", "Arrives late every day and leaves before the final bell rings.", "Uses teaching solely as a temporary stepping stone to personal fame."]),
  ("Code of Ethics: Teacher's Relationship with the School Head", "Under the Code of Ethics, when a teacher receives an official administrative policy directive from the School Principal that the teacher disagrees with, the teacher should:", "Professionally discuss concerns through proper channels, seek collegial dialogue, and comply with legitimate administrative policies in good faith.", ["Stage a public smear campaign on social media against the principal.", "Order students to boycott the principal's office.", "Refuse to teach any classes until the principal is fired."]),
  ("DepEd Child Protection: Cyber-Safety and Child Abuse Reporting", "If a teacher discovers that a student is being subjected to sexual harassment, exploitation, or severe online abuse, the teacher's immediate legal duty is to:", "Report the incident immediately to the School Child Protection Committee and designated authorities in accordance with child protection protocols.", ["Keep the abuse a secret to avoid damaging the school's public reputation.", "Wait until the end of the school year before mentioning it to anyone.", "Tell the child that they must have deserved the abuse."]),
  ("Synthesis of Social Dimensions: The Teacher as a Nation Builder", "Ultimately, in Philippine society and educational philosophy, the teacher is revered as a 'Nation Builder' because the teacher:", "Nurtures the minds, character, civic virtues, and competencies of the next generation of democratic citizens and leaders.", ["Manufactures industrial military weaponry in factories.", "Collects commercial taxes for international foreign banks.", "Enforces political authoritarian decrees with armed power."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item evaluates knowledge in {item[0]}. {item[2]} represents standard educational sociology, leadership theory, RA 9155, and the Code of Ethics for Professional Teachers."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('socialDimensionsExams.ts', 'SOCIAL_DIMENSIONS_EXAM_QUESTIONS', questions)
