import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Assessment Types: Diagnostic Assessment", "At the very beginning of the school year, Teacher Sarah administers a pre-test to determine students' specific prerequisite misconceptions, skill gaps, and learning deficits in algebra. This is a:", "Diagnostic Assessment (identifying specific learning difficulties and gaps prior to instruction).", ["Summative Assessment.", "Placement Assessment.", "Formative Assessment."]),
  ("Assessment Types: Placement Assessment", "A university administers a standardized entrance exam to determine whether an incoming freshman should be placed in Remedial English, General English, or Advanced Creative Writing. This is a:", "Placement Assessment (determining student entry level and appropriate instructional program).", ["Formative Assessment.", "Diagnostic Assessment.", "Summative Assessment."]),
  ("Assessment Types: Formative Assessment (Assessment FOR Learning)", "During a science lesson on genetics, Teacher Mark asks students to write down on a whiteboard the genotype ratio of a Punnett square and display it. He notices 40% of the class made an error and immediately pauses to re-explain. This is:", "Formative Assessment / Assessment FOR Learning (monitoring learning during instruction to adjust teaching).", ["Summative Assessment (Assessment OF Learning).", "Assessment AS Learning.", "High-stakes Accountability Testing."]),
  ("Assessment Types: Summative Assessment (Assessment OF Learning)", "At the end of the quarterly grading period, a school administers a 50-item comprehensive departmental examination to evaluate student overall achievement and assign report card grades. This is:", "Summative Assessment / Assessment OF Learning (evaluating final achievement for grading and certification).", ["Diagnostic Assessment.", "Formative Assessment.", "Placement Assessment."]),
  ("Assessment Types: Assessment AS Learning (Metacognition)", "When students use scoring rubrics to self-assess their own essay drafts, track their learning goals in reflection journals, and monitor their own cognitive progress, they engage in:", "Assessment AS Learning (fostering metacognitive self-assessment and self-regulation).", ["Assessment OF Learning.", "Assessment FOR Learning.", "Diagnostic Assessment."]),
  ("DepEd Grading System: DepEd Order 8, s. 2015", "Under DepEd Order 8, s. 2015 (Policy Guidelines on Classroom Assessment for K to 12), what are the three official assessment components used to compute quarterly grades across learning areas?", "Written Work (WW), Performance Tasks (PT), and Quarterly Assessment (QA).", ["Attendance, Homework, and Final Exam.", "Classroom Cleanliness, Decorum, and Recitation.", "Notebooks, Uniform Compliance, and Quizzes."]),
  ("DepEd Grading Weight Distribution (DepEd Order 8, s. 2015)", "In Grade 1 to 10 Languages, AP, and EsP, what is the official percentage weight distribution of Written Work (WW), Performance Tasks (PT), and Quarterly Assessment (QA)?", "Written Work = 30%, Performance Tasks = 50%, Quarterly Assessment = 20%.", ["WW = 40%, PT = 40%, QA = 20% (Math & Science distribution).", "WW = 20%, PT = 60%, QA = 20% (MAPEH & EPP/TLE distribution).", "WW = 50%, PT = 25%, QA = 25%."]),
  ("DepEd Grading: Math & Science Weight Distribution", "In Grade 1 to 10 Mathematics and Science, what is the official percentage weight allocation under DepEd Order 8, s. 2015?", "Written Work = 40%, Performance Tasks = 40%, Quarterly Assessment = 20%.", ["Written Work = 30%, Performance Tasks = 50%, Quarterly Assessment = 20%.", "Written Work = 20%, Performance Tasks = 60%, Quarterly Assessment = 20%.", "Written Work = 10%, Performance Tasks = 70%, Quarterly Assessment = 20%."]),
  ("DepEd Grading: MAPEH and EPP/TLE Weight Distribution", "In skill-intensive subjects such as MAPEH (Music, Arts, PE, Health) and EPP/TLE, why is the Performance Tasks (PT) component weighted heavily at 60%?", "Because MAPEH and TLE prioritize hands-on skill demonstration, artistic performance, physical application, and authentic product creation.", ["Because these subjects prohibit written examinations entirely.", "Because students do not have textbooks for these subjects.", "Because performance tasks take zero grading time for teachers."]),
  ("DepEd Transmutation Table (DepEd Order 8, s. 2015)", "Under the DepEd K to 12 grading system, what is the minimum initial percentage score required to achieve a passing transmuted grade of 75?", "60.00% (an initial score of 60% transmutes to a passing grade of 75).", ["50.00%.", "70.00%.", "75.00%."]),
  ("DepEd Grading: Core Values Reporting (Non-Numerical)", "How are the four core DepEd values (Maka-Diyos, Makatao, Makakalikasan, Makabansa) officially reported in the student's report card (Form 138)?", "Using qualitative non-numerical behavioral descriptors: Always Observed (AO), Sometimes Observed (SO), Rarely Observed (RO), Not Observed (NO).", ["Using numerical percentages from 0 to 100.", "Using letter grades (A, B, C, D, F).", "By ranking students from 1st to 50th in morals."]),
  ("Table of Specifications (TOS): Purpose and Construction", "A Table of Specifications (TOS) is a two-way alignment grid developed before constructing a test primarily to ensure:", "Content Validity and balance, ensuring test items proportionally reflect instructional time, learning competencies, and Bloom's cognitive levels.", ["That all test questions have the answer 'A'.", "That the test is impossible for average students to pass.", "That the teacher does not need to grade the exams."]),
  ("TOS Construction: Calculating Item Allocations", "A teacher taught a 40-hour unit on Ecosystems, spending 10 hours (25% of class time) on 'Food Webs and Energy Pyramids'. In a 60-item test, how many items should be allocated to Food Webs according to the TOS?", "15 items (25% of 60 items = 15).", ["10 items.", "20 items.", "25 items."]),
  ("Item Analysis: Difficulty Index (p-value)", "In classical item analysis, the 'Difficulty Index' (p) of a test item is calculated as the proportion of students who answered the item correctly. An item with $p = 0.85$ is interpreted as:", "An Easy item (85% of test-takers answered correctly).", ["A Difficult item.", "A Moderate item ($0.30 \le p \le 0.70$).", "An invalid item."]),
  ("Difficulty Index: Optimal LET Item Range", "In standardized board examinations and classroom testing, items with a Difficulty Index ($p$) between 0.30 and 0.70 are considered:", "Moderately difficult and ideal for maximizing test reliability and student discrimination.", ["Too easy and should be rejected immediately.", "Extremely difficult and should be discarded.", "Unreliable and completely ambiguous."])
]
d.extend([
  ("Item Analysis: Discrimination Index (d-value)", "The 'Discrimination Index' ($D = \\frac{RU - RL}{N/2}$) measures an item's ability to distinguish between high-performing and low-performing students. A Positive Discrimination Index ($D > 0$) means:", "More students in the Upper 27% group answered correctly than students in the Lower 27% group (the item discriminates favorably).", ["More students in the Lower group answered correctly than in the Upper group (Negative Discrimination).", "Both upper and lower groups scored exactly identical zero.", "The item is completely defective."]),
  ("Item Analysis: Negative Discrimination Index", "An item analysis reveals a Discrimination Index of $D = -0.40$. What does this negative value indicate, and what action must the teacher take?", "More low-performing students got the item correct than high-performing students (suggesting a flawed distractor, miskey, or ambiguity); the item must be REVISED or DISCARDED.", ["The item is exceptionally good and should be kept forever.", "The item should be made the only question on the final exam.", "High-performing students should be penalized for missing it."]),
  ("Item Analysis: Zero Discrimination ($D = 0.00$)", "If an item has a Discrimination Index of $D = 0.00$, what does this indicate?", "The item failed to discriminate between high and low achievers (equal numbers of upper and lower students got it right, or everyone got it right/wrong).", ["The item has perfect predictive validity.", "The item has a negative difficulty index.", "The item is 100% reliable."]),
  ("Item Analysis: Distractor Efficiency", "In a multiple-choice item, an effective 'Plausible Distractor' is one that:", "Attracts more students from the Lower group than from the Upper group, and is selected by a reasonable proportion of students.", ["Is never chosen by a single student in the entire class (ineffective/dead distractor).", "Attracts 100% of the students from the Upper group.", "Contains funny joke words that distract students."]),
  ("Item Analysis: Ineffective / Dead Distractors", "In analyzing a 4-option multiple-choice item, option D was selected by 0 students from both the upper and lower groups. Option D is classified as:", "An Ineffective (Dead / Non-functional) Distractor that should be revised or replaced with a more plausible alternative.", ["A perfectly discriminating distractor.", "The correct answer key.", "A statistically reliable distractor."]),
  ("Assessment Validity: Content Validity", "A teacher constructs a 50-item final exam for Grade 10 World History using a comprehensive Table of Specifications (TOS) aligned directly with the prescribed curriculum competencies. This establishes high:", "Content Validity (the test adequately samples the domain of knowledge and skills taught).", ["Construct Validity.", "Predictive Criterion Validity.", "Concurrent Validity."]),
  ("Assessment Validity: Face Validity", "When an assessment appears, on superficial inspection by non-experts, to measure what it claims to measure, it has:", "Face Validity (superficial appearance of test relevance).", ["Construct Validity.", "Criterion-Related Validity.", "Predictive Validity."]),
  ("Assessment Validity: Criterion-Related (Predictive Validity)", "A university uses an entrance examination score to accurately forecast an applicant's future Grade Point Average (GPA) during their first year of college. This demonstrates high:", "Predictive Criterion-Related Validity.", ["Concurrent Validity.", "Content Validity.", "Face Validity."]),
  ("Assessment Validity: Concurrent Validity", "When scores on a newly developed short diagnostic math test correlate highly with scores on an established, comprehensive standardized math achievement test administered at the same time, it establishes:", "Concurrent Criterion-Related Validity.", ["Predictive Validity.", "Content Validity.", "Face Validity."]),
  ("Assessment Validity: Construct Validity", "When an assessment measures an unobservable, theoretical psychological trait or psychological construct (such as 'Self-Efficacy', 'Critical Thinking', or 'Mathematical Anxiety'), it demonstrates:", "Construct Validity (evidence through convergent/divergent correlations and factor analysis).", ["Content Validity.", "Face Validity.", "Administrative Validity."]),
  ("Assessment Reliability: Definition & Concept", "In measurement and evaluation, 'Reliability' refers to:", "The consistency, stability, and dependability of test scores across repeated administrations under similar conditions.", ["The extent to which the test measures what it claims to measure (Validity).", "The speed at which students complete the exam.", "The physical length and paper weight of the test booklet."]),
  ("Relationship between Validity and Reliability", "Which of the following statements accurately characterizes the fundamental psychometric relationship between Validity and Reliability?", "'A test can be reliable without being valid, but a test CANNOT be valid without first being reliable.'", ["'A test can be valid without being reliable.'", "'Reliability and validity are identical concepts.'", "'A test that is valid is guaranteed to be 100% unreliable.'"]),
  ("Reliability Methods: Test-Retest Method (Stability)", "Administering the identical test to the same group of students on two separate occasions with a two-week interval measures:", "Test-Retest Reliability (Coefficient of Stability across time).", ["Equivalent Forms Reliability (Equivalence).", "Split-Half Reliability (Internal Consistency).", "Inter-Rater Reliability."]),
  ("Reliability Methods: Parallel / Equivalent Forms (Equivalence)", "Administering two different but equivalent forms (Form A and Form B) of a test covering identical content specifications to the same group of students measures:", "Equivalent Forms Reliability (Coefficient of Equivalence).", ["Test-Retest Reliability.", "Split-Half Reliability.", "Inter-Rater Reliability."]),
  ("Reliability Methods: Split-Half Method (Internal Consistency)", "Dividing a single test administration into two halves (e.g., Odd items vs Even items) and correlating the scores, then adjusting with the Spearman-Brown Prophecy Formula, measures:", "Split-Half Reliability (Internal Consistency).", ["Test-Retest Stability.", "Inter-Rater Agreement.", "Predictive Validity."])
])
d.extend([
  ("Reliability Methods: Kuder-Richardson (KR-20 / KR-21) and Cronbach's Alpha", "While Kuder-Richardson formulas (KR-20) measure internal consistency for dichotomously scored items (Right/Wrong), Cronbach's Alpha (Coefficient Alpha) is used for:", "Polytonously scored items (e.g., Likert scales, essay rubrics, partial credit scoring).", ["Dichotomous true-false items only.", "Athletic running speeds.", "Eye color categorization."]),
  ("Reliability Methods: Inter-Rater (Scorer) Reliability", "Having two independent teachers independently score the same set of student performance essays and calculating the correlation between their scores measures:", "Inter-Rater / Scorer Reliability (consistency across different human evaluators).", ["Test-Retest Stability.", "Split-Half Consistency.", "Content Validity."]),
  ("Rubric Types: Analytic vs Holistic Rubrics", "An 'Analytic Rubric' breaks performance down into separate criteria (e.g., Thesis, Evidence, Organization, Mechanics) with individual descriptors, whereas a 'Holistic Rubric':", "Evaluates the overall quality of the performance as a single unified whole with a single aggregate score.", ["Assigns negative points for creative thinking.", "Eliminates all grading criteria.", "Calculates the physical word count of an essay."]),
  ("Rubric Design: When to Use Holistic vs Analytic", "A teacher should choose a 'Holistic Rubric' over an Analytic Rubric when:", "A quick, overall summative evaluation of total performance is needed without detailed diagnostic component feedback.", ["Detailed diagnostic feedback is required for formative revision (Analytic).", "Students need specific criteria to rewrite their drafts.", "Grading multiple complex criteria with varying weights."]),
  ("Authentic Assessment: Performance-Based Assessment", "Which of the following represents an authentic 'Performance-Based Assessment' task?", "Students conduct a simulated city council public hearing, presenting research-based environmental proposals with community role-play.", ["Students answer a 50-item multiple-choice scantron test.", "Students copy a textbook chapter onto lined paper.", "Students memorize a list of 20 historical dates for a matching quiz."]),
  ("Portfolio Assessment: Types of Portfolios", "A 'Growth / Developmental Portfolio' showcases student progress and skill development over time with self-reflections, whereas a 'Showcase / Best-Work Portfolio':", "Displays only the student's highest-quality, polished exemplary finished products.", ["Contains every single rough draft and scrap paper ever written.", "Is kept secret from the student.", "Is graded exclusively with a multiple-choice key."]),
  ("Portfolio Assessment: The Essential Role of Student Reflection", "Why is 'Student Self-Reflection' considered the indispensable heart and defining characteristic of an authentic portfolio assessment?", "Because self-reflection fosters metacognitive awareness, critical self-evaluation, and ownership of personal learning progress.", ["Because it saves the teacher from reading the portfolio.", "Because reflections are graded with automated scantron machines.", "Because reflections replace the need for any artifacts."]),
  ("Norm-Referenced vs Criterion-Referenced Assessment", "While a 'Norm-Referenced Assessment' compares a student's performance against a peer norm group (e.g., 'scored at the 85th percentile'), a 'Criterion-Referenced Assessment':", "Measures a student's performance against a fixed, predetermined standard or mastery criterion (e.g., 'solved 8 out of 10 linear equations correctly').", ["Compares students based on physical height.", "Ranks students alphabetically.", "Assigns grades randomly."]),
  ("Measurement and Statistics: Measures of Central Tendency", "In descriptive statistics, the three primary measures of central tendency are the Mean, Median, and Mode. When a data distribution contains extreme outliers (e.g., one student scored 100 while all others scored below 20), which measure is the most appropriate and resilient?", "The Median (the middle score, unaffected by extreme outliers).", ["The Mean (the arithmetic average, heavily distorted by outliers).", "The Mode.", "The Standard Deviation."]),
  ("Measures of Dispersion: Range vs Standard Deviation", "While the 'Range' (Maximum - Minimum) provides only the crude spread of the two extreme scores, the 'Standard Deviation' ($\sigma$ or $s$) is superior because it:", "Measures the average distance and spread of ALL individual scores around the mean, utilizing every single data value in the distribution.", ["Requires zero mathematical calculation.", "Is always equal to the arithmetic mean.", "Calculates only the highest score."]),
  ("Normal Distribution Curve (Bell Curve): Empirical Rule (68-95-99.7)", "In a perfectly symmetrical Normal Distribution (Bell Curve), approximately what percentage of scores fall within ONE standard deviation ($ \pm 1\sigma $) of the mean?", "68.26% (approximately 68% of all scores).", ["95.44% (within $\pm 2\sigma$).", "99.74% (within $\pm 3\sigma$).", "50.00%."]),
  ("Normal Distribution: Mean, Median, and Mode Relationship", "In a theoretical, perfectly symmetrical Normal Distribution curve, how are the Mean, Median, and Mode positioned?", "The Mean, Median, and Mode are all exactly EQUAL and located at the exact center of the distribution ($Mean = Median = Mode$).", ["The Mean is greater than the Median and Mode.", "The Mode is greater than the Median and Mean.", "The Median is zero while the Mean is 100."]),
  ("Distribution Skewness: Positively Skewed Distribution", "In a 'Positively Skewed' (Right-Skewed) distribution (e.g., a very difficult examination where most students obtained low scores with a few high outliers), how are the central tendencies arranged?", "Mode < Median < Mean (the Mean is pulled to the right toward the high score tail).", ["Mean < Median < Mode (Negatively Skewed).", "Mean = Median = Mode (Symmetrical).", "Median < Mode < Mean."]),
  ("Distribution Skewness: Negatively Skewed Distribution", "In a 'Negatively Skewed' (Left-Skewed) distribution (e.g., an easy mastery test where most students scored high with a few very low scores), how are the measures arranged?", "Mean < Median < Mode (the Mean is pulled to the left toward the low score tail).", ["Mode < Median < Mean (Positively Skewed).", "Mean = Median = Mode (Symmetrical).", "Mode = Mean < Median."]),
  ("Standardized Scores: Z-Scores ($Z = \\frac{X - \\mu}{\\sigma}$)", "A student scores 85 on a test where the class mean is $\\mu = 75$ and standard deviation is $\\sigma = 5$. What is the student's standardized $Z$-score?", "$Z = +2.0$ (indicating the student scored 2.0 standard deviations above the class mean).", ["$Z = +1.0$.", "$Z = -2.0$.", "$Z = 0.0$."])
])
d.extend([
  ("Standardized Scores: T-Scores ($T = 50 + 10Z$)", "If a student obtains a $Z$-score of $Z = +1.5$, what is the student's equivalent standardized $T$-Score (which has a mean of 50 and standard deviation of 10)?", "$T = 65$ ($50 + 10(1.5) = 65$).", ["$T = 55$.", "$T = 75$.", "$T = 45$."]),
  ("Standardized Scores: Stanines (Standard Nines)", "In educational measurement, 'Stanines' divide the normal distribution into how many standard score bands with a mean of 5 and standard deviation of 2?", "9 score bands (ranging from Stanine 1 to Stanine 9).", ["5 score bands.", "10 score bands.", "100 score bands."]),
  ("Percentile Ranks: Meaning and Interpretation", "If a student's score is reported at the '82nd Percentile Rank' ($PR = 82$), what does this psychometrically mean?", "The student scored equal to or higher than 82% of the test-takers in the norm comparison group.", ["The student answered exactly 82% of the exam questions correctly (Percentage Score).", "The student failed 18% of the questions.", "The student's final report card mark is 82."]),
  ("Test Construction: Rules for Multiple-Choice Items", "In constructing multiple-choice question stems, test construction guidelines dictate that the teacher should:", "Include the central problem and key qualifying concepts in the STEM itself, keeping options concise and grammatically parallel.", ["Put the main question in the options and leave the stem blank.", "Use 'All of the above' and 'None of the above' on every single question.", "Include grammatical clues that give away the correct choice."]),
  ("Test Construction: Avoiding Clues (Grammatical Cues)", "A test question asks: 'Which of the following is an *ancient* instrument?' followed by options: A. guitar, B. violin, C. oboe, D. piano. Why is this item poorly constructed?", "Because the indefinite article 'an' grammatically eliminates options A, B, and D, pointing test-wise students directly to 'C. oboe'.", ["Because ancient instruments are not in the curriculum.", "Because all four instruments are modern.", "Because multiple-choice tests are illegal."]),
  ("Test Construction: Matching Items Guidelines", "When constructing a 'Matching Type' test, best testing practice requires:", "Keeping premises and responses homogeneous (e.g., all authors and works), having more responses than premises (to prevent elimination guessing), and keeping all items on a single page.", ["Having 50 premises and 2 responses.", "Mixing dates, authors, chemical formulas, and geometry shapes in the same matching set.", "Splitting matching columns across three different physical pages."]),
  ("Test Construction: Essay Item Guidelines", "To improve the reliability and objectivity of scoring essay questions, a teacher should:", "Write focused prompts with clear parameters, construct an analytical scoring rubric before administering the test, and grade all student responses to Question 1 before moving to Question 2.", ["Grade essays without any rubric based on handwriting beauty.", "Read all essays from one student from start to finish before grading the next student.", "Give higher scores to students who use longer paragraphs without content relevance."]),
  ("Grading Errors: Halo Effect vs Horn Effect", "In grading subjective performance tasks, the 'Halo Effect' occurs when a teacher's overall positive impression of a student's prior behavior unfairly inflates their grade, while the 'Horn Effect' occurs when:", "A negative impression of a student's previous misbehavior unfairly lowers their academic grade on unrelated work.", ["The teacher grades essays with red ink.", "The teacher grades too strictly for all students (Severity Error).", "The teacher gives everyone average scores (Central Tendency Error)."]),
  ("Grading Errors: Central Tendency Error", "When an evaluator hesitates to assign extreme high or extreme low ratings, clustering nearly all student performance scores in the middle average range, the teacher commits:", "The Central Tendency Error.", ["The Halo Effect.", "The Severity Error.", "The Contrast Error."]),
  ("Grading Errors: Severity vs Leniency Error", "A teacher who consistently assigns overly harsh, low ratings to all students is displaying __________, while a teacher who gives top marks to everyone regardless of quality displays __________.", "Severity Error; Leniency Error.", ["Leniency Error; Severity Error.", "Halo Effect; Horn Effect.", "Contrast Error; Proximity Error."]),
  ("Assessment Ethics: Confidentiality of Test Data (RA 10173)", "Under professional ethics and data privacy laws, posting student test scores, exam papers, and class rankings publicly on a classroom bulletin board with student names visible is:", "An unethical and illegal breach of student privacy that damages dignity and violates Data Privacy protocols.", ["A commendable practice that motivates low-performing pupils.", "Legally mandated by the Department of Education.", "Permitted if the teacher uses colorful pins."]),
  ("Assessment Feedback: Timeliness and Specificity", "Formative assessment research (Black & Wiliam) demonstrates that feedback is most powerful when it is:", "Timely, specific, criteria-referenced, and descriptive of actionable next steps for improvement, rather than merely assigning a letter grade.", ["Delayed by 3 months until the end of the school year.", "A single checkmark or grade with zero explanation.", "Given only to the top 3 students in the class."]),
  ("Standard Error of Measurement (SEM)", "The 'Standard Error of Measurement' (SEM) in classical test theory reflects:", "The standard deviation of errors of measurement around a student's true score ($SEM = s\\sqrt{1 - r}$), defining the confidence band of performance.", ["The percentage of students who failed the exam.", "The financial budget of the testing center.", "The total number of misprinted exam sheets."]),
  ("Confidence Intervals in Test Score Reporting", "Reporting a student's test score as a 'Confidence Interval' (e.g., $Score = 85 \\pm 3$ at the 95% confidence level) acknowledges that:", "No single observed test score is perfectly exact; true ability lies within a statistical score band due to inherent measurement error.", ["The student cheated on 3 questions.", "The teacher made a grading calculation mistake.", "The test must be discarded immediately."]),
  ("Assessment: Grading on a Curve vs Standard-Based Grading", "Why is 'Grading on a Curve' (strictly forcing student grades into a predetermined percentage distribution: 10% A, 20% B, 40% C, 20% D, 10% F) pedagogically criticized?", "Because it fosters unhealthy zero-sum peer competition and can fail competent students simply because peers performed slightly higher, regardless of mastery.", ["Because it makes all students receive an A grade.", "Because it eliminates all exams from schools.", "Because it takes zero mathematical computation."])
])
d.extend([
  ("Assessment: Constructive Alignment (John Biggs)", "John Biggs' principle of 'Constructive Alignment' in outcome-based education (OBE) requires mutual coherence between:", "Intended Learning Outcomes (ILOs), Teaching and Learning Activities (TLAs), and Assessment Tasks (ATs).", ["Textbook Publisher, Printing Paper, and Delivery Truck.", "School Tuition, Teacher Salary, and Building Maintenance.", "Classroom Seating, Room Temperature, and Clock Time."]),
  ("Assessment of HOTS: Bloom's Revised Taxonomy (Creating)", "In the Revised Bloom's Taxonomy (Anderson & Krathwohl), which of the following assessment tasks best assesses the highest cognitive level of 'Creating'?", "Designing a novel solar-powered water purification prototype for a rural community.", ["Listing the chemical elements in water.", "Explaining the water cycle in a written paragraph.", "Calculating the speed of water flow through a pipe."]),
  ("Assessment of HOTS: Bloom's Evaluating vs Analyzing", "While 'Analyzing' involves breaking material into component parts and determining relationships (e.g., differentiating, organizing), 'Evaluating' involves:", "Making informed, criteria-based judgments and critiques regarding the value, validity, or effectiveness of ideas/solutions.", ["Memorizing factual definitions from an encyclopedia.", "Executing a standard computational calculation algorithm.", "Reciting poetry aloud from memory."]),
  ("Authentic Assessment: GRASPS Model (Wiggins & McTighe)", "In Designing Authentic Performance Tasks, Wiggins and McTighe's 'GRASPS' framework structures scenarios around:", "Goal, Role, Audience, Situation, Product/Performance, and Standards/Criteria.", ["Grade, Rank, Attendance, Schedule, Pacing, and Score.", "General, Relevant, Academic, Standard, Primary, and Secondary.", "Goals, Resources, Administration, Safety, Policies, and Security."]),
  ("Checklists vs Rating Scales vs Rubrics", "While a 'Checklist' records the simple presence or absence of a behavior/trait (Yes/No), a 'Rating Scale':", "Indicates the degree, frequency, or quality with which a trait is exhibited along a quantitative or qualitative continuum.", ["Calculates the student's final university grade point average.", "Is used only for multiple-choice tests.", "Contains no descriptive criteria."]),
  ("Assessment Bias: Cultural & Linguistic Bias in Testing", "A reading comprehension test using sports terminology unique to American baseball (e.g., 'striking out', 'bunting', 'dugout') administered to rural Filipino students displays:", "Cultural/Contextual Bias (penalizing students who lack specific cultural background knowledge rather than testing reading ability).", ["High construct validity.", "Perfect psychometric reliability.", "Predictive validity."]),
  ("Standardized Testing: Raw Score vs Scaled Score", "While a 'Raw Score' is simply the number of items answered correctly, a 'Scaled Score' is:", "A mathematically transformed score that accounts for differences in test form difficulty, allowing fair comparisons across different test administrations.", ["The score multiplied by 1,000.", "The student's chronological birth year.", "The time in minutes spent answering the exam."]),
  ("Assessment: Ipsative Assessment", "An 'Ipsative Assessment' evaluates a learner's current performance against:", "Their own previous personal performance and baseline, measuring individual growth over time rather than comparing against peers.", ["A national standardized peer norm group.", "A fixed absolute criterion standard.", "The highest score achieved in the school district."]),
  ("Assessment for Learning: Peer Assessment Best Practices", "To make 'Peer Assessment' effective and constructively valid in the classroom, the teacher must:", "Train students explicitly on using clear rubrics, model constructive feedback, and establish a safe culture of mutual respect.", ["Let students assign permanent report card grades to each other secretly.", "Encourage students to publicly mock peer errors.", "Use peer grading to eliminate teacher grading entirely."]),
  ("Self-Assessment: Metacognitive Prompts", "A student completes an assignment and answers the prompt: 'What part of this problem was most challenging for me, and what strategy did I use to overcome it?' This develops:", "Metacognitive self-regulation, self-monitoring, and reflective learning capacity.", ["Rote mechanical obedience.", "Operant behavioral conditioning.", "Test anxiety and learned helplessness."]),
  ("Item Formats: Binary-Choice (True-False) Items", "In constructing True-False binary-choice test items, guidelines recommend:", "Writing declarative statements that are completely, unequivocally true or false, avoiding broad generalizations with qualifiers like 'always' or 'never'.", ["Making 90% of the questions false.", "Using double negatives in every sentence.", "Writing sentences with 100 words."]),
  ("Item Formats: Short-Answer / Fill-in-the-Blank Items", "In constructing Completion / Fill-in-the-Blank items, test developers should:", "Place the blank near or at the END of the sentence rather than at the beginning, and ensure there is only one unambiguous correct answer.", ["Leave 5 blanks in a 7-word sentence (mutilated text).", "Place blanks randomly without sentence structure.", "Use blanks that can be answered by 50 different synonyms."]),
  ("Grading Systems: Cumulative vs Averaging Grading System", "In an 'Averaging Grading System', the final grade is the simple arithmetic mean of all grading periods, whereas in a 'Cumulative Grading System':", "The final grade gives greater weight to the final grading period (e.g., Previous Grade $\\times \\frac{1}{3} +$ Present Grade $\\times \\frac{2}{3}$), rewarding progressive improvement over time.", ["The first quarter grade is repeated four times.", "Grades are assigned randomly by a computer.", "Only failing grades are recorded."]),
  ("Assessment Feedback: The Praise-Prompt-Leave Technique", "During independent studio or lab work, a teacher using the 'Praise-Prompt-Leave' coaching technique:", "Praises a specific correctly executed element, prompts the student with a guiding question for the next step, and steps away to allow independent problem-solving.", ["Hovering over the student for 45 minutes shouting corrections.", "Ignoring the student for the entire semester.", "Taking the pencil and completing the work for the student."]),
  ("Assessment of Learning Synthesis: The Balanced Assessment System", "A comprehensive, 21st-century assessment system in schools must be 'Balanced' by harmoniously integrating:", "Diagnostic (Before), Formative (During), Summative (After), Traditional (Knowledge), and Authentic/Performance-Based (Application) assessments.", ["Only 100-item multiple-choice exams administered once a year.", "Purely subjective oral interviews with zero written evidence.", "Standardized ranking of students from best to worst without feedback."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item evaluates assessment competence in {item[0]}. {item[2]} represents standard psychometric measurement, evaluation theory, and DepEd Order 8, s. 2015."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('assessmentExams.ts', 'ASSESSMENT_EXAM_QUESTIONS', questions)
