import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Communication Models: Shannon-Weaver", "In the Shannon-Weaver Mathematical Model of Communication, which element represents anything that interferes with or distorts the message during transmission?", "Noise (physical, physiological, psychological, or semantic).", ["Channel encoding.", "Feedback loop mechanism.", "Contextual decoder."], "Noise in the Shannon-Weaver model is any factor that degrades or distorts the signal between sender transmitter and receiver."),
  ("Communication Models: Berlo's SMCR", "David Berlo's SMCR model emphasizes that effective communication between Sender and Receiver requires alignment in:", "Communication skills, attitudes, knowledge, social system, and culture.", ["Physical stature and vocal pitch volume.", "Hardware processor speed and electrical conductivity.", "Standard typographical font size and line spacing."], "Berlo's SMCR Model posits that both Source and Receiver are shaped by five factors: communication skills, attitudes, knowledge, social system, and culture."),
  ("Communication Models: Transactional Model", "Dean Barnlund's Transactional Model of Communication is distinguished from linear models because it views communicators as:", "Simultaneous senders and receivers who co-create meaning continuously through shared feedback.", ["Passive recipients who store encoded electrical signals without responding.", "Isolated agents communicating only through formal legal written statutes.", "Automated transmitters broadcasting monologues to unverified audiences."], "The Transactional Model recognizes that sending and receiving occur simultaneously and continuously within a shared field of experience."),
  ("Intercultural Communication: High vs Low Context", "Edward T. Hall's cultural framework identifies 'High-Context Cultures' as those where meaning is derived primarily from:", "Non-verbal cues, shared relational history, social hierarchy, and implicit situational background.", ["Direct, explicit, literal, and detailed verbal statements.", "Standardized legal contracts written in computer code.", "Automated statistical algorithms without human mediation."], "In High-Context cultures (e.g., Filipino, Japanese), much of the message is embedded in the physical context, non-verbal cues, and shared history rather than explicit words."),
  ("Intercultural Communication: Low-Context Characteristics", "A manager in a 'Low-Context Culture' (such as Germany or the United States) prefers workplace communication that is:", "Direct, explicit, clear, and focused on literal verbal detail without ambiguity.", ["Heavily reliant on subtle pauses, facial expressions, and shared silence.", "Veiled in poetic metaphors to avoid direct factual confrontation.", "Delivered exclusively through third-party family intermediaries."], "Low-Context communication values explicit verbal clarity, directness, and unambiguous detail."),
  ("Intercultural Communication: Ethnocentrism", "A foreign consultant judges a host country's negotiation customs as 'primitive and unprofessional' simply because they differ from his home practices. This is an example of:", "Ethnocentrism (evaluating other cultures using the standards and preconceptions of one's own culture).", ["Cultural relativism.", "Intercultural competence.", "Code-switching."], "Ethnocentrism is the tendency to view one's own cultural group as superior and standard, judging other cultures negatively based on one's own cultural norms."),
  ("Non-Verbal Communication: Kinesics", "The study of bodily motion, gestures, posture, eye contact, and facial expressions in human interaction is termed:", "Kinesics.", ["Proxemics.", "Haptics.", "Chronemics."], "Kinesics (coined by Ray Birdwhistell) is the interpretation of body motion communication such as facial expressions and gestures."),
  ("Non-Verbal Communication: Proxemics", "Edward T. Hall categorized human interpersonal distance. What is the standard range for 'Personal Space' (reserved for friendly conversations with acquaintances)?", "1.5 feet to 4 feet (18 inches to 48 inches).", ["0 to 18 inches (Intimate space).", "4 feet to 12 feet (Social space).", "12 feet to 25+ feet (Public space)."], "Hall established four spatial zones: Intimate (0-1.5 ft), Personal (1.5-4 ft), Social (4-12 ft), and Public (12+ ft)."),
  ("Non-Verbal Communication: Haptics & Chronemics", "The communicative use of touch in professional and social interactions is called 'Haptics', while the communicative use of time and punctuality is called:", "Chronemics.", ["Artifactics.", "Paralanguage.", "Olfactics."], "Haptics pertains to touch, and Chronemics pertains to the perception and use of time (punctuality, pacing, wait time)."),
  ("Non-Verbal Communication: Paralanguage (Vocalics)", "Which of the following aspects of speech is classified as 'Paralanguage' (vocalics)?", "Tone, pitch, volume, speaking rate, and vocal inflections.", ["The semantic dictionary definitions of written words.", "The physical distance maintained between conversation partners.", "The clothing and personal jewelry worn by the speaker."], "Paralanguage encompasses non-verbal vocal qualities accompanying speech—pitch, rate, tone, volume, pauses, and inflection."),
  ("Language Registers: Martin Joos' Five Registers", "A national constitution, legal statute, or traditional religious marriage vow represents which language register?", "Frozen (Static) Register, where language is printed, unchanging, and ceremonial.", ["Formal Register, used in academic lectures and corporate reports.", "Consultative Register, used in standard doctor-patient dialogues.", "Casual Register, used between close peer friends."], "Martin Joos identified 5 styles: Frozen (immutable/ceremonial), Formal (one-way presentation), Consultative (two-way professional), Casual (informal peer), Intimate (private/family)."),
  ("Language Registers: Consultative Register", "A conversation between a high school guidance counselor and a student seeking career advice naturally operates in which register?", "Consultative Register, featuring two-way professional dialogue with mutual feedback.", ["Frozen Register.", "Intimate Register.", "Static ceremonial register."], "Consultative register is the standard two-way professional register where speaker and listener interact professionally with background knowledge provided."),
  ("Academic Writing: Cohesion and Coherence", "In academic discourse, 'Cohesion' refers to the grammatical and lexical linking of sentences, whereas 'Coherence' refers to:", "The logical flow, semantic organization, and overall intelligibility of ideas across the text.", ["The exact word count of introductory paragraphs.", "The physical binding and typography of a printed thesis volume.", "The number of color illustrations included in the appendices."], "Cohesion is the explicit linguistic glue (connectives, reference); Coherence is the logical, meaningful conceptual flow of the text as a whole."),
  ("Academic Integrity: Plagiarism Types", "A student rewrites several paragraphs from a published journal article by swapping words with synonyms while keeping the exact sentence structure and argument without citation. This is:", "Patchwriting / Paraphrasing plagiarism without attribution.", ["Legitimate academic synthesis under Fair Use.", "Primary historical source triangulation.", "Peer-reviewed literature benchmarking."], "Patchwriting (copying text with minor synonym swaps and structural retention without proper attribution) constitutes plagiarism."),
  ("Academic Referencing: APA 7th Edition (In-Text)", "In APA 7th edition referencing, how is a parenthetical citation formatted for a work by three or more authors on its first mention?", "(FirstAuthor et al., 2023).", ["(FirstAuthor, SecondAuthor, & ThirdAuthor, 2023).", "(FirstAuthor and others, 2023, pp. 1-10).", "(FirstAuthor, et. al., 2023)."], "APA 7th edition simplified in-text citations: for works with 3 or more authors, use the first author's surname followed immediately by 'et al.' and year from the first mention.")
]
d.extend([
  ("Workplace Communication: Memorandum", "The primary internal operational purpose of an official organizational Memorandum (Memo) is to:", "Disseminate official policy announcements, directives, or updates within an organization.", ["Solicit commercial consumer orders through newspaper advertisements.", "File criminal indictments in provincial trial courts.", "Publish peer-reviewed academic literature in international journals."]),
  ("Workplace Communication: Minutes of the Meeting", "Which of the following is an essential requirement when writing official Minutes of the Meeting (MoM)?", "Accurately and objectively recording decisions made, motions approved, and assigned action items without personal editorial bias.", ["Transcribing every casual personal remark and joke word-for-word in humorous prose.", "Omitting the date, time, and list of attendees to preserve organizational secrecy.", "Recording only the opinions of the presiding chairperson while ignoring all motions."]),
  ("Workplace Communication: Formal Business Letter", "In a formal business letter using full-block format, which structural convention is strictly followed?", "All elements (date, inside address, salutation, body, complimentary close) are aligned flush with the left margin without paragraph indentations.", ["All text is centered on the page like a ceremonial invitation.", "The sender's name and signature must be written in red calligraphy ink.", "Paragraphs are indented five spaces while the date is placed in a right-aligned footer."]),
  ("Workplace Communication: Incident Report", "When preparing a professional Incident Report regarding an equipment failure or workplace injury, the writer must ensure that the tone is:", "Objective, factual, chronological, and free from emotional speculation or unsubstantiated accusations.", ["Sensational, melodramatic, and written in heroic verse.", "Aggressive and demanding immediate criminal imprisonment for coworkers.", "Poetic and filled with figurative metaphors."]),
  ("Workplace Communication: Executive Summary", "An 'Executive Summary' in a formal business proposal or feasibility report is designed to:", "Provide a concise, high-level overview of the problem, proposed solution, budget, and strategic outcomes for busy decision-makers.", ["List every line of raw computer code used in data analysis.", "Serve as an exhaustive bibliography of every textbook in the corporate library.", "Replace the need for financial balance sheets."]),
  ("Persuasive Speaking: Aristotle's Rhetorical Proofs", "When a speaker presents verified statistical data, logical syllogisms, and documented empirical evidence to support a claim, which rhetorical appeal is being utilized?", "Logos (appeal to logic and reason).", ["Ethos (appeal to credibility and moral character).", "Pathos (appeal to emotion and sympathy).", "Kairos (appeal to opportune timing)."]),
  ("Persuasive Speaking: Ethos & Pathos", "A veteran physician advocating for vaccination shares her 25 years of pediatric clinical experience (Appeal X) and tells a poignant story of a child she treated (Appeal Y). Appeals X and Y represent:", "X = Ethos (credibility), Y = Pathos (emotional resonance).", ["X = Pathos, Y = Logos.", "X = Logos, Y = Ethos.", "X = Kairos, Y = Mythos."]),
  ("Public Speaking: Monroe's Motivated Sequence", "Monroe's Motivated Sequence for persuasive speaking arranges the organizational steps in which standard psychological order?", "Attention, Need, Satisfaction, Visualization, and Action.", ["Need, Attention, Action, Visualization, and Satisfaction.", "Attention, Visualization, Action, Need, and Satisfaction.", "Visualization, Need, Attention, Action, and Satisfaction."]),
  ("Public Speaking: Delivery Methods", "Which method of speech delivery involves speaking from a brief set of structured notes or an outline, combining careful preparation with natural, conversational spontaneity?", "Extemporaneous speaking.", ["Impromptu speaking (speaking spontaneously without any prior preparation).", "Manuscript speaking (reading a written text word-for-word).", "Memorized speaking (reciting a script verbatim from memory)."]),
  ("Public Speaking: Impromptu Speaking", "During an unannounced faculty meeting, a teacher is asked on the spot to give a five-minute summary of a project without prior notes. This delivery format is:", "Impromptu speech.", ["Extemporaneous speech.", "Manuscript speech.", "Oratorical declamation."]),
  ("Public Speaking: Speech Anxiety (Glossophobia)", "In speech communication, 'Glossophobia' refers to:", "The anxiety or fear of public speaking in front of an audience.", ["The inability to pronounce foreign vowel sounds.", "The visual impairment caused by bright stage lighting.", "The legal prohibition against public assemblies."]),
  ("Digital Literacy: Professional Email Netiquette", "Which of the following practices adheres to professional email etiquette in academic and corporate communication?", "Writing a clear, descriptive subject line and using a respectful salutation, professional tone, and complete email signature.", ["Typing the entire email message in ALL CAPS with multiple exclamation marks.", "Leaving the subject line blank to surprise the recipient.", "Using informal text-speak abbreviations ('u r gr8') in formal business queries."]),
  ("Digital Literacy: Data Privacy in Communication", "When sending a sensitive group announcement to 50 external clients who do not know each other, the sender should place client email addresses in:", "BCC (Blind Carbon Copy) to protect recipient privacy and prevent unauthorized data harvesting.", ["CC (Carbon Copy), exposing all personal emails to everyone.", "The Subject Line for public transparency.", "The primary 'To' field without encryption."]),
  ("Academic Writing: Thesis Statement", "An effective 'Thesis Statement' in an argumentative research paper must be:", "A clear, specific, arguable claim that previews the paper's core supporting points and roadmap.", ["A broad factual statement that everyone universally agrees with without dispute.", "A vague question that leaves the author's stance completely unknown.", "A direct quote copied verbatim from a general dictionary definition."]),
  ("Academic Writing: Synthesizing Sources", "In academic literature reviews, 'Synthesis' differs from simple summarization because synthesis:", "Combines and analyzes multiple sources thematically to highlight patterns, agreements, contradictions, and new insights.", ["Lists author summaries sequentially one paragraph after another without connection.", "Copies entire abstracts directly from online databases.", "Deletes all citations to minimize word count."])
])
d.extend([
  ("Language Varieties: World Englishes (Kachru)", "Braj Kachru's 'Three Concentric Circles of English' classifies Philippine English, Indian English, and Singaporean English under the:", "Outer Circle (institutionalized second-language varieties with distinct regional norms and national functions).", ["Inner Circle (traditional native-English speaking bases like the UK and USA).", "Expanding Circle (English learned purely as a foreign language for trade).", "Virtual Circle (unstandardized internet slang)."]),
  ("Language Varieties: Code-Switching", "A bilingual speaker in Manila says: 'Nag-submit na ako ng aking proposal kahapon, but the director requested revisions.' This linguistic phenomenon is termed:", "Code-Switching (alternating between two or more languages in a single conversation).", ["Linguistic imperialism.", "Aphasia.", "Semantic shift."]),
  ("Language Varieties: Diglossia", "In sociolinguistics, 'Diglossia' describes a situation where a community uses two distinct language varieties for different social functions:", "A 'High' (H) variety for formal, academic, and official domains, and a 'Low' (L) variety for casual daily conversations.", ["A spoken variety for daytime and a written variety for nighttime.", "Two identical dialects that differ only in spelling.", "A language that has zero native speakers."]),
  ("Communication Barriers: Semantic Noise", "A technical engineer uses complex jargon, rare acronyms, and specialized nomenclature when talking to general public clients, causing misunderstanding. This is:", "Semantic Noise, where unfamiliar vocabulary and ambiguous symbols hinder meaning.", ["Physical Noise, such as loud traffic sounds.", "Physiological Noise, such as hearing loss.", "Atmospheric interference with radio waves."]),
  ("Communication Barriers: Psychological Noise", "A student fails to comprehend an important classroom lecture because he is experiencing intense anxiety over an impending family eviction. This is an example of:", "Psychological Noise, where internal emotional stress interferes with message reception.", ["Physical Noise.", "Environmental Noise.", "Syntactic ambiguity."]),
  ("Communication Ethics: Credo for Ethical Communication", "The National Communication Association (NCA) Credo for Ethical Communication asserts that fundamental to ethical communication is:", "Truthfulness, accuracy, honesty, and reason as essential to the integrity of communication.", ["Manipulating statistics to achieve desired persuasive outcomes.", "Concealing known safety hazards to protect corporate PR.", "Interrupting opposing speakers to dominate debates."]),
  ("Interpersonal Communication: Johari Window", "In the Johari Window model of self-awareness, the quadrant containing information that is known to oneself but hidden from others is the:", "Hidden Area (Façade / Private Self).", ["Open Area (Arena / Public Self).", "Blind Area (Blind Spot).", "Unknown Area."]),
  ("Interpersonal Communication: Johari Blind Spot", "In the Johari Window, traits and behaviors that are known to others but unknown to oneself are located in the:", "Blind Spot (Blind Area).", ["Open Area.", "Hidden Area.", "Unknown Area."]),
  ("Listening Skills: Active Listening", "Which of the following is a primary characteristic of 'Active Listening' in professional counseling and negotiation?", "Reflecting feelings, paraphrasing content, asking clarifying questions, and withholding premature judgment.", ["Silently formulating one's counter-arguments while the other person is speaking.", "Interrupting frequently to offer personal anecdotes.", "Checking smartphone notifications while nodding periodically."]),
  ("Listening Skills: Critical Listening", "When evaluating a political candidate's campaign speech to detect logical fallacies, emotional bias, and unsubstantiated claims, the listener is engaged in:", "Critical (Evaluative) Listening.", ["Appreciative Listening.", "Empathetic Listening.", "Discriminative Listening."]),
  ("Listening Skills: Empathetic Listening", "When a guidance counselor listens to a grieving student to provide emotional support and understand feelings without evaluating or judging, this is:", "Empathetic (Therapeutic) Listening.", ["Critical Listening.", "Appreciative Listening.", "Comprehensive Listening."]),
  ("Academic Writing: Paraphrasing Techniques", "Which of the following represents an effective, ethical paraphrase of an original text?", "Completely restructuring sentence architecture and phrasing ideas in one's own voice while accurately citing the source.", ["Replacing every third word with a thesaurus synonym while preserving the exact sentence structure.", "Putting the entire original paragraph in quotation marks without an in-text citation.", "Altering numerical statistics to make the data support one's personal bias."]),
  ("Academic Writing: Literature Review Purpose", "The primary purpose of a 'Literature Review' in academic research is to:", "Survey existing scholarly works to establish background context, identify research gaps, and justify the current study.", ["Fill page quotas required by university formatting manuals.", "List dictionary definitions of common everyday English words.", "Prove that no other scholar in world history has ever studied the topic."]),
  ("Academic Writing: Abstract Components", "An effective academic 'Structured Abstract' (150-250 words) must concisely summarize which core elements?", "Background/Purpose, Methodology, Key Findings/Results, and Conclusions/Implications.", ["Exhaustive line-by-line financial receipts of research grants.", "Biographical essays of all research laboratory assistants.", "Transcriptions of unedited audio recordings."]),
  ("Academic Writing: Tone and Register", "Which of the following sentence excerpts exemplifies the appropriate objective, formal tone for academic research writing?", "'The experimental data indicate a statistically significant positive correlation between study duration and retention rates.'", ["'I totally think our crazy test results proved our awesome theory 100%!'", "'You know, it's pretty obvious that kids who study more do way better.'", "'Believe me, this research is gonna change the entire education system forever!'"])
])
d.extend([
  ("Non-Verbal Communication: Oculesics", "The study of eye movement, gaze direction, blink rates, and pupil dilation in human communication is known as:", "Oculesics.", ["Chronemics.", "Olfactics.", "Gustorics."]),
  ("Non-Verbal Communication: Artifactics", "The communicative messages conveyed through personal clothing, hairstyles, tattoos, jewelry, and office décor are classified as:", "Artifactics (Objectics).", ["Kinesics.", "Proxemics.", "Haptics."]),
  ("Intercultural Communication: Cultural Sensitivity", "When preparing instructional materials for a culturally diverse classroom including Muslim, Christian, and Lumad learners, a teacher demonstrates cultural sensitivity by:", "Using inclusive language, culturally diverse examples, and avoiding dietary or religious stereotyping.", ["Assuming all learners share identical religious feast celebrations.", "Using ethnic minority caricatures to generate humor in introductory lessons.", "Translating all texts into 16th-century archaic Latin."]),
  ("Workplace Communication: Resume Formats", "A job applicant with extensive linear career progression in the same field should select which resume format to showcase career growth?", "Chronological Resume (listing work history in reverse chronological order).", ["Functional Resume (focusing strictly on skills without employment dates).", "Creative Infographic Resume without text.", "Unformatted raw text file without headings."]),
  ("Workplace Communication: Functional Resume", "A career-changer or an applicant with significant employment gaps should consider which resume format to highlight transferable capabilities?", "Functional (Skills-Based) Resume.", ["Chronological Resume.", "Academic Curriculum Vitae (CV).", "Federal government dossier."]),
  ("Workplace Communication: Job Interview STAR Method", "When answering behavioral interview questions (e.g., 'Describe a time you resolved a team conflict'), the 'STAR' method stands for:", "Situation, Task, Action, and Result.", ["Strategy, Time, Assessment, and Review.", "Summary, Topic, Argument, and Resolution.", "Standard, Technique, Analysis, and Report."]),
  ("Communication Theory: Cultivation Theory", "George Gerbner's Cultivation Theory posits that long-term, heavy exposure to television and media tends to:", "Cultivate perceptions of reality among viewers that match the televised world (e.g., 'Mean World Syndrome').", ["Eliminate all political disagreements across national populations.", "Increase physical cognitive reaction speeds by 500%.", "Cause viewers to completely stop speaking their native languages."]),
  ("Communication Theory: Agenda-Setting Theory", "Max McCombs and Donald Shaw's Agenda-Setting Theory asserts that news media may not tell people what to think, but they are stunningly successful in:", "Telling people what to think about (setting the salience of issues in the public mind).", ["Forcing people to vote for specific political candidates.", "Controlling the physical weather through radio broadcast towers.", "Eliminating all economic inflation in commercial markets."]),
  ("Communication Theory: Framing Theory", "In media communication, 'Framing' refers to:", "The way information is presented, structured, and contextualized to emphasize certain aspects while downplaying others.", ["The wooden border surrounding a printed canvas painting.", "The physical dimensions of a smartphone display screen.", "The compression format of digital video files."]),
  ("Language and Gender: Deborah Tannen's Genderlect", "Deborah Tannen's 'Genderlect' theory suggests that masculine conversation often focuses on 'Report Talk' (status/independence), while feminine conversation often emphasizes:", "'Rapport Talk' (connection, intimacy, and relationship building).", ["Authoritarian military command phrasing.", "Pure mathematical calculation and economic trade terms.", "Silent non-verbal isolation."]),
  ("Public Speaking: Vocal Variety", "To maintain audience engagement during a 45-minute keynote address, a public speaker should consciously utilize 'Vocal Variety', which involves:", "Varying pitch, tone, tempo, volume, and strategic pauses to match the emotional content.", ["Speaking in a continuous, unvarying monotone at maximum speed.", "Shouting every sentence into the microphone without variation.", "Whispering the entire presentation to force intense concentration."]),
  ("Public Speaking: Visual Aids Design (6x6 Rule)", "In presentation slide design, the '6x6 Rule' recommends that speakers should generally limit slides to:", "No more than 6 bullet points per slide and no more than 6 words per bullet point.", ["6 different font colors and 6 background animations per slide.", "6 minutes of continuous silent reading per slide.", "6 embedded video advertisements per transition."]),
  ("Persuasive Communication: Cognitive Dissonance", "Leon Festinger's theory of Cognitive Dissonance explains that when individuals encounter persuasive information contradicting their deeply held beliefs, they experience:", "Psychological discomfort that motivates them to reject the message, rationalize their behavior, or change their belief.", ["Immediate mathematical clarity and absolute certainty.", "Instant loss of all spoken language capabilities.", "Spontaneous physical euphoria without cognitive effort."]),
  ("Persuasive Communication: Inoculation Theory", "William McGuire's Inoculation Theory suggests that communicators can strengthen audience resistance to opposing propaganda by:", "Exposing them to mild, weakened counter-arguments and teaching them how to refute those arguments in advance.", ["Completely isolating them from all external information and internet access.", "Administering medical vaccines before public debates.", "Forcing them to memorize entire dictionaries."]),
  ("Academic Writing: Avoidance of Bias", "According to APA 7th edition guidelines on Bias-Free Language, writers should refer to participants using:", "Person-first language (e.g., 'a person with a visual impairment') or identity-first terms preferred by the community.", ["Generic dehumanizing labels (e.g., 'the blind', 'the afflicted').", "Archaic medical terms from the 18th century.", "Fictitious pseudonyms without institutional ethical approval."])
])
d.extend([
  ("Digital Literacy: Media Literacy & Disinformation", "When evaluating the credibility of an online news article before citing it in academic research, the CRAAP Test evaluates:", "Currency, Relevance, Authority, Accuracy, and Purpose.", ["Color, Resolution, Animation, Audio, and Performance.", "Cost, Revenue, Advertising, Audience, and Profit.", "Clickbait, Retweets, Algorithms, Analytics, and Promotion."]),
  ("Digital Literacy: Filter Bubbles & Echo Chambers", "In digital algorithm studies, an 'Echo Chamber' or 'Filter Bubble' is an online environment where:", "Users are exposed only to opinions that conform to their existing beliefs due to algorithmic personalization.", ["Users receive completely unbiased, neutral international news broadcasts.", "Audio microphone feedback creates loud screeching echoes on phone calls.", "Internet connections are permanently restricted to public library databases."]),
  ("Academic Writing: Signposting", "In scholarly essays and thesis writing, 'Signposting' refers to:", "Transitional phrases and structural cues that guide the reader through the logic, stages, and roadmap of the paper.", ["Placing physical directional traffic arrows in academic campus parking lots.", "Using oversized neon fonts on printed title pages.", "Inserting commercial logos in table of contents headers."]),
  ("Academic Writing: Hedging in Academic Discourse", "In academic writing, 'Hedging' (using epistemic words like 'suggests', 'indicates', 'appears to') is utilized to:", "Express appropriate intellectual humility, distinguish probability from absolute certainty, and avoid over-generalization.", ["Conceal the fact that the researcher conducted zero empirical experiments.", "Artificially inflate the total word count of a brief essay.", "Make the writing sound completely casual and unscholarly."]),
  ("Workplace Communication: Crisis Communication", "During an acute organizational crisis (e.g., a data breach or campus emergency), effective crisis communication requires:", "Rapid, transparent, accurate, empathetic, and unified messaging from designated official spokespersons.", ["Total silence and denying that any event occurred to prevent panic.", "Blaming junior staff publicly on social media channels.", "Releasing conflicting unverified rumors through anonymous accounts."]),
  ("Interpersonal Communication: Assertiveness vs Aggressiveness", "In professional communication, 'Assertive Communication' differs from 'Aggressive Communication' because assertiveness involves:", "Clearly and respectfully expressing one's rights and needs while respecting the rights and feelings of others.", ["Dominating conversations, shouting, and humiliating colleagues into submission.", "Passively yielding to every demand while suppressing legitimate concerns.", "Using manipulative sarcasm and silent treatment to achieve goals."]),
  ("Workplace Communication: Constructive Feedback", "When delivering constructive performance feedback to a colleague, the 'SBI' feedback model stands for:", "Situation, Behavior, and Impact.", ["Standard, Benchmark, and Inspection.", "Strategy, Budget, and Implementation.", "Summary, Briefing, and Instruction."]),
  ("Workplace Communication: Email Subject Lines", "Which of the following represents an exemplary professional email subject line for submitting an assignment?", "'BSED 3-A Research Proposal Draft - Hershey Tabanao (Oct 24)'", ["'URGENT PLEASE READ RIGHT NOW!!!'", "'hello maam'", "'(No Subject)'"]),
  ("Rhetorical Analysis: Fallacies (Ad Hominem)", "In an academic debate on educational technology, a speaker attacks her opponent's personal physical appearance rather than addressing his data. This is an:", "Ad Hominem fallacy (attacking the person instead of the argument).", ["Straw Man fallacy.", "False Dilemma fallacy.", "Post Hoc Ergo Propter Hoc fallacy."]),
  ("Rhetorical Analysis: Fallacies (Straw Man)", "A debater distorts and exaggerates an opponent's argument to an absurd extreme, and then attacks that distorted caricature. This is a:", "Straw Man fallacy.", ["Red Herring fallacy.", "Slippery Slope fallacy.", "Bandwagon fallacy."]),
  ("Rhetorical Analysis: Fallacies (False Dilemma)", "A presenter claims: 'Either we adopt this specific software brand immediately, or our school will completely collapse into total failure.' This is a:", "False Dilemma / Either-Or fallacy (artificially limiting choices to two extreme opposites).", ["Circular Reasoning (Begging the Question).", "Appeal to Ignorance.", "Hasty Generalization."]),
  ("Rhetorical Analysis: Fallacies (Post Hoc)", "A teacher says: 'It rained heavily this morning, and immediately three students were tardy; therefore, the rain caused them to wake up late.' Assuming causation purely from chronological sequence is:", "Post Hoc Ergo Propter Hoc (False Cause fallacy).", ["Appeal to Tradition.", "Ad Populum fallacy.", "Equivocation fallacy."]),
  ("Academic Writing: Primary vs Secondary Sources", "In communication research, an original transcript of a speech delivered by a president is classified as a:", "Primary Source (an original, firsthand historical artifact from the time of the event).", ["Secondary Source (an analysis or commentary written about the event).", "Tertiary Source (an indexed compendium like an encyclopedia).", "Fictional narrative."]),
  ("Communication Models: Lasswell's Formula", "Harold Lasswell's classical communication formula asks:", "'Who says What, in Which Channel, to Whom, with What Effect?'", ["'When does Money create Power in Politics?'", "'Where does Language originate in the Human Brain?'", "'Why do Computers process Binary Algorithms?'"]),
  ("Professional Communication: Effective Powerpoint Presentations", "When preparing instructional slides for a professional conference, the best practice is to:", "Use high-contrast readable typography, meaningful visual diagrams, and concise bullet points that support the speaker's narrative.", ["Paste entire textbook pages in 8pt font and read them word-for-word with back turned to the audience.", "Use flashing rainbow transitions and unrelated animated cartoon GIFs on every bullet.", "Fill every square inch of the screen with dense raw financial balance sheets."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item tests core competency in {item[0]}. {item[2]} represents standard purposive communication analysis and linguistic theory."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('purposiveCommExams.ts', 'PURPOSIVE_COMM_EXAM_QUESTIONS', questions)
