import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("TPACK Framework: Core Components (Mishra & Koehler)", "The Technological Pedagogical Content Knowledge (TPACK) framework posits that effective classroom technology integration requires the dynamic intersection of which three core knowledge bodies?", "Content Knowledge (CK), Pedagogical Knowledge (PK), and Technological Knowledge (TK).", ["Curriculum Knowledge, Administrative Knowledge, and Legal Knowledge.", "Hardware Knowledge, Software Knowledge, and Network Knowledge.", "Psychological Knowledge, Sociological Knowledge, and Anthropological Knowledge."], "Mishra and Koehler's TPACK framework models the complex interplay of Content Knowledge (subject matter), Pedagogical Knowledge (teaching methods), and Technological Knowledge (digital tools)."),
  ("TPACK Framework: Technological Content Knowledge (TCK)", "A biology teacher understands how specialized 3D molecular simulation software transforms and represents protein folding concepts that cannot be shown in 2D textbooks. In TPACK, this is:", "Technological Content Knowledge (TCK).", ["Pedagogical Content Knowledge (PCK).", "Technological Pedagogical Knowledge (TPK).", "Technological Knowledge (TK) only."], "TCK is understanding how technology and content influence and constrain one another—how specific technological tools can represent and transform specific subject-matter concepts."),
  ("TPACK Framework: Technological Pedagogical Knowledge (TPK)", "A teacher knows how to use an online collaborative whiteboard (e.g., Jamboard/Padlet) to facilitate small-group brainstorming across diverse subjects, regardless of topic. In TPACK, this is:", "Technological Pedagogical Knowledge (TPK).", ["Technological Content Knowledge (TCK).", "Content Knowledge (CK).", "Pedagogical Content Knowledge (PCK)."], "TPK is understanding how teaching and learning change when particular technologies are used, including pedagogical affordances and constraints of tools across learning activities."),
  ("TPACK Framework: True TPACK Synthesis", "When a mathematics teacher seamlessly designs an inquiry-based lesson using GeoGebra dynamic geometry software to guide students to discover the properties of parabolas, this embodies:", "True TPACK (Technological Pedagogical Content Knowledge).", ["Isolated Technological Knowledge (TK).", "Pure Content Knowledge (CK).", "Traditional Pedagogical Knowledge (PK)."], "True TPACK is the emergent form of knowledge that goes beyond all three components in isolation, creatively integrating pedagogy, content, and technology for deep student learning."),
  ("SAMR Model: Ruben Puentedura's Four Levels", "The SAMR model describes four levels of technology integration in the classroom, arranged from enhancement to transformation in which ascending order?", "Substitution, Augmentation, Modification, and Redefinition.", ["Simple, Advanced, Moderate, and Revolutionary.", "Software, Application, Media, and Resources.", "Selection, Adaptation, Mastery, and Review."], "Puentedura's SAMR model classifies tech integration into Enhancement (Substitution, Augmentation) and Transformation (Modification, Redefinition)."),
  ("SAMR Model: Substitution Level", "A teacher asks students to read a PDF version of a textbook chapter on their tablets instead of reading the physical printed textbook, with zero functional change. In the SAMR model, this is:", "Substitution (direct tech substitute with no functional change).", ["Augmentation.", "Modification.", "Redefinition."], "At the Substitution level, technology acts as a direct tool substitute with no functional improvement in the learning task."),
  ("SAMR Model: Augmentation Level", "Students read a digital e-book that includes interactive built-in dictionaries, audio narration, and hyperlinked self-check quizzes. In the SAMR model, this is:", "Augmentation (direct tech substitute with functional improvements).", ["Substitution.", "Modification.", "Redefinition."], "At the Augmentation level, technology is a direct tool substitute with functional enhancements (e.g., audio, search, hyperlinks) that improve the task."),
  ("SAMR Model: Modification Level", "Students write historical essays on a shared cloud document, receive real-time peer feedback, embed multimedia primary source audio recordings, and co-author chapters. In SAMR, this represents:", "Modification (significant task redesign).", ["Substitution.", "Augmentation.", "Redefinition."], "At the Modification level, technology allows for significant task redesign that would be difficult to accomplish with traditional analog tools."),
  ("SAMR Model: Redefinition Level", "Students produce a collaborative documentary video, conduct live video-conference interviews with international scientists, and publish their findings globally to solicit public feedback. In SAMR, this is:", "Redefinition (creation of novel tasks previously inconceivable without technology).", ["Substitution.", "Augmentation.", "Modification."], "At the Redefinition level, technology enables the creation of new learning tasks that were previously inconceivable in a traditional classroom."),
  ("ASSURE Instructional Design Model (Heinich & Molenda)", "In the ASSURE instructional design model for technology integration, what does the acronym ASSURE stand for?", "Analyze learners, State standards/objectives, Select strategies/media, Utilize media/materials, Require learner participation, and Evaluate/revise.", ["Assess readiness, Standardize curriculum, Survey technology, Utilize hardware, Review software, and Examine test scores.", "Acquire computers, Set up networks, Supervise classrooms, Upgrade servers, Run programs, and Execute grading.", "Apply pedagogy, Structure lessons, Systematize grading, Unify assessments, Regulate media, and Enhance retention."], "ASSURE is an instructional model: Analyze learners, State objectives, Select strategies/technology/media, Utilize media/materials, Require learner participation, Evaluate and revise."),
  ("ASSURE Model: 'R' (Require Learner Participation)", "Why is the step 'Require Learner Participation' crucial in the ASSURE model?", "Because effective learning requires active cognitive engagement, practice, and feedback rather than passive media consumption.", ["Because students must manually clean the computer laboratory hardware.", "Because teachers must record attendance every 5 minutes.", "Because standardized testing requires computer software practice."], "Active learner participation ensures that students interact meaningfully with the media, practice new skills, and receive formative feedback."),
  ("UNESCO ICT Competency Framework for Teachers (ICT-CFT)", "The UNESCO ICT Competency Framework for Teachers outlines three successive approaches to ICT integration in schools in which order?", "Technology Literacy, Knowledge Deepening, and Knowledge Creation.", ["Hardware Acquisition, Network Maintenance, and Server Programming.", "Basic Typing, Internet Surfing, and Social Media Posting.", "Textbook Digitization, Automated Testing, and Online Attendance."], "The UNESCO ICT-CFT structures teacher development into three phases: Technology Literacy (basic tool use), Knowledge Deepening (complex problem solving), and Knowledge Creation (generating new knowledge and innovation)."),
  ("ICT-CFT: Knowledge Creation Approach", "A teacher who mentors students to identify community health challenges, design original mobile health apps, and collaborate with local clinics is operating at which UNESCO ICT-CFT approach?", "Knowledge Creation approach (fostering innovation, higher-order problem solving, and continuous learning).", ["Technology Literacy approach.", "Knowledge Deepening approach.", "Basic ICT adoption approach."], "The Knowledge Creation approach aims to develop learners and citizens who innovate, create new knowledge, and solve complex societal problems using ICT."),
  ("PPST Domain 1: ICT Integration Indicator 1.3", "PPST Indicator 1.3.2 requires Proficient Teachers to 'Show skills in the positive use of ICT to facilitate the teaching and learning process.' A positive use of ICT means:", "Leveraging digital tools strategically to enhance learner engagement, critical thinking, and accessibility while ensuring digital safety.", ["Allowing students to play unmoderated online video games whenever they finish seatwork.", "Replacing all teacher-student human interactions with automated recorded videos.", "Using social media to publicly post students' low test scores."], "Positive use of ICT entails pedagogically purposeful, safe, ethical, and effective application of digital tools to enhance learning."),
  ("Digital Citizenship (Ribble's Nine Elements)", "Mike Ribble identifies nine elements of Digital Citizenship. Which element encompasses the electronic exchange of information and adherence to professional online netiquette?", "Digital Communication & Digital Etiquette (Netiquette).", ["Digital Commerce.", "Digital Law.", "Digital Health & Wellness."], "Digital Communication addresses electronic exchange of information; Digital Etiquette focuses on the electronic standards of conduct and mindful online behavior.")
]
d.extend([
  ("Digital Citizenship: Digital Footprint", "In teaching digital citizenship, what is a 'Digital Footprint' and why must students be mindful of it?", "The permanent trail of data, posts, photos, and activity left behind on the internet that can impact future academic and career opportunities.", ["The physical size of a computer mousepad.", "The electrical energy consumed by a smartphone charger.", "The brand name of a student's tablet device."]),
  ("Digital Citizenship: Digital Law & Intellectual Property", "Which of the following actions constitutes an ethical and legal violation of intellectual property in digital educational environments?", "Downloading and distributing pirated commercial software or claiming copyrighted online artwork as one's own without attribution.", ["Citing a published open-access journal article with proper APA reference.", "Using Creative Commons licensed images in accordance with their CC-BY terms.", "Linking to a publicly available educational video on YouTube."]),
  ("Copyright & Fair Use in Education", "Under Intellectual Property Law (RA 8293) and the Fair Use doctrine, a teacher is legally and ethically permitted to:", "Reproduce brief excerpts, poems, or diagrams from copyrighted works for non-profit, face-to-face educational commentary and classroom instruction.", ["Photocopy an entire commercial textbook and sell it for profit to students.", "Upload copyrighted commercial Hollywood blockbuster movies to a public website.", "Strip the original author's name from an academic article and replace it with the teacher's name."]),
  ("Creative Commons Licenses: CC BY-NC-ND", "What does a 'CC BY-NC-ND' Creative Commons license indicate regarding the reuse of an educational material?", "Attribution required (BY), Non-Commercial use only (NC), and No Derivatives / adaptations permitted (ND).", ["Public domain with zero copyright restrictions.", "Commercial resale permitted with no author attribution.", "Free to modify and remix for corporate advertisements."]),
  ("Open Educational Resources (OER)", "What is the defining characteristic of Open Educational Resources (OER)?", "Teaching and learning materials in the public domain or released under an open license that permit free access, reuse, adaptation, and sharing.", ["High-priced proprietary software requiring annual subscription fees.", "Encrypted textbooks that self-delete after 30 days.", "Secret research documents restricted to university presidents."]),
  ("Learning Management Systems (LMS)", "A platform such as Moodle, Canvas, or Google Classroom is classified as a Learning Management System (LMS) because it:", "Administers, documents, tracks, reports, and delivers educational courses and learning content in a structured digital environment.", ["Manufactures computer microchips and server hardware.", "Blocks all student internet access permanently.", "Functions solely as an automated spreadsheet calculator."]),
  ("Blended Learning Models: Flipped Classroom", "In a Flipped Classroom blended learning rotation, how is instruction organized?", "Direct instruction (recorded mini-lectures / readings) is accessed asynchronously at home, while synchronous class time is devoted to active collaborative problem solving.", ["Students listen to lectures in class and do multiple-choice tests at home alone.", "The teacher grades papers in silence during class hours while students sleep.", "All learning is 100% textbook reading without any teacher interaction."]),
  ("Blended Learning: Station Rotation Model", "In a 'Station Rotation' blended learning model, students within a single classroom rotate on a fixed schedule between:", "Online digital instruction, teacher-led small-group instruction, and collaborative peer project stations.", ["Different physical schools across the province every week.", "Different sports teams on the athletic field.", "Sleeping areas and study areas every 5 minutes."]),
  ("Synchronous vs Asynchronous Online Learning", "What is the fundamental pedagogical difference between Synchronous and Asynchronous online learning?", "Synchronous occurs in real-time with live interaction (e.g., live Zoom class), while Asynchronous occurs at flexible, self-paced times (e.g., discussion boards).", ["Synchronous uses only text, while Asynchronous uses only video.", "Synchronous requires zero internet connection, while Asynchronous requires satellites.", "Synchronous is for elementary pupils, while Asynchronous is for doctoral students only."]),
  ("Educational Multimedia: Mayer's Cognitive Theory of Multimedia Learning", "Richard Mayer's Cognitive Theory of Multimedia Learning is based on which three foundational assumptions?", "Dual Channels (visual/auditory), Limited Capacity (working memory), and Active Processing (filtering/organizing/integrating).", ["Infinite Memory, Single Channel, and Passive Absorption.", "Short-Term Reflex, Long-Term Instinct, and Genetic Imprinting.", "Left Brain, Right Brain, and Subconscious Processing."]),
  ("Mayer's Multimedia Principle", "According to Mayer's Multimedia Principle, people learn significantly better from:", "Words and pictures combined, rather than from words alone.", ["Monochrome text alone without any visual illustrations.", "Continuous loud background music playing during lectures.", "Flashing neon animations on every single sentence."]),
  ("Mayer's Coherence Principle", "Mayer's 'Coherence Principle' in instructional design states that learners perform better when:", "Extraneous words, pictures, sounds, and background music are EXCLUDED rather than included.", ["Every available inch of the presentation slide is filled with decorative clip art.", "Loud rock music plays continuously during science explanations.", "Unrelated funny memes are inserted into serious medical diagrams."]),
  ("Mayer's Redundancy Principle", "According to Mayer's 'Redundancy Principle', learning is hindered when a presenter:", "Presents identical on-screen text, graphics, AND reads the text verbatim simultaneously, overloading the visual and auditory channels.", ["Presents spoken narration accompanied by relevant graphics.", "Uses concise bullet points with visual diagrams.", "Provides a printed summary handout after class."]),
  ("Mayer's Spatial & Temporal Contiguity Principles", "The 'Contiguity Principle' in multimedia design dictates that corresponding words and graphics should be:", "Placed physically close to each other on the screen (spatial) and presented at the same time (temporal).", ["Placed on completely separate pages with a 10-minute time delay.", "Hidden behind secret password screens.", "Printed in tiny 4pt font at the bottom of the page."]),
  ("Educational Technology: Web 2.0 vs Web 1.0 Tools", "How do Web 2.0 tools (e.g., Wikis, collaborative blogs, interactive simulations, Canva) fundamentally differ from early Web 1.0 websites?", "Web 2.0 empowers users to actively create, collaborate, remix, and share user-generated content rather than passively reading static web pages.", ["Web 2.0 operates without electricity or internet connections.", "Web 2.0 is restricted to government military agencies.", "Web 2.0 displays only black-and-white plain text without images."])
])
d.extend([
  ("Assistive Technology: Screen Readers (Accessibility)", "An 'Assistive Technology' such as NVDA or JAWS (Screen Readers) enables students with severe visual impairments to learn by:", "Converting digital on-screen text and image alt-text into synthesized audio speech or refreshable Braille output.", ["Projecting holographic laser images onto the classroom whiteboard.", "Automatically answering multiple-choice exam questions.", "Translating English text into 16th-century Latin."]),
  ("Assistive Technology: Speech-to-Text (Dictation)", "Speech-to-Text software (such as voice typing) provides vital accommodation for students with physical motor disabilities or dysgraphia by:", "Transcribing spoken words into typed digital text without requiring manual keyboard typing.", ["Reading aloud printed physical textbooks.", "Formatting raw mathematical equations into 3D animations.", "Blocking background classroom noise."]),
  ("Mobile Learning (m-Learning) Pedagogies", "Which of the following is a primary pedagogical affordance of Mobile Learning (m-Learning) in education?", "Ubiquitous, contextual, 'anytime-anywhere' access to micro-learning modules and collaborative communication.", ["Eliminating the need for all teachers, schools, and curricula.", "Forcing students to play video games for 10 hours daily.", "Replacing all scientific laboratory experiments with text messages."]),
  ("Gamification: Badges & Leaderboards (Deterding)", "In educational technology, 'Gamification' (Sebastian Deterding) differs from 'Educational Games' (Game-Based Learning) because gamification:", "Integrates game-design mechanics (e.g., progress bars, experience points, quest milestones) into non-game learning activities.", ["Requires students to play full commercial adventure video games for credit.", "Involves gambling real currency on test outcomes.", "Replaces all academic reading with sports competitions."]),
  ("Game-Based Learning (GBL): Minecraft Education", "Using Minecraft Education Edition in a social studies class to reconstruct the ancient walled city of Intramuros is an example of:", "Game-Based Learning (using a structured game environment to achieve specific curricular learning goals).", ["Gamification mechanics.", "Passive multimedia consumption.", "Rote memorization drill."]),
  ("Virtual Reality (VR) in Education: Immersive Learning", "Immersive Virtual Reality (VR) headsets enhance science and medical education primarily by providing:", "High-presence, 360-degree interactive 3D simulations of hazardous, microscopic, or remote environments (e.g., inside a human heart or outer space).", ["Traditional flat text reading on a 2D screen.", "Automated multiple-choice grading spreadsheets.", "A replacement for all physical nutrition."]),
  ("Augmented Reality (AR) in Education", "How does Augmented Reality (AR, e.g., using a tablet camera to overlay 3D beating heart models onto a paper worksheet) differ from Virtual Reality (VR)?", "AR overlays digital information and 3D graphics onto the real physical world, whereas VR replaces the real world with a fully simulated digital environment.", ["AR requires complete sensory isolation in a dark room, while VR does not.", "AR operates only on desktop computers from the 1990s.", "AR is strictly for audio listening without visual display."]),
  ("Cybersecurity in Education: Phishing and Malware", "A teacher receives an email appearing to come from the school principal asking for student login credentials and passwords via an external link. The teacher should:", "Recognize this as a potential 'Phishing' cyber-attack, avoid clicking the link, and report it immediately to the IT security officer.", ["Immediately reply with all student passwords to be helpful.", "Forward the email to all students so they can enter their passwords.", "Post the password link on the public school Facebook page."]),
  ("Data Privacy in Online Learning (RA 10173)", "When publishing student achievement photos, awards, or video presentations on the public school website, a teacher must ensure compliance with RA 10173 by:", "Securing explicit parental/guardian consent and avoiding the public disclosure of sensitive personal identifiers (e.g., home addresses, student ID numbers).", ["Posting full birth certificates and medical records of all pupils publicly.", "Selling student contact numbers to commercial marketing companies.", "Refusing to allow parents to view school events."]),
  ("Artificial Intelligence in Education (AIED): Adaptive Learning", "In contemporary educational technology, 'Adaptive Learning Systems' (e.g., intelligent tutoring software) benefit diverse learners by:", "Dynamically adjusting the difficulty, pacing, and scaffolding of instructional content in real-time based on individual learner performance and error patterns.", ["Assigning identical homework exercises to all 50 students regardless of skill.", "Automatically failing students who do not complete quizzes in 60 seconds.", "Replacing human teachers with robotic police officers."]),
  ("Ethics of Generative AI in Student Work", "When students use Generative AI tools (such as ChatGPT) to assist in drafting research essays, academic integrity ethically requires that they:", "Transparently cite and disclose the use of AI, verify all factual claims and sources independently, and ensure the core analysis and writing represent their own authentic intellectual work.", ["Copy and paste AI-generated text verbatim and claim full personal authorship.", "Fabricate false laboratory data using AI without testing.", "Submit AI-generated essays without reading or understanding them."]),
  ("AI Hallucinations in Education", "In educational research, what is an 'AI Hallucination' and why must students be trained to detect it?", "A phenomenon where Large Language Models generate plausible-sounding but factually false, invented, or fabricated citations and information with high confidence.", ["When a computer screen emits optical illusions that hypnotize the viewer.", "When computer speakers produce acoustic echo feedback.", "When an algorithm refuses to turn on during daytime hours."]),
  ("Instructional Video Design: Microlearning Principles", "Cognitive research in educational video design indicates that instructional video segments are most effective for learner retention when they:", "Are concise and modular (microlearning: 3 to 6 minutes long), focused on a single clear learning objective, and accompanied by guiding questions.", ["Are 2 hours long with uninterrupted continuous monotone lecture audio.", "Feature loud rock music playing over quiet spoken explanations.", "Contain no visual diagrams and only tiny 6pt scrolling text."]),
  ("Collaborative Digital Tools: Padlet and Jamboard", "Using an interactive digital wall (such as Padlet) at the beginning of a lesson allows a teacher to:", "Collect, organize, and visually display prior knowledge, brainstorms, and multimedia responses from all students simultaneously in real time.", ["Conduct a 100-item high-stakes final examination.", "Print physical textbook volumes for the school library.", "Block all student collaborative communication."]),
  ("Electronic Portfolios (e-Portfolios) in Assessment", "An 'e-Portfolio' is an authentic digital assessment tool that serves to:", "Collect, showcase, and reflect upon a curated body of student artifacts, projects, and developmental growth over time.", ["Record only multiple-choice raw exam scores.", "Store administrative receipts for school tuition payments.", "Function as a speed-typing competition scoreboard."])
])
d.extend([
  ("Digital Rubrics in Assessment: Rubric Affordances", "Using digital rubric evaluation tools inside an LMS (e.g., Canvas SpeedGrader or Google Classroom Rubrics) improves assessment because:", "It provides transparent, criteria-based diagnostic feedback linked directly to specific student submission points with consistent scoring efficiency.", ["It eliminates the need for teachers to evaluate student work.", "It automatically assigns an 'A' grade to every student.", "It removes all subjective judgment by standardizing multiple-choice questions."]),
  ("Formative Assessment Tech: Kahoot, Quizizz, Mentimeter", "Using interactive formative polling tools (e.g., Kahoot, Quizizz, Mentimeter) during a lesson helps the teacher to:", "Obtain real-time diagnostic data on class understanding, identify common misconceptions instantly, and adjust instruction immediately.", ["Assign permanent failing marks on report cards.", "Replace all classroom group discussions with silent typing.", "Force students to compete for monetary prizes."]),
  ("Computer-Based Testing (CBT): Computerized Adaptive Testing (CAT)", "In 'Computerized Adaptive Testing' (CAT), the testing algorithm selects each subsequent question based on:", "The test-taker's performance on previous items (giving harder items after correct answers, and easier items after incorrect answers) to estimate ability precisely.", ["A purely random sequence of questions from a 10,000-item bank.", "The student's chronological age and alphabetical last name.", "The time of day the student logs into the examination terminal."]),
  ("Podcast in Education: Auditory Learning Affordances", "Having students create and publish their own educational 'Podcasts' on local history topics develops which competencies?", "Research synthesis, oral communication, scriptwriting, audio digital editing, and storytelling skills.", ["Manual handwriting and calligraphy dexterity.", "Physical athletic endurance.", "Mechanical typewriter repair."]),
  ("Infographics in Education: Visual Information Literacy", "Having students design an 'Infographic' (using Canva or Piktochart) to summarize climate change impacts teaches them to:", "Synthesize complex statistical data, identify key messages, and communicate information visually using hierarchy, icons, and concise text.", ["Copy and paste 50 pages of raw text without editing.", "Memorize dictionary definitions without visual aids.", "Write computer assembly code for hardware processors."]),
  ("Digital Storytelling: Educational Affordances", "Digital Storytelling combines traditional narrative storytelling with digital multimedia (images, voiceover, music, video clips) primarily to:", "Deepen emotional engagement, foster personal voice, and enhance multimodal literacy across learning areas.", ["Replace all standard reading and writing instruction with video gaming.", "Allow students to watch television cartoons during class time.", "Eliminate the need for narrative story structure."]),
  ("Social Media in Professional Teacher Development (PLNs)", "How do professional educators leverage social media platforms (e.g., Twitter/X educational chats, LinkedIn, Facebook teacher groups)?", "To build Personal Learning Networks (PLNs), share open educational resources, discuss evidence-based pedagogies, and collaborate globally.", ["To post confidential student disciplinary records publicly.", "To engage in partisan political arguments during classroom hours.", "To sell commercial consumer products to students' parents."]),
  ("Distance Education: Moore's Theory of Transactional Distance", "Michael G. Moore's Theory of Transactional Distance posits that the psychological and communications gap in distance learning is determined by:", "The dynamic interplay of Dialogue (interaction), Structure (course rigidity/flexibility), and Learner Autonomy.", ["The physical geographic distance in kilometers between student and school.", "The monetary cost of internet broadband subscription packages.", "The physical weight of printed modular textbooks."]),
  ("Distance Education: Reducing Transactional Distance", "To reduce transactional distance and prevent learner isolation in an online course, an instructor should:", "Increase timely, meaningful dialogue, provide frequent interactive feedback, and facilitate collaborative peer activities.", ["Make the course completely rigid with zero opportunities for student-teacher communication.", "Require students to study completely alone for 10 months without check-ins.", "Upload 500 pages of unannotated PDF readings with zero guidance."]),
  ("Flipped Learning: In-Class Active Learning Strategies", "In a properly implemented Flipped Classroom, the freed classroom time should be used primarily for:", "Higher-order collaborative tasks, hands-on lab experiments, debates, case study analysis, and individualized teacher coaching.", ["Having students watch the lecture video again in complete silence.", "Administering 3-hour multiple-choice standardized tests.", "Letting students do personal homework from other subjects."]),
  ("WebQuests: Bernie Dodge's Inquiry Framework", "A 'WebQuest' (developed by Bernie Dodge) is an inquiry-oriented instructional lesson format in which:", "Most or all of the information that learners interact with comes from curated resources on the World Wide Web.", ["Students search random commercial websites without teacher guidance.", "Students play online video games for 60 minutes.", "The teacher lectures from printed textbooks with zero internet use."]),
  ("WebQuest Components: Standard Structure", "What are the standard structural components of a well-designed WebQuest?", "Introduction, Task, Process, Resources, Evaluation (Rubric), and Conclusion.", ["Title, Index, Bibliography, Appendix, and Glossary.", "Abstract, Methodology, Results, Discussion, and References.", "Login, Password, Captcha, Firewall, and Logout."]),
  ("Technological Equity: The Access Divide vs The Usage Divide", "While the 'First-Level Digital Divide' concerns inequalities in physical access to hardware and internet connectivity, the 'Second-Level Digital Divide' concerns:", "Inequalities in digital literacy, critical thinking skills, and the pedagogical quality of how technology is utilized for learning.", ["The difference in screen brightness between two tablet computers.", "The color of computer cables installed in school classrooms.", "The physical weight of laptop bags carried by students."]),
  ("Digital Wellness: Screen Time & Ergonomics", "In teaching digital health and wellness, teachers must guide students in 'Digital Ergonomics' by promoting:", "Proper posture, 20-20-20 screen eye breaks (looking 20 feet away for 20 seconds every 20 minutes), and balanced physical activity.", ["Staring at smartphone screens in total darkness for 8 continuous hours.", "Slouching over laptops on the floor without breaks.", "Using maximum screen brightness with zero eye blink breaks."]),
  ("Assistive Tech: Universal Design for Learning (UDL) in EdTech", "How does EdTech support the UDL principle of 'Multiple Means of Action and Expression'?", "By allowing learners to demonstrate mastery through diverse digital mediums—such as creating a video, recording a podcast, coding a game, or writing a blog post.", ["By forcing all learners to submit identical handwritten 5-page essays.", "By restricting all assessments to timed multiple-choice scantron sheets.", "By eliminating all forms of student choice in project formats."])
])
d.extend([
  ("Community of Inquiry (CoI) Framework (Garrison, Anderson, Archer)", "The Community of Inquiry (CoI) model for online and blended learning asserts that effective educational experiences require the intersection of which three presences?", "Cognitive Presence, Social Presence, and Teaching Presence.", ["Technological Presence, Hardware Presence, and Software Presence.", "Administrative Presence, Financial Presence, and Legal Presence.", "Physical Presence, Somatic Presence, and Biological Presence."]),
  ("CoI Framework: Teaching Presence", "In the Community of Inquiry model, 'Teaching Presence' is established by the instructor through:", "Instructional design, organization of learning activities, facilitating meaningful discourse, and providing direct instruction and timely feedback.", ["Setting automated grading bots to assign random test scores.", "Remaining completely silent and never responding to student messages.", "Uploading 1,000 pages of text with zero course navigation structure."]),
  ("CoI Framework: Social Presence", "In an asynchronous online class, 'Social Presence' is demonstrated when learners:", "Present themselves as real, authentic people through personal introductions, collaborative tone, emotional expression, and supportive peer communication.", ["Post only robotic, one-word automated responses.", "Never interact with any peers or instructors during the semester.", "Use anonymous pseudonyms to insult classmates."]),
  ("Educational Data Mining & Learning Analytics", "In educational technology, 'Learning Analytics' involves collecting and analyzing learner digital trace data (e.g., login frequency, video completion, quiz attempts) primarily to:", "Understand and optimize learning processes, identify at-risk students early, and provide timely personalized instructional interventions.", ["Sell student personal data to commercial advertisers for profit.", "Publicly shame low-performing students on school leaderboards.", "Automate the immediate expulsion of struggling learners."]),
  ("Digital Assessment Security: Plagiarism Detection Tools", "When using automated plagiarism detection software (e.g., Turnitin), a teacher must interpret the 'Similarity Index' by:", "Carefully inspecting the matched text in context to distinguish legitimate properly cited quotes from actual uncredited copying.", ["Automatically failing any student who has a similarity index above 0%.", "Assuming that the computer algorithm's percentage is infallible without review.", "Ignoring all matches and assigning arbitrary letter grades."]),
  ("Video Conferencing Netiquette: Breakout Rooms", "When facilitating small-group discussions in Zoom/Teams Breakout Rooms, best pedagogical practice requires the teacher to:", "Set clear tasks/roles with a shared collaborative workspace, provide explicit time limits, and actively visit/monitor rooms to support discussions.", ["Leave the main room and disconnect from the internet for 60 minutes.", "Place 50 students in a single breakout room with no assigned task.", "Mute all student microphones and turn off all cameras permanently."]),
  ("Open Source Software in Education (OSS)", "Using Open Source Software (such as GIMP for image editing, Audacity for audio recording, or LibreOffice) in schools provides the advantage of:", "Zero licensing costs, freedom to install on unlimited devices, and the ability to customize and distribute legally without piracy.", ["Requiring expensive monthly corporate subscription fees per student.", "Self-deleting from computers after 14 days of use.", "Being completely incompatible with all operating systems."]),
  ("Gamified Learning Platforms: ClassDojo & Positive Behavior", "Using a gamified classroom management app (like ClassDojo) effectively involves:", "Reinforcing positive character values (e.g., teamwork, persistence, helping others) through immediate constructive feedback and parent communication.", ["Using public point deductions to publicly shame and humiliate struggling pupils.", "Replacing all academic teaching with point-collecting competitions.", "Posting student behavioral points on commercial public billboards."]),
  ("Online Discussions: Asynchronous Threaded Forums", "To foster higher-order critical thinking in an asynchronous discussion forum, an instructor should design prompts that:", "Are open-ended, controversial, or case-based, requiring students to synthesize evidence, apply concepts, and evaluate peer arguments.", ["Ask simple factual recall questions that have a single one-word correct answer.", "Ask students to copy and paste paragraph 1 from the textbook.", "Require students to post 50 identical responses within 5 minutes."]),
  ("Cloud Computing in Education (Google Workspace / Microsoft 365)", "Cloud-based educational suites transform classroom workflow because they enable:", "Real-time simultaneous collaborative document editing, automated continuous saving, and seamless cross-device file accessibility.", ["The physical printing of 5,000 pages of paper every day.", "Complete disconnection from school server networks.", "The destruction of all previous student project drafts."]),
  ("Digital Literacy: Evaluating Digital Sources (The SIFT Method)", "Mike Caulfield's 'SIFT' methodology for evaluating online information and combating digital misinformation stands for:", "Stop, Investigate the source, Find better coverage, and Trace claims, quotes, and media back to the original context.", ["Search, Inspect, Forward, and Tweet.", "Skim, Ignore, Finalize, and Transmit.", "Scan, Illustrate, Format, and Type."]),
  ("Interactive Whiteboards (IWB) Pedagogical Affordances", "An Interactive Whiteboard (IWB) moves beyond a traditional chalkboard when a teacher utilizes it to:", "Manipulate dynamic 3D geometry models, annotate digital primary sources collaboratively, and save annotated lessons for student review.", ["Use it strictly as a static projection screen for 60 minutes of uninterrupted PowerPoint text.", "Write with standard permanent markers that damage the screen.", "Display a static clock on the wall."]),
  ("Audio-Visual Materials: Educational Podcasting (Scripting)", "Before recording an educational podcast, students must engage in 'Pre-Production', which fundamentally involves:", "Conducting thorough topic research, drafting an organized conversational script/outline, and planning sound effects and cues.", ["Speaking randomly into a microphone without prior preparation.", "Buying $10,000 professional recording studio equipment.", "Reading a dictionary aloud from start to finish."]),
  ("Blended Learning: HyFlex Model (Hybrid Flexible)", "The 'HyFlex' (Hybrid Flexible) course design model provides students the choice to:", "Participate synchronously in-person in the physical classroom, synchronously online via video conference, OR asynchronously online, with all modes achieving equivalent learning outcomes.", ["Attend class only on weekends without taking any exams.", "Choose their own letter grades at the start of the semester.", "Take all courses without any teacher instruction or materials."]),
  ("Technological Pedagogical Synthesis: 21st Century Digital Teacher", "Ultimately, the primary goal of educational technology integration is NOT to use technology for its own sake, but to:", "Empower and enhance student-centered learning, foster higher-order thinking and creativity, and expand equitable educational access.", ["Replace all certified human teachers with automated computer software.", "Spend the entire school annual budget on expensive hardware gadgets.", "Force students to sit in front of computer screens for 12 hours daily."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item evaluates educational technology competence in {item[0]}. {item[2]} represents standard TPACK, SAMR, and digital learning design best practice."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('techTeachingLearningExams.ts', 'TECH_TEACHING_LEARNING_EXAM_QUESTIONS', questions)
