import sys
sys.path.append('src/scripts')
from builder_core import q, save

d = [
  ("Philosophy of Self: Socrates", "Socrates famously declared that 'An unexamined life is not worth living.' In Socratic philosophy, genuine self-knowledge is achieved through:", "Relentless critical self-questioning, introspective dialogue, and pursuing moral virtue over material desires.", ["Passive obedience to prevailing aristocratic social conventions.", "Accumulating immense material fortunes through trade monopolies.", "Memorizing astrological horoscopes to determine destiny."], "Socrates believed true selfhood is found in the immortal rational soul (psyche), and that living well requires continuous philosophical examination and virtue."),
  ("Philosophy of Self: Plato's Tripartite Soul", "In Plato's Republic, the human psyche (soul) is conceptualized as comprising three distinct components:", "Rational (reason), Spirited (passions/will), and Appetitive (bodily desires).", ["Conscious, Subconscious, and Unconscious.", "Id, Ego, and Superego.", "Somatic, Intellectual, and Spiritual."], "Plato divided the soul into Reason (guides and seeks truth), Spirit (courage and honor), and Appetite (bodily urges like hunger and thirst)."),
  ("Philosophy of Self: St. Augustine", "St. Augustine of Hippo integrated Platonic thought with Christian theology, viewing the human self as:", "A restless soul seeking its ultimate home, peace, and truth in God.", ["A purely biological machine governed exclusively by physical laws.", "A tabula rasa devoid of any spiritual essence.", "A temporary illusion created by social conventions."], "Augustine famously wrote in Confessions: 'Our heart is restless until it rests in You,' seeing the self as a spiritual entity oriented toward God."),
  ("Philosophy of Self: Rene Descartes", "Rene Descartes arrived at his foundational philosophical certainty 'Cogito, ergo sum' (I think, therefore I am) through:", "Methodological doubt, concluding that the act of doubting logically proves the existence of a thinking entity (res cogitans).", ["Empirical observation of external physical biological anatomy.", "Consulting ancient monarchical legal decrees.", "Measuring electrical neural impulses with laboratory instruments."], "Descartes doubted everything that could possibly be doubted, realizing that he could not doubt that he was doubting, which proved his existence as a thinking substance."),
  ("Philosophy of Self: John Locke", "John Locke rejected innate ideas, proposing that at birth the human mind is a 'Tabula Rasa' (blank slate). For Locke, personal identity is founded on:", "Consciousness and continuous memory across time.", ["Physical bodily continuity and identical biological cells.", "An unchanging, metaphysical, immaterial substance.", "Hereditary aristocratic bloodlines."], "Locke argued that personal identity consists in psychological continuity—specifically consciousness and the memory of one's past experiences."),
  ("Philosophy of Self: David Hume", "David Hume's empiricist investigation of the self led to his famous 'Bundle Theory', which asserts that:", "There is no static, permanent 'self', only a dynamic bundle of fleeting, ever-changing sensory perceptions.", ["The self is an immortal, indivisible spiritual diamond inside the brain.", "The self is created entirely by formal constitutional legislation.", "The self is an innate mathematical blueprint present before birth."], "Hume observed that whenever he looked introspectively, he only encountered specific perceptions (heat, cold, light, pain), concluding there is no constant underlying self."),
  ("Philosophy of Self: Immanuel Kant", "Immanuel Kant synthesized rationalism and empiricism by proposing that the 'Self' is:", "An actively organizing transcendental subject that synthesizes raw sensory impressions into unified, coherent experience.", ["A passive mirror that mechanically reflects physical light rays.", "A collection of totally random chemical reactions in the bloodstream.", "An imaginary fiction with zero organizing function."], "Kant argued that without an active transcendental unity of apperception to organize sensory data according to categories (space, time, causality), conscious experience would be impossible."),
  ("Philosophy of Self: Gilbert Ryle", "Gilbert Ryle attacked Cartesian dualism as the myth of the 'Ghost in the Machine', arguing that the self is best understood as:", "A pattern of observable human behaviors, dispositions, and actions rather than an internal hidden entity.", ["An ethereal phantom residing inside the pineal gland.", "A divine spark trapped within corrupt physical flesh.", "An unchanging spiritual substance separate from physical matter."], "Ryle's logical behaviorism asserts that mental states are not hidden internal occurrences but dispositions to act in certain observable ways in specific contexts."),
  ("Philosophy of Self: Maurice Merleau-Ponty", "Maurice Merleau-Ponty's phenomenological perspective asserts that the self is fundamentally an 'Embodied Subjectivity', meaning:", "The mind and physical body are indissolubly integrated; we perceive and experience the world through our living body.", ["The body is merely a disposable vehicle for a detached intellectual spirit.", "The mind exists exclusively in external digital computer cloud servers.", "Physical sensations are completely irrelevant to human self-consciousness."], "Merleau-Ponty rejected dualism, asserting that consciousness, the body, and the world are fundamentally intertwined in living bodily experience."),
  ("Sociology of Self: George Herbert Mead's 'I and Me'", "According to George Herbert Mead's symbolic interactionism, what is the difference between the 'I' and the 'Me'?", "The 'I' is the spontaneous, creative, impulsive self, while the 'Me' is the socialized self that internalizes societal expectations.", ["The 'I' is the physical body, while the 'Me' is the digital avatar.", "The 'I' is the conscious mind, while the 'Me' is the subconscious id.", "The 'I' is the legal citizen, while the 'Me' is the political leader."], "Mead's 'Me' represents learned societal attitudes and rules (the generalized other), while the 'I' is the individual's spontaneous, novel response to the 'Me'."),
  ("Sociology of Self: The Generalized Other", "In Mead's theory of social development, reaching the 'Game Stage' allows a child to internalize the 'Generalized Other', which is:", "The widespread cultural norms, values, and expectations of the broader social community.", ["The rules of a specific single board game played at home.", "The direct command of an individual biological mother.", "The imaginary fantasy persona created during solo play."], "The Generalized Other is the internalized perspective of the entire community, enabling cooperative, organized social functioning."),
  ("Sociology of Self: Charles Horton Cooley", "Charles Horton Cooley formulated the concept of the 'Looking-Glass Self', which posits that our self-concept develops through:", "Imagining how we appear to others, imagining their judgment of that appearance, and developing an emotional self-feeling.", ["Looking at our physical reflection in bathroom glass mirrors every morning.", "Reading daily astrological horoscope columns in newspapers.", "Undergoing standardized computer personality aptitude tests."], "The Looking-Glass Self asserts that we use others as a social mirror, shaping our identity based on our perceptions of how others view and evaluate us."),
  ("Anthropology of Self: Egocentric vs Sociocentric", "In anthropological studies, how does an 'Egocentric Self' (typical in Western cultures) contrast with a 'Sociocentric Self' (typical in Asian/Filipino cultures)?", "Egocentric views the self as autonomous and distinct, while Sociocentric views the self as fundamentally relational and interdependent.", ["Egocentric refers to criminal selfishness, while Sociocentric refers to state communism.", "Egocentric means living in rural areas, while Sociocentric means living in urban cities.", "Egocentric relies on biological instincts, while Sociocentric relies on digital algorithms."], "Western cultures tend to emphasize individual autonomy and independence (egocentric), whereas collectivist societies view identity as relational and embedded in community (sociocentric)."),
  ("Psychology of Self: William James' 'Me-Self'", "William James divided the self into the 'I' (the self as knower/pure ego) and the 'Me' (the self as known/empirical self). The 'Me-Self' encompasses:", "The Material Self, Social Self, and Spiritual Self.", ["The Conscious, Subconscious, and Superconscious Self.", "The Physical, Chemical, and Biological Self.", "The Primary, Secondary, and Tertiary Self."], "James categorized the empirical 'Me' into: Material (body, clothes, possessions), Social (recognition from others), and Spiritual (inner psychological core and consciousness)."),
  ("Psychology of Self: Carl Rogers' Real vs Ideal Self", "Carl Rogers' Humanistic theory asserts that psychological well-being and self-actualization occur when there is high 'Congruence' between:", "The Real Self (who one actually is) and the Ideal Self (who one aspires to be).", ["The Conscious Ego and the Collective Unconscious.", "The Material Self and the Financial Balance Sheet.", "The Physical Body Mass Index and Social Media Popularity."], "Rogers emphasized that mental health is characterized by congruence—harmony and alignment—between one's real self-experience and idealized aspirations.")
]
d.extend([
  ("Psychology of Self: Carl Rogers' Incongruence", "When an individual experiences a wide gap between their Real Self and unrealistic societal demands in their Ideal Self, Carl Rogers warns that this leads to:", "Incongruence, resulting in anxiety, low self-worth, and psychological maladjustment.", ["Automatic intellectual genius.", "Instant enlightenment and spiritual transcendence.", "Complete biological immunity to physical diseases."]),
  ("Psychology of Self: Sigmund Freud's Structural Model", "In Freudian psychoanalysis, which structural component of the personality operates on the 'Reality Principle', mediating between instinctual drives and moral constraints?", "The Ego.", ["The Id (operates on the Pleasure Principle).", "The Superego (operates on the Morality Principle).", "The Collective Unconscious."]),
  ("Psychology of Self: Freud's Superego", "In Freud's theory, the component of personality that internalizes parental, cultural, and moral standards, functioning as the moral conscience, is:", "The Superego.", ["The Id.", "The Ego.", "The Libido."]),
  ("Psychology of Self: Carl Jung's Archetypes (Persona)", "In Carl Jung's analytical psychology, the 'Persona' represents:", "The public social mask or facade an individual presents to the external world to adapt to society.", ["The hidden, repressed, dark, and animalistic aspects of the self (The Shadow).", "The unconscious feminine archetype in a man (Anima).", "The unconscious masculine archetype in a woman (Animus)."]),
  ("Psychology of Self: Carl Jung's Shadow", "According to Carl Jung, psychological wholeness and individuation require that a person acknowledge and integrate the 'Shadow', which is:", "The repressed, unacknowledged desires, instincts, and dark impulses of the unconscious self.", ["The public resume used for corporate employment.", "The conscious mathematical reasoning faculty.", "The biological circadian rhythm of sleep cycles."]),
  ("Psychology of Self: Albert Bandura's Self-Efficacy", "Albert Bandura's Social Cognitive Theory defines 'Self-Efficacy' as:", "An individual's belief in their own capability to organize and execute courses of action required to achieve designated goals.", ["An individual's overall emotional feeling of global self-worth.", "A person's genetic intelligence quotient score.", "The total monetary value of one's accumulated assets."]),
  ("Psychology of Self: Sources of Self-Efficacy", "According to Bandura, what is the most powerful and influential source of self-efficacy beliefs?", "Mastery experiences (past successful performances and accomplishments).", ["Vicarious experiences (watching others succeed).", "Verbal persuasion (encouraging words from mentors).", "Physiological and affective states (managing heart rate and stress)."]),
  ("Psychology of Self: Bandura's Human Agency", "Albert Bandura's concept of 'Human Agency' emphasizes that individuals are:", "Active self-organizing, proactive, self-reflecting, and self-regulating contributors to their life circumstances.", ["Passive pawns driven mechanically by unconscious biological instincts.", "Helpless victims completely controlled by external environmental stimuli.", "Pre-programmed biological automatons with zero cognitive choice."]),
  ("Physical Self: Body Image & Social Comparison", "Leon Festinger's Social Comparison Theory explains that constantly comparing one's physical body to heavily filtered, idealized models on social media often leads to:", "Upward social comparison, resulting in body dissatisfaction, low self-esteem, and negative body image.", ["Downward social comparison, creating instant self-actualization.", "Genetic transformation of physical facial bone structure.", "Spontaneous elimination of all physical appetites."]),
  ("Physical Self: Body Dysmorphic Disorder", "A psychological condition characterized by persistent, distressing, and obsessive preoccupation with perceived minor or imaginary flaws in physical appearance is:", "Body Dysmorphic Disorder (BDD).", ["Anorexia Athletica.", "Ego-Syntonic Euphoria.", "Bipolar Affective Disorder."]),
  ("Sexual Self: Biological Sex vs Gender Identity", "In contemporary gender and sexuality studies, 'Biological Sex' is determined by chromosomes, hormones, and anatomical traits, whereas 'Gender Identity' refers to:", "One's deeply felt, internal, and individual sense of being female, male, or another gender.", ["One's legal tax bracket registered with municipal authorities.", "One's occupational career choice in the corporate workforce.", "One's physical blood type and metabolic rate."]),
  ("Sexual Self: Gender Expression vs Sexual Orientation", "A person's outward presentation of gender through clothing, hairstyle, behavior, and voice is 'Gender Expression', while 'Sexual Orientation' refers to:", "An enduring emotional, romantic, sexual, or affectional attraction toward specific genders.", ["A temporary legal contract signed during marriage ceremonies.", "An individual's formal political affiliation during national elections.", "A person's dietary preference regarding organic nutrition."]),
  ("Sexual Self: Reproductive Health Law (RA 10354)", "In the Philippines, Republic Act 10354 (Responsible Parenthood and Reproductive Health Act of 2012) guarantees universal access to:", "Medically safe, legal, accessible, and affordable reproductive healthcare services and age-appropriate reproductive education.", ["Mandatory state-imposed limits of only one child per family.", "Commercial surrogacy contracts for foreign tourists.", "Automatic surgical sterilization for all high school graduates."]),
  ("Material Self: Russell Belk's Extended Self", "Consumer psychologist Russell Belk proposed the concept of the 'Extended Self', which asserts that:", "People consciously and unconsciously regard their personal possessions, clothing, cars, and homes as integral parts of their identity.", ["The human body can stretch physically through daily yoga exercises.", "Personal bank accounts belong entirely to the national state.", "Digital computers will eventually replace human biological brains."]),
  ("Material Self: Compulsive Buying Disorder", "When an individual repeatedly purchases excessive, unnecessary consumer goods as an unhealthy coping mechanism to temporarily soothe anxiety or fill emotional voids, this is:", "Compulsive buying behavior (oniomania / shopping addiction).", ["Rational economic investment diversification.", "Aristotelian phronesis in household budget management.", "Kantian duty under the Categorical Imperative."])
])
d.extend([
  ("Spiritual Self: Viktor Frankl's Logotherapy", "In Man's Search for Meaning, Viktor Frankl developed 'Logotherapy', which posits that the primary human motivational force is:", "The Will to Meaning (finding purpose in life even amidst unavoidable suffering).", ["The Will to Pleasure (Freudian hedonism).", "The Will to Power (Nietzschean dominance).", "The Will to Wealth (capital accumulation)."]),
  ("Spiritual Self: Sources of Meaning (Frankl)", "According to Viktor Frankl, what are the three fundamental avenues through which an individual can discover meaning in life?", "By creating a work/doing a deed, by experiencing something/encountering someone (love), and by the attitude taken toward unavoidable suffering.", ["By winning physical lotteries, inheriting royal titles, and hoarding rare jewels.", "By achieving absolute military conquest, political power, and celebrity fame.", "By sleeping 14 hours daily, avoiding all human work, and consuming luxury sweets."]),
  ("Spiritual Self: Spirituality vs Religiosity", "In psychological and developmental research, 'Spirituality' is distinguished from 'Religiosity' because spirituality:", "Focuses on personal connection to the transcendent, sacred, and ultimate meaning, independent of formal institutional structures.", ["Requires mandatory weekly attendance at a specific registered tax-exempt church.", "Is strictly prohibited in all democratic secular constitutions.", "Pertains exclusively to ancient medieval monastic asceticism."]),
  ("Political Self: National Identity & Consciousness", "In the formation of the Filipino 'Political Self', developing national consciousness requires moving beyond localized regionalism and clan loyalty to embrace:", "A collective commitment to the common good, civic responsibility, democratic participation, and social justice for all Filipinos.", ["Blind, unquestioning obedience to local dynastic political warlords.", "Total indifference to national economic issues and civic elections.", "Surrendering all Philippine territorial sovereign waters without protest."]),
  ("Political Self: Sikolohiyang Pilipino (Kapwa Core)", "Dr. Virgilio Enriquez founded Sikolohiyang Pilipino (Indigenous Filipino Psychology), identifying the core concept of Filipino personhood as:", "Kapwa (Shared Identity / 'The self in the other'), recognizing the fundamental unity of self and fellow human beings.", ["Hiya (purely negative destructive shame).", "Utang na Loob (contractual monetary debt).", "Pakikisama (superficial compromise to avoid friction)."]),
  ("Political Self: Levels of Interaction (Ibang-Tao vs Hindi Ibang-Tao)", "In Sikolohiyang Pilipino, human social interactions are categorized into two domains. Which level represents the deepest, most intimate relationship of mutual trust?", "Pakikipagpalagayang-loob / Pakikiisa (Hindi Ibang-Tao - One of Us).", ["Pakikitungo (Civility - Ibang-Tao).", "Pakikisalamuha (Interaction - Ibang-Tao).", "Pakikibagay (Conforming - Ibang-Tao)."]),
  ("Digital Self: Online Impression Management", "Erving Goffman's sociological dramaturgical theory, applied to the 'Digital Self', explains that social media users engage in 'Impression Management' by:", "Carefully curating, editing, and staging photos and posts to present a favorable, idealized online front-stage persona.", ["Publishing raw, unedited CCTV security camera feeds of their bedrooms 24/7.", "Deleting all personal electronic communication devices permanently.", "Using only encrypted military command codes for social messaging."]),
  ("Digital Self: Disinhibition Effect", "John Suler's concept of the 'Online Disinhibition Effect' explains why people often say and do things online that they would never do in person, driven by:", "Anonymity, invisibility, asynchronous communication, and perceived lack of immediate social consequences.", ["Increased biological oxygen flow to the frontal cerebral cortex.", "The physical electromagnetic radiation emitted by computer screens.", "Standard corporate computer typing software requirements."]),
  ("Digital Self: Toxic vs Benign Disinhibition", "While 'Toxic Disinhibition' manifests as cyberbullying, trolling, and hate speech, 'Benign Disinhibition' online manifests as:", "Sharing deep emotional vulnerabilities, seeking mental health support, and expressing genuine philanthropic compassion.", ["Hacking municipal power grids to cause blackouts.", "Spamming commercial advertising in academic research forums.", "Stealing credit card credentials through phishing websites."]),
  ("Digital Self: Fear of Missing Out (FOMO)", "The compulsive psychological urge to continuously check social media feeds due to anxiety that others are having rewarding experiences without one is termed:", "FOMO (Fear of Missing Out).", ["Cybernetic Phobia.", "Digital Amnesia.", "Technological Euphoria."]),
  ("Managing Self: Metacognition (Flavell)", "John Flavell defined 'Metacognition' as 'thinking about thinking'. The two primary components of metacognition are:", "Metacognitive Knowledge (awareness of cognition) and Metacognitive Regulation (monitoring and controlling learning processes).", ["Short-Term Memory and Long-Term Sensory Storage.", "Visual Perception and Auditory Reception.", "Verbal IQ and Non-Verbal Performance IQ."]),
  ("Managing Self: Metacognitive Strategies", "A nursing student preparing for board exams assesses her comprehension after each chapter, creates concept maps, and adjusts study tactics when confused. This exemplifies:", "Metacognitive self-regulation and monitoring.", ["Rote passive memorization.", "Operant conditioning without awareness.", "Instinctual genetic reflex."]),
  ("Managing Self: Self-Regulated Learning (Zimmerman)", "Barry Zimmerman's model of 'Self-Regulated Learning' structures the learning cycle into three iterative phases:", "Forethought (planning/goal-setting), Performance (monitoring/strategy execution), and Self-Reflection (self-evaluation/adaptation).", ["Input, Processing, and Output.", "Memorization, Recitation, and Testing.", "Stimulus, Organism, and Response."]),
  ("Managing Self: Growth vs Fixed Mindset (Dweck)", "Carol Dweck's research distinguishes a 'Growth Mindset' from a 'Fixed Mindset' because individuals with a Growth Mindset believe that:", "Intelligence, abilities, and talents can be developed through dedication, strategic effort, and learning from mistakes.", ["Intelligence is fixed at birth and cannot be altered by practice.", "Effort is useless because only innate natural genius produces success.", "Failure indicates permanent personal inadequacy and should be hidden."]),
  ("Managing Self: Stress Appraisal Theory (Lazarus)", "In Richard Lazarus' Cognitive Appraisal Theory of Stress, 'Primary Appraisal' involves evaluating:", "Whether an event is irrelevant, benign-positive, or stressful (representing a threat, challenge, or loss).", ["Whether one has adequate coping resources and options to manage the stressor (Secondary Appraisal).", "The exact numerical blood pressure measurement during cardiovascular testing.", "The physical monetary cost of pharmaceutical prescriptions."])
])
d.extend([
  ("Managing Self: Secondary Appraisal (Lazarus)", "In Lazarus' stress model, 'Secondary Appraisal' refers to:", "Evaluating one's available coping resources, skills, and strategic options to overcome or manage the stressor.", ["Determining whether the original event was dangerous in the first place.", "Measuring environmental air temperature during an emergency.", "Calculating the compound interest on a personal bank loan."]),
  ("Managing Self: Problem-Focused vs Emotion-Focused Coping", "When a student receives a failing midterm grade, she schedules a consultation with the professor, creates a new study timetable, and hires a tutor. This coping style is:", "Problem-Focused Coping (directly addressing the root cause of the stressor to change the situation).", ["Emotion-Focused Coping (regulating emotional distress through meditation or venting).", "Avoidant Denial Coping (pretending the exam never occurred).", "Fatalistic Resignation."]),
  ("Managing Self: Emotion-Focused Coping", "When facing an unalterable bereavement or terminal diagnosis of a loved one, engaging in expressive journaling, mindfulness meditation, and seeking compassionate social support is an example of:", "Emotion-Focused Coping (adapting to unchangeable circumstances by managing the emotional impact).", ["Problem-Focused Coping.", "Aggressive Counter-Attacking.", "Compulsive Consumerism."]),
  ("Managing Self: General Adaptation Syndrome (Selye)", "Hans Selye's 'General Adaptation Syndrome' (GAS) outlines the physiological response to chronic stress in three sequential stages:", "Alarm Reaction, Stage of Resistance, and Stage of Exhaustion.", ["Shock, Recovery, and Euphoria.", "Denial, Anger, and Acceptance.", "Fight, Flight, and Freeze."]),
  ("Managing Self: Selye's Exhaustion Stage", "Prolonged, unmitigated exposure to severe chronic stress depletes bodily resources, leading to Selye's 'Stage of Exhaustion', characterized by:", "Severe immune system suppression, burnout, chronic illness, and physiological breakdown.", ["Immediate physical invulnerability to all bacterial pathogens.", "Permanent elevation of resting basal metabolic efficiency.", "Spontaneous biological rejuvenation of vital organs."]),
  ("Managing Self: Self-Compassion (Kristin Neff)", "Kristin Neff identifies the three core components of 'Self-Compassion' as:", "Self-Kindness (vs self-judgment), Common Humanity (vs isolation), and Mindfulness (vs over-identification).", ["Self-Esteem, Self-Promotion, and Self-Congratulation.", "Pride, Perfectionism, and Relentless Self-Criticism.", "Narcissism, Entitlement, and Emotional Detachment."]),
  ("Managing Self: Emotional Intelligence (Goleman)", "Daniel Goleman's model of 'Emotional Intelligence' (EQ) encompasses five foundational domains:", "Self-Awareness, Self-Regulation, Internal Motivation, Empathy, and Social Skills.", ["Logical Reasoning, Spatial Orientation, Musical Pitch, Bodily Kinesthetics, and Linguistic Fluency.", "Id, Ego, Superego, Libido, and Thanatos.", "Sensorimotor, Preoperational, Concrete Operational, Formal Operational, and Post-Formal."]),
  ("Managing Self: EQ Self-Regulation", "A teacher who feels intense surge of anger toward a disruptive student pauses, takes three deep breaths, and calmly redirects the behavior without shouting demonstrates high:", "Self-Regulation (the ability to manage and redirect disruptive emotions and adapt to circumstances).", ["Cognitive Dissonance.", "Authoritarian Aggression.", "Emotional Disengagement."]),
  ("Managing Self: SMART Goal Setting", "In effective self-management and academic planning, the 'SMART' criteria for goal formulation stand for:", "Specific, Measurable, Achievable, Relevant, and Time-bound.", ["Simple, Meaningful, Artistic, Rational, and Thorough.", "Strategic, Manageable, Approved, Recorded, and Tested.", "Standard, Modern, Advanced, Rapid, and Technical."]),
  ("Managing Self: Pomodoro Technique", "The 'Pomodoro Technique' for overcoming academic procrastination and maintaining cognitive focus involves:", "Working with focused concentration for 25 minutes, followed by a short 5-minute break.", ["Studying continuously for 8 hours without drinking water or eating.", "Sleeping for 25 minutes after every 5 minutes of light reading.", "Listening to loud rock music while memorizing mathematical formulas."]),
  ("Managing Self: Mindful Meditation & Neuroplasticity", "Neuroscientific research demonstrates that regular mindfulness meditation practice fosters 'Neuroplasticity', leading to:", "Structural thickening in the prefrontal cortex (executive control) and reduced reactivity in the amygdala (fear/stress center).", ["The complete destruction of short-term memory storage networks.", "The total genetic mutation of cardiovascular blood vessels.", "The permanent shutdown of sensory auditory processing pathways."]),
  ("Philosophy of Self: Paul Churchland's Eliminative Materialism", "Paul Churchland's neurophilosophical position of 'Eliminative Materialism' claims that traditional 'folk psychology' concepts like beliefs, desires, and the soul will eventually be replaced by:", "Precise scientific understanding of neurobiological brain states, synaptic chemistry, and neural architecture.", ["Ancient astrological celestial alignments.", "Medieval theological demonology manuals.", "Unregulated commercial advertising campaigns."]),
  ("Philosophy of Self: Merleau-Ponty's Body-Subject", "Maurice Merleau-Ponty's rejection of Cartesian mind-body dualism is encapsulated in his assertion that:", "'I do not have a body; I am my body'—the living body is the very vehicle of being in the world.", ["'The body is an evil prison from which the intellect must escape through fasting.'", "'The physical brain is an illusion produced by computer programming.'", "'The mind exists in outer space while the body exists on earth.'"]),
  ("Sociology of Self: Looking-Glass Self Stages", "In Cooley's Looking-Glass Self, which step involves experiencing pride, mortification, or self-worth based on our interpretation of others' evaluations?", "Step 3: Developing a self-feeling based on the perceived judgment.", ["Step 1: Imagining our appearance to the other person.", "Step 2: Imagining the other person's judgment of our appearance.", "Step 0: Taking a physical photograph of oneself."]),
  ("Sociology of Self: Erving Goffman's Dramaturgy", "Erving Goffman compared everyday human social interaction to theatrical performances on a stage. The 'Backstage' area represents:", "The private setting where individuals drop their social facades, relax, and step out of their public roles.", ["The public podium where a keynote address is broadcast live on television.", "The formal job interview room where a resume is scrutinized.", "The classroom where a teacher delivers an official lecture."])
])
d.extend([
  ("Psychology of Self: Erik Erikson's Identity vs Role Confusion", "According to Erik Erikson's psychosocial stages, adolescents (ages 12-18) face the central psychosocial crisis of:", "Identity vs Role Confusion (discovering who they are, their values, and their life direction).", ["Trust vs Mistrust.", "Autonomy vs Shame and Doubt.", "Generativity vs Stagnation."]),
  ("Psychology of Self: James Marcia's Identity Statuses", "A college student who has blindly adopted her parents' chosen career path as an accountant without exploring alternatives or experiencing a personal crisis is in:", "Identity Foreclosure.", ["Identity Achievement (explored options and made personal commitment).", "Moratorium (active crisis/exploration without commitment).", "Identity Diffusion (neither exploration nor commitment)."]),
  ("Psychology of Self: Marcia's Identity Moratorium", "A student who is actively taking diverse electives, volunteering, and questioning career paths without yet finalizing a career choice is in:", "Moratorium.", ["Identity Foreclosure.", "Identity Diffusion.", "Identity Achievement."]),
  ("Psychology of Self: Marcia's Identity Diffusion", "An individual who expresses no interest in career planning, has never explored personal values, and exhibits apathy toward the future is in:", "Identity Diffusion.", ["Identity Foreclosure.", "Moratorium.", "Identity Achievement."]),
  ("Psychology of Self: Self-Esteem vs Self-Efficacy", "In psychological assessment, while 'Self-Esteem' reflects a global affective evaluation of one's worth, 'Self-Efficacy' reflects:", "A task-specific cognitive confidence in one's capability to perform designated actions successfully.", ["The total financial savings in an individual's emergency fund.", "The physical beauty score rated by social media followers.", "An individual's chronological biological age."]),
  ("Psychology of Self: Locus of Control (Rotter)", "Julian Rotter's concept of 'Internal Locus of Control' describes individuals who believe that:", "Their successes and failures are primarily the result of their own efforts, choices, and capabilities.", ["Their lives are controlled entirely by luck, fate, powerful external authorities, or chance (External Locus).", "Human life is pre-determined by astrological zodiac positions.", "All events are randomized quantum anomalies."]),
  ("Psychology of Self: External Locus of Control", "A student who blames the test layout, room temperature, and teacher's mood for a poor score, refusing to acknowledge lack of study, exhibits:", "External Locus of Control.", ["Internal Locus of Control.", "High Metacognitive Regulation.", "Autonomous Self-Determination."]),
  ("Psychology of Self: Self-Determination Theory (Deci & Ryan)", "Deci and Ryan's Self-Determination Theory posits that human psychological flourishing and intrinsic motivation require fulfilling three basic psychological needs:", "Autonomy (choice/volition), Competence (mastery/effectiveness), and Relatedness (belonging/connection).", ["Food, Clothing, and Shelter.", "Money, Fame, and Authority.", "Id, Ego, and Superego."]),
  ("Psychology of Self: Intrinsic vs Extrinsic Motivation", "A student reads advanced biology textbooks on weekends solely out of deep curiosity and joy of learning. This behavior is driven by:", "Intrinsic Motivation (engaging in an activity for its inherent satisfaction).", ["Extrinsic Motivation (engaging in an activity to obtain external rewards or avoid punishment).", "Social Conformity Pressure.", "Amotivation."]),
  ("Psychology of Self: Mihaly Csikszentmihalyi's Flow", "Mihaly Csikszentmihalyi defined 'Flow' as an optimal psychological state of deep immersion and energized focus that occurs when:", "There is a perfect balance between a high level of challenge and a high level of personal skill.", ["A person feels extreme boredom from a task that is too easy.", "A person experiences intense panic from an impossible task with zero skill.", "An individual sleeps soundly for eight hours."]),
  ("Spiritual Self: Fowler's Stages of Faith Development", "In James Fowler's model of faith development, 'Individuative-Reflective Faith' (typical in young adulthood) is characterized by:", "Critically examining one's inherited beliefs, taking personal responsibility for values, and forming an autonomous worldview.", ["Magical thinking and literal acceptance of religious stories in early childhood.", "Conforming unquestioningly to the collective faith of one's immediate peer group.", "Universalizing transcendent love for all humanity."]),
  ("Spiritual Self: Meaning Making in Adversity", "In Viktor Frankl's logotherapy, 'Tragic Optimism' refers to the capacity of the human spirit to:", "Maintain hope, find meaning, and cultivate courage in the face of the 'tragic triad' (pain, guilt, and death).", ["Ignore all suffering by engaging in relentless hedonistic escapism.", "Believe that physical accidents never occur in human life.", "Surrender completely to nihilistic despair."]),
  ("Physical Self: Somatotypes (Sheldon)", "William Sheldon's historical somatotype theory classified body types into Endomorph (soft/round), Mesomorph (muscular/athletic), and:", "Ectomorph (lean/slender/linear).", ["Xenomorph.", "Polymorph.", "Metamorph."]),
  ("Digital Self: Cyberbullying Impact", "Research indicates that victims of persistent online harassment and cyberbullying face severe risks of:", "Depression, chronic anxiety, social withdrawal, academic decline, and suicidal ideation.", ["Instantaneous enhancement of digital graphic design competence.", "Immediate biological immunity to seasonal viral infections.", "Spontaneous elevation of standardized math test percentiles."]),
  ("Managing Self: Delayed Gratification (Mischel)", "Walter Mischel's famous 'Marshmallow Experiment' demonstrated that children who exhibited 'Delayed Gratification' (resisting immediate temptation for a larger future reward) later showed:", "Higher academic achievement, better emotional coping skills, and greater life success in adulthood.", ["Severe cognitive decline and memory loss in teenage years.", "Total inability to make executive decisions in the workplace.", "Chronic failure in interpersonal friendships."])
])

questions = []
for idx, item in enumerate(d):
    exp = item[4] if len(item) > 4 else f"This item assesses competence in {item[0]}. {item[2]} represents established developmental and psychological consensus."
    questions.append(q(idx + 1, item[0], item[1], item[2], item[3], exp))

save('understandingSelfExams.ts', 'UNDERSTANDING_SELF_EXAM_QUESTIONS', questions)
